-- City Titles Part 050 (4901-5000번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0011', '11월 리조트 유후인 패키지 온천 벳부 날씨 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0012', '11월 해외 패키지 일본여행 벳부 리조트 날씨 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0013', '11월 패키지 온천 리조트 항공권 해외 직항 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0014', '11월 유후인 리조트 다케산 일본여행 직항 온천 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0015', '11월 유후인 일본여행 항공권 벳부 패키지 해외 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0016', '11월 해외 벳부 일본여행 날씨 패키지 다케산 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0017', '11월 벳부 유후인 다케산 리조트 패키지 직항 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0018', '11월 해외 패키지 직항 유후인 벳부 리조트 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0019', '11월 온천 다케산 해외 항공권 벳부 일본여행 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0020', '11월 벳부 패키지 다케산 일본여행 온천 직항 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0001', '12월 날씨 패키지 온천 벳부 직항 유후인 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0002', '12월 벳부 다케산 항공권 리조트 날씨 패키지 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0003', '12월 리조트 다케산 일본여행 온천 직항 항공권 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0004', '12월 유후인 해외 날씨 패키지 벳부 리조트 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0005', '12월 유후인 일본여행 항공권 날씨 해외 패키지 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0006', '12월 직항 벳부 리조트 날씨 유후인 다케산 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0007', '12월 벳부 해외 온천 다케산 리조트 일본여행 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0008', '12월 패키지 직항 벳부 다케산 해외 날씨 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0009', '12월 패키지 직항 항공권 온천 해외 벳부 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0010', '12월 리조트 일본여행 해외 온천 벳부 날씨 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0011', '12월 온천 일본여행 벳부 리조트 항공권 유후인 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0012', '12월 해외 온천 날씨 패키지 일본여행 직항 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0013', '12월 리조트 다케산 직항 온천 패키지 해외 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0014', '12월 일본여행 리조트 온천 해외 직항 패키지 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0015', '12월 직항 온천 해외 벳부 일본여행 다케산 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0016', '12월 패키지 직항 리조트 온천 벳부 다케산 날씨 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0017', '12월 일본여행 벳부 직항 다케산 유후인 리조트 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0018', '12월 온천 일본여행 패키지 날씨 직항 다케산 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0019', '12월 해외 직항 유후인 온천 일본여행 벳부 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0020', '12월 온천 일본여행 리조트 벳부 다케산 유후인 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0001', '일본여행 온천 날씨 벳부 항공권 리조트 유후인 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0002', '일본여행 직항 패키지 리조트 다케산 벳부 해외 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0003', '일본여행 항공권 직항 날씨 패키지 온천 해외 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0004', '일본여행 날씨 직항 리조트 온천 패키지 항공권 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0005', '일본여행 날씨 패키지 다케산 직항 항공권 유후인 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0006', '일본여행 리조트 다케산 벳부 유후인 온천 패키지 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0007', '일본여행 직항 유후인 항공권 리조트 패키지 온천 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0008', '일본여행 다케산 리조트 항공권 벳부 패키지 온천 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0009', '일본여행 온천 항공권 다케산 벳부 유후인 패키지 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0010', '일본여행 온천 벳부 날씨 직항 리조트 다케산 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0011', '일본여행 항공권 유후인 날씨 해외 온천 직항 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0012', '일본여행 벳부 다케산 직항 항공권 리조트 날씨 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0013', '일본여행 해외 다케산 벳부 패키지 날씨 직항 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0014', '일본여행 해외 벳부 유후인 리조트 항공권 날씨 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0015', '일본여행 벳부 리조트 다케산 날씨 패키지 항공권 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0016', '일본여행 직항 온천 벳부 패키지 유후인 항공권 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0017', '일본여행 패키지 다케산 리조트 벳부 항공권 날씨 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0018', '일본여행 다케산 날씨 벳부 해외 리조트 항공권 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0019', '일본여행 유후인 온천 직항 해외 리조트 패키지 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0020', '일본여행 유후인 패키지 온천 다케산 항공권 벳부 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0001', '일본여행 벳부 직항 항공권 리조트 유후인 온천 지옥순례', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0002', '일본여행 항공권 벳부 리조트 직항 료칸 해외 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0003', '일본여행 벳부 해외 다케산 항공권 료칸 직항 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0004', '일본여행 직항 온천 날씨 료칸 항공권 벳부 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0005', '일본여행 온천 료칸 항공권 직항 지옥순례 패키지 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0006', '일본여행 료칸 패키지 유후인 다케산 항공권 날씨 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0007', '일본여행 날씨 항공권 리조트 지옥순례 유후인 온천 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0008', '일본여행 패키지 날씨 료칸 해외 직항 지옥순례 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0009', '일본여행 료칸 날씨 벳부 직항 해외 항공권 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0010', '일본여행 리조트 해외 패키지 항공권 벳부 온천 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0011', '일본여행 리조트 해외 지옥순례 날씨 벳부 항공권 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0012', '일본여행 해외 유후인 패키지 벳부 항공권 료칸 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0013', '일본여행 날씨 패키지 직항 벳부 지옥순례 다케산 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0014', '일본여행 료칸 다케산 날씨 벳부 온천 해외 직항 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0015', '일본여행 패키지 료칸 직항 벳부 해외 유후인 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0016', '일본여행 리조트 해외 패키지 지옥순례 온천 유후인 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0017', '일본여행 패키지 날씨 다케산 료칸 항공권 직항 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0018', '일본여행 유후인 다케산 리조트 벳부 직항 패키지 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0019', '일본여행 료칸 유후인 온천 지옥순례 리조트 해외 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRFO_0020', '일본여행 지옥순례 패키지 직항 유후인 료칸 해외 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0001', '일본여행 해외 날씨 직항 온천 패키지 간사이공항 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0002', '일본여행 간사이공항 유후인 온천 날씨 직항 오사카', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0003', '일본여행 날씨 패키지 해외 유후인 에어텔 온천 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0004', '일본여행 날씨 온천 항공권 간사이공항 리조트 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0005', '일본여행 리조트 간사이공항 오사카 패키지 에어텔 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0006', '일본여행 패키지 온천 간사이공항 항공권 날씨 오사카', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0007', '일본여행 에어텔 날씨 직항 온천 리조트 오사카 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0008', '일본여행 벳부 리조트 패키지 항공권 날씨 간사이공항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0009', '일본여행 에어텔 벳부 항공권 온천 날씨 간사이공항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0010', '일본여행 항공권 패키지 직항 오사카 온천 유후인 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0011', '일본여행 리조트 날씨 벳부 간사이공항 해외 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0012', '일본여행 에어텔 항공권 해외 간사이공항 벳부 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0013', '일본여행 패키지 온천 간사이공항 날씨 벳부 에어텔', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0014', '일본여행 직항 벳부 해외 날씨 간사이공항 온천 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0015', '일본여행 날씨 직항 항공권 해외 온천 유후인 오사카', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0016', '일본여행 에어텔 항공권 해외 간사이공항 직항 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0017', '일본여행 해외 온천 항공권 에어텔 직항 리조트 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0018', '일본여행 직항 간사이공항 벳부 리조트 유후인 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0019', '일본여행 벳부 항공권 직항 날씨 간사이공항 오사카 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0020', '일본여행 패키지 직항 유후인 벳부 날씨 온천 간사이공항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0001', '치앙마이 직항 태국 날씨 항공권 해외 패키지 여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0002', '치앙마이 항공권 리조트 태국 해외 날씨 여행 직항 일정', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0003', '치앙마이 패키지 일정 직항 태국 해외 리조트 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0004', '치앙마이 태국 해외 일정 패키지 항공권 직항 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0005', '치앙마이 리조트 패키지 일정 여행 항공권 날씨 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0006', '치앙마이 리조트 해외 태국 패키지 날씨 항공권 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0007', '치앙마이 리조트 일정 직항 패키지 태국 날씨 여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0008', '치앙마이 여행 일정 직항 날씨 패키지 리조트 해외 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0009', '치앙마이 리조트 태국 패키지 날씨 직항 해외 여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0010', '치앙마이 패키지 태국 직항 여행 리조트 날씨 항공권', 'ChiangMai');
