-- City Titles Part 062 (6101-6200번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0001', '일본 해외 항공권 날씨 우메다스카이빌딩 신사이바시', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0002', '일본 유니버셜스튜디오 신세카이 오사카 여행 직항 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0003', '일본 패키지 오사카 유니버셜스튜디오 신세카이', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0004', '일본 여행 도톤보리 신세카이 직항 리조트 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0005', '일본 직항 날씨 오사카 유니버셜스튜디오 리조트 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0006', '일본 도톤보리 여행 직항 리조트 우메다스카이빌딩', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0007', '일본 신세카이 신사이바시 오사카 해외 유니버셜스튜디오', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0008', '일본 패키지 여행 해외 직항 날씨 우메다스카이빌딩', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0009', '일본 신사이바시 항공권 날씨 오사카 직항 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0010', '일본 직항 해외 항공권 날씨 패키지 신사이바시 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0011', '일본 도톤보리 신세카이 해외 신사이바시 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0012', '일본 신사이바시 항공권 패키지 여행 해외 도톤보리 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0013', '일본 패키지 유니버셜스튜디오 직항 우메다스카이빌딩', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0014', '일본 도톤보리 패키지 해외 유니버셜스튜디오 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0015', '일본 도톤보리 직항 유니버셜스튜디오 신사이바시 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0016', '일본 여행 유니버셜스튜디오 날씨 도톤보리 신사이바시', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0017', '일본 패키지 해외 날씨 오사카 도톤보리 우메다스카이빌딩', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0018', '일본 직항 패키지 리조트 도톤보리 신사이바시 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0019', '일본 여행 리조트 오사카 유니버셜스튜디오 해외 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0020', '일본 유니버셜스튜디오 날씨 오사카 우메다스카이빌딩', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0021', '일본 패키지 직항 우메다스카이빌딩 유니버셜스튜디오', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0022', '일본 도톤보리 신세카이 날씨 항공권 우메다스카이빌딩', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0023', '일본 리조트 항공권 우메다스카이빌딩 날씨 신사이바시', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0024', '일본 리조트 도톤보리 유니버셜스튜디오 우메다스카이빌딩', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0025', '일본 오사카 여행 도톤보리 우메다스카이빌딩 해외 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0026', '일본 신세카이 도톤보리 오사카 항공권 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0027', '일본 리조트 항공권 신세카이 우메다스카이빌딩 신사이바시', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0028', '일본 오사카 신사이바시 여행 직항 날씨 패키지 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0029', '일본 직항 날씨 오사카 신세카이 신사이바시 리조트 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MRFIV_0030', '일본 직항 유니버셜스튜디오 우메다스카이빌딩 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0001', '일본여행 유니버셜스튜디오 도톤보리 날씨 직항 신사이바시', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0002', '일본여행 도톤보리 항공권 오사카 해외 유니버셜스튜디오', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0003', '일본여행 패키지 오사카 리조트 날씨 신사이바시 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0004', '일본여행 리조트 신사이바시 직항 오사카 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0005', '일본여행 오사카 도톤보리 신사이바시 항공권 리조트 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0006', '일본여행 도톤보리 항공권 오사카 리조트 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0007', '일본여행 리조트 오사카 날씨 직항 신사이바시 도톤보리', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0008', '일본여행 도톤보리 날씨 항공권 해외 직항 신사이바시', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0009', '일본여행 리조트 날씨 유니버셜스튜디오 도톤보리 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0010', '일본여행 날씨 도톤보리 해외 직항 패키지 항공권 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0011', '일본여행 날씨 항공권 도톤보리 패키지 오사카 신사이바시', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0012', '일본여행 패키지 신사이바시 해외 도톤보리 항공권 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0013', '일본여행 오사카 항공권 해외 날씨 직항 도톤보리 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0014', '일본여행 리조트 오사카 신사이바시 항공권 직항 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0015', '일본여행 날씨 리조트 신사이바시 패키지 직항 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0016', '일본여행 패키지 도톤보리 항공권 해외 오사카 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0017', '일본여행 해외 도톤보리 오사카 날씨 항공권 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0018', '일본여행 신사이바시 항공권 날씨 리조트 유니버셜스튜디오', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0019', '일본여행 패키지 유니버셜스튜디오 도톤보리 해외 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0020', '일본여행 해외 날씨 신사이바시 리조트 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0021', '일본여행 리조트 도톤보리 유니버셜스튜디오 신사이바시', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0022', '일본여행 도톤보리 직항 리조트 항공권 패키지 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0023', '일본여행 오사카 유니버셜스튜디오 직항 패키지 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0024', '일본여행 날씨 오사카 항공권 리조트 패키지 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0025', '일본여행 항공권 유니버셜스튜디오 해외 리조트 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0026', '일본여행 도톤보리 날씨 항공권 리조트 해외 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0027', '일본여행 리조트 오사카 도톤보리 날씨 유니버셜스튜디오', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0028', '일본여행 항공권 직항 날씨 패키지 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0029', '일본여행 날씨 항공권 신사이바시 유니버셜스튜디오 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_RAN_0030', '일본여행 오사카 유니버셜스튜디오 도톤보리 해외 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0001', '독일 패키지 항공권 서유럽 일주 가격 관광 프랑스', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0002', '독일 항공권 직항 패키지 가격 여행 서유럽 비행시간', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0003', '독일 관광 패키지 프랑스 일주 직항 서유럽 항공권 가격', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0004', '독일 직항 프랑스 패키지 비행시간 가격 여행 항공권', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0005', '독일 프랑스 직항 서유럽 관광 여행 일주 패키지', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0006', '독일 서유럽 여행 항공권 가격 일주 비행시간 프랑스', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0007', '독일 일주 프랑스 여행 패키지 가격 서유럽 비행시간', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0008', '독일 여행 항공권 일주 프랑스 가격 패키지 관광 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0009', '독일 관광 여행 비행시간 가격 항공권 패키지 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0010', '독일 가격 일주 서유럽 패키지 여행 항공권 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0011', '독일 직항 여행 프랑스 항공권 가격 패키지 일주', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0012', '독일 일주 여행 관광 서유럽 패키지 프랑스 비행시간', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0013', '독일 프랑스 패키지 서유럽 가격 직항 비행시간 항공권', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0014', '독일 관광 가격 항공권 여행 비행시간 서유럽 패키지', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0015', '독일 프랑스 비행시간 가격 일주 여행 패키지 관광 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0016', '독일 비행시간 패키지 여행 가격 관광 서유럽 직항 일주', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0017', '독일 비행시간 프랑스 관광 패키지 일주 항공권 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0018', '독일 서유럽 직항 패키지 가격 비행시간 관광 일주', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0019', '독일 서유럽 여행 항공권 일주 직항 패키지 프랑스 관광', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0020', '독일 일주 패키지 프랑스 직항 가격 항공권 관광 여행', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0021', '독일 관광 비행시간 일주 가격 프랑스 직항 패키지 여행', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0022', '독일 가격 직항 비행시간 항공권 패키지 프랑스 서유럽', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0023', '독일 여행 직항 가격 패키지 관광 서유럽 항공권 프랑스', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0024', '독일 프랑스 패키지 관광 비행시간 직항 여행 일주 가격', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0025', '독일 직항 패키지 여행 프랑스 비행시간 가격 관광 일주', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0026', '독일 여행 가격 일주 패키지 프랑스 비행시간 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0027', '독일 패키지 관광 여행 항공권 서유럽 가격 직항 일주', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0028', '독일 항공권 직항 패키지 가격 여행 관광 일주 비행시간', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0029', '독일 서유럽 프랑스 관광 패키지 여행 일주 직항 항공권', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0030', '독일 여행 프랑스 일주 패키지 관광 항공권 비행시간', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0031', '독일 가격 비행시간 직항 항공권 일주 프랑스 여행 관광', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0032', '독일 비행시간 항공권 일주 서유럽 패키지 가격 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0033', '독일 비행시간 일주 패키지 관광 직항 여행 서유럽', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0034', '독일 직항 가격 여행 패키지 프랑스 서유럽 관광 항공권', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_CMK_0035', '독일 패키지 여행 서유럽 직항 항공권 일주 프랑스 관광', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_MKL_0001', '독일 라인강 프랑스 서유럽 베를린 가격 직항 관광', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_MKL_0002', '독일 패키지 직항 베를린 서유럽 비행시간 프랑스 가격', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_MKL_0003', '독일 여행 패키지 프랑스 프랑크푸르트 포츠담 비행시간', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_MKL_0004', '독일 프랑스 여행 서유럽 라인강 항공권 일주 베를린', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GERMAN_MKL_0005', '독일 베를린 라인강 프랑크푸르트 프랑스 포츠담 관광', 'Germany');
