-- City Titles Part 006 (501-600번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_SNM_0012', '시드니 여행 멜버른 홈쇼핑 4박6일 호주', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_SNM_0013', '시드니 멜버른 여행 4박6일 호주 추석 여행사', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_SNM_0014', '시드니 호주 멜버른 홈쇼핑 여행 여행사', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_SNM_0015', '시드니 추석 여행 패키지 4박6일 여행사 호주', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_SNM_0016', '시드니 추석 호주 멜버른 홈쇼핑 패키지', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_SNM_0017', '시드니 패키지 여행사 호주 여행 홈쇼핑', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_SNM_0018', '시드니 추석 4박6일 여행 호주 멜버른 여행사', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_SNM_0019', '시드니 여행 홈쇼핑 추석 멜버른 4박6일', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_SNM_0020', '시드니 홈쇼핑 여행 멜버른 4박6일 호주', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0001', '부산출발 호주 시드니 패키지 6박7일 가족', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0002', '부산출발 호주 투어 가족 여행 패키지 시드니', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0003', '부산출발 호주 여행 투어 가족 6박7일 시드니', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0004', '부산출발 호주 시드니 부산출발 가족 패키지', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0005', '부산출발 호주 패키지 부산출발 투어 여행', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0006', '부산출발 호주 투어 시드니 여행 부산출발 가족', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0007', '부산출발 호주 가족 여행 부산출발 패키지 투어', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0008', '부산출발 호주 부산출발 투어 6박7일 시드니', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0009', '부산출발 호주 6박7일 시드니 투어 여행', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0010', '부산출발 호주 여행 가족 6박7일 투어 패키지', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0011', '부산출발 호주 투어 패키지 6박7일 부산출발', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0012', '부산출발 호주 부산출발 시드니 6박7일 투어', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0013', '부산출발 호주 투어 시드니 6박7일 패키지', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0014', '부산출발 호주 부산출발 가족 투어 6박7일', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0015', '부산출발 호주 부산출발 패키지 시드니 6박7일', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0016', '부산출발 호주 여행 부산출발 가족 6박7일', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0017', '부산출발 호주 부산출발 6박7일 투어 패키지', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0018', '부산출발 호주 가족 투어 시드니 여행 부산출발', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0019', '부산출발 호주 6박7일 시드니 부산출발 가족', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_SYDNEY_GBM_0020', '부산출발 호주 가족 부산출발 6박7일 투어', 'Sydney');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0002', '뉴질랜드 패키지 퀸즈타운 여행 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0004', '뉴질랜드 여행 가족여행 패키지 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0005', '뉴질랜드 가족여행 패키지 여행 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0009', '뉴질랜드 퀸즈타운 패키지 가족여행 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0010', '뉴질랜드 퀸즈타운 패키지 여행 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0011', '뉴질랜드 패키지 여행 퀸즈타운 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0012', '뉴질랜드 퀸즈타운 가족여행 패키지 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0013', '뉴질랜드 여행 패키지 퀸즈타운 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0014', '뉴질랜드 여행 퀸즈타운 가족여행 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0016', '뉴질랜드 여행 패키지 가족여행 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0017', '뉴질랜드 여행 퀸즈타운 패키지 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0018', '뉴질랜드 가족여행 여행 퀸즈타운 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0019', '뉴질랜드 가족여행 여행 패키지 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_CMK_0020', '뉴질랜드 퀸즈타운 가족여행 여행 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0001', '뉴질랜드 퀸즈타운 여행 스카이라인 패키지 애로우타운 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0002', '뉴질랜드 퀸즈타운 스카이라인 애로우타운 가족여행 카와라우다리', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0003', '뉴질랜드 애로우타운 가족여행 스카이라인 퀸즈타운 와카티푸 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0004', '뉴질랜드 패키지 여행 퀸즈타운 카와라우다리 스카이라인 애로우타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0005', '뉴질랜드 패키지 와카티푸 애로우타운 퀸즈타운 카와라우다리', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0006', '뉴질랜드 패키지 애로우타운 여행 퀸즈타운 스카이라인 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0007', '뉴질랜드 퀸즈타운 애로우타운 가족여행 리마커블스산맥 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0008', '뉴질랜드 리마커블스산맥 카와라우다리 가족여행 애로우타운 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0009', '뉴질랜드 퀸즈타운 가족여행 와카티푸 카와라우다리 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0010', '뉴질랜드 카와라우다리 패키지 스카이라인 여행 애로우타운 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0011', '뉴질랜드 와카티푸 가족여행 퀸즈타운 여행 카와라우다리 스카이라인', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0012', '뉴질랜드 스카이라인 와카티푸 리마커블스산맥 여행 애로우타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0013', '뉴질랜드 리마커블스산맥 가족여행 여행 애로우타운 패키지 와카티푸', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0014', '뉴질랜드 스카이라인 리마커블스산맥 패키지 퀸즈타운 애로우타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0015', '뉴질랜드 애로우타운 퀸즈타운 여행 카와라우다리 패키지 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0016', '뉴질랜드 퀸즈타운 와카티푸 스카이라인 애로우타운 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0017', '뉴질랜드 퀸즈타운 패키지 여행 리마커블스산맥 애로우타운 와카티푸', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0018', '뉴질랜드 애로우타운 패키지 스카이라인 퀸즈타운 가족여행 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0019', '뉴질랜드 리마커블스산맥 와카티푸 애로우타운 카와라우다리 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_MKL_0020', '뉴질랜드 여행 스카이라인 패키지 와카티푸 리마커블스산맥 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0001', '뉴질랜드 여행 여름 연휴 퀸즈타운 휴일 패키지 일주 혼자여행 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0002', '뉴질랜드 가족여행 여름 일주 혼자여행 휴일 퀸즈타운 패키지 연휴 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0003', '뉴질랜드 일주 여름 여행 패키지 혼자여행 퀸즈타운 휴일 연휴 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0004', '뉴질랜드 가족여행 패키지 혼자여행 여행 여름 퀸즈타운 연휴 휴일 일주', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0005', '뉴질랜드 패키지 휴일 혼자여행 여름 가족여행 여행 퀸즈타운 일주 연휴', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0006', '뉴질랜드 가족여행 휴일 퀸즈타운 여름 혼자여행 연휴 여행 패키지 일주', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0007', '뉴질랜드 일주 가족여행 휴일 여행 여름 혼자여행 패키지 퀸즈타운 연휴', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0008', '뉴질랜드 혼자여행 퀸즈타운 여행 일주 가족여행 휴일 패키지 연휴 여름', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0009', '뉴질랜드 연휴 가족여행 여행 퀸즈타운 여름 일주 패키지 혼자여행 휴일', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0010', '뉴질랜드 퀸즈타운 가족여행 혼자여행 연휴 여행 휴일 여름 패키지 일주', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0011', '뉴질랜드 가족여행 퀸즈타운 연휴 여행 휴일 일주 패키지 혼자여행 여름', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0012', '뉴질랜드 혼자여행 가족여행 퀸즈타운 일주 패키지 여행 여름 휴일 연휴', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0013', '뉴질랜드 퀸즈타운 혼자여행 여름 휴일 일주 연휴 여행 가족여행 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0014', '뉴질랜드 퀸즈타운 여름 연휴 가족여행 패키지 여행 혼자여행 일주 휴일', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0015', '뉴질랜드 가족여행 여행 일주 연휴 패키지 여름 휴일 퀸즈타운 혼자여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0016', '뉴질랜드 패키지 혼자여행 가족여행 퀸즈타운 일주 여행 휴일 여름 연휴', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0017', '뉴질랜드 휴일 일주 혼자여행 여행 패키지 가족여행 연휴 여름 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0018', '뉴질랜드 여름 연휴 일주 퀸즈타운 패키지 휴일 혼자여행 가족여행 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0019', '뉴질랜드 퀸즈타운 여름 가족여행 여행 연휴 휴일 혼자여행 패키지 일주', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ML_0020', '뉴질랜드 여름 가족여행 여행 휴일 퀸즈타운 연휴 패키지 혼자여행 일주', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0001', '퀸즈타운 휴일 뉴질랜드 패키지 하나투어 여행 여름', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0002', '퀸즈타운 뉴질랜드 여름 휴일 여행 패키지 하나투어', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0003', '퀸즈타운 뉴질랜드 하나투어 패키지 여름 휴일 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0004', '퀸즈타운 패키지 여행 뉴질랜드 여름 하나투어 휴일', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0005', '퀸즈타운 뉴질랜드 패키지 하나투어 여행 휴일 여름', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0006', '퀸즈타운 휴일 여행 하나투어 뉴질랜드 여름 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0007', '퀸즈타운 여행 여름 휴일 패키지 뉴질랜드 하나투어', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0008', '퀸즈타운 뉴질랜드 하나투어 여행 패키지 휴일 여름', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0009', '퀸즈타운 뉴질랜드 여름 여행 패키지 휴일 하나투어', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0010', '퀸즈타운 뉴질랜드 여름 하나투어 휴일 패키지 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0011', '퀸즈타운 휴일 여름 여행 패키지 하나투어 뉴질랜드', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0012', '퀸즈타운 패키지 뉴질랜드 휴일 하나투어 여행 여름', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0013', '퀸즈타운 하나투어 여행 여름 뉴질랜드 휴일 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0014', '퀸즈타운 하나투어 뉴질랜드 여행 휴일 여름 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0015', '퀸즈타운 하나투어 여행 뉴질랜드 여름 휴일 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0016', '퀸즈타운 하나투어 여행 휴일 여름 뉴질랜드 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0017', '퀸즈타운 뉴질랜드 여름 패키지 휴일 여행 하나투어', 'Queenstown');
