-- City Titles Part 017 (1601-1700번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0018', '미동부 개나다 미극 나이아거라 09월 패키쥐 여헹코스 인쳔출발 8월 가졍여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0019', '나이아거라 미동부 개나다 미극 09월 패키쥐 여헹코스 인쳔출발 하반기 효도여헹', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0020', '개나다 미극 미동부 나이아거라 09월 패키쥐 여헹코스 인쳔출발 2026년 해왜여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0001', '나이아가라폭포 나이아가라크루즈 스카일론타워 클리프턴힐 인천출발 6월 패키지 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0002', '캐나다 나이아가라 미동부 나이아가라파크 크루즈 스카일론타워 인천출발 7월 패키지 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0003', '미국 미동부 나이아가라 나이아가라폭포 스카일론타워 여행코스 인천출발 8월 패키지 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0004', '나이아가라 파크 스카일론타워 클리프턴힐 크루즈 인천출발 하반기 패키지 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0005', '캐나다 미국 미동부 나이아가라 나이아가라폭포 인천출발 2026년 패키지 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0006', '나이아가라 미동부 미국 캐나다 나이아가라크루즈 인천출발 6월 패키지 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0007', '미국 캐나다 미동부 나이아가라 스카일론타워 인천출발 7월 패키지 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0008', '나이아가라 나이아가라폭포 클리프턴힐 파크 인천출발 8월 패키지 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0009', '캐나다 미동부 나이아가라 미국 크루즈 인천출발 하반기 패키지 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0010', '나이아가라 미동부 캐나다 미국 스카일론타워 인천출발 2026년 패키지 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0011', '미국 캐나다 패키지 미동부 09월 나이아가라 여행코스 인천출발 6월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0012', '캐나다 미국 미동부 09월 나이아가라 패키지 여행코스 인천출발 7월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0013', '나이아가라 미국 캐나다 미동부 09월 패키지 여행코스 인천출발 8월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0014', '미동부 캐나다 미국 나이아가라 09월 패키지 여행코스 인천출발 하반기 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0015', '나이아가라 캐나다 미국 미동부 09월 패키지 여행코스 인천출발 2026년 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0016', '미국 나이아가라 캐나다 미동부 09월 패키지 여행코스 인천출발 6월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0017', '나이아가라 미동부 미국 캐나다 09월 패키지 여행코스 인천출발 7월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0018', '캐나다 나이아가라 미동부 미국 09월 패키지 여행코스 인천출발 8월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0019', '미동부 미국 나이아가라 캐나다 09월 패키지 여행코스 인천출발 하반기 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_GPT_0020', '나이아가라 미국 미동부 캐나다 09월 패키지 여행코스 인천출발 2026년 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0001', '중남미 멕시코 쿠바 칸쿤 패키지 여행 국적기 직항 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0002', '멕시코 쿠바 칸쿤 여행 패키지 아시아나 대한항공 항공 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0003', '중남미 멕시코시티 쿠바 칸쿤 패키지 여행 국적기 직항 아시아나', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0004', '쿠바 멕시코 칸쿤 패키지 여행 인천출발 국적기 대한항공 항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0005', '중남미 멕시코 쿠바 칸쿤 패키지 여행 국적기 직항 항공 아시아나', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0006', '멕시코시티 쿠바 칸쿤 중남미 패키지 여행 국적기 대한항공 직항', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0007', '쿠바 칸쿤 멕시코 패키지 여행 국적기 항공 직항 인천출발 아시아나', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0008', '중남미 멕시코 쿠바 칸쿤 여행 패키지 국적기 항공 직항 대한항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0009', '멕시코 쿠바 칸쿤 여행 인천출발 국적기 항공 아시아나 대한항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0010', '쿠바 멕시코시티 칸쿤 패키지 여행 국적기 직항 아시아나 대한항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0011', '중남미 멕시코 쿠바 칸쿤 패키지 인천출발 국적기 항공 대한항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0012', '멕시코 쿠바 칸쿤 여행 국적기 아시아나 대한항공 항공 직항 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0013', '중남미 멕시코시티 쿠바 칸쿤 패키지 국적기 항공 직항 대한항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0014', '쿠바 멕시코 칸쿤 여행 패키지 국적기 직항 인천출발 아시아나', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0015', '멕시코 쿠바 칸쿤 여행 국적기 항공 아시아나 대한항공 직항', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0016', '중남미 멕시코시티 쿠바 칸쿤 패키지 여행 국적기 항공 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0017', '쿠바 멕시코 칸쿤 여행 패키지 국적기 항공 대한항공 직항', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0018', '멕시코시티 쿠바 칸쿤 여행 인천출발 국적기 항공 아시아나', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0019', '중남미 멕시코 쿠바 칸쿤 패키지 여행 인천출발 항공 국적기', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_CMK_0020', '쿠바 멕시코 칸쿤 여행 패키지 국적기 직항 항공 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0001', '칸쿤 리비에라마야 멕시코 쿠바 패키지 여행 소칼로광장 코요아칸 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0002', '멕시코시티 소칼로광장 쿠바 칸쿤 패키지 여행 국적기 직항 마야문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0003', '중미 멕시코 쿠바 칸쿤 리비에라마야 패키지 여행 메트로폴리타나대성당', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0004', '쿠바 멕시코 칸쿤 패키지 여행 프란시스코광장 헤밍웨이박물관 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0005', '멕시코 쿠바 칸쿤 패키지 여행 리비에라마야 소칼로광장 국적기 항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0006', '중미 쿠바 멕시코 칸쿤 패키지 여행 메트로폴리타나대성당 코요아칸', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0007', '칸쿤 멕시코 쿠바 패키지 여행 프란시스코광장 국적기 직항 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0008', '쿠바 멕시코시티 칸쿤 패키지 여행 소칼로광장 마야문명 아즈텍문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0009', '중미 멕시코 쿠바 칸쿤 패키지 여행 국적기 리비에라마야 코요아칸', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0010', '멕시코 쿠바 칸쿤 패키지 여행 헤밍웨이박물관 프란시스코광장', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0011', '쿠바 멕시코 칸쿤 패키지 여행 마야문명 아즈텍문명 소칼로광장', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0012', '칸쿤 쿠바 멕시코 패키지 여행 코요아칸 메트로폴리타나대성당', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0013', '중미 멕시코시티 쿠바 칸쿤 패키지 여행 리비에라마야 프란시스코광장', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0014', '쿠바 멕시코 칸쿤 패키지 여행 소칼로광장 국적기 직항 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0015', '멕시코 쿠바 칸쿤 패키지 여행 메트로폴리타나대성당 리비에라마야', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0016', '중미 멕시코 쿠바 칸쿤 패키지 여행 헤밍웨이박물관 코요아칸', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0017', '쿠바 멕시코 칸쿤 패키지 여행 소칼로광장 프란시스코광장 국적기', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0018', '칸쿤 멕시코 쿠바 패키지 여행 리비에라마야 아즈텍문명 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0019', '멕시코시티 쿠바 칸쿤 패키지 여행 코요아칸 국적기 직항', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_MKL_0020', '중미 멕시코 쿠바 칸쿤 패키지 여행 메트로폴리타나대성당 소칼로광장', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0001', '중미 멕시코 쿠바 칸쿤 패키지 여행 인천출발 8박10일 아즈텍문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0002', '멕시코 쿠바 칸쿤 여행 패키지 인천출발 국적기 항공 직항 10일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0003', '쿠바 멕시코시티 칸쿤 패키지 여행 인천출발 마야문명 국적기 9일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0004', '중남미 쿠바 멕시코 칸쿤 패키지 여행 인천출발 6박9일 투어', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0005', '멕시코 쿠바 칸쿤 패키지 여행 인천출발 8박10일 국적기 직항', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0006', '쿠바 멕시코시티 칸쿤 여행 패키지 인천출발 9일 항공 대한항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0007', '중미 멕시코 쿠바 칸쿤 패키지 여행 인천출발 10일 마야문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0008', '멕시코 쿠바 칸쿤 여행 인천출발 국적기 직항 6박9일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0009', '쿠바 멕시코 칸쿤 패키지 여행 인천출발 8박10일 아즈텍문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0010', '중남미 멕시코시티 쿠바 칸쿤 여행 인천출발 국적기 항공 9일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0011', '멕시코 쿠바 칸쿤 패키지 여행 인천출발 대한항공 10일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0012', '쿠바 멕시코 칸쿤 여행 패키지 인천출발 아시아나 항공 6박9일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0013', '중미 멕시코 쿠바 칸쿤 패키지 여행 인천출발 국적기 직항 8박10일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0014', '멕시코 쿠바 칸쿤 여행 인천출발 항공 9일 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0015', '쿠바 멕시코시티 칸쿤 패키지 여행 인천출발 아즈텍문명 10일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0016', '중남미 멕시코 쿠바 칸쿤 여행 인천출발 국적기 직항 6박9일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0017', '멕시코 쿠바 칸쿤 패키지 인천출발 아시아나 항공 9일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0018', '쿠바 멕시코시티 칸쿤 여행 인천출발 국적기 직항 8박10일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0019', '중미 멕시코 쿠바 칸쿤 패키지 여행 인천출발 대한항공 10일', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_DMK_0020', '멕시코 쿠바 칸쿤 여행 인천출발 6박9일 국적기 직항', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0001', '멕시코 아즈텍문명 유적지 탐방과 칸쿤 올인클루시브 리조트 숙박 인천출발 국적기 직항 8박10일 완전일주 패키지 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0002', '유카탄 반도 마야문명 체험과 멕시코시티 소칼로광장 대성당 시내 관광 칸쿤 호텔존 올인클루시브 포함 9일 일정 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0003', '쿠바 하바나 올드카 시내 투어와 헤밍웨이 박물관 방문 멕시코 칸쿤 리비에라마야 휴양이 결합된 카리브해 완전일주 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0004', '인천출발 대한항공 국적기 직항 멕시코 쿠바 2개국 일주 아즈텍문명과 마야문명 탐방 고급 10일 패키지 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0005', '멕시코 칸쿤 호텔존 리조트 숙박과 스칼렛 아르떼 공연 관람 쿠바 하바나 올드카 체험 마야문명 탐방 8박10일 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0006', '쿠바 아바나 프란시스코광장 탐방과 헤밍웨이 발자취 투어 멕시코 칸쿤 올인클루시브 숙박 카리브해 완전일주 일정', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0007', '인천출발 국적기 직항 멕시코 아즈텍문명 유적지 쿠바 하바나 올드타운 탐방 칸쿤 호텔존 3박 휴양 결합 9일 패키지 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0008', '중미 핵심 2개국 쿠바 멕시코 일주 마야문명 체험 칸쿤 리비에라마야 투어 아시아나 국적기 직항 8박10일 일정', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0018', '카리브해 액티비티 포함 쿠바 하바나 올드타운 시내 관광 멕시코 칸쿤 올인클루시브 숙박 8박10일 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0019', '멕시코 아즈텍문명 마야문명 유적 탐방 쿠바 하바나 헤밍웨이 발자취 체험 인천출발 중미 완전일주 9일 패키지 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0020', '중남미 멕시코 쿠바 칸쿤 여행 인천출발 국적기 2개국 항공권', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0001', '중미 멕시코 쿠바 칸쿤 패키지 여행 인천출발 올인클루시브 아즈텍문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0002', '멕시코 쿠바 칸쿤 여행 인천출발 국적기 항공 하바나올드카 마야문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0003', '쿠바 멕시코시티 칸쿤 패키지 인천출발 노쇼핑 노팁 카리브해', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0004', '중남미 멕시코 쿠바 칸쿤 여행 인천출발 호텔존 스칼렛아르떼 완전일주', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0005', '멕시코 쿠바 칸쿤 패키지 인천출발 국적기 직항 아시아나 대한항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0006', '쿠바 멕시코 칸쿤 여행 인천출발 하바나올드카 아즈텍문명', 'CentralAmerica');
