-- City Titles Part 010 (901-1000번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0020', '미국 로스앤젤레스 일일관광 미주여행 일정 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0001', 'LA 로스앤졀레스 미국 패키지 여행 직항 미서부 헐리우드 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0002', '로스앤졀레스 패키지 LA 미국 미주여행 직항 크루즈 헐리우드 인쳔출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0003', '미국 LA 로스앤졀레스 여행 패키지 직항 미서부 크루즈 헐리우드 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0004', '로스앤졀레스 LA 미주여행 패키지 미국 여행 직항 헐리우드 인쳔출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0005', 'LA 패키지 미국 로스앤졀레스 여행 직항 미서부 헐리우드 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0006', '미주여행 로스앤졀레스 LA 미국 패키지 여행 직항 크루즈 헐리우드 인쳔출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0007', '미서부 LA 로스앤졀레스 패키지 미국 여행 직항 헐리우드 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0008', '로스앤졀레스 미국 미주여행 패키지 LA 여행 직항 크루즈 헐리우드 인쳔출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0009', '헐리우드사인 그리피스천문대 산테모니카피어 보네스비치 로데오드라이브 게티센터 로스앤졀레스 여행 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0001', 'LA 할리우드사인 그리피스천문대 산타모니카피어 베니스비치 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0002', '로스앤젤레스 할리우드명예의거리 돌비극장 베벌리힐스 패키지', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0003', 'LA 게티센터 월트디즈니 할리우드사인 할리우드명예의거리 투어', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0004', '로스앤젤레스 산타모니카피어 베니스비치 할리우드사인 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0005', 'LA 할리우드사인 게티센터 베벌리힐스 월트디즈니 투어', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0006', '로스앤젤레스 돌비극장 할리우드명예의거리 게티센터 패키지', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0007', 'LA 베니스비치 산타모니카피어 할리우드사인 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0008', '로스앤젤레스 게티센터 베벌리힐스 할리우드명예의거리 투어', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0009', 'LA 할리우드사인 돌비극장 그리피스천문대 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0010', '로스앤젤레스 산타모니카피어 베니스비치 게티센터 패키지', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0011', 'LA 베벌리힐스 월트디즈니 게티센터 할리우드사인 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0012', '로스앤젤레스 할리우드명예의거리 돌비극장 할리우드사인 투어', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0013', 'LA 산타모니카피어 베니스비치 할리우드명예의거리 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0014', '로스앤젤레스 게티센터 월트디즈니 베벌리힐스 투어', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0015', 'LA 할리우드사인 산타모니카피어 베니스비치 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0016', '로스앤젤레스 돌비극장 게티센터 할리우드명예의거리 패키지', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0017', 'LA 할리우드사인 베벌리힐스 게티센터 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0018', '로스앤젤레스 산타모니카피어 베니스비치 월트디즈니 투어', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0019', 'LA 할리우드명예의거리 돌비극장 게티센터 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_GPT_0020', '로스앤젤레스 그리피스천문대 할리우드사인 베벌리힐스 여행', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0001', '미국 샌프란시스코 패키지 라스베가스 그랜드캐년 미주여행 직항 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0002', '샌프란시스코 패키지 미국 라스베가스 그랜드캐년 미주여행 직항 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0003', '미주여행 샌프란시스코 미국 패키지 라스베가스 직항 그랜드캐년 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0004', '샌프란시스코 미국 미주여행 패키지 라스베가스 직항 그랜드캐년 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0005', '미국 패키지 샌프란시스코 라스베가스 미주여행 직항 그랜드캐년 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0006', '라스베가스 샌프란시스코 패키지 미국 미주여행 직항 그랜드캐년 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0007', '샌프란시스코 미주여행 미국 패키지 라스베가스 직항 그랜드캐년 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0008', '미국 미주여행 샌프란시스코 패키지 라스베가스 직항 그랜드캐년 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0009', '패키지 샌프란시스코 미국 라스베가스 미주여행 직항 그랜드캐년 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0010', '샌프란시스코 미국 패키지 미주여행 라스베가스 직항 그랜드캐년 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0011', '라스베가스 미국 샌프란시스코 패키지 미주여행 직항 그랜드캐년 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0012', '미국 샌프란시스코 미주여행 패키지 직항 라스베가스 그랜드캐년 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0013', '샌프란시스코 패키지 미주여행 미국 직항 라스베가스 그랜드캐년 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0014', '미주여행 미국 샌프란시스코 패키지 라스베가스 직항 그랜드캐년 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0015', '미국 라스베가스 샌프란시스코 패키지 미주여행 직항 그랜드캐년 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0016', '샌프란시스코 라스베가스 미국 패키지 미주여행 직항 그랜드캐년 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0017', '미주여행 패키지 미국 샌프란시스코 라스베가스 직항 그랜드캐년 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0018', '미국 샌프란시스코 라스베가스 미주여행 패키지 직항 그랜드캐년 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0019', '샌프란시스코 미국 미주여행 라스베가스 패키지 직항 그랜드캐년 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_CMK_0020', '패키지 미주여행 미국 샌프란시스코 라스베가스 직항 그랜드캐년 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0001', '코이트타워 롬바드스트리트 캘리포니아코스탈트레일 샌프란시스코 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0002', '요세미티국립공원 세콰이어 킹스캐년 피너클스 국립공원 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0003', '롬바드스트리트 코이트타워 캘리포니아코스탈트레일 샌프란시스코 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0004', '요세미티국립공원 피너클스 세콰이어 킹스캐년 국립공원 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0005', '캘리포니아코스탈트레일 코이트타워 롬바드스트리트 샌프란시스코 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0006', '세콰이어 킹스캐년 피너클스 국립공원 요세미티국립공원 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0007', '산호세 메세드 바이살리아 요세미티국립공원 샌프란시스코 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0008', '캘리포니아코스탈트레일 국립공원 코이트타워 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0009', '롬바드스트리트 코이트타워 국립공원 샌프란시스코 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0010', '요세미티국립공원 캘리포니아코스탈트레일 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0011', '코이트타워 샌프란시스코 롬바드스트리트 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0012', '세콰이어 킹스캐년 국립공원 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0013', '피너클스 국립공원 요세미티국립공원 샌프란시스코 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0014', '롬바드스트리트 캘리포니아코스탈트레일 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0015', '산호세 샌프란시스코 코이트타워 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0016', '메세드 바이살리아 국립공원 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0017', '피너클스 코이트타워 샌프란시스코 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0018', '세콰이어 국립공원 요세미티국립공원 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0019', '캘리포니아코스탈트레일 산호세 샌프란시스코 여행 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_MKL_0020', '롬바드스트리트 국립공원 샌프란시스코 패키지 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0001', '샌프란시스코 여행 8박10일 2026년 가을 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0002', '샌프란시스코 패키지 6월 7월 8월 여행 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0003', '9월 10월 하반기 샌프란시스코 여행 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0004', '6박8일 10박12일 7일 샌프란시스코 여행 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0005', '샌프란시스코 패키지 8박10일 하반기 여행 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0006', '2026년 샌프란시스코 여행 6월 7월 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0007', '8월 9월 가을 샌프란시스코 패키지 여행 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0008', '7월 10월 샌프란시스코 여행 6박8일 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0009', '샌프란시스코 8박10일 여행 2026년 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0010', '샌프란시스코 패키지 가을 10박12일 여행 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0011', '6월 8월 하반기 샌프란시스코 여행 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0012', '7일 6박8일 샌프란시스코 패키지 여행 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0013', '9월 2026년 샌프란시스코 여행 8박10일 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0014', '10박12일 7월 샌프란시스코 패키지 여행 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0015', '8월 6박8일 샌프란시스코 여행 가을 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0016', '10월 하반기 샌프란시스코 패키지 여행 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0017', '2026년 가을 샌프란시스코 여행 7일 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0018', '6월 9월 샌프란시스코 패키지 여행 8박10일 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0019', '7월 8월 샌프란시스코 여행 10박12일 직항 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_DMK_0020', '하반기 2026년 샌프란시스코 패키지 여행 6박8일 직항 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0001', '샌프란시스코여행 요세미티국립공원 캘리포니아코스탈트레일 세콰이어 킹스캐년 피너클스 국립공원 산호세 바이살리아 메세드 하이킹 한국인가이드 전일정가이드 인생여행 버킷리스트 가을단풍 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0002', '미주여행 샌프란시스코 요세미티국립공원 캘리포니아코스탈트레일 세콰이어 킹스캐년 꿈의여행 맞춤여행 전일정가이드 하이킹 버킷리스트 인생여행 가을단풍 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0003', '가족여행 샌프란시스코 캘리포니아코스탈트레일 요세미티국립공원 세콰이어 킹스캐년 피너클스 국립공원 전일정가이드 하이킹 맞춤여행 버킷리스트 꿈의여행 가을단풍 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0004', '효도여행 샌프란시스코 요세미티국립공원 세콰이어 킹스캐년 피너클스 국립공원 한국인가이드 맞춤여행 전일정가이드 하이킹 인생여행 꿈의여행 버킷리스트 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0005', '우정여행 샌프란시스코 요세미티국립공원 피너클스 세콰이어 킹스캐년 하이킹 맞춤여행 전일정가이드 인생여행 꿈의여행 가을단풍 버킷리스트 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0006', '졸업여행 샌프란시스코 요세미티국립공원 세콰이어 킹스캐년 피너클스 국립공원 산호세 메세드 바이살리아 한국인가이드 전일정가이드 맞춤여행 버킷리스트 인생여행 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0007', '맞춤여행 샌프란시스코 요세미티국립공원 캘리포니아코스탈트레일 세콰이어 킹스캐년 하이킹 한국인가이드 전일정가이드 꿈의여행 인생여행 버킷리스트 가을단풍 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0008', '꿈의여행 샌프란시스코 요세미티국립공원 피너클스 킹스캐년 세콰이어 국립공원 하이킹 한국인가이드 전일정가이드 맞춤여행 인생여행 가을단풍 버킷리스트 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0009', '인생여행 샌프란시스코 캘리포니아코스탈트레일 요세미티국립공원 세콰이어 킹스캐년 맞춤여행 전일정가이드 하이킹 버킷리스트 꿈의여행 가을단풍 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0010', '여행 샌프란시스코 요세미티국립공원 세콰이어 킹스캐년 피너클스 국립공원 한국인가이드 맞춤여행 전일정가이드 인생여행 꿈의여행 버킷리스트 인천출발 아시아나항공', 'SanFrancisco');
