-- City Titles Part 016 (1501-1600번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0018', '나이아가라 미동부 캐나다 미국 패키지 여행코스 인천출발 7월 나이아가라크루즈 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0019', '미국 캐나다 나이아가라 미동부 패키지 인천출발 8월 클리프턴힐 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0020', '캐나다 미국 나이아가라 미동부 패키지 여행코스 인천출발 하반기 나이아가라파크 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0001', '나이아가라폭포 나이아가라크루즈 스카일론타워 클리프턴힐 나이아가라파크 인천출발 6월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0002', '나이아가라크루즈 스카일론타워 클리프턴힐 나이아가라폭포 파크 인천출발 7월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0003', '스카일론타워 클리프턴힐 나이아가라파크 나이아가라폭포 크루즈 인천출발 8월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0004', '나이아가라파크 나이아가라폭포 스카일론타워 클리프턴힐 크루즈 인천출발 하반기 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0005', '클리프턴힐 나이아가라폭포 크루즈 스카일론타워 파크 인천출발 2026년 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0006', '나이아가라폭포 스카일론타워 파크 클리프턴힐 크루즈 인천출발 6월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0007', '나이아가라크루즈 파크 스카일론타워 나이아가라폭포 클리프턴힐 인천출발 7월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0008', '스카일론타워 파크 클리프턴힐 나이아가라크루즈 폭포 인천출발 8월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0009', '나이아가라폭포 파크 스카일론타워 클리프턴힐 크루즈 인천출발 하반기 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0010', '클리프턴힐 파크 나이아가라폭포 스카일론타워 크루즈 인천출발 2026년 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0011', '나이아가라폭포 크루즈 스카일론타워 파크 클리프턴힐 인천출발 09월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0012', '나이아가라크루즈 스카일론타워 파크 클리프턴힐 폭포 인천출발 6월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0013', '스카일론타워 나이아가라폭포 파크 클리프턴힐 크루즈 인천출발 7월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0014', '나이아가라파크 스카일론타워 나이아가라폭포 클리프턴힐 크루즈 인천출발 8월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0015', '클리프턴힐 스카일론타워 파크 나이아가라폭포 크루즈 인천출발 하반기 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0016', '나이아가라폭포 파크 스카일론타워 크루즈 클리프턴힐 인천출발 2026년 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0017', '나이아가라크루즈 파크 클리프턴힐 스카일론타워 폭포 인천출발 6월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0018', '스카일론타워 클리프턴힐 파크 나이아가라크루즈 폭포 인천출발 7월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0019', '나이아가라파크 클리프턴힐 스카일론타워 크루즈 폭포 인천출발 8월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_MKL_0020', '클리프턴힐 나이아가라파크 스카일론타워 폭포 크루즈 인천출발 하반기 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0001', '6월 인천출발 나이아가라 미국 캐나다 미동부 패키지 나이아가라폭포 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0002', '7월 인천출발 나이아가라 미동부 미국 캐나다 패키지 스카일론타워 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0003', '8월 인천출발 나이아가라 미국 캐나다 미동부 패키지 나이아가라크루즈 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0004', '하반기 인천출발 나이아가라 캐나다 미국 미동부 패키지 클리프턴힐 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0005', '2026년 인천출발 나이아가라 미국 캐나다 미동부 패키지 나이아가라파크 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0006', '6월 인천출발 미동부 미국 캐나다 나이아가라 패키지 폭포 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0007', '7월 인천출발 미동부 캐나다 미국 나이아가라 패키지 크루즈 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0008', '8월 인천출발 미동부 나이아가라 미국 캐나다 패키지 스카일론타워 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0009', '하반기 인천출발 미동부 캐나다 나이아가라 미국 패키지 클리프턴힐 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0010', '2026년 인천출발 미동부 나이아가라 캐나다 미국 패키지 파크 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0011', '6월 인천출발 나이아가라 패키지 미국 캐나다 미동부 폭포 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0012', '7월 인천출발 나이아가라 패키지 미동부 미국 캐나다 크루즈 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0013', '8월 인천출발 나이아가라 패키지 캐나다 미국 미동부 스카일론타워 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0014', '하반기 인천출발 나이아가라 패키지 미국 미동부 캐나다 클리프턴힐 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0015', '2026년 인천출발 나이아가라 패키지 미동부 캐나다 미국 파크 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0016', '09월 인천출발 나이아가라 미국 캐나다 미동부 패키지 폭포 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0017', '09월 인천출발 미동부 나이아가라 패키지 미국 캐나다 크루즈 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0018', '09월 인천출발 나이아가라 미동부 패키지 캐나다 미국 스카일론타워 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0019', '09월 인천출발 캐나다 미국 나이아가라 미동부 패키지 클리프턴힐 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_DMK_0020', '09월 인천출발 미동부 캐나다 나이아가라 미국 패키지 파크 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0001', '나이아가라폭포 나이아가라크루즈 스카일론타워 클리프턴힐 나이아가라파크 인천출발 6월 패키지 여행코스 미동부상품 홈쇼핑 폭포뷰 노팁 노옵션 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0002', '미국 캐나다 나이아가라 패키지 미동부 여행코스 인천출발 7월 나이아가라폭포 스카일론타워 나이아가라파크 폭포뷰 홈쇼핑 여행적기 노쇼핑 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0003', '나이아가라 미동부 미국 캐나다 패키지 인천출발 8월 나이아가라크루즈 스카일론타워 클리프턴힐 여행코스 미동부상품 폭포뷰 노옵션 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0004', '캐나다 나이아가라 미국 미동부 패키지 여행코스 인천출발 하반기 나이아가라폭포 클리프턴힐 파크 홈쇼핑 여행적기 노팁 휴양지 국외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0005', '미국 미동부 캐나다 나이아가라 패키지 인천출발 2026년 스카일론타워 나이아가라크루즈 여행코스 폭포뷰 노옵션 노쇼핑 휴양지 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0006', '나이아가라 미국 캐나다 미동부 패키지 여행코스 인천출발 6월 나이아가라폭포 스카일론타워 홈쇼핑 여행적기 노팁 노옵션 휴양지 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0007', '미동부 나이아가라 캐나다 미국 패키지 인천출발 7월 나이아가라크루즈 클리프턴힐 파크 여행코스 폭포뷰 노쇼핑 노옵션 휴양지 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0008', '캐나다 미동부 나이아가라 미국 패키지 여행코스 인천출발 8월 스카일론타워 파크 크루즈 홈쇼핑 폭포뷰 노팁 노옵션 휴양지 국외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0009', '나이아가라 미동부 미국 캐나다 패키지 인천출발 하반기 나이아가라폭포 파크 스카일론타워 여행코스 폭포뷰 노쇼핑 노옵션 휴양지 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0010', '미국 캐나다 미동부 나이아가라 패키지 인천출발 2026년 클리프턴힐 스카일론타워 크루즈 여행코스 폭포뷰 노팁 노옵션 휴양지 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0011', '나이아가라 미국 캐나다 미동부 패키지 인천출발 09월 나이아가라폭포 크루즈 스카일론타워 여행코스 폭포뷰 노옵션 노쇼핑 휴양지 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0012', '미동부 미국 캐나다 나이아가라 패키지 여행코스 인천출발 6월 파크 스카일론타워 클리프턴힐 홈쇼핑 폭포뷰 노팁 노옵션 휴양지 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0013', '캐나다 나이아가라 미동부 미국 패키지 인천출발 7월 나이아가라크루즈 파크 스카일론타워 여행코스 폭포뷰 노쇼핑 노옵션 휴양지 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0014', '나이아가라 미동부 캐나다 미국 패키지 인천출발 8월 나이아가라폭포 스카일론타워 파크 여행코스 폭포뷰 노옵션 노팁 휴양지 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0015', '미국 미동부 나이아가라 캐나다 패키지 인천출발 하반기 클리프턴힐 스카일론타워 크루즈 여행코스 폭포뷰 노쇼핑 노옵션 휴양지 국외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0016', '캐나다 미국 미동부 나이아가라 패키지 인천출발 2026년 파크 나이아가라폭포 클리프턴힐 여행코스 폭포뷰 노팁 노옵션 휴양지 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0017', '나이아가라 캐나다 미국 미동부 패키지 인천출발 6월 스카일론타워 파크 크루즈 여행코스 폭포뷰 노옵션 노쇼핑 휴양지 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0018', '미동부 캐나다 나이아가라 미국 패키지 인천출발 7월 나이아가라폭포 클리프턴힐 파크 여행코스 폭포뷰 노팁 노옵션 휴양지 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0019', '캐나다 미동부 미국 나이아가라 패키지 인천출발 8월 스카일론타워 크루즈 파크 여행코스 폭포뷰 노쇼핑 노옵션 휴양지 국외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_ML_0020', '나이아가라 미국 미동부 캐나다 패키지 인천출발 하반기 나이아가라크루즈 스카일론타워 파크 여행코스 폭포뷰 노팁 노옵션 휴양지 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0001', '미국 캐나다 패키지 미동부 09월 나이아가라 여행코스 인천출발 6월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0002', '캐나다 미국 미동부 패키지 09월 나이아가라 여행코스 인천출발 7월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0003', '미동부 미국 캐나다 패키지 09월 나이아가라 여행코스 인천출발 8월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0004', '나이아가라 미국 캐나다 미동부 09월 패키지 여행코스 인천출발 하반기 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0005', '캐나다 미동부 미국 나이아가라 09월 패키지 여행코스 인천출발 2026년 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0006', '미국 나이아가라 캐나다 미동부 09월 패키지 여행코스 인천출발 6월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0007', '나이아가라 캐나다 미국 미동부 09월 패키지 여행코스 인천출발 7월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0008', '미동부 캐나다 미국 나이아가라 09월 패키지 여행코스 인천출발 8월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0009', '나이아가라 미국 미동부 캐나다 09월 패키지 여행코스 인천출발 하반기 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0010', '미국 캐나다 미동부 나이아가라 09월 패키지 여행코스 인천출발 2026년 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0011', '캐나다 미국 미동부 나이아가라 09월 패키지 여행코스 인천출발 6월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0012', '미동부 나이아가라 미국 캐나다 09월 패키지 여행코스 인천출발 7월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0013', '나이아가라 미동부 캐나다 미국 09월 패키지 여행코스 인천출발 8월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0014', '캐나다 나이아가라 미동부 미국 09월 패키지 여행코스 인천출발 하반기 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0015', '미국 미동부 캐나다 나이아가라 09월 패키지 여행코스 인천출발 2026년 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0016', '나이아가라 미국 캐나다 미동부 09월 패키지 여행코스 인천출발 6월 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0017', '미동부 캐나다 나이아가라 미국 09월 패키지 여행코스 인천출발 7월 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0018', '나이아가라 캐나다 미동부 미국 09월 패키지 여행코스 인천출발 8월 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0019', '캐나다 미동부 나이아가라 미국 09월 패키지 여행코스 인천출발 하반기 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_SNK_0020', '미국 나이아가라 미동부 캐나다 09월 패키지 여행코스 인천출발 2026년 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0001', '미극 개나다 나이아거라 미동부 패키쥐 인쳔출발 6월 나이아거라폭포 여헹', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0002', '개나다 미극 나이아거라 패키쥐 미동부 여헹코스 인쳔출발 7월 스카일런타워 가졍여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0003', '미극 미동부 개나다 나이아거라 패키쥐 인쳔출발 8월 나이아가러크루즈 효도여헹', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0004', '나이아거라 미극 개나다 미동부 패키쥐 여헹코스 인쳔출발 하반기 클리프턴힐 해왜여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0005', '개나다 나이아거라 미동부 미극 패키쥐 인쳔출발 2026년 나이아거라파크 가졍여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0006', '미극 나이아거라 개나다 미동부 패키쥐 인쳔출발 6월 스카일런타워 효도여헹', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0007', '미동부 미극 개나다 나이아거라 패키쥐 여헹코스 인쳔출발 7월 나이아거라폭포 해왜여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0008', '개나다 미동부 미극 나이아거라 패키쥐 인쳔출발 8월 나이아가러크루즈 가졍여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0009', '나이아거라 미동부 미극 개나다 패키쥐 여헹코스 인쳔출발 하반기 클리프턴힐 효도여헹', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0010', '미극 개나다 미동부 나이아거라 패키쥐 인쳔출발 2026년 나이아거라파크 해왜여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0011', '미극 개나다 패키쥐 미동부 09월 나이아거라 여헹코스 인쳔출발 6월 해왜여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0012', '개나다 미극 미동부 패키쥐 09월 나이아거라 여헹코스 인쳔출발 7월 가졍여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0013', '미동부 미극 개나다 패키쥐 09월 나이아거라 여헹코스 인쳔출발 8월 효도여헹', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0014', '나이아거라 미극 개나다 미동부 09월 패키쥐 여헹코스 인쳔출발 하반기 해왜여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0015', '개나다 미동부 미극 나이아거라 09월 패키쥐 여헹코스 인쳔출발 2026년 가졍여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0016', '미극 나이아거라 개나다 미동부 09월 패키쥐 여헹코스 인쳔출발 6월 효도여헹', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_OT_0017', '나이아거라 개나다 미극 미동부 09월 패키쥐 여헹코스 인쳔출발 7월 해왜여행', 'NiagaraFalls');
