-- City Titles Part 115 (11401-11500번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0005', '파타야 항공권 여행 해외 날씨 직항 인천출발', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0006', '파타야 항공권 날씨 여행 해외 인천출발 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0007', '파타야 날씨 해외 여행 직항 인천출발 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0008', '파타야 인천출발 날씨 항공권 여행 직항 해외', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0009', '파타야 여행 직항 인천출발 날씨 해외 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0010', '파타야 인천출발 해외 날씨 직항 여행 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0011', '파타야 직항 해외 날씨 항공권 인천출발 여행', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0012', '파타야 항공권 인천출발 직항 여행 해외 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0013', '파타야 인천출발 여행 직항 항공권 해외 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0014', '파타야 날씨 인천출발 항공권 해외 직항 여행', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0015', '파타야 항공권 여행 날씨 직항 해외 인천출발', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0016', '파타야 해외 여행 항공권 날씨 인천출발 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0017', '파타야 해외 직항 날씨 여행 항공권 인천출발', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0018', '파타야 인천출발 해외 직항 여행 항공권 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0019', '파타야 항공권 해외 여행 인천출발 직항 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0020', '파타야 직항 날씨 인천출발 여행 해외 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0001', '파타야 방콕 인천출발 치앙마이 해외 항공권 직항 푸켓 태국 날씨 여행', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0002', '파타야 태국 치앙마이 방콕 날씨 항공권 푸켓 여행 인천출발 직항 해외', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0003', '파타야 방콕 인천출발 태국 날씨 직항 푸켓 여행 치앙마이 해외 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0004', '파타야 인천출발 푸켓 치앙마이 직항 해외 날씨 항공권 태국 방콕 여행', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0005', '파타야 항공권 치앙마이 태국 여행 인천출발 해외 푸켓 직항 방콕 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0006', '파타야 직항 푸켓 날씨 태국 항공권 인천출발 여행 방콕 치앙마이 해외', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0007', '파타야 인천출발 태국 방콕 푸켓 직항 날씨 여행 항공권 치앙마이 해외', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0008', '파타야 푸켓 항공권 직항 치앙마이 날씨 태국 해외 인천출발 방콕 여행', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0009', '파타야 여행 해외 치앙마이 방콕 푸켓 날씨 태국 항공권 직항 인천출발', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0010', '파타야 여행 태국 항공권 해외 날씨 푸켓 방콕 인천출발 직항 치앙마이', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0011', '파타야 날씨 항공권 해외 치앙마이 방콕 여행 인천출발 푸켓 태국 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0012', '파타야 인천출발 치앙마이 날씨 해외 항공권 여행 푸켓 방콕 직항 태국', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0013', '파타야 인천출발 날씨 푸켓 항공권 직항 치앙마이 방콕 해외 태국 여행', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0014', '파타야 여행 직항 항공권 치앙마이 태국 인천출발 방콕 해외 날씨 푸켓', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0015', '파타야 방콕 항공권 여행 치앙마이 인천출발 직항 푸켓 해외 태국 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0016', '파타야 항공권 방콕 여행 직항 인천출발 날씨 치앙마이 푸켓 태국 해외', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0017', '파타야 날씨 푸켓 태국 항공권 해외 방콕 인천출발 치앙마이 직항 여행', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0018', '파타야 항공권 방콕 인천출발 푸켓 직항 치앙마이 해외 날씨 여행 태국', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0019', '파타야 여행 태국 날씨 치앙마이 직항 해외 인천출발 방콕 항공권 푸켓', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0020', '파타야 날씨 여행 태국 푸켓 직항 인천출발 해외 치앙마이 항공권 방콕', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0002', '브라질 이과수폭포 아르헨티나 모레노빙하 볼리비아 소금호수 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0003', '페루 마추픽추 쿠스코 볼리비아 우유니 아르헨티나 브라질 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0004', '남미일주 페루 볼리비아 아르헨티나 브라질 소금사막 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0005', '페루 마추픽추 아르헨티나 모레노빙하 브라질 리오데자네이로 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0006', '남미일주 페루 우유니소금사막 아르헨티나 브라질 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0007', '페루 볼리비아 우유니 아르헨티나 브라질 남미 패키지여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0008', '아르헨티나 모레노빙하 페루 마추픽추 브라질 이과수폭포 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0009', '브라질 리오 아르헨티나 부에노스아이레스 페루 볼리비아 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0010', '남미일주 페루 볼리비아 브라질 아르헨티나 소금사막 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0011', '페루 마추픽추 볼리비아 우유니 아르헨티나 브라질 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0012', '브라질 리오데자네이로 아르헨티나 모레노빙하 페루 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0013', '남미일주 볼리비아 우유니소금사막 페루 마추픽추 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0014', '아르헨티나 모레노빙하 브라질 이과수폭포 페루 쿠스코 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0015', '브라질 아르헨티나 페루 볼리비아 소금사막 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0016', '페루 마추픽추 볼리비아 소금호수 아르헨티나 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0017', '남미일주 브라질 아르헨티나 페루 볼리비아 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0018', '페루 쿠스코 마추픽추 아르헨티나 브라질 남미여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0019', '남미일주 페루 볼리비아 아르헨티나 브라질 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0020', '페루 마추픽추 브라질 아르헨티나 볼리비아 패키지여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0003', '우유니소금사막 소금호수 마추픽추 이과수폭포 페루 볼리비아 아르헨티나 브라질 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0004', '모레노빙하 파타고니아 마추픽추 토레스델파이네 아르헨티나 브라질 볼리비아 남미핵심일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0012', '소금호수 마추픽추 우유니소금사막 이과수폭포 페루 볼리비아 아르헨티나 브라질 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0013', '마추픽추 파타고니아 토레스델파이네 모레노빙하 아르헨티나 브라질 볼리비아 페루 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0018', '모레노빙하 마추픽추 파타고니아 소금호수 아르헨티나 브라질 볼리비아 페루 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0019', '마추픽추 우유니소금사막 이과수폭포 아르헨티나 브라질 볼리비아 페루 남미핵심일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0011', '홈쇼핑 남미일주 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아 인천출발 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0015', '홈쇼핑 남미여행 인천출발 아르헨티나 브라질 볼리비아 페루 파타고니아 마추픽추 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0016', '대한항공 남미핵심일주 아르헨티나 브라질 볼리비아 페루 모레노빙하 마추픽추 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0017', '남미일주 홈쇼핑 인천출발 아르헨티나 브라질 볼리비아 페루 파타고니아 9박13일 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0018', '추석연휴 pick 남미핵심일주 아르헨티나 브라질 볼리비아 페루 마추픽추 모레노빙하 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0019', '대한항공 남미패키지 21일 일정 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0020', '홈쇼핑 남미핵심일주 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 소금호수 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0009', '하바나 올드카 시승 체험 메트로폴리타나 대성당 관람 칸쿤 호텔존 올인클루시브 숙박 결합 8박10일 완전일주 여행 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0010', '멕시코시티 소칼로광장 시내 관광과 쿠바 하바나 문화 체험 칸쿤 호텔존 해변 휴양 국적기 직항 10일 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0011', '아즈텍문명 마야문명 체험 결합 멕시코 쿠바 완전일주 칸쿤 올인클루시브 숙박 하바나 올드카 투어 9일 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0012', '칸쿤 리비에라마야 해변 휴양과 하바나 헤밍웨이 박물관 투어 인천출발 대한항공 국적기 직항 8박10일 패키지 일정', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0013', '멕시코 칸쿤 스칼렛 아르떼 공연 관람 호텔존 리조트 숙박 쿠바 하바나 올드타운 시내 관광 포함된 9일 완전일주 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0014', '쿠바 프란시스코광장 탐방과 헤밍웨이 박물관 문화 체험 멕시코 칸쿤 올인클루시브 숙박 마야문명 탐방 포함 10일 투어', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0015', '인천출발 국적기 직항 멕시코 아즈텍문명 탐방 쿠바 하바나 올드카 투어 칸쿤 호텔존 해양 액티비티 8박10일 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0016', '대한항공 국적기 직항 중미 2개국 일주 쿠바 멕시코 칸쿤 마야문명 아즈텍문명 체험 올인클루시브 숙박 9일 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_ML_0017', '아시아나 항공 직항 인천출발 멕시코시티 쿠바 하바나 칸쿤 호텔존 올인클루시브 완전일주 10일 일정 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0019', '캐나다 미극 패키지 여햄 아시아나항공 대한항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0020', '미극 캐나다 여행 패키지 인천출발 대한항공 아시아나항공 항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0001', '퀘벡 몬트리올 토론토 나이아가라 캐나다동부 패키지여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0002', '퀘벡 구시가지 샤토프롱트낙 몬트리올 캐나다 패키지 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0003', '퀘벡 샤토프롱트낙 몬트리올 나이아가라 토론토 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0004', '퀘벡 몬트리올 토론토 캐나다 나이아가라 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0005', '퀘벡 구시가지 샤토프롱트낙 캐나다동부 몬트리올 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0006', '퀘벡 토론토 나이아가라 몬트리올 캐나다 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0007', '퀘벡 구시가지 샤토프롱트낙 몬트리올 토론토 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0008', '퀘벡 몬트리올 캐나다 나이아가라 토론토 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0009', '퀘벡 샤토프롱트낙 구시가지 몬트리올 캐나다여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0010', '퀘벡 몬트리올 토론토 나이아가라 캐나다 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0011', '퀘벡 구시가지 샤토프롱트낙 캐나다동부 패키지 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0012', '퀘벡 몬트리올 토론토 나이아가라 캐나다동부여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0013', '퀘벡 샤토프롱트낙 구시가지 몬트리올 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0014', '퀘벡 토론토 캐나다동부 몬트리올 패키지 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0015', '퀘벡 몬트리올 나이아가라 토론토 패키지 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0016', '퀘벡 샤토프롱트낙 캐나다 몬트리올 여행 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0017', '퀘벡 구시가지 샤토프롱트낙 캐나다동부 투어', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0018', '퀘벡 몬트리올 나이아가라 토론토 캐나다여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0019', '퀘벡 샤토프롱트낙 구시가지 캐나다동부 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_GPT_0020', '퀘벡 몬트리올 토론토 나이아가라 캐나다여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0010', '돌비극장 헐리우드명예의거리 베벌리헬스 로데오드라이브 게티센터 로스앤졀레스 패키지 인쳔출발 아시아나항공', 'LosAngeles');
