-- City Titles Part 071 (7001-7100번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0013', '여행 베이징 상하이 구채구 충칭 샤먼 하이난 백두산 장가계', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0014', '여행 백두산 샤먼 구채구 장가계 몽골 베이징 충칭 하이난', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0015', '여행 장가계 상하이 몽골 구채구 샤먼 베이징 하이난 백두산', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0016', '여행 베이징 상하이 충칭 구채구 장가계 몽골 샤먼 백두산', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0017', '여행 장가계 하이난 백두산 샤먼 베이징 몽골 상하이 구채구', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0018', '여행 샤먼 충칭 장가계 하이난 백두산 베이징 몽골 상하이', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0019', '여행 몽골 충칭 샤먼 상하이 구채구 장가계 베이징 하이난', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0020', '여행 백두산 구채구 베이징 샤먼 장가계 몽골 상하이 충칭', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0021', '패키지 베이징 백두산 충칭 샤먼 몽골 하이난 장가계 상하이', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0022', '패키지 충칭 백두산 장가계 하이난 상하이 샤먼 베이징', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0023', '패키지 장가계 구채구 샤먼 충칭 상하이 몽골 하이난 백두산', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0024', '패키지 베이징 구채구 백두산 샤먼 상하이 장가계 하이난', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0025', '패키지 샤먼 구채구 상하이 몽골 장가계 백두산 충칭 하이난', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0026', '패키지 상하이 백두산 하이난 장가계 구채구 충칭 샤먼 몽골', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0027', '패키지 몽골 충칭 상하이 백두산 장가계 베이징 샤먼 하이난', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0028', '패키지 몽골 구채구 하이난 충칭 장가계 샤먼 백두산 상하이', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0029', '패키지 샤먼 장가계 하이난 백두산 상하이 몽골 베이징 충칭', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0030', '패키지 구채구 백두산 장가계 충칭 하이난 몽골 상하이 샤먼', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0031', '패키지 장가계 하이난 샤먼 충칭 몽골 구채구 백두산 상하이', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0032', '패키지 백두산 몽골 상하이 충칭 장가계 구채구 베이징 샤먼', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0033', '패키지 베이징 충칭 하이난 백두산 구채구 샤먼 몽골 상하이', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0034', '패키지 상하이 충칭 몽골 베이징 백두산 샤먼 하이난 구채구', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0035', '패키지 구채구 몽골 베이징 하이난 장가계 샤먼 충칭 백두산', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0036', '패키지 장가계 구채구 몽골 베이징 샤먼 하이난 상하이 충칭', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0037', '패키지 베이징 구채구 상하이 장가계 하이난 백두산 몽골', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0038', '패키지 충칭 상하이 샤먼 장가계 구채구 베이징 몽골 백두산', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0039', '패키지 상하이 베이징 충칭 구채구 장가계 백두산 하이난', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HIN_NCK_0040', '패키지 몽골 하이난 구채구 상하이 샤먼 베이징 충칭 장가계', 'Hainan');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0001', '계림 직항 날씨 관광 중국 가격 항공권 양삭 패키지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0002', '계림 항공권 가격 관광 양삭 직항 패키지 여행 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0003', '계림 가격 관광 여행 항공권 직항 날씨 중국 패키지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0004', '계림 양삭 직항 날씨 여행 항공권 가격 중국 패키지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0005', '계림 양삭 여행 패키지 날씨 관광 항공권 중국 가격', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0006', '계림 중국 관광 날씨 패키지 직항 항공권 양삭 여행', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0007', '계림 가격 패키지 양삭 항공권 여행 직항 날씨 관광', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0008', '계림 날씨 항공권 직항 패키지 여행 가격 관광 중국', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0009', '계림 중국 날씨 관광 직항 가격 항공권 패키지 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0010', '계림 관광 중국 양삭 직항 패키지 가격 항공권 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0011', '계림 직항 관광 항공권 가격 양삭 패키지 중국 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0012', '계림 여행 패키지 양삭 날씨 항공권 중국 가격 직항', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0013', '계림 관광 패키지 중국 직항 양삭 여행 항공권 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0014', '계림 항공권 여행 직항 가격 중국 날씨 관광 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0015', '계림 양삭 가격 여행 날씨 관광 패키지 직항 항공권', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0016', '계림 여행 직항 양삭 관광 항공권 패키지 가격 중국', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0017', '계림 여행 패키지 중국 양삭 가격 직항 관광 항공권', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0018', '계림 관광 날씨 가격 항공권 패키지 여행 중국 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0019', '계림 직항 여행 양삭 관광 가격 날씨 항공권 중국', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_CMK_0020', '계림 날씨 패키지 양삭 중국 여행 가격 항공권 관광', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0001', '계림 패키지 중국 직항 날씨 가격 항공권 무비자여행', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0002', '계림 직항 이강유람 중국 은자암동굴 관광 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0003', '계림 관광 가격 양삭 항공권 직항 은자암동굴', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0004', '계림 은자암동굴 패키지 서가재래시장 항공권 이강유람', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0005', '계림 은자암동굴 패키지 항공권 날씨 직항 이강유람', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0006', '계림 은자암동굴 항공권 날씨 무비자여행 패키지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0007', '계림 관광 중국 은자암동굴 패키지 무비자여행 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0008', '계림 서가재래시장 중국 은자암동굴 가격 항공권', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0009', '계림 양삭 가격 무비자여행 이강유람 은자암동굴', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0010', '계림 가격 날씨 관광 패키지 항공권 중국 직항', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0011', '계림 항공권 무비자여행 서가재래시장 관광 직항 가격', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0012', '계림 양삭 은자암동굴 중국 관광 이강유람', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0013', '계림 항공권 무비자여행 중국 이강유람 서가재래시장', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0014', '계림 관광 직항 날씨 이강유람 은자암동굴 항공권', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0015', '계림 서가재래시장 패키지 은자암동굴 항공권 이강유람', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0016', '계림 가격 무비자여행 직항 서가재래시장 날씨 관광', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0017', '계림 무비자여행 직항 패키지 서가재래시장 가격 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0018', '계림 중국 날씨 무비자여행 관광 은자암동굴 직항', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0019', '계림 직항 양삭 가격 중국 항공권 서가재래시장', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0020', '계림 중국 이강유람 항공권 무비자여행 양삭 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0021', '계림 양삭 중국 관광 은자암동굴 직항 가격 항공권', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0022', '계림 양삭 이강유람 패키지 무비자여행 중국', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0023', '계림 항공권 날씨 관광 가격 은자암동굴 무비자여행', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0024', '계림 무비자여행 은자암동굴 중국 날씨 관광 패키지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0025', '계림 가격 중국 항공권 날씨 이강유람 무비자여행', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0026', '계림 중국 은자암동굴 직항 무비자여행 서가재래시장', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0027', '계림 이강유람 항공권 패키지 서가재래시장 중국 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0028', '계림 직항 이강유람 패키지 서가재래시장 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0029', '계림 은자암동굴 이강유람 가격 양삭 무비자여행 직항', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_MKL_0030', '계림 양삭 이강유람 은자암동굴 무비자여행 항공권', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0001', '11월 가격 날씨 무비자 관광 패키지 항공권 여행', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0002', '11월 가격 직항 무비자 관광 패키지 중국 항공권', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0003', '11월 중국 직항 양삭 계림 날씨 관광 항공권', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0004', '11월 중국 계림 양삭 무비자 날씨 직항 관광', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0005', '11월 항공권 직항 관광 계림 가격 중국 무비자', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0006', '11월 중국 양삭 가격 여행 패키지 계림 무비자', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0007', '11월 패키지 계림 무비자 중국 날씨 직항 가격', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0008', '11월 패키지 관광 계림 여행 항공권 직항 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0009', '11월 패키지 직항 가격 양삭 관광 날씨 무비자', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0010', '11월 가격 여행 무비자 중국 관광 양삭 직항', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0011', '11월 날씨 여행 중국 직항 관광 계림 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0012', '11월 항공권 여행 양삭 관광 직항 가격 계림', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0013', '11월 직항 관광 여행 항공권 가격 패키지 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0014', '11월 관광 여행 무비자 패키지 가격 계림 중국', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0015', '11월 중국 무비자 직항 여행 항공권 패키지 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0016', '11월 양삭 패키지 중국 무비자 관광 가격 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0017', '11월 직항 날씨 항공권 여행 중국 무비자 계림', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0018', '11월 여행 가격 날씨 무비자 양삭 관광 직항', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0019', '11월 관광 여행 무비자 패키지 가격 계림 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0020', '11월 중국 관광 직항 양삭 무비자 패키지 항공권', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0021', '11월 패키지 관광 무비자 직항 항공권 여행 가격', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__GUILIN_DMK_0022', '11월 양삭 여행 관광 직항 날씨 계림 항공권', 'Guilin');
