-- City Titles Part 019 (1801-1900번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0014', '남미일주 패키지 18일 투어 마추픽추 파타고니아 아르헨티나 브라질 볼리비아 페루', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0015', '남미핵심일주 19일 일정 아르헨티나 브라질 페루 볼리비아 마추픽추 이과수폭포 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0016', '남미여행 13일 코스 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0017', '남미일주 패키지 12일 여행 아르헨티나 브라질 볼리비아 페루 모레노빙하 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0018', '남미핵심일주 21일 투어 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 소금호수', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0019', '남미여행 좋은시기 9박13일 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0020', '남미일주 패키지 2026년11월 인천출발 아르헨티나 브라질 볼리비아 페루 파타고니아 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0001', '남미일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 투어 가족여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0002', '남미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 우유니소금사막 파타고니아 크루즈', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0003', '남미여행 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 이과수폭포 홈쇼핑 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0004', '남미일주 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 소금호수 트레킹 국적기 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0005', '남미핵심일주 아르헨티나 브라질 볼리비아 페루 마추픽추 모레노빙하 스위트룸 패키지 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0006', '남미여행 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 항공권 비용 경비', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0007', '남미일주 투어 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아 대한항공 국적기 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0008', '남미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 이과수폭포 가족여행 우정관광', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0009', '남미여행 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 모레노빙하 크루즈 홈쇼핑', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0010', '남미일주 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아 항공권 아시아나항공 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0011', '남미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 우유니소금사막 항공 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0012', '남미여행 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 소금호수 가족여행 스위트룸', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0013', '남미일주 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 모레노빙하 파타고니아 트레킹', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0014', '남미핵심일주 투어 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아 홈쇼핑 아시아나항공', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0015', '남미여행 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 항공권 경비 비용 포함', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0016', '남미일주 아르헨티나 브라질 볼리비아 페루 마추픽추 소금호수 우유니소금사막 크루즈 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0017', '남미핵심일주 아르헨티나 브라질 볼리비아 페루 마추픽추 이과수폭포 트레킹 가족여행 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0018', '남미여행 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아 국적기 스위트룸 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0019', '남미일주 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 모레노빙하 아시아나항공 홈쇼핑', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_ML_0020', '남미핵심일주 투어 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아 항공권 대한항공 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0001', '추석연휴 남미일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0002', '대한항공 남미핵심일주 9박13일 패키지 마추픽추 우유니소금사막 볼리비아 페루 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0003', '홈쇼핑 남미일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 파타고니아 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0004', '남미핵심일주 패키지 마추픽추 이과수폭포 아르헨티나 브라질 볼리비아 페루', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0005', '남미패키지 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아 항공권', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0006', '추석연휴 홈쇼핑 남미여행 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 관광일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0007', '대한항공 남미일주 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 모레노빙하 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0008', '남미핵심일주 홈쇼핑 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0009', '대한항공 남미일정 아르헨티나 브라질 볼리비아 페루 마추픽추 투어 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0010', '추석연휴 남미핵심일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0012', '대한항공 남미핵심일주 17일 투어 아르헨티나 브라질 볼리비아 페루 마추픽추 여행일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0013', '중남미일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 17일 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_SNK_0014', '추석연휴 부산출발 남미핵심일주 아르헨티나 브라질 볼리비아 페루 마추픽추 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0001', '나미일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽쥬 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0002', '남미핵심일주 패키지 아르젠티나 브라질 볼리비아 페루 우유니소검사막 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0003', '여햄 패키지 남미일주 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0004', '남미핵심일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 모레노빙하', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0005', '남미여행 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 토레스델파이네', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0006', '남미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 소금호수 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0007', '남미일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 이과수폿포', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0008', '남미핵심일주 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽쥬 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0009', '남미여햄 패키지 아르헨티나 브라질 볼리비아 페루 우유니소금사막 이과수폭포', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0010', '남미일주 인천출발 아르헨티나 브라질 볼리비아 페루 모레노빙하 토레스델파이네', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0011', '남미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 소검호수', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0012', '남미일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 우유니소금사막', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0013', '남미핵심여행 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0014', '남미일주 인천출발 아르헨티나 브라질 볼리비아 페루 모레노빙하 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0015', '남미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 이과수폭포 마추픽쥬', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0016', '남미일주 투어 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 소금호수', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0017', '납미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0019', '남미핵심일주 아르헨티나 브라질 볼리비아 페루 모레노빙하 마추픽쥬 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_OT_0020', '남미여햄 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 토레스델파이네', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_GPT_0001', '남미일주 페루 마추픽추 우유니소금사막 이과수폭포 아르헨티나 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0001', '장가계 여행 힐링 항공권 원가계 패키지 추석연휴 중국', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0002', '장가계 항공권 힐링 원가계 여행 패키지 추석연휴 중국', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0003', '장가계 추석연휴 중국 패키지 원가계 항공권 힐링 여행', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0004', '장가계 추석연휴 항공권 중국 여행 원가계 패키지 힐링', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0005', '장가계 힐링 여행 중국 패키지 항공권 원가계 추석연휴', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0006', '장가계 여행 중국 패키지 원가계 추석연휴 항공권 힐링', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0007', '장가계 원가계 추석연휴 항공권 힐링 패키지 중국 여행', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0008', '장가계 원가계 여행 패키지 추석연휴 힐링 중국 항공권', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0009', '장가계 힐링 중국 항공권 추석연휴 여행 패키지 원가계', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0010', '장가계 추석연휴 중국 여행 패키지 힐링 항공권 원가계', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0011', '장가계 원가계 힐링 중국 항공권 패키지 여행 추석연휴', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0012', '장가계 항공권 힐링 추석연휴 중국 원가계 여행 패키지', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0013', '장가계 원가계 추석연휴 힐링 중국 패키지 여행 항공권', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0014', '장가계 힐링 원가계 패키지 추석연휴 항공권 여행 중국', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0015', '장가계 힐링 원가계 여행 중국 추석연휴 패키지 항공권', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0016', '장가계 중국 추석연휴 힐링 원가계 여행 패키지 항공권', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0017', '장가계 항공권 원가계 중국 여행 패키지 추석연휴 힐링', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0018', '장가계 중국 여행 추석연휴 원가계 힐링 패키지 항공권', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0019', '장가계 힐링 추석연휴 항공권 원가계 여행 중국 패키지', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_CMK_0020', '장가계 힐링 추석연휴 중국 항공권 원가계 여행 패키지', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0001', '장가계 천문산 추석연휴 힐링 패키지 여행 항공권', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0002', '장가계 항공권 추석연휴 72기루 중국 유리잔도 원가계', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0003', '장가계 유리잔도 중국 72기루 천문산 추석연휴 힐링', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0004', '장가계 추석연휴 천문산 힐링 원가계 72기루 패키지', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0005', '장가계 72기루 원가계 유리잔도 항공권 천문산 추석연휴', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0006', '장가계 천문산 여행 유리잔도 추석연휴 중국 힐링 항공권', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0007', '장가계 유리잔도 여행 중국 항공권 원가계 천문산', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0008', '장가계 72기루 천문산 유리잔도 여행 항공권 원가계', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0009', '장가계 72기루 패키지 항공권 중국 추석연휴 유리잔도', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0010', '장가계 힐링 중국 원가계 패키지 72기루 항공권', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0011', '장가계 72기루 원가계 여행 중국 천문산 추석연휴', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0012', '장가계 여행 추석연휴 중국 천문산 72기루 원가계', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0013', '장가계 힐링 유리잔도 천문산 항공권 72기루 추석연휴', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0014', '장가계 원가계 추석연휴 힐링 72기루 중국 여행 항공권', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0015', '장가계 힐링 항공권 중국 원가계 여행 패키지 유리잔도', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0016', '장가계 추석연휴 패키지 여행 원가계 항공권 중국', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0017', '장가계 추석연휴 천문산 중국 여행 패키지 72기루', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0018', '장가계 여행 추석연휴 항공권 힐링 72기루 유리잔도', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0019', '장가계 원가계 힐링 천문산 여행 유리잔도 72기루', 'Zhangjiajie');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ZHANG_MKL_0020', '장가계 천문산 힐링 원가계 72기루 항공권 유리잔도', 'Zhangjiajie');
