-- City Titles Part 018 (1701-1800번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0007', '중미 멕시코 쿠바 칸쿤 패키지 여행 인천출발 카리브해 올인클루시브', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0008', '멕시코 쿠바 칸쿤 여행 인천출발 국적기 아시아나 항공 완전일주', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0009', '쿠바 멕시코시티 칸쿤 패키지 인천출발 노팁 호텔존', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0010', '중남미 멕시코 쿠바 칸쿤 여행 인천출발 하바나올드카 아즈텍문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0011', '멕시코 쿠바 칸쿤 패키지 인천출발 스칼렛아르떼 카리브해', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0012', '쿠바 멕시코 칸쿤 여행 인천출발 국적기 항공 노쇼핑', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0013', '중미 멕시코 쿠바 칸쿤 패키지 여행 인천출발 아즈텍문명 마야문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0014', '멕시코 쿠바 칸쿤 여행 인천출발 국적기 직항 올인클루시브', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0015', '쿠바 멕시코시티 칸쿤 패키지 인천출발 노팁 하바나올드카', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0016', '중남미 멕시코 쿠바 칸쿤 여행 인천출발 아즈텍문명 호텔존', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0017', '멕시코 쿠바 칸쿤 패키지 인천출발 카리브해 국적기 직항', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0018', '쿠바 멕시코 칸쿤 여행 인천출발 아시아나 대한항공', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0019', '중미 멕시코 쿠바 칸쿤 패키지 여행 인천출발 스칼렛아르떼', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_SNK_0020', '멕시코 쿠바 칸쿤 여행 인천출발 국적기 항공 완전일주', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0002', '멕시코 쿠바 칸쿤 여햄 인천출발 국적기 항공 하바나올드카', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0003', '쿠바 멕시코시티 칸쿤 팩키지 인천출발 노쇼핑 노팁 카리브해', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0004', '중남미 멕시코 쿠바 칸쿤 여햄 인천출발 호텔존 스칼렛아르테', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0005', '멕시코 쿠바 칸쿤 팩키지 인천출발 국적기 직항 아시아나', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0006', '쿠바 멕시코 칸쿤 여햄 인천출발 하바나올드카 아즈텍문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0007', '중미 멕시코 쿠바 칸쿤 팩키지 여햄 인천출발 카리브해', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0008', '멕시코 쿠바 칸쿤 여햄 인천출발 국적기 아시아나 완전일주', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0009', '쿠바 멕시코시티 칸쿤 팩키지 인천출발 노팁 호텔존', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0010', '중남미 멕시코 쿠바 칸쿤 여햄 인천출발 하바나올드카', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0011', '멕시코 쿠바 칸쿤 팩키지 인천출발 스칼렛아르떼', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0012', '쿠바 멕시코 칸쿤 여햄 인천출발 국적기 항공 노쇼핑', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0013', '중미 멕시코 쿠바 칸쿤 팩키지 여햄 인천출발 아즈텍문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0014', '멕시코 쿠바 칸쿤 여햄 인천출발 국적기 직항', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0015', '쿠바 멕시코시티 칸쿤 팩키지 인천출발 노팁', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0016', '중남미 멕시코 쿠바 칸쿤 여햄 인천출발 아즈텍문명', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0017', '멕시코 쿠바 칸쿤 팩키지 인천출발 카리브해', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0018', '쿠바 멕시코 칸쿤 여햄 인천출발 아시아나', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0019', '중미 멕시코 쿠바 칸쿤 팩키지 여햄 인천출발', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_OT_0020', '멕시코 쿠바 칸쿤 여햄 인천출발 국적기', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0001', '쿠바 아바나 올드타운 멕시코 칸쿤 리비에라마야 패키지 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0002', '멕시코시티 소칼로광장 메트로폴리타나대성당 코요아칸 쿠바 아바나', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0003', '칸쿤 리비에라마야 올인클루시브 하바나올드카 멕시코 쿠바 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0004', '쿠바 하바나 헤밍웨이박물관 멕시코 칸쿤 리조트 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0005', '멕시코 칸쿤 카리브해 호텔존 리비에라마야 쿠바 패키지여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0006', '중미일주 멕시코 쿠바 칸쿤 아바나 리비에라마야 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0007', '쿠바 멕시코 칸쿤 아즈텍문명 마야문명 하바나여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0008', '멕시코 칸쿤 쿠바 아바나 올드카 리조트 올인클루시브', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0009', '쿠바 멕시코 칸쿤 하바나 헤밍웨이박물관 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0010', '중미 2개국 멕시코 쿠바 칸쿤 아바나 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0011', '칸쿤 멕시코시티 소칼로광장 쿠바 아바나 올드카 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0012', '쿠바 멕시코 칸쿤 리비에라마야 리조트 패키지여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0013', '쿠바 아바나 헤밍웨이박물관 멕시코 칸쿤 올인클루시브', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0014', '멕시코 칸쿤 카리브해 리비에라마야 쿠바 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0015', '중미여행 멕시코 쿠바 칸쿤 아바나 리조트 일정', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0016', '쿠바 멕시코 칸쿤 리비에라마야 호텔존 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0017', '칸쿤 멕시코 쿠바 아즈텍문명 마야문명 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0018', '쿠바 아바나 올드타운 멕시코 칸쿤 리조트 패키지', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0019', '멕시코 칸쿤 리비에라마야 쿠바 하바나여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA3C_GPT_0020', '중미 2개국 쿠바 멕시코 칸쿤 패키지 여행', 'CentralAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0001', '남미일주 패키지 남미핵심일주 노쇼핑 노옵션 노팁 아르헨티나 브라질 볼리비아 페루', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0002', '중남미 핵심4국 핵심3국 남미여행 패키지 아르헨티나 브라질 볼리비아 페루 관광지 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0003', '남미일주 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 남미핵심일주 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0004', '노쇼핑 노옵션 노팁 남미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 중남미여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0005', '아르헨티나 브라질 볼리비아 페루 핵심4국 남미핵심일주 패키지 남미여행 인천출발', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0006', '남미일주 패키지 남미핵심일정 노쇼핑 노옵션 노팁 아르헨티나 브라질 볼리비아 페루', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0007', '남미여행 남미일주 패키지 남미핵심일주 아르헨티나 브라질 볼리비아 페루 중남미 핵심투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0008', '패키지 남미핵심일주 노쇼핑 노옵션 노팁 아르헨티나 브라질 볼리비아 페루 남미투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0009', '남미 남미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 중남미 핵심4국 관광여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0010', '남미일주 패키지 인천출발 노쇼핑 노옵션 노팁 아르헨티나 브라질 볼리비아 페루 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0011', '중남미 남미여행 패키지 아르헨티나 브라질 볼리비아 페루 남미핵심일주 핵심4국 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0012', '남미핵심일주 패키지 노쇼핑 노옵션 노팁 아르헨티나 브라질 볼리비아 페루 중남미 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0013', '아르헨티나 브라질 볼리비아 페루 남미핵심일주 패키지 남미일주 인천출발 중남미여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0014', '남미여행 남미일주 패키지 노쇼핑 노옵션 노팁 아르헨티나 브라질 볼리비아 페루 핵심투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0015', '중남미 핵심4국 남미핵심일주 아르헨티나 브라질 볼리비아 페루 남미여행 패키지 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0016', '남미일주 패키지 아르헨티나 브라질 볼리비아 페루 노쇼핑 노옵션 노팁 인천출발 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0017', '남미여행 패키지 남미핵심일주 노쇼핑 노옵션 노팁 아르헨티나 브라질 볼리비아 페루', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0018', '아르헨티나 브라질 볼리비아 페루 중남미 남미일주 패키지 남미핵심일주 핵심4국 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0019', '남미 남미핵심일주 패키지 아르헨티나 브라질 볼리비아 페루 노쇼핑 노옵션 노팁 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_CMK_0020', '중남미 핵심4국 패키지 남미일주 아르헨티나 브라질 볼리비아 페루 남미핵심일주 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0001', '남미일주 패키지 마추픽추 우유니소금사막 소금호수 이과수폭포 토레스델파이네 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0002', '남미핵심일주 마추픽추 모레노빙하 파타고니아 아르헨티나 브라질 볼리비아 페루 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0005', '남미여행 마추픽추 소금호수 우유니소금사막 이과수폭포 아르헨티나 브라질 볼리비아 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0006', '남미일주 패키지 마추픽추 우유니소금사막 모레노빙하 아르헨티나 브라질 페루 여행일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0007', '남미핵심일주 마추픽추 파타고니아 토레스델파이네 소금호수 볼리비아 아르헨티나 브라질 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0008', '마추픽추 소금호수 우유니소금사막 모레노빙하 파타고니아 아르헨티나 페루 볼리비아 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0009', '남미여행 마추픽추 이과수폭포 토레스델파이네 브라질 아르헨티나 볼리비아 페루 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0010', '남미일주 패키지 마추픽추 소금호수 우유니소금사막 파타고니아 아르헨티나 볼리비아 페루', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0011', '남미핵심일주 모레노빙하 파타고니아 마추픽추 아르헨티나 브라질 볼리비아 페루 관광투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0014', '남미일주 마추픽추 소금호수 우유니소금사막 이과수폭포 브라질 아르헨티나 볼리비아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0015', '남미여행 마추픽추 파타고니아 모레노빙하 아르헨티나 브라질 페루 볼리비아 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0016', '마추픽추 소금호수 우유니소금사막 파타고니아 토레스델파이네 아르헨티나 페루 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0017', '남미핵심일주 마추픽추 이과수폭포 파타고니아 아르헨티나 브라질 볼리비아 페루 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_MLK_0020', '남미여행 마추픽추 모레노빙하 파타고니아 아르헨티나 브라질 볼리비아 페루 패키지투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0001', '남미일주 패키지 2025년11월 인천출발 마추픽추 우유니소금사막 아르헨티나 브라질', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0002', '남미핵심일주 2025년11월 9박13일 패키지 페루 볼리비아 아르헨티나 브라질 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0003', '남미여행 패키지 2025년12월 인천출발 마추픽추 모레노빙하 아르헨티나 볼리비아 페루', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0004', '중남미투어 18일 패키지 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0005', '남미일주 패키지 19일 투어 인천출발 아르헨티나 브라질 페루 볼리비아 이과수폭포 일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0006', '남미핵심일주 13일 투어 패키지 마추픽추 우유니소금사막 소금호수 아르헨티나 브라질', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0007', '남미여행 12일 일정 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아 패키지 투어', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0008', '남미일주 9박13일 패키지 인천출발 아르헨티나 브라질 볼리비아 페루 파타고니아 여행', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0009', '남미핵심일정 21일 투어 아르헨티나 브라질 볼리비아 페루 마추픽추 이과수폭포 패키지', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0010', '남미여행 좋은시기 인천출발 아르헨티나 브라질 볼리비아 페루 마추픽추 파타고니아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0011', '남미일주 패키지 2025년11월 인천출발 마추픽추 모레노빙하 아르헨티나 브라질 볼리비아', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0012', '중남미 2026년11월 패키지 남미핵심일주 아르헨티나 브라질 볼리비아 페루 관광일정', 'SouthAmerica');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SA4C_DMK_0013', '남미여행 2025년12월 17일 투어 인천출발 아르헨티나 브라질 볼리비아 페루 파타고니아', 'SouthAmerica');
