-- City Titles Part 057 (5601-5700번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0011', '12월 필리핀 동남아 일정 항공권 리조트 날씨 패키지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0012', '12월 여행 항공권 마닐라 필리핀 날씨 패키지 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0013', '12월 날씨 리조트 동남아 일정 직항 필리핀 항공권', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0014', '12월 직항 일정 날씨 리조트 여행 항공권 해외 필리핀', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0015', '12월 일정 여행 직항 패키지 해외 필리핀 동남아 날씨', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0016', '12월 직항 해외 여행 마닐라 리조트 항공권 일정', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0017', '12월 패키지 일정 날씨 마닐라 항공권 리조트 여행', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0018', '12월 날씨 일정 직항 항공권 리조트 필리핀 여행', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0019', '12월 여행 항공권 패키지 마닐라 해외 리조트 날씨', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0020', '12월 패키지 동남아 리조트 해외 날씨 필리핀 일정', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0021', '12월 여행 직항 일정 패키지 날씨 해외 동남아 필리핀', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0022', '12월 여행 필리핀 패키지 리조트 일정 마닐라 항공권', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0023', '12월 동남아 직항 필리핀 해외 여행 일정 마닐라', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0024', '12월 여행 필리핀 패키지 동남아 날씨 해외 일정', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0025', '12월 직항 필리핀 마닐라 패키지 동남아 항공권 여행', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0026', '12월 리조트 동남아 패키지 일정 여행 직항 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0027', '12월 일정 직항 여행 동남아 필리핀 패키지 항공권', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0028', '12월 마닐라 여행 날씨 해외 직항 일정 리조트 패키지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0029', '12월 일정 여행 리조트 날씨 동남아 해외 마닐라 직항', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_DMKTF__0030', '12월 해외 항공권 동남아 필리핀 날씨 패키지 리조트', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0001', '클락 여행 일정 필리핀 동남아 날씨 리조트 항공권', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0002', '클락 해외 여행 일정 필리핀 항공권 직항 동남아 패키지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0003', '클락 리조트 해외 직항 날씨 동남아 일정 필리핀 여행', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0004', '클락 직항 항공권 일정 동남아 필리핀 해외 날씨 여행', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0005', '클락 날씨 항공권 리조트 해외 일정 패키지 필리핀 여행', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0006', '클락 리조트 여행 직항 동남아 항공권 날씨 해외 필리핀', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0007', '클락 일정 동남아 필리핀 날씨 해외 패키지 리조트 직항', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0008', '클락 여행 직항 해외 항공권 리조트 일정 패키지 동남아', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0009', '클락 리조트 동남아 직항 패키지 필리핀 날씨 여행 해외', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0010', '클락 패키지 해외 필리핀 날씨 일정 직항 리조트 항공권', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0011', '클락 일정 리조트 패키지 필리핀 동남아 직항 해외', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0012', '클락 패키지 직항 여행 날씨 해외 리조트 필리핀 일정', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0013', '클락 직항 패키지 여행 필리핀 항공권 일정 리조트 날씨', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0014', '클락 동남아 필리핀 일정 날씨 패키지 여행 직항 리조트', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0015', '클락 일정 필리핀 동남아 직항 항공권 여행 패키지 날씨', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0016', '클락 날씨 패키지 직항 일정 리조트 여행 항공권 해외', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0017', '클락 날씨 직항 리조트 패키지 일정 해외 동남아 여행', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0018', '클락 패키지 여행 필리핀 항공권 동남아 해외 직항', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0019', '클락 패키지 리조트 동남아 직항 일정 필리핀 해외', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0020', '클락 직항 동남아 해외 패키지 일정 필리핀 날씨 항공권', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0021', '클락 리조트 직항 패키지 일정 해외 동남아 항공권', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0022', '클락 해외 동남아 패키지 여행 필리핀 직항 일정 리조트', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0023', '클락 필리핀 직항 리조트 패키지 날씨 여행 항공권', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0024', '클락 여행 패키지 동남아 해외 날씨 일정 필리핀 항공권', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0025', '클락 날씨 패키지 항공권 여행 동남아 직항 리조트', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0026', '클락 리조트 직항 필리핀 항공권 동남아 여행 패키지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0027', '클락 항공권 동남아 일정 해외 직항 날씨 리조트 여행', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0028', '클락 여행 직항 리조트 필리핀 날씨 패키지 항공권', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0029', '클락 리조트 패키지 여행 해외 항공권 직항 필리핀 날씨', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MMK_0030', '클락 패키지 동남아 해외 여행 직항 항공권 필리핀 일정', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0001', '클락 항공권 필리핀 호핑 해외 리조트 직항 마사지 쇼핑', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0002', '클락 전망대 직항 호핑투어 날씨 패키지 샤브샤브 휴양', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0003', '클락 마사지 샤브샤브 패키지 열대과일 직항 항공권 일정', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0004', '클락 전망대 패키지 호핑 해외 휴양 필리핀 날씨 항공권', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0005', '클락 직항 호핑 해외 전망대 마사지 일정 필리핀 날씨', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0006', '클락 필리핀 동남아 열대과일 패키지 호핑투어 전망대', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0007', '클락 호핑 관광지 리조트 마사지 샤브샤브 해외 직항', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0008', '클락 직항 휴양 리조트 패키지 날씨 전망대 호핑 쇼핑', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0009', '클락 샤브샤브 동남아 필리핀 일정 패키지 여행 리조트', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0010', '클락 샤브샤브 쇼핑 리조트 호핑투어 날씨 항공권 동남아', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0011', '클락 호핑 날씨 전망대 필리핀 휴양 리조트 관광지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0012', '클락 호핑 필리핀 일정 직항 날씨 호핑투어 리조트', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0013', '클락 패키지 항공권 전망대 여행 필리핀 일정 마사지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0014', '클락 쇼핑 관광지 패키지 마사지 동남아 직항 날씨', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0015', '클락 항공권 전망대 휴양 동남아 패키지 샤브샤브', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0016', '클락 직항 일정 패키지 날씨 필리핀 호핑투어 관광지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0017', '클락 일정 전망대 필리핀 해외 리조트 동남아 열대과일', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0018', '클락 해외 호핑 동남아 샤브샤브 필리핀 관광지 마사지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0019', '클락 전망대 항공권 관광지 직항 여행 샤브샤브 필리핀', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0020', '클락 항공권 샤브샤브 호핑 열대과일 휴양 리조트 동남아', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0021', '클락 날씨 관광지 리조트 항공권 휴양 호핑투어 호핑', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0022', '클락 호핑투어 일정 항공권 휴양 리조트 해외 필리핀', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0023', '클락 일정 날씨 해외 전망대 동남아 열대과일 직항', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0024', '클락 항공권 필리핀 일정 해외 날씨 호핑투어 전망대', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0025', '클락 패키지 휴양 샤브샤브 호핑투어 해외 날씨 마사지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0026', '클락 필리핀 전망대 열대과일 휴양 쇼핑 리조트 날씨', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0027', '클락 리조트 전망대 샤브샤브 열대과일 호핑 직항 쇼핑', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0028', '클락 일정 동남아 필리핀 해외 쇼핑 마사지 관광지 휴양', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0029', '클락 호핑투어 날씨 마사지 직항 전망대 샤브샤브 여행', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKSH_0030', '클락 휴양 항공권 패키지 해외 전망대 호핑투어 호핑', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0001', '클락 호핑투어 동남아 패키지 항공권 관광지 날씨 일정 필리핀 쇼핑 휴양', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0002', '클락 해외 패키지 호핑투어 쇼핑 필리핀 마사지 휴양 관광지 리조트', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0003', '클락 필리핀 직항 관광지 호핑투어 샤브샤브 전망대 쇼핑 항공권 호핑', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0004', '클락 열대과일 일정 전망대 날씨 호핑 동남아 필리핀 직항 해외 호핑투어', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0005', '클락 패키지 관광지 필리핀 호핑투어 호핑 전망대 여행 동남아 직항 리조트', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0006', '클락 샤브샤브 호핑 마사지 일정 호핑투어 항공권 리조트 전망대 여행 해외', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0007', '클락 휴양 해외 직항 패키지 항공권 샤브샤브 호핑 마사지 날씨 여행', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0008', '클락 패키지 관광지 여행 필리핀 해외 항공권 동남아 샤브샤브 리조트 호핑', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0009', '클락 패키지 열대과일 날씨 호핑투어 필리핀 직항 해외 마사지 쇼핑 호핑', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0010', '클락 날씨 쇼핑 호핑 샤브샤브 휴양 관광지 열대과일 해외 마사지 여행', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0011', '클락 마사지 직항 여행 호핑 동남아 호핑투어 날씨 해외 샤브샤브 열대과일', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0012', '클락 항공권 호핑 패키지 쇼핑 필리핀 여행 해외 마사지 일정 열대과일', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0013', '클락 전망대 쇼핑 일정 열대과일 샤브샤브 직항 리조트 호핑 패키지 관광지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0014', '클락 전망대 패키지 휴양 필리핀 동남아 호핑투어 항공권 날씨 여행 쇼핑', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0015', '클락 호핑 리조트 필리핀 관광지 샤브샤브 항공권 휴양 호핑투어 패키지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0016', '클락 해외 쇼핑 리조트 항공권 필리핀 날씨 동남아 호핑투어 패키지 관광지', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0017', '클락 열대과일 관광지 일정 샤브샤브 호핑 휴양 항공권 필리핀 동남아 날씨', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0018', '클락 일정 여행 호핑 동남아 열대과일 해외 패키지 관광지 필리핀 항공권', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0019', '클락 여행 열대과일 호핑 동남아 패키지 항공권 호핑투어 직항 샤브샤브', 'Clark');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_CLOC_MKLKLO_0020', '클락 해외 호핑 샤브샤브 필리핀 관광지 동남아 일정 여행 날씨 패키지', 'Clark');
