-- City Titles Part 022 (2101-2200번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0002', '영국 날씨 가격 항공권 여행 직항 런던 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0003', '영국 날씨 직항 여행 런던 가격 비행시간 패키지', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0004', '영국 직항 패키지 항공권 날씨 런던 여행 비행시간', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0005', '영국 비행시간 패키지 직항 런던 항공권 여행 가격', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0006', '영국 여행 가격 직항 관광 비행시간 날씨 런던', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0007', '영국 여행 항공권 패키지 날씨 관광 런던 직항', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0008', '영국 비행시간 항공권 날씨 여행 관광 직항 패키지', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0009', '영국 관광 직항 항공권 날씨 비행시간 패키지 가격', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0010', '영국 항공권 직항 비행시간 가격 여행 패키지 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0011', '영국 비행시간 가격 여행 날씨 항공권 직항 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0012', '영국 여행 직항 비행시간 항공권 날씨 가격 런던', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0013', '영국 런던 비행시간 직항 항공권 패키지 여행 가격', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0014', '영국 패키지 직항 항공권 런던 가격 날씨 비행시간', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0015', '영국 여행 관광 런던 직항 가격 패키지 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0016', '영국 가격 패키지 날씨 비행시간 직항 관광 여행', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0017', '영국 패키지 직항 항공권 여행 가격 관광 비행시간', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0018', '영국 직항 항공권 런던 가격 여행 비행시간 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0019', '영국 런던 비행시간 직항 패키지 관광 날씨 가격', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_CMK_0020', '영국 비행시간 직항 런던 항공권 여행 관광 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0001', '11월 가격 날씨 패키지 런던 항공권 비행시간 직항', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0002', '11월 가격 직항 9박 11일 런던 항공권 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0003', '11월 가격 런던 비행시간 패키지 직항 여행 항공권', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0004', '11월 패키지 영국 항공권 여행 가격 직항 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0005', '11월 관광 패키지 비행시간 직항 가격 날씨 영국', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0006', '11월 날씨 여행 런던 패키지 직항 가격 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0007', '11월 런던 항공권 패키지 관광 비행시간 직항 가격', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0008', '11월 여행 패키지 런던 직항 영국 날씨 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0009', '11월 가격 항공권 영국 9박 11일 관광 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0010', '11월 가격 9박 11일 비행시간 관광 런던 영국', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0011', '11월 런던 여행 관광 패키지 항공권 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0012', '11월 직항 영국 관광 여행 9박 11일 가격 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0013', '11월 런던 비행시간 관광 항공권 영국 가격 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0014', '11월 날씨 항공권 직항 관광 영국 패키지', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0015', '11월 날씨 9박 11일 런던 직항 패키지 영국', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0016', '11월 런던 영국 여행 관광 직항 9박 11일', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0017', '11월 패키지 직항 런던 여행 비행시간 항공권 가격', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0018', '11월 여행 항공권 영국 9박 11일 비행시간 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0019', '11월 비행시간 가격 패키지 날씨 9박 11일 런던', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0041', '12월 관광 항공권 가격 영국 런던 여행 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0042', '12월 직항 9박 11일 비행시간 여행 런던 가격', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0043', '12월 런던 날씨 여행 가격 관광 패키지 비행시간', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0044', '12월 여행 날씨 비행시간 패키지 가격 9박 11일', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0045', '12월 9박 11일 패키지 직항 여행 영국 비행시간', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0046', '12월 날씨 비행시간 가격 관광 항공권 직항 패키지', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0047', '12월 직항 항공권 영국 관광 런던 패키지 비행시간', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0048', '12월 비행시간 관광 패키지 가격 날씨 9박 11일', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0049', '12월 비행시간 영국 관광 9박 11일 여행 런던', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0050', '12월 관광 비행시간 항공권 영국 여행 가격 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0051', '12월 비행시간 직항 날씨 패키지 9박 11일 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0052', '12월 영국 패키지 항공권 여행 런던 날씨 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0053', '12월 패키지 런던 관광 직항 비행시간 9박 11일', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0054', '12월 관광 런던 항공권 패키지 직항 가격 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0055', '12월 런던 여행 항공권 비행시간 패키지 직항 영국', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0056', '12월 런던 날씨 관광 영국 비행시간 항공권', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0057', '12월 항공권 직항 관광 가격 영국 패키지 런던', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0058', '12월 9박 11일 가격 패키지 날씨 항공권 직항', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0059', '12월 관광 항공권 영국 직항 비행시간 여행 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__ENGLAND_DMK_0060', '12월 날씨 패키지 가격 여행 항공권 비행시간 관광', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0001', '영국 비행시간 패키지 항공권 가족 비틀즈 관광 해리포터 커플 날씨 먹거리', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0002', '영국 관광 도심 비행시간 커플 가볼만한곳 런던 흑맥주 힐링 비틀즈 가족', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0003', '영국 패키지 가족 가볼만한곳 날씨 관광 여행 흑맥주 힐링 직항 해리포터', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0004', '영국 가족 커플 직항 해리포터 가볼만한곳 위스키 런던 도심 힐링 먹거리', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0005', '영국 힐링 위스키 도심 가볼만한곳 날씨 비행시간 가족 패키지 해리포터', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0006', '영국 해리포터 항공권 먹거리 흑맥주 패키지 런던 비행시간 관광 비틀즈', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0007', '영국 항공권 패키지 여행 날씨 가족 런던 도심 가격 먹거리 커플 비행시간', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0008', '영국 커플 먹거리 가격 가족 여행 패키지 힐링 비틀즈 비행시간 위스키', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0009', '영국 흑맥주 먹거리 힐링 해리포터 관광 여행 가볼만한곳 비틀즈 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0010', '영국 여행 항공권 흑맥주 힐링 커플 가격 비틀즈 관광 가볼만한곳 날씨', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0011', '영국 위스키 가족 가볼만한곳 해리포터 흑맥주 도심 가격 여행 패키지 커플', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0012', '영국 비행시간 런던 흑맥주 도심 가족 가격 날씨 직항 위스키 비틀즈 커플', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0013', '영국 가볼만한곳 커플 항공권 여행 가족 해리포터 런던 흑맥주 관광 힐링', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0014', '영국 커플 흑맥주 패키지 도심 힐링 가족 해리포터 직항 여행 런던', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0015', '영국 비행시간 커플 위스키 가족 힐링 관광 날씨 해리포터 먹거리 여행', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0016', '영국 흑맥주 관광 패키지 항공권 해리포터 날씨 커플 가족 가격 직항', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0017', '영국 여행 도심 날씨 직항 비행시간 흑맥주 항공권 가족 가격 위스키', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0018', '영국 여행 가족 직항 가볼만한곳 흑맥주 패키지 관광 해리포터 비틀즈 힐링', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0019', '영국 관광 직항 먹거리 여행 날씨 가격 항공권 가볼만한곳 커플 힐링', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ENGLAND_ML_0020', '영국 비틀즈 위스키 날씨 직항 흑맥주 런던 도심 해리포터 관광 항공권', 'UnitedKingdom');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0001', '스위스 비행시간 항공권 취리히 가격 서유럽 베른', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0002', '스위스 비행시간 가격 여행 날씨 서유럽 숙소 직항', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0003', '스위스 항공권 취리히 베른 여행 비행시간 관광 가격', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0004', '스위스 여행 가격 취리히 관광 숙소 항공권 비행시간', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0005', '스위스 항공권 여행 비행시간 패키지 숙소 서유럽', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0006', '스위스 직항 숙소 비행시간 가격 패키지 서유럽 베른', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0007', '스위스 서유럽 항공권 베른 취리히 패키지 날씨 가격', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0008', '스위스 여행 서유럽 관광 항공권 비행시간 가격 숙소', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0009', '스위스 항공권 관광 패키지 가격 취리히 직항 서유럽', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0010', '스위스 직항 패키지 항공권 베른 숙소 날씨 취리히', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0011', '스위스 서유럽 비행시간 가격 항공권 날씨 베른 직항', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0012', '스위스 비행시간 취리히 서유럽 숙소 직항 관광 여행', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0013', '스위스 직항 가격 비행시간 패키지 관광 베른 취리히', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0014', '스위스 비행시간 항공권 패키지 여행 날씨 서유럽', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0015', '스위스 가격 비행시간 취리히 베른 관광 숙소 항공권', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0016', '스위스 날씨 서유럽 직항 비행시간 베른 관광 항공권', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0017', '스위스 비행시간 날씨 가격 숙소 취리히 항공권', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0018', '스위스 숙소 베른 비행시간 날씨 항공권 관광 여행', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0019', '스위스 관광 날씨 여행 가격 항공권 패키지 직항', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_CMK_0020', '스위스 비행시간 여행 베른 서유럽 패키지 관광 숙소', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_DMK_0021', '11월 패키지 직항 항공권 서유럽 숙소 베른 관광', 'Switzerland');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SWISS_DMK_0022', '11월 베른 스위스 서유럽 항공권 비행시간 관광', 'Switzerland');
