-- City Titles Part 041 (4001-4100번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0012', '12월 날씨 해외 여행 항공권 리조트 4박6일 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0013', '12월 동남아 해외 라오스 직항 리조트 패키지 일정', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0014', '12월 리조트 동남아 방비엥 4박6일 일정 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0015', '12월 여행 패키지 동남아 방비엥 4박6일 직항 일정', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0016', '12월 동남아 라오스 방비엥 일정 날씨 4박6일 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0017', '12월 라오스 항공권 패키지 해외 날씨 리조트 4박6일', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0018', '12월 방비엥 여행 일정 직항 라오스 4박6일 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0019', '12월 패키지 라오스 방비엥 리조트 일정 4박6일', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0020', '12월 패키지 직항 4박6일 항공권 날씨 일정 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0001', '도쿄 해외 일정 패키지 여행 일본 날씨 리조트 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0002', '도쿄 리조트 일본 직항 날씨 해외 항공권 에어텔 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0003', '도쿄 일본 패키지 해외 여행 리조트 에어텔 직항 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0004', '도쿄 여행 에어텔 리조트 해외 항공권 일정 패키지 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0005', '도쿄 일본 리조트 해외 일정 에어텔 직항 항공권 날씨', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0006', '도쿄 직항 에어텔 해외 여행 항공권 리조트 일본 패키지', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0007', '도쿄 직항 일본 해외 여행 패키지 일정 날씨 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0008', '도쿄 에어텔 여행 직항 패키지 리조트 항공권 날씨 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0009', '도쿄 패키지 날씨 일정 에어텔 리조트 해외 여행 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0010', '도쿄 해외 항공권 리조트 직항 일정 날씨 여행 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0011', '도쿄 에어텔 리조트 일본 여행 날씨 일정 직항 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0012', '도쿄 직항 패키지 항공권 해외 에어텔 여행 일본 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0013', '도쿄 항공권 패키지 에어텔 일본 해외 리조트 여행 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0014', '도쿄 일본 일정 날씨 패키지 에어텔 해외 리조트 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0015', '도쿄 에어텔 날씨 항공권 일본 패키지 리조트 일정 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0016', '도쿄 날씨 해외 일정 리조트 직항 패키지 여행 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0017', '도쿄 직항 해외 에어텔 여행 날씨 패키지 항공권 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0018', '도쿄 항공권 리조트 직항 패키지 여행 날씨 일본 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0019', '도쿄 일본 날씨 패키지 일정 직항 항공권 해외 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0020', '도쿄 여행 해외 날씨 패키지 일본 에어텔 항공권 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0001', '도쿄 에어텔 리조트 감성숙소 일본 패키지 해외 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0002', '도쿄 에어텔 온천 준비물 료칸 일정 감성숙소 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0003', '도쿄 패키지 리조트 날씨 항공권 일본 에어텔 료칸 자유', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0004', '도쿄 감성숙소 온천 료칸 여행 일본 일정 날씨 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0005', '도쿄 감성숙소 가족 일본 에어텔 리조트 료칸 여행 날씨', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0006', '도쿄 패키지 온천 직항 준비물 일본 해외 감성숙소 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0007', '도쿄 일정 에어텔 일본 해외 항공권 패키지 준비물 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0008', '도쿄 항공권 일정 자유 날씨 온천 준비물 에어텔 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0009', '도쿄 리조트 감성숙소 직항 항공권 여행 에어텔 패키지', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0010', '도쿄 해외 가족 리조트 온천 항공권 날씨 패키지 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0011', '도쿄 리조트 직항 날씨 일정 해외 감성숙소 온천 가족', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0012', '도쿄 감성숙소 료칸 준비물 여행 리조트 해외 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0013', '도쿄 항공권 자유 패키지 일본 해외 날씨 에어텔 가족', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0014', '도쿄 료칸 직항 온천 준비물 일정 여행 자유 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0015', '도쿄 자유 온천 리조트 감성숙소 여행 료칸 항공권 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0016', '도쿄 일정 일본 가족 리조트 자유 항공권 패키지 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0017', '도쿄 여행 자유 직항 일본 일정 에어텔 온천 료칸', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0018', '도쿄 날씨 자유 일정 리조트 직항 해외 가족 온천', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0019', '도쿄 리조트 해외 날씨 자유 직항 패키지 온천 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0020', '도쿄 해외 날씨 감성숙소 패키지 항공권 직항 일본 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0001', '도쿄 자유 날씨 료칸 일정 항공권 온천 직항 리조트 해외 감성숙소 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0002', '도쿄 일본 자유 감성숙소 일정 에어텔 가족 준비물 패키지 날씨 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0003', '도쿄 료칸 날씨 일정 가족 온천 항공권 패키지 여행 리조트 직항 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0004', '도쿄 여행 자유 패키지 리조트 일정 가족 준비물 온천 일본 직항 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0005', '도쿄 해외 에어텔 감성숙소 일본 날씨 리조트 온천 여행 자유 항공권 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0006', '도쿄 날씨 감성숙소 리조트 해외 일본 일정 가족 직항 항공권 여행 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0007', '도쿄 항공권 해외 일본 일정 패키지 준비물 직항 리조트 감성숙소 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0008', '도쿄 패키지 가족 준비물 여행 료칸 에어텔 날씨 항공권 일정 감성숙소', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0009', '도쿄 감성숙소 료칸 자유 가족 일정 에어텔 일본 날씨 온천 직항 준비물', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0010', '도쿄 해외 항공권 온천 일본 준비물 패키지 료칸 일정 가족 날씨 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0011', '도쿄 감성숙소 직항 에어텔 가족 여행 일정 료칸 온천 날씨 패키지 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0012', '도쿄 일정 일본 에어텔 직항 감성숙소 온천 날씨 료칸 리조트 여행 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0013', '도쿄 에어텔 날씨 자유 여행 일정 직항 감성숙소 항공권 일본 해외 료칸', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0014', '도쿄 패키지 자유 온천 여행 준비물 일본 리조트 날씨 항공권 일정 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0015', '도쿄 날씨 여행 패키지 자유 해외 준비물 가족 에어텔 일본 직항 온천', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0016', '도쿄 항공권 가족 준비물 일본 여행 리조트 자유 일정 날씨 직항 패키지', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0017', '도쿄 항공권 에어텔 료칸 자유 패키지 리조트 해외 날씨 일본 온천 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0018', '도쿄 에어텔 직항 패키지 일본 감성숙소 항공권 일정 료칸 여행 해외 온천', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0019', '도쿄 직항 날씨 감성숙소 해외 온천 료칸 패키지 항공권 에어텔 자유 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0020', '도쿄 일정 에어텔 리조트 일본 항공권 날씨 여행 패키지 료칸 자유 온천', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0001', '10월 해외 패키지 직항 도쿄 여행 항공권 일본 디즈니랜드 날씨 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0002', '10월 리조트 날씨 도쿄타워 일본 항공권 패키지 직항 디즈니랜드 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0003', '10월 도쿄 도쿄타워 일정 해외 여행 일본 패키지 리조트 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0004', '10월 날씨 일본 디즈니랜드 패키지 도쿄 도쿄타워 직항 해외 여행 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0005', '10월 디즈니랜드 일정 해외 날씨 일본 여행 리조트 도쿄타워 직항 패키지', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0006', '10월 항공권 해외 패키지 도쿄 도쿄타워 여행 직항 디즈니랜드 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0007', '10월 일정 패키지 날씨 직항 도쿄 리조트 디즈니랜드 일본 여행 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0008', '10월 패키지 해외 디즈니랜드 직항 일본 리조트 도쿄 도쿄타워 일정 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0009', '10월 해외 날씨 도쿄 도쿄타워 직항 여행 패키지 리조트 일정 디즈니랜드', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0010', '10월 도쿄타워 해외 패키지 디즈니랜드 여행 리조트 일본 항공권 날씨', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0011', '10월 도쿄 일정 여행 직항 도쿄타워 날씨 항공권 디즈니랜드 일본 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0012', '10월 해외 날씨 여행 리조트 도쿄 항공권 일정 패키지 일본 디즈니랜드', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0013', '10월 패키지 직항 리조트 일정 디즈니랜드 항공권 해외 도쿄 도쿄타워', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0014', '10월 도쿄 일본 리조트 디즈니랜드 날씨 직항 해외 일정 패키지 도쿄타워', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0015', '10월 도쿄 리조트 일정 직항 패키지 디즈니랜드 날씨 해외 일본 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0016', '10월 항공권 날씨 패키지 리조트 해외 도쿄 디즈니랜드 도쿄타워 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0017', '10월 날씨 리조트 패키지 항공권 직항 해외 여행 일정 디즈니랜드', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0018', '10월 여행 디즈니랜드 도쿄 도쿄타워 일정 해외 항공권 리조트 날씨 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0019', '10월 도쿄 리조트 도쿄타워 일정 여행 직항 항공권 디즈니랜드 날씨 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_OMKRT_0020', '10월 일본 디즈니랜드 해외 날씨 패키지 직항 도쿄 일정 항공권 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0001', '11월 항공권 일본 도쿄 직항 리조트 도쿄타워 날씨', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0002', '11월 항공권 도쿄타워 리조트 날씨 도쿄 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0003', '11월 패키지 도쿄타워 일정 리조트 해외 직항 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0004', '11월 일본 리조트 해외 도쿄 도쿄타워 날씨 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0005', '11월 항공권 여행 도쿄타워 디즈니랜드 해외 도쿄 날씨', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0006', '11월 패키지 디즈니랜드 도쿄 여행 해외 항공권 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0007', '11월 일본 리조트 일정 직항 해외 항공권 여행 도쿄', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0008', '11월 해외 도쿄 도쿄타워 일정 패키지 항공권 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0009', '11월 디즈니랜드 패키지 리조트 도쿄타워 날씨 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0010', '11월 도쿄타워 여행 직항 디즈니랜드 일본 패키지 도쿄', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_NMKRT_0011', '11월 패키지 일정 해외 직항 리조트 여행 날씨', 'Tokyo');
