-- City Titles Part 092 (9101-9200번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0022', '이탈리아 항공권 먹거리 피자 가볼만한곳 직항 겨울', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0023', '이탈리아 비행시간 패키지 항공권 여행 숙소 파스타 날씨', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0024', '이탈리아 여행 직항 숙소 먹거리 파스타 비행시간 피자', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0025', '이탈리아 관광 힐링 먹거리 직항 여행 항공권 가격 숙소', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0026', '이탈리아 가볼만한곳 힐링 날씨 가격 가을 비행시간', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0027', '이탈리아 가격 여행 직항 가볼만한곳 힐링 먹거리 관광', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0028', '이탈리아 힐링 여행 가을 파스타 가격 숙소 날씨', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0029', '이탈리아 가격 여행 관광 힐링 항공권 파스타 날씨', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0030', '이탈리아 숙소 비행시간 가격 여행 관광 직항 힐링 날씨', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0031', '이탈리아 힐링 관광 여행 날씨 직항 숙소 겨울', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0032', '이탈리아 관광 패키지 파스타 숙소 비행시간 항공권 여행', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0033', '이탈리아 파스타 비행시간 먹거리 가격 패키지 항공권', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0034', '이탈리아 먹거리 여행 패키지 항공권 직항 가볼만한곳', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0035', '이탈리아 파스타 패키지 가을 겨울 여행 관광 힐링 날씨', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0021', '프랑스 패키지 가격 항공권 여행 파리 관광 직항', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0022', '프랑스 노르망디 관광 항공권 비행시간 여행 파리 가격', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0023', '프랑스 노르망디 파리 비행시간 관광 패키지 날씨 직항', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0024', '프랑스 파리 여행 관광 비행시간 노르망디 항공권 날씨', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0025', '프랑스 날씨 노르망디 항공권 파리 가격 여행 직항', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0026', '프랑스 직항 항공권 날씨 가격 패키지 여행 파리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0027', '프랑스 날씨 패키지 비행시간 항공권 파리 직항 노르망디', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0028', '프랑스 패키지 비행시간 항공권 직항 날씨 관광 여행', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0029', '프랑스 비행시간 날씨 패키지 관광 직항 여행 파리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0030', '프랑스 직항 비행시간 항공권 노르망디 파리 가격 날씨', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0031', '프랑스 비행시간 날씨 관광 파리 노르망디 여행 직항', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0032', '프랑스 항공권 직항 패키지 비행시간 관광 가격 여행', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0033', '프랑스 여행 직항 파리 비행시간 날씨 관광 항공권', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0034', '프랑스 관광 항공권 비행시간 여행 날씨 패키지 파리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_CMK_0035', '프랑스 관광 여행 직항 항공권 날씨 노르망디 패키지', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0021', '프랑스 쉬농소성 직항 파리 비행시간 항공권 패키지 삘라사구', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0022', '프랑스 비행시간 패키지 파리 쉬농소성 직항 여행 항공권', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0023', '프랑스 삘라사구 패키지 가격 비행시간 노르망디 여행', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0024', '프랑스 날씨 관광 쉬농소성 항공권 오르세미술관', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0025', '프랑스 오르세미술관 항공권 패키지 노르망디 보르도와이너리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0026', '프랑스 툴루즈 쉬농소성 비행시간 삘라사구 직항 날씨', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0027', '프랑스 삘라사구 날씨 파리 가격 관광 여행 보르도와이너리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0028', '프랑스 보르도와이너리 비행시간 쉬농소성 항공권 가격', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0029', '프랑스 여행 패키지 파리 관광 오르세미술관 직항 노르망디', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_MKL_0030', '프랑스 툴루즈 비행시간 가격 관광 삘라사구 여행 항공권', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0021', '11월 비행시간 가격 관광 노르망디 패키지 파리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0022', '11월 날씨 10박12일 항공권 패키지 노르망디 가격', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0023', '11월 패키지 날씨 파리 10박12일 노르망디 항공권 직항', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0024', '11월 항공권 노르망디 관광 비행시간 패키지 여행 가격', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0025', '11월 비행시간 노르망디 관광 직항 파리 여행 10박12일', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0026', '11월 직항 프랑스 10박12일 파리 여행 가격 날씨', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0027', '11월 가격 노르망디 패키지 10박12일 직항 파리 날씨', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0028', '11월 날씨 직항 여행 파리 가격 관광 10박12일 패키지', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0029', '11월 날씨 가격 파리 노르망디 항공권 프랑스 직항 관광', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0030', '11월 10박12일 항공권 직항 관광 패키지 노르망디', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0031', '11월 관광 날씨 파리 가격 항공권 10박12일 직항', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0032', '11월 패키지 가격 프랑스 비행시간 노르망디 관광 날씨', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0033', '11월 여행 날씨 항공권 프랑스 패키지 관광 10박12일', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0034', '11월 파리 가격 프랑스 직항 패키지 10박12일 노르망디', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0035', '11월 날씨 직항 프랑스 관광 노르망디 10박12일 가격', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0021', '프랑스 파리 관광 에스카르고 먹거리 항공권 향수공방체험 비행시간 여행', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0022', '프랑스 에스카르고 날씨 여행 항공권 가을 먹거리 비행시간 가격 숙소 겨울', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0023', '프랑스 날씨 향수공방체험 비행시간 직항 가격 숙소 부르기뇽 관광 겨울', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0024', '프랑스 파리 가볼만한곳 비행시간 힐링 향수공방체험 여행 노르망디 패키지', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0025', '프랑스 여행 비행시간 패키지 노르망디 직항 파리 에스카르고 관광', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0026', '프랑스 여행 가격 먹거리 향수공방체험 패키지 겨울 가을 항공권 비행시간', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0027', '프랑스 항공권 날씨 관광 숙소 가을 부르기뇽 비행시간 에스카르고 먹거리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0028', '프랑스 파리 숙소 먹거리 향수공방체험 직항 비행시간 노르망디 여행 가격', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0029', '프랑스 날씨 가을 가격 숙소 비행시간 직항 여행 부르기뇽 에스카르고 관광', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0030', '프랑스 여행 비행시간 항공권 먹거리 가격 숙소 향수공방체험 가을 파리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0031', '프랑스 부르기뇽 가볼만한곳 날씨 노르망디 에스카르고 겨울 직항 힐링 가격', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0032', '프랑스 가을 날씨 먹거리 에스카르고 가격 힐링 파리 부르기뇽 가볼만한곳', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0033', '프랑스 에스카르고 가볼만한곳 먹거리 직항 날씨 겨울 노르망디 가을 항공권', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0034', '프랑스 여행 관광 향수공방체험 가을 노르망디 날씨 가격 겨울 힐링 패키지', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0035', '프랑스 항공권 힐링 노르망디 패키지 에스카르고 향수공방체험 먹거리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0036', '프랑스 날씨 노르망디 겨울 가볼만한곳 비행시간 패키지 숙소 직항 관광', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0037', '프랑스 노르망디 숙소 파리 힐링 관광 부르기뇽 날씨 가볼만한곳 패키지', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0038', '프랑스 노르망디 부르기뇽 힐링 먹거리 가격 파리 여행 직항 겨울 패키지', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0039', '프랑스 먹거리 패키지 힐링 날씨 가볼만한곳 부르기뇽 비행시간 항공권', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0040', '프랑스 항공권 여행 패키지 파리 가볼만한곳 힐링 겨울 숙소 부르기뇽', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0021', '동유럽 일주 오스트리아 직항 항공권 헝가리 관광', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0022', '동유럽 체코 일주 가격 비행시간 여행 오스트리아', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0023', '동유럽 헝가리 가격 여행 비행시간 체코 직항 일주', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0024', '동유럽 가격 직항 비행시간 패키지 항공권 일주', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0025', '동유럽 직항 관광 비행시간 일주 가격 여행 패키지', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0026', '동유럽 일주 직항 체코 헝가리 관광 오스트리아 가격', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0027', '동유럽 패키지 직항 가격 일주 여행 항공권 관광', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0028', '동유럽 관광 항공권 직항 가격 패키지 헝가리', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0029', '동유럽 체코 헝가리 비행시간 직항 패키지 일주', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_CMK_0030', '동유럽 항공권 패키지 체코 헝가리 오스트리아 직항', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0021', '동유럽 알프스 비행시간 부다페스트 잘츠부르크 체코 직항', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0022', '동유럽 일주 직항 항공권 비행시간 패키지 체코', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0023', '동유럽 체코 잘츠부르크 비행시간 가격 관광 패키지', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0024', '동유럽 체코 일주 프라하 관광 알프스 항공권 패키지', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0025', '동유럽 부다페스트 관광 패키지 일주 가격 오스트리아', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0026', '동유럽 프라하 관광 직항 알프스 부다페스트 패키지', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0027', '동유럽 잘츠부르크 여행 패키지 부다페스트 비행시간 체코', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0028', '동유럽 일주 부다페스트 헝가리 오스트리아 프라하 가격', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0029', '동유럽 관광 할슈타트 알프스 프라하 잘츠부르크 여행', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0030', '동유럽 비행시간 할슈타트 여행 가격 알프스 패키지', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0031', '동유럽 할슈타트 헝가리 비행시간 가격 오스트리아 항공권', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0032', '동유럽 직항 체코 오스트리아 프라하 헝가리 잘츠부르크', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0033', '동유럽 항공권 프라하 비행시간 패키지 헝가리 할슈타트', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0034', '동유럽 비행시간 알프스 잘츠부르크 패키지 할슈타트 일주', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_MKL_0035', '동유럽 비행시간 알프스 헝가리 여행 부다페스트', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0021', '동유럽 힐링 가볼만한곳 야간투어 가을 여행 헝가리 숙소 오스트리아', 'Austria');
