-- City Titles Part 015 (1401-1500번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0016', '밴쿠버 10월 8박 캐나다여행 패키지 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0017', '밴프 밴쿠버 6월 6박8일 여행 캐나다 패키지 국적기 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0018', '밴쿠버 2026년 10박12일 캐나다여행 패키지 국적기 대한항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0019', '밴프 밴쿠버 8월 7일 여행 캐나다 패키지 국적기 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0020', '밴쿠버 9월 8박10일 여행 캐나다 패키지 국적기 대한항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0001', '밴쿠버여행패키지 캐나다여행 로키 밴프여행 오로라 자유일정 가족여행 효도여행 패키지여행 갈만한곳 레이크루이스 여행코스 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0002', '캐나다여행 밴쿠버 패키지여행 로키 밴프여행 오로라 나이아가라 가족여행 효도여행 자유일정 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0003', '밴쿠버여행패키지 캐나다여행 로키 밴프여행 여행코스 가족여행 혼자여행 효도여행 갈만한곳', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0004', '캐나다여행 밴쿠버 패키지여행 나이아가라 밴프여행 레이크루이스 오로라 가족여행 여행코스', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0005', '밴쿠버여행패키지 캐나다여행 밴프여행 로키 나이아가라 자유일정 가족여행 효도여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0006', '캐나다여행 밴쿠버 패키지여행 여행코스 오로라 나이아가라 밴프여행 가족여행 효도여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0007', '밴쿠버여행패키지 캐나다여행 패키지여행 밴프여행 로키 오로라 갈만한곳 레이크루이스 가족여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0008', '캐나다여행 밴쿠버 밴프여행 로키 여행코스 패키지여행 가족여행 효도여행 자유일정', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0009', '밴쿠버여행패키지 캐나다여행 오로라 밴프여행 나이아가라 레이크루이스 갈만한곳 가족여행 효도여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0010', '캐나다여행 밴쿠버 패키지여행 밴프여행 로키 가족여행 혼자여행 여행코스 효도여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0011', '밴쿠버여행패키지 캐나다여행 나이아가라 밴프여행 로키 패키지여행 자유일정 가족여행 효도여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0012', '캐나다여행 밴쿠버 오로라 밴프여행 여행코스 갈만한곳 레이크루이스 가족여행 효도여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0013', '밴쿠버여행패키지 캐나다여행 패키지여행 밴프여행 로키 나이아가라 가족여행 효도여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0014', '캐나다여행 밴쿠버 밴프여행 오로라 여행코스 자유일정 가족여행 효도여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0015', '밴쿠버여행패키지 캐나다여행 레이크루이스 밴프여행 로키 나이아가라 여행코스 가족여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0016', '캐나다여행 밴쿠버 패키지여행 밴프여행 오로라 나이아가라 가족여행 효도여행 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0017', '밴쿠버여행패키지 캐나다여행 밴프여행 여행코스 로키 자유일정 가족여행 효도여행 갈만한곳', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0018', '캐나다여행 밴쿠버 오로라 밴프여행 레이크루이스 나이아가라 여행코스 가족여행 패키지여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0019', '밴쿠버여행패키지 캐나다여행 밴프여행 로키 나이아가라 효도여행 가족여행 패키지여행 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_ML_0020', '캐나다여행 밴쿠버 패키지여행 밴프여행 오로라 여행코스 가족여행 효도여행 자유일정', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0001', '미동부 뉴욕 캐나다 동부 토론토 나이아가라 몬트리올 7박10일 인천출발 패키지 일정', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0002', '캐나다 동부 토론토 나이아가라 미동부 뉴욕 몬트리올 7박10일 인천출발 패키지 관광지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0003', '토론토 캐나다 동부 나이아가라 미동부 뉴욕 몬트리올 인천출발 7박10일 패키지 일정', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0004', '나이아가라 토론토 캐나다 동부 미동부 뉴욕 몬트리올 7박10일 인천출발 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0005', '캐나다 토론토 미동부 동부 나이아가라 몬트리올 인천출발 7박10일 패키지 일정', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0006', '뉴욕 미동부 캐나다 동부 토론토 나이아가라 몬트리올 7박10일 인천출발 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0007', '동부 캐나다 토론토 나이아가라 미동부 뉴욕 몬트리올 인천출발 7박10일 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0008', '토론토 나이아가라 캐나다 동부 미동부 뉴욕 몬트리올 7박10일 인천출발 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0009', '캐나다 동부 미동부 토론토 나이아가라 몬트리올 뉴욕 인천출발 7박10일 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0010', '나이아가라 캐나다 동부 토론토 미동부 뉴욕 몬트리올 인천출발 7박10일 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0011', '몬트리올 캐나다 동부 토론토 나이아가라 미동부 뉴욕 인천출발 7박10일 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0012', '미동부 캐나다 동부 토론토 나이아가라 몬트리올 7박10일 인천출발 패키지 일정', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0013', '뉴욕 토론토 캐나다 동부 나이아가라 몬트리올 인천출발 7박10일 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0014', '동부 나이아가라 캐나다 토론토 미동부 몬트리올 인천출발 7박10일 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0015', '토론토 캐나다 동부 미동부 나이아가라 몬트리올 7박10일 인천출발 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0016', '캐나다 미동부 동부 토론토 나이아가라 몬트리올 7박10일 인천출발 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0017', '나이아가라 몬트리올 캐나다 동부 토론토 미동부 인천출발 7박10일 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0018', '캐나다 동부 토론토 미동부 나이아가라 몬트리올 7박10일 인천출발 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0019', '토론토 나이아가라 몬트리올 캐나다 동부 미동부 7박10일 인천출발 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_SNK_0020', '미동부 뉴욕 캐나다 동부 토론토 나이아가라 7박10일 인천출발 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0001', '케나다 여행 패키지 밴쿠버 로키산멕 밴푸 국적기 대한항공 아시아나항공 인촌출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0002', '캐나다 여행 패키지 벤쿠버 로키산멕 밴프 국적기 대한항공 아시아나항공 인천츨발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0003', '케나다 패키지여행 밴쿠버 로키산맥 벤프 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0005', '케나다 여행 패키지 밴쿠버 로키산맥 밴프 국적기 대한항공 아시아나항공 인천츨발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0006', '캐나다 패키지여행 벤쿠버 로키산멕 밴푸 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0007', '케나다 여행 패키지 밴쿠버 로키산멕 벤프 국적기 대한항공 아시아나항공 인촌출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0008', '캐나다 여행 패키지 밴쿠버 로키산맥 밴푸 국적기 대한항공 아시아나항공 인천츨발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0009', '케나다 여행 패키지 벤쿠버 로키산멕 밴프 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0010', '캐나다 패키지여행 밴쿠버 로키산멕 밴푸 국적기 대한항공 아시아나항공 인촌출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0011', '케나다 여행 패키지 밴쿠버 로키산멕 벤프 국적기 대한항공 아시아나항공 인천츨발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0013', '케나다 여행 패키지 밴쿠버 로키산맥 벤프 국적기 대한항공 아시아나항공 인천츨발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0014', '캐나다 패키지여행 밴쿠버 로키산멕 밴푸 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0015', '케나다 여행 패키지 벤쿠버 로키산멕 밴프 국적기 대한항공 아시아나항공 인촌출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0016', '캐나다 여행 패키지 밴쿠버 로키산멕 밴푸 국적기 대한항공 아시아나항공 인천츨발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0017', '케나다 여행 패키지 밴쿠버 로키산맥 벤프 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0018', '캐나다 패키지여행 벤쿠버 로키산멕 밴푸 국적기 대한항공 아시아나항공 인촌출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0019', '케나다 여행 패키지 밴쿠버 로키산멕 밴프 국적기 대한항공 아시아나항공 인천츨발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_OT_0020', '캐나다 여행 패키지 벤쿠버 로키산멕 밴푸 국적기 대한항공 아시아나항공 인촌출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0001', '밴쿠버 로키산맥 레이크루이스 밴프 국립공원 5박7일 패키지 여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0002', '밴쿠버 캐나다 로키 밴프 여행 패키지 8박10일', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0003', '밴쿠버 밴프 로키산맥 5박7일 국립공원 에메랄드호수 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0004', '캐나다 밴쿠버 5박7일 밴프 로키 패키지 여행 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0005', '밴쿠버 5박7일 로키 밴프 에메랄드호수 국립공원 여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0006', '밴쿠버 밴프 로키산맥 국립공원 여행5박7일 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0007', '캐나다 밴쿠버 로키 밴프 5박7일 일정 패키지 여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0008', '밴쿠버 로키 밴프 여행 캐나다 패키지 5박7일 일정', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0009', '밴쿠버 캐나다 밴프 국립공원 로키산맥 5박7일 여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0010', '밴쿠버 로키산맥 밴프 5박7일 국립공원 캐나다 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0011', '밴쿠버 밴프 로키산맥 캐나다 5박7일 패키지 여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0012', '밴쿠버 로키 밴프 여행 일정 5박7일 캐나다 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0013', '밴쿠버 밴프 국립공원 로키산맥 5박7일 여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0014', '밴쿠버 로키 밴프 여행 5박7일 캐나다 일정', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0015', '밴쿠버 밴프 로키 국립공원 캐나다 5박7일 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0016', '밴쿠버 로키산맥 밴프 캐나다 여행 5박7일 일정', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0017', '밴쿠버 밴프 국립공원 캐나다 5박7일 패키지 여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0018', '밴쿠버 로키 밴프 여행 인천출발 캐나다', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0019', '밴쿠버 밴프 로키산맥 여행 캐나다 일정 5박7일', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_GPT_0020', '밴쿠버 캐나다 로키 밴프 국립공원 패키지 5박7일', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0001', '미국 캐나다 나이아가라 미동부 패키지 인천출발 6월 나이아가라폭포 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0002', '캐나다 미국 나이아가라 패키지 미동부 여행코스 인천출발 7월 스카일론타워 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0003', '미국 미동부 캐나다 나이아가라 패키지 인천출발 8월 나이아가라크루즈 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0004', '나이아가라 미국 캐나다 미동부 패키지 여행코스 인천출발 하반기 클리프턴힐 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0005', '캐나다 나이아가라 미동부 미국 패키지 인천출발 2026년 나이아가라파크 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0006', '미국 나이아가라 캐나다 미동부 패키지 인천출발 6월 스카일론타워 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0007', '미동부 미국 캐나다 나이아가라 패키지 여행코스 인천출발 7월 나이아가라폭포 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0008', '캐나다 미동부 미국 나이아가라 패키지 인천출발 8월 나이아가라크루즈 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0009', '나이아가라 미동부 미국 캐나다 패키지 여행코스 인천출발 하반기 클리프턴힐 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0010', '미국 캐나다 미동부 나이아가라 패키지 인천출발 2026년 나이아가라파크 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0011', '미국 캐나다 나이아가라 패키지 미동부 여행코스 인천출발 09월 스카일론타워 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0012', '캐나다 미국 미동부 나이아가라 패키지 인천출발 6월 나이아가라폭포 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0013', '나이아가라 미국 미동부 캐나다 패키지 인천출발 7월 나이아가라크루즈 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0014', '미국 미동부 나이아가라 캐나다 패키지 여행코스 인천출발 8월 클리프턴힐 가족여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0015', '캐나다 나이아가라 미국 미동부 패키지 인천출발 하반기 나이아가라파크 효도여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0016', '미국 나이아가라 미동부 캐나다 패키지 여행코스 인천출발 2026년 스카일론타워 해외여행', 'NiagaraFalls');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NG_CMK_0017', '미동부 캐나다 미국 나이아가라 패키지 인천출발 6월 나이아가라폭포 가족여행', 'NiagaraFalls');
