-- City Titles Part 085 (8401-8500번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0013', '미국 캐나다 여행 패키지 2026년 출발 7박9일 일정 나이아가라 퀘벡 포함 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0014', '캐나다 미국 패키지 여행 8일 일정 몬트리올 나이아가라 포함 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0015', '2025년 11월 미국 캐나다 패키지 여행 9일 일정 국적기 직항 인천출발 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0016', '캐나다 미국 여행 패키지 2025년 4분기 출발 10일 일정 나이아가라 몬트리올 퀘벡 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0017', '미국 캐나다 여행 패키지 7박9일 일정 인천출발 국적기 직항 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0018', '미국 캐나다 패키지 여행 8일 일정 나이아가라 퀘벡 몬트리올 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0019', '캐나다 미국 여행 패키지 9일 일정 국적기 항공권 인천출발 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0020', '미국 캐나다 패키지 여행 10일 일정 인천출발 나이아가라 퀘벡 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0001', '퀘벡 노트르담 성당 몽모렌시 폭포 몬트리올 나이아가라 특급호텔 샤토숙박 허니문 가족여행 단체', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0002', '퀘벡 몬트리올 로렌시안 트리탑 몽트랑블랑 미국여행 캐나다패키지 나이아가라 미동부 패키지 럭셔리 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0003', '퀘벡 나이아가라 폭포뷰호텔 혼블로어 유람선 샤토숙박 특급호텔 리조트 허니문 연인 가족여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0004', '퀘벡 몬트리올 캐나다패키지 미국여행 미동부 나이아가라 헬기투어 전망대 리조트 맞춤일정 단체여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0005', '퀘벡 몽모렌시 폭포 몬트리올 나이아가라 캐나다 미국여행 동부투어 보스턴 뉴욕 워싱턴DC 프리미엄 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0006', '퀘벡 노트르담 성당 몬트리올 나이아가라 호텔 리조트 특급호텔 가족여행 단체관광 허니문 맞춤투어', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0007', '퀘벡 몽트랑블랑 로렌시안 트리탑 캐나다패키지 미국여행 나이아가라 뉴욕 보스턴 미동부 투어 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0008', '퀘벡 몬트리올 나이아가라 혼블로어 유람선 헬기투어 전망대 우드버리아울렛 맞춤여행 단체 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0009', '퀘벡 캐나다패키지 미국여행 나이아가라 몽모렌시폭포 몬트리올 미동부 럭셔리 일정 허니문 가족여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0010', '퀘벡 몬트리올 나이아가라 특급호텔 샤토숙박 리조트 가족여행 부부 연인 허니문 단체관광 맞춤일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0011', '퀘벡 노트르담 성당 몽모렌시폭포 캐나다패키지 미국여행 나이아가라 동부투어 뉴욕 보스턴 포함 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0012', '퀘벡 몬트리올 몽트랑블랑 로렌시안 트리탑 나이아가라 캐나다 미국여행 미동부 패키지 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0013', '퀘벡 나이아가라 헬기투어 혼블로어 유람선 폭포뷰호텔 특급호텔 허니문 연인 맞춤 패키지 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0014', '퀘벡 몬트리올 나이아가라 리조트 샤토숙박 호텔 단체여행 가족여행 부부 허니문 프리미엄 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0015', '퀘벡 몽모렌시 폭포 몬트리올 나이아가라 특급호텔 리조트 캐나다패키지 미국여행 맞춤투어 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0016', '퀘벡 몬트리올 나이아가라 동부투어 뉴욕 보스턴 워싱턴DC 미국여행 캐나다패키지 단체관광 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0017', '퀘벡 노트르담 성당 몽트랑블랑 로렌시안 트리탑 나이아가라 캐나다패키지 미국여행 미동부 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0018', '퀘벡 몬트리올 나이아가라 호텔 리조트 특급호텔 샤토숙박 허니문 연인 맞춤여행 가족 단체 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0019', '퀘벡 몽모렌시폭포 몬트리올 나이아가라 혼블로어 유람선 헬기투어 전망대 프리미엄 패키지 허니문', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_ML_0020', '퀘벡 캐나다패키지 미국여행 나이아가라 미동부 몬트리올 보스턴 뉴욕 워싱턴DC 포함 럭셔리 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0001', '캐나다패키지 나이아가라 퀘벡 미국 미동부 폭포뷰호텔 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0002', '나이아가라 퀘벡 몬트리올 포함 미국여행 캐나다패키지 미동부 특급호텔', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0003', '미국여행 캐나다패키지 미동부 나이아가라 폭포뷰호텔 허니문 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0004', '캐나다패키지 미국여행 미동부 나이아가라 퀘벡 포함 특급호텔 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0005', '나이아가라 포함 미국여행 캐나다패키지 미동부 퀘벡 폭포뷰호텔 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0006', '미국여행 캐나다패키지 나이아가라 퀘벡 포함 미동부 특급호텔 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0007', '캐나다패키지 미국여행 미동부 나이아가라 퀘벡 폭포뷰호텔 일정 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0008', '미국여행 캐나다패키지 나이아가라 퀘벡 포함 미동부 호텔 숙박 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0009', '나이아가라 포함 미국여행 캐나다패키지 미동부 퀘벡 폭포뷰호텔 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0010', '캐나다패키지 미국여행 미동부 나이아가라 퀘벡 포함 호텔 숙박 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0011', '미국여행 캐나다패키지 나이아가라 퀘벡 포함 미동부 폭포뷰호텔 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0012', '캐나다패키지 미국여행 미동부 나이아가라 퀘벡 호텔 포함 일정 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0013', '미국여행 캐나다패키지 미동부 퀘벡 나이아가라 폭포뷰호텔 포함 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0014', '나이아가라 퀘벡 포함 미국여행 캐나다패키지 미동부 특급호텔 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0015', '캐나다패키지 미국여행 미동부 나이아가라 퀘벡 호텔 일정 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0016', '미국여행 캐나다패키지 미동부 나이아가라 퀘벡 폭포뷰호텔 포함 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0017', '캐나다패키지 미국여행 미동부 나이아가라 퀘벡 포함 일정 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0018', '미국 캐나다패키지 미동부 퀘벡 나이아가라 포함 일정 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0019', '캐나다패키지 미국여행 미동부 나이아가라 퀘벡 호텔 포함 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_SNK_0020', '미국 캐나다패키지 미동부 나이아가라 퀘벡 포함 여행 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0001', '미국 캐나다 여햄 패키지 인천출발 국적기 대한한공 아시아나 직항 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0002', '캐나다 몬트리올 퀘백 나이아가르 여햄 패키지 국적기 아시아나 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0003', '미국 캐나다 여행 패키지 인천출발 노팁 대한항공 아시하나 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0004', '미국 캐나가 패키지 여행 국적기 대한항공 아시아나 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0005', '미극 캐나다 여행 패키지 국적기 대한항공 아시아나항공 항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0006', '캐나다 미국 패키지 여행 국적기 아시아나 대안항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0007', '미국 캐나다 여행 패키지 대한항공 아시아나 항공원', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0008', '캐나가 미국 여행 패키지 인천출발 아시아나항공 대한항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0009', '미극 캐나다 패키지 여행 국적기 아시아나 대한항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0010', '미국 캐나다 여행 패키지 인천출발 국적기 대한항공 아시아나항공 항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0011', '캐나가 미국 패키지 여행 인천출발 국적기 아시아나항공 대한항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0012', '미극 캐나다 여헹 패키지 인천출발 국적기 대한항공 아시아나 직항 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0013', '미국 캐나가 여행 패키지 인천출발 퀘백 아시아나 대한항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0014', '캐나다 미극 패키지 여햄 인천출발 국적기 대한항공 아시아나항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0015', '미국 캐나다 여햄 패키지 국적기 아시아나항공 대한항공 항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0016', '미극 캐나다 패키지 여행 노팁 노옵션아시아나 대한항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0017', '캐나가 미국 여행 패키지 아시아나 대한항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_OT_0018', '미국 캐나다 여햄 패키지 인천출발 국적기 아시아나항공 대한항공 항공원', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0056', '12월 여행 날씨 직항 파리 관광 패키지 항공권', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0057', '12월 날씨 여행 패키지 가격 노르망디 10박12일 프랑스', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0058', '12월 항공권 프랑스 직항 가격 노르망디 파리 비행시간', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0059', '12월 패키지 10박12일 가격 항공권 여행 노르망디', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0060', '12월 가격 프랑스 여행 항공권 노르망디 10박12일 파리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0061', '12월 프랑스 비행시간 10박12일 패키지 노르망디 관광', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0062', '12월 파리 여행 가격 노르망디 날씨 관광 패키지 비행시간', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0063', '12월 비행시간 가격 항공권 프랑스 패키지 노르망디', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0064', '12월 날씨 가격 파리 패키지 프랑스 비행시간 여행 직항', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0065', '12월 비행시간 항공권 직항 날씨 파리 관광 패키지 가격', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0066', '12월 가격 여행 패키지 직항 노르망디 10박12일 파리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0067', '12월 관광 가격 파리 여행 직항 패키지 노르망디 비행시간', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0068', '12월 관광 패키지 파리 직항 날씨 노르망디 10박12일', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0069', '12월 10박12일 비행시간 파리 패키지 항공권 직항', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__FRANCE_DMK_0070', '12월 노르망디 파리 비행시간 10박12일 패키지 프랑스', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0001', '도쿄 자유 날씨 료칸 일정 항공권 온천 직항 리조트 해외 감성숙소 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0002', '도쿄 일본 자유 감성숙소 일정 에어텔 가족 준비물 패키지 날씨 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0003', '도쿄 료칸 날씨 일정 가족 온천 항공권 패키지 여행 리조트 직항 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0004', '도쿄 여행 자유 패키지 리조트 일정 가족 준비물 온천 일본 직항 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0005', '도쿄 해외 에어텔 감성숙소 일본 날씨 리조트 온천 여행 자유 항공권 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0006', '도쿄 날씨 감성숙소 리조트 해외 일본 일정 가족 직항 항공권 여행 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0007', '도쿄 항공권 해외 일본 일정 패키지 준비물 직항 리조트 감성숙소 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0008', '도쿄 패키지 가족 준비물 여행 료칸 에어텔 날씨 항공권 일정 감성숙소', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0009', '도쿄 감성숙소 료칸 자유 가족 일정 에어텔 일본 날씨 온천 직항 준비물', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0010', '도쿄 해외 항공권 온천 일본 준비물 패키지 료칸 일정 가족 날씨 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0011', '도쿄 감성숙소 직항 에어텔 가족 여행 일정 료칸 온천 날씨 패키지 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0012', '도쿄 일정 일본 에어텔 직항 감성숙소 온천 날씨 료칸 리조트 여행 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0013', '도쿄 에어텔 날씨 자유 여행 일정 직항 감성숙소 항공권 일본 해외 료칸', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0014', '도쿄 패키지 자유 온천 여행 준비물 일본 리조트 날씨 항공권 일정 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0015', '도쿄 날씨 여행 패키지 자유 해외 준비물 가족 에어텔 일본 직항 온천', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0016', '도쿄 항공권 가족 준비물 일본 여행 리조트 자유 일정 날씨 직항 패키지', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0017', '도쿄 항공권 에어텔 료칸 자유 패키지 리조트 해외 날씨 일본 온천 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0018', '도쿄 에어텔 직항 패키지 일본 감성숙소 항공권 일정 료칸 여행 해외 온천', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKLO_0019', '도쿄 직항 날씨 감성숙소 해외 온천 료칸 패키지 항공권 에어텔 자유 여행', 'Tokyo');
