-- City Titles Part 007 (601-700번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0018', '퀸즈타운 휴일 하나투어 뉴질랜드 패키지 여름 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0019', '퀸즈타운 뉴질랜드 여름 패키지 휴일 하나투어 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNK_0020', '퀸즈타운 여행 휴일 뉴질랜드 패키지 여름 하나투어', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0001', '뉴질랜드 퀸즈타운 여행 패키지 6박8일 대한항공 직항', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0002', '퀸즈타운 뉴질랜드 패키지여행 아시아나 직항 포함', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0003', '뉴질랜드 퀸즈타운 허니문 패키지 추천 럭셔리 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0004', '퀸즈타운 뉴질랜드 가족여행 패키지 자유일정 포함', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0005', '뉴질랜드 퀸즈타운 신혼여행 패키지 노팁 노옵션', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0006', '대한항공 직항 뉴질랜드 퀸즈타운 여행 7일 일정', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0007', '퀸즈타운 자유여행+패키지 뉴질랜드 여행상품', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0008', '뉴질랜드 퀸즈타운 겨울 스키 패키지 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0009', '퀸즈타운 뉴질랜드 단풍여행 가을 패키지 추천', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0010', '뉴질랜드 퀸즈타운 패키지여행 남북섬 일주 일정', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0011', '뉴질랜드 퀸즈타운 골프여행 패키지 상품', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0012', '퀸즈타운 뉴질랜드 럭셔리 패키지여행 노쇼핑', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0013', '뉴질랜드 퀸즈타운 10박12일 패키지여행 일정', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0014', '퀸즈타운 뉴질랜드 패키지여행 부모님 효도여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0015', '뉴질랜드 퀸즈타운 자유일정 허니문 여행 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0016', '퀸즈타운 뉴질랜드 노팁 노옵션 패키지여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0017', '대한항공 직항 뉴질랜드 퀸즈타운 가족 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0018', '뉴질랜드 퀸즈타운 자유여행+패키지 추천', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0019', '뉴질랜드 퀸즈타운 패키지여행 겨울 크리스마스 일정', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_GPT_0020', '퀸즈타운 뉴질랜드 패키지여행 여름 휴가 추천', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0001', '뉴질랜드 효도여행 하나투어 패키지 퀸즈타운 명소 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0002', '뉴질랜드 패키지 퀸즈타운 명소 패키지 효도여행 하나투어', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0003', '뉴질랜드 하나투어 명소 퀸즈타운 패키지 패키지 효도여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0004', '뉴질랜드 패키지 명소 패키지 하나투어 효도여행 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0005', '뉴질랜드 효도여행 패키지 퀸즈타운 하나투어 패키지 명소', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0006', '뉴질랜드 하나투어 효도여행 퀸즈타운 패키지 명소 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0007', '뉴질랜드 명소 퀸즈타운 패키지 효도여행 패키지 하나투어', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0008', '뉴질랜드 퀸즈타운 효도여행 패키지 패키지 명소 하나투어', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0009', '뉴질랜드 명소 퀸즈타운 패키지 하나투어 효도여행 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0010', '뉴질랜드 퀸즈타운 효도여행 하나투어 패키지 명소 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0011', '뉴질랜드 하나투어 패키지 퀸즈타운 명소 패키지 효도여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0012', '뉴질랜드 효도여행 퀸즈타운 패키지 명소 패키지 하나투어', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0013', '뉴질랜드 패키지 패키지 퀸즈타운 하나투어 효도여행 명소', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0014', '뉴질랜드 효도여행 패키지 명소 하나투어 퀸즈타운 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0015', '뉴질랜드 효도여행 패키지 패키지 하나투어 명소 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0016', '뉴질랜드 퀸즈타운 패키지 하나투어 명소 효도여행 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0017', '뉴질랜드 명소 효도여행 패키지 하나투어 패키지 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0018', '뉴질랜드 효도여행 명소 하나투어 패키지 패키지 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0019', '뉴질랜드 명소 패키지 하나투어 패키지 효도여행 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_SNM_0020', '뉴질랜드 명소 패키지 효도여행 하나투어 퀸즈타운 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0001', '인천출발 가족여행 뉴질랜드 패키지 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0002', '인천출발 패키지 뉴질랜드 여행 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0003', '인천출발 패키지 가족여행 퀸즈타운 뉴질랜드', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0004', '인천출발 퀸즈타운 뉴질랜드 패키지 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0005', '인천출발 퀸즈타운 패키지 뉴질랜드 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0007', '인천출발 가족여행 뉴질랜드 퀸즈타운 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0008', '인천출발 여행 패키지 퀸즈타운 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0009', '인천출발 가족여행 뉴질랜드 여행 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0011', '인천출발 퀸즈타운 뉴질랜드 가족여행 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0012', '인천출발 패키지 여행 퀸즈타운 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0013', '인천출발 패키지 퀸즈타운 여행 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0014', '인천출발 가족여행 뉴질랜드 퀸즈타운 여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0015', '인천출발 패키지 여행 퀸즈타운 뉴질랜드', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0016', '인천출발 퀸즈타운 여행 뉴질랜드 가족여행', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0017', '인천출발 여행 퀸즈타운 뉴질랜드 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0018', '인천출발 여행 뉴질랜드 가족여행 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0019', '인천출발 뉴질랜드 가족여행 여행 퀸즈타운', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_QZT_ICH_0020', '인천출발 뉴질랜드 가족여행 퀸즈타운 패키지', 'Queenstown');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0001', '하와이 패키지 미국 와이키키 투어 인천출발 대한항공 미주여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0002', '하와이 미국 패키지 와이키키 투어 인천출발 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0003', '하와이 패키지 와이키키 투어 미국 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0004', '하와이 미국 와이키키 패키지 투어 인천출발 아시아나항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0005', '하와이 와이키키 패키지 미국 투어 인천출발 대한항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0006', '하와이 패키지 투어 미국 와이키키 인천출발 아시아나항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0007', '하와이 투어 와이키키 패키지 미국 인천출발 대한항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0008', '하와이 패키지 미국 와이키키 투어 인천출발 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0009', '하와이 미국 와이키키 투어 패키지 인천출발 대한항공 미주여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0010', '하와이 투어 패키지 와이키키 미국 인천출발 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0011', '하와이 미국 패키지 투어 와이키키 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0012', '하와이 패키지 와이키키 미국 투어 인천출발 아시아나항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0013', '하와이 와이키키 투어 미국 패키지 인천출발 대한항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0014', '하와이 패키지 투어 미주여행 와이키키 미국 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0015', '하와이 미주여행 패키지 와이키키 미국 투어 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0016', '하와이 투어 패키지 미국 와이키키 미주여행 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0017', '하와이 미국 인천출발 와이키키 패키지 투어 대한항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0018', '하와이 와이키키 인천출발 패키지 미국 투어 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0019', '하와이 미주여행 와이키키 패키지 미국 투어 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_CMK_0020', '하와이 패키지 인천출발 와이키키 미국 투어 아시아나항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0001', '와이키키해변 다이아몬드헤드 하나우마베이 마노아폭포 하와이 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0002', '코코헤드 선셋비치 할로나블로우홀 진주만 하와이 패키지 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0003', '애리조나기념관 이올라니궁전 알로하타워 와이키키해변 하와이 대한항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0004', '다이아몬드헤드 하나우마베이 코코헤드 와이키키 하와이 패키지 아시아나항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0005', '마노아폭포 선셋비치 할로나블로우홀 하와이 인천출발 대한항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0006', '진주만 애리조나기념관 이올라니궁전 하와이 패키지 아시아나항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0007', '와이키키 알로하타워 다이아몬드헤드 하와이 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0008', '하나우마베이 마노아폭포 코코헤드 하와이 패키지 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0009', '선셋비치 와이키키해변 다이아몬드헤드 하와이 대한항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0010', '이올라니궁전 알로하타워 진주만 하와이 패키지 아시아나항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0011', '와이키키 다이아몬드헤드 마노아폭포 하와이 인천출발 대한항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0012', '할로나블로우홀 코코헤드 선셋비치 하와이 패키지 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0013', '애리조나기념관 와이키키해변 알로하타워 하와이 대한항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0014', '이올라니궁전 진주만 다이아몬드헤드 하와이 패키지 아시아나항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0015', '와이키키 코코헤드 하나우마베이 하와이 인천출발 대한항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0016', '선셋비치 마노아폭포 할로나블로우홀 하와이 패키지 아시아나항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0017', '알로하타워 진주만 와이키키해변 하와이 대한항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0018', '이올라니궁전 다이아몬드헤드 하나우마베이 하와이 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0019', '와이키키해변 마노아폭포 코코헤드 하와이 인천출발 대한항공 해외여행', 'Honolulu');
