-- City Titles Part 027 (2601-2700번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0010', '방콕 직항 리조트 9월 해외 가을 날씨 패키지 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0011', '방콕 항공권 3박5일 태국 가을 해외 9월 리조트', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0012', '방콕 태국 항공권 9월 패키지 리조트 가을 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0013', '방콕 날씨 리조트 해외 9월 태국 가을 추석연휴', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0014', '방콕 날씨 리조트 패키지 여행 가을 9월 직항 태국', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0015', '방콕 패키지 날씨 직항 3박5일 리조트 9월', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0016', '방콕 항공권 날씨 리조트 태국 해외 패키지 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0017', '방콕 직항 항공권 날씨 해외 9월 가을 3박5일', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0018', '방콕 해외 직항 태국 추석연휴 9월 항공권 리조트', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0019', '방콕 여행 리조트 패키지 직항 추석연휴 가을', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0020', '방콕 항공권 여행 태국 리조트 해외 패키지 9월', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0001', '방콕 리조트 10월 태국 가을 직항 패키지 3박5일', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0002', '방콕 여행 추석연휴 패키지 10월 날씨 항공권 가을', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0003', '방콕 직항 해외 리조트 10월 3박5일 가을 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0004', '방콕 추석연휴 리조트 패키지 10월 날씨 3박5일 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0005', '방콕 3박5일 가을 날씨 해외 패키지 10월 리조트', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0006', '방콕 가을 리조트 10월 날씨 태국 여행 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0007', '방콕 가을 패키지 해외 태국 여행 10월 추석연휴 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0008', '방콕 패키지 항공권 10월 리조트 태국 해외 날씨 가을', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0009', '방콕 여행 직항 리조트 날씨 10월 태국 3박5일', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0010', '방콕 추석연휴 날씨 항공권 직항 태국 10월 가을 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0011', '방콕 여행 10월 날씨 가을 패키지 항공권 3박5일', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0012', '방콕 날씨 해외 10월 직항 패키지 가을 태국 추석연휴', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0013', '방콕 10월 날씨 직항 태국 여행 패키지 추석연휴', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0014', '방콕 태국 3박5일 날씨 추석연휴 직항 해외 10월', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MOMW_0015', '방콕 가을 패키지 리조트 태국 10월 항공권 직항 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0001', '방콕 추석연휴 리조트 패키지 가을 태국 직항 11월', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0002', '방콕 추석연휴 여행 3박5일 11월 가을 직항 태국', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0003', '방콕 여행 3박5일 리조트 11월 해외 가을 태국 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0004', '방콕 3박5일 항공권 여행 11월 태국 가을 날씨', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0005', '방콕 추석연휴 날씨 패키지 11월 태국 직항 해외 가을', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0006', '방콕 날씨 여행 11월 3박5일 태국 해외 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0007', '방콕 11월 해외 추석연휴 날씨 가을 리조트 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0008', '방콕 추석연휴 가을 태국 해외 11월 날씨 패키지 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0009', '방콕 가을 11월 날씨 태국 추석연휴 항공권 3박5일', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0010', '방콕 11월 항공권 패키지 직항 날씨 해외 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0011', '방콕 리조트 11월 항공권 가을 해외 추석연휴 날씨', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0012', '방콕 여행 추석연휴 11월 날씨 해외 패키지 태국 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MNMW_0013', '방콕 11월 항공권 여행 태국 가을 날씨 패키지 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0001', '방콕 패키지 여행 직항 날씨 해외 항공권 크루즈 가족 추천 마사지 쇼핑', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0002', '방콕 마사지 투어 관광지 크루즈 요트 날씨 선셋 해외 야경 파타야 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0003', '방콕 추천 선셋 직항 날씨 투어 항공권 요트 야시장 가족 여행 아시아티크', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0004', '방콕 크루즈 가족 날씨 야경 아시아티크 선셋 해외 투어 쇼핑 직항 야시장', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0005', '방콕 여행 야시장 해외 파타야 쇼핑 직항 항공권 날씨 아시아티크 선셋', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0006', '방콕 야경 추천 가족 해외 직항 요트 여행 아시아티크 마사지 선셋 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0007', '방콕 추천 가족 마사지 요트 야경 직항 크루즈 아시아티크 선셋 패키지', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0008', '방콕 패키지 추천 해외 가족 직항 파타야 날씨 여행 야경 투어 선셋', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0009', '방콕 가족 마사지 선셋 아시아티크 파타야 패키지 항공권 야시장 쇼핑 날씨', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0010', '방콕 해외 야경 크루즈 관광지 여행 패키지 요트 파타야 마사지 선셋', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0011', '방콕 파타야 쇼핑 항공권 직항 야경 선셋 가족 날씨 마사지 아시아티크', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0012', '방콕 선셋 마사지 야시장 해외 투어 패키지 가족 파타야 요트 관광지 추천', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0013', '방콕 투어 추천 관광지 야시장 가족 크루즈 패키지 아시아티크 야경 파타야', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0014', '방콕 날씨 추천 직항 마사지 해외 투어 가족 선셋 파타야 관광지 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0015', '방콕 파타야 관광지 패키지 항공권 투어 쇼핑 마사지 해외 선셋 아시아티크', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0016', '방콕 투어 날씨 패키지 야경 해외 아시아티크 관광지 추천 야시장 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0017', '방콕 추천 야시장 날씨 야경 마사지 아시아티크 선셋 요트 해외 파타야', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0018', '방콕 야시장 투어 직항 야경 가족 파타야 날씨 선셋 해외 관광지 추천', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0019', '방콕 항공권 마사지 날씨 아시아티크 야경 파타야 패키지 쇼핑 야시장', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0020', '방콕 쇼핑 여행 마사지 항공권 요트 가족 투어 날씨 직항 해외 야시장', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0001', '방콕 태국 리조트 추석연휴 날씨 항공권 패키지 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0002', '방콕 항공권 날씨 추석연휴 리조트 해외 괌 싱가포르', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0003', '방콕 코타키나발루 괌 해외 직항 추석연휴 여행 패키지', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0004', '방콕 직항 코타키나발루 사이판 푸켓 괌 패키지 리조트', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0005', '방콕 태국 여행 날씨 패키지 싱가포르 괌 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0006', '방콕 사이판 패키지 푸켓 여행 리조트 직항 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0007', '방콕 태국 푸켓 괌 해외 사이판 항공권 패키지 날씨', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0008', '방콕 태국 괌 싱가포르 푸켓 여행 날씨 리조트 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0009', '방콕 패키지 추석연휴 태국 항공권 코타키나발루 날씨', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0010', '방콕 여행 싱가포르 사이판 패키지 추석연휴 항공권 날씨', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0011', '방콕 항공권 날씨 패키지 추석연휴 여행 싱가포르 사이판', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0012', '방콕 괌 사이판 패키지 싱가포르 추석연휴 날씨 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0013', '방콕 날씨 태국 항공권 사이판 싱가포르 직항 괌 패키지', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0014', '방콕 리조트 푸켓 날씨 태국 괌 싱가포르 여행 사이판', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0015', '방콕 항공권 괌 사이판 싱가포르 태국 패키지 날씨 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0016', '방콕 사이판 추석연휴 항공권 태국 날씨 직항 패키지', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0017', '방콕 태국 리조트 괌 푸켓 직항 날씨 싱가포르 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0018', '방콕 싱가포르 항공권 푸켓 패키지 직항 태국 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0019', '방콕 코타키나발루 여행 직항 추석연휴 싱가포르 날씨', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0020', '방콕 사이판 직항 패키지 싱가포르 코타키나발루 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_01', '푸껫 여행 태국 리조트 해외 날씨 직항 항공권 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_02', '푸껫 직항 패키지 날씨 리조트 여행 항공권 태국 해외', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_03', '푸껫 태국 여행 직항 날씨 리조트 항공권 해외 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_04', '푸껫 날씨 여행 항공권 태국 직항 리조트 해외 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_05', '푸껫 직항 해외 리조트 여행 태국 날씨 항공권 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_06', '푸껫 날씨 태국 여행 항공권 해외 패키지 리조트 직항', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_07', '푸껫 리조트 해외 태국 직항 날씨 패키지 항공권 여행', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_08', '푸껫 리조트 태국 항공권 해외 직항 날씨 여행 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_09', '푸껫 리조트 여행 항공권 태국 해외 직항 날씨 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_10', '푸껫 여행 날씨 직항 리조트 패키지 해외 태국 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_11', '푸껫 날씨 직항 항공권 해외 태국 패키지 여행 리조트', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_12', '푸껫 항공권 리조트 직항 태국 패키지 여행 해외 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_13', '푸껫 해외 태국 날씨 리조트 패키지 직항 여행 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_14', '푸껫 항공권 리조트 날씨 해외 패키지 여행 태국 직항', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_15', '푸껫 태국 직항 날씨 항공권 여행 패키지 해외 리조트', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_16', '푸껫 항공권 날씨 해외 여행 패키지 직항 리조트 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_17', '푸껫 리조트 태국 항공권 해외 직항 여행 패키지 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_18', '푸껫 리조트 여행 해외 항공권 직항 날씨 태국 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_19', '푸껫 리조트 항공권 해외 태국 직항 패키지 여행 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_20', '푸껫 해외 패키지 태국 항공권 여행 직항 리조트 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_01', '푸껫 빠통비치 호텔 숙소 날씨 빅부다 왓찰롱 쇼핑 태국 여행 마사지', 'Phuket');
