-- City Titles Part 036 (3501-3600번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0012', '12월 3박5일 푸꾸옥 베트남 동남아 날씨 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0013', '12월 날씨 항공권 여행 일정 동남아 리조트 3박5일', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0014', '12월 리조트 직항 동남아 날씨 패키지 항공권 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0015', '12월 날씨 직항 패키지 일정 여행 3박5일 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0016', '12월 리조트 항공권 베트남 해외 패키지 여행 일정', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0017', '12월 여행 3박5일 해외 동남아 푸꾸옥 항공권 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0018', '12월 일정 여행 리조트 직항 패키지 해외 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0019', '12월 베트남 푸꾸옥 해외 3박5일 리조트 여행 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0020', '12월 날씨 해외 직항 항공권 패키지 3박5일 푸꾸옥', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0001', '하노이 일정 직항 날씨 베트남 하롱베이 항공권 패키지', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0002', '하노이 패키지 하롱베이 날씨 리조트 직항 해외 베트남', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0003', '하노이 직항 항공권 여행 해외 동남아 하롱베이 일정', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0004', '하노이 동남아 여행 일정 하롱베이 직항 리조트 항공권', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0005', '하노이 해외 여행 일정 베트남 리조트 날씨 항공권', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0006', '하노이 여행 하롱베이 직항 패키지 베트남 리조트 항공권', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0007', '하노이 일정 날씨 항공권 리조트 해외 동남아 베트남', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0008', '하노이 일정 패키지 항공권 직항 여행 베트남 동남아', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0009', '하노이 일정 날씨 동남아 직항 여행 베트남 하롱베이', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0010', '하노이 직항 베트남 리조트 하롱베이 일정 동남아 날씨', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0011', '하노이 동남아 베트남 날씨 일정 해외 항공권 리조트', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0012', '하노이 하롱베이 리조트 직항 패키지 베트남 날씨 일정', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0013', '하노이 하롱베이 해외 날씨 리조트 패키지 항공권 동남아', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0014', '하노이 하롱베이 여행 베트남 동남아 패키지 날씨 해외', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0015', '하노이 해외 하롱베이 리조트 베트남 직항 패키지 일정', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0016', '하노이 항공권 여행 일정 해외 날씨 리조트 하롱베이', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0017', '하노이 항공권 하롱베이 베트남 패키지 리조트 직항', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0018', '하노이 동남아 일정 직항 해외 여행 날씨 베트남 리조트', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0019', '하노이 동남아 여행 리조트 일정 베트남 직항 하롱베이', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MMK_0020', '하노이 리조트 동남아 베트남 날씨 일정 해외 여행', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0001', '하노이 리조트 하롱베이 해외 에어텔 휴양 직항 패키지', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0002', '하노이 하롱베이 에어텔 자유 항공권 패키지 야시장 날씨', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0003', '하노이 휴양 케이블카 항공권 호핑투어 하롱베이 야시장', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0004', '하노이 호핑투어 관광지 해외 여행 항공권 날씨 동남아', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0005', '하노이 날씨 동남아 여행 항공권 하롱베이 케이블카', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0006', '하노이 야시장 여행 베트남 관광지 항공권 하롱베이', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0007', '하노이 호핑투어 직항 해외 하롱베이 여행 휴양 자유', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0008', '하노이 관광지 자유 패키지 베트남 휴양 일정 동남아', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0009', '하노이 일정 자유 여행 에어텔 베트남 패키지 항공권', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0010', '하노이 하롱베이 날씨 리조트 여행 케이블카 관광지 야경', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0011', '하노이 야시장 직항 여행 케이블카 베트남 해외 호핑투어', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0012', '하노이 야경 패키지 리조트 자유 항공권 에어텔 베트남', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0013', '하노이 동남아 자유 관광지 호핑투어 베트남 휴양', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0014', '하노이 여행 동남아 에어텔 패키지 휴양 항공권 호핑투어', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0015', '하노이 자유 리조트 직항 날씨 여행 항공권 하롱베이', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0016', '하노이 날씨 하롱베이 여행 직항 동남아 야시장 해외', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0017', '하노이 리조트 하롱베이 베트남 직항 항공권 일정', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0018', '하노이 리조트 베트남 일정 야경 에어텔 휴양 케이블카', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0019', '하노이 하롱베이 항공권 리조트 해외 직항 에어텔 동남아', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKSH_0020', '하노이 야시장 케이블카 해외 동남아 여행 휴양 자유', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0001', '하노이 항공권 케이블카 리조트 동남아 자유 해외 에어텔 베트남 일정', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0002', '하노이 베트남 야경 항공권 일정 날씨 직항 동남아 케이블카 해외 호핑투어', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0003', '하노이 베트남 동남아 에어텔 관광지 일정 호핑투어 자유 야시장 직항', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0004', '하노이 휴양 패키지 베트남 항공권 에어텔 야경 해외 관광지 직항 케이블카', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0005', '하노이 날씨 베트남 자유 관광지 에어텔 휴양 직항 해외 패키지 하롱베이', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0006', '하노이 야시장 여행 에어텔 리조트 패키지 자유 일정 직항 해외 동남아', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0007', '하노이 관광지 야경 해외 일정 야시장 베트남 호핑투어 여행 자유 케이블카', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0008', '하노이 리조트 자유 동남아 하롱베이 직항 야경 패키지 에어텔 관광지', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0009', '하노이 자유 야시장 동남아 케이블카 해외 호핑투어 항공권 일정 에어텔', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0010', '하노이 관광지 리조트 여행 에어텔 호핑투어 일정 해외 야시장 케이블카', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0011', '하노이 패키지 직항 케이블카 리조트 관광지 항공권 야시장 동남아 야경', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0012', '하노이 케이블카 동남아 야시장 야경 해외 날씨 직항 관광지 여행 하롱베이', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0013', '하노이 호핑투어 해외 날씨 직항 리조트 케이블카 일정 항공권 관광지', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0014', '하노이 날씨 관광지 여행 패키지 야시장 항공권 리조트 에어텔 휴양', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0015', '하노이 야시장 베트남 하롱베이 여행 휴양 야경 호핑투어 관광지 동남아', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0016', '하노이 패키지 동남아 직항 야경 관광지 여행 일정 자유 하롱베이 에어텔', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0017', '하노이 베트남 야시장 직항 자유 휴양 리조트 항공권 여행 하롱베이 에어텔', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0018', '하노이 야시장 자유 직항 일정 야경 하롱베이 베트남 휴양 에어텔 해외', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0019', '하노이 리조트 여행 휴양 에어텔 패키지 날씨 베트남 야시장 일정 직항', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKLKLO_0020', '하노이 호핑투어 여행 해외 휴양 하롱베이 관광지 야경 일정 케이블카', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0001', '하노이 일정 베트남 항공권 하롱베이 패키지 리조트', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0002', '하노이 동남아 리조트 해외 베트남 기차거리 패키지', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0003', '하노이 여행 베트남 거북탑 항공권 해외 기차거리 직항', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0004', '하노이 직항 리조트 베트남 날씨 패키지 기차거리', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0005', '하노이 서기둥사원 리조트 일정 호치민 날씨 직항 베트남', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0006', '하노이 기차거리 리조트 베트남 패키지 일정 해외 날씨', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0007', '하노이 여행 기차거리 동남아 일정 해외 서기둥사원', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0008', '하노이 거북탑 패키지 베트남 기차거리 호치민 여행', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0009', '하노이 여행 서기둥사원 일정 기차거리 직항 하롱베이', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0010', '하노이 하롱베이 리조트 해외 호치민 거북탑 패키지', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0011', '하노이 베트남 호치민 기차거리 동남아 해외 거북탑', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0012', '하노이 호치민 동남아 항공권 하롱베이 거북탑 패키지', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0013', '하노이 해외 패키지 기차거리 리조트 동남아 여행 날씨', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0014', '하노이 동남아 리조트 기차거리 패키지 호치민 거북탑', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0015', '하노이 항공권 베트남 여행 호치민 날씨 패키지 일정', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0016', '하노이 항공권 직항 거북탑 패키지 리조트 베트남 날씨', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0017', '하노이 리조트 일정 동남아 패키지 여행 호치민 기차거리', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0018', '하노이 거북탑 날씨 동남아 베트남 서기둥사원 기차거리', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0019', '하노이 항공권 호치민 베트남 일정 리조트 여행 동남아', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_MKR_0020', '하노이 베트남 하롱베이 리조트 동남아 패키지 날씨', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0001', '인천출발 항공권 여행 해외 패키지 하노이 베트남', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0002', '인천출발 직항 여행 일정 하노이 리조트 대한항공 항공권', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0003', '인천출발 패키지 날씨 해외 일정 직항 하노이 하롱베이', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0004', '인천출발 하노이 직항 날씨 여행 동남아 대한항공 리조트', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0005', '인천출발 해외 동남아 베트남 리조트 대한항공 항공권', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0006', '인천출발 항공권 베트남 날씨 하롱베이 리조트 동남아', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0007', '인천출발 대한항공 일정 직항 날씨 하노이 동남아 베트남', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0008', '인천출발 대한항공 여행 하롱베이 직항 베트남 리조트', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0009', '인천출발 리조트 항공권 베트남 패키지 여행 대한항공', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0010', '인천출발 대한항공 직항 하롱베이 베트남 일정 패키지', 'Hanoi');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_HANOI_ICMKK_0011', '인천출발 날씨 여행 대한항공 하노이 직항 항공권 베트남', 'Hanoi');
