-- City Titles Part 093 (9201-9300번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0022', '동유럽 힐링 숙소 일주 미식 직항 오스트리아 항공권 체코 야간투어 관광', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0023', '동유럽 야간투어 항공권 패키지 가을 힐링 일주 가볼만한곳 미식 오스트리아', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0024', '동유럽 숙소 항공권 관광 미식 가격 가볼만한곳 직항 오스트리아 야간투어', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0025', '동유럽 미식 일주 비행시간 가볼만한곳 힐링 여행 오스트리아 항공권', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0026', '동유럽 가을 겨울 일주 비행시간 항공권 야간투어 가볼만한곳 오스트리아', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0027', '동유럽 미식 일주 오스트리아 겨울 여행 관광 항공권 헝가리 비행시간 가격', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0028', '동유럽 헝가리 항공권 직항 미식 가을 케이블카 비행시간 가격 패키지 일주', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0029', '동유럽 헝가리 직항 체코 숙소 관광 가격 겨울 야간투어 가을 패키지', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_ML_0030', '동유럽 관광 겨울 항공권 일주 케이블카 직항 여행 체코 가격 가을', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0021', '11월 관광 동유럽 직항 가격 여행 7박9일 헝가리', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0022', '11월 가격 7박9일 동유럽 헝가리 체코 직항 비행시간', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0023', '11월 일주 직항 여행 오스트리아 동유럽 헝가리 항공권', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0024', '11월 오스트리아 항공권 일주 패키지 7박9일 가격', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0025', '11월 가격 오스트리아 패키지 직항 관광 체코 동유럽', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0026', '11월 비행시간 패키지 여행 직항 7박9일 관광', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0027', '11월 일주 헝가리 직항 가격 동유럽 항공권 여행 관광', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0028', '11월 7박9일 패키지 가격 여행 동유럽 헝가리 체코', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0029', '11월 직항 헝가리 체코 가격 비행시간 항공권 7박9일', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0030', '11월 여행 체코 동유럽 일주 오스트리아 7박9일', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0051', '12월 일주 7박9일 비행시간 가격 체코 항공권', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0052', '12월 패키지 일주 항공권 동유럽 가격 관광 7박9일', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0053', '12월 체코 동유럽 일주 비행시간 헝가리 여행 관광', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0054', '12월 여행 패키지 일주 비행시간 관광 항공권 7박9일', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0055', '12월 체코 오스트리아 7박9일 관광 일주 비행시간', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0056', '12월 항공권 오스트리아 직항 7박9일 관광 체코', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0057', '12월 7박9일 동유럽 체코 관광 여행 일주 가격', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0058', '12월 가격 체코 여행 일주 패키지 동유럽 헝가리 관광', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0059', '12월 체코 관광 항공권 가격 패키지 비행시간', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__AUSTRIA_DMK_0060', '12월 체코 관광 일주 가격 항공권 직항 패키지 동유럽', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0021', '12월 헝가리 할슈타트 여행 7박9일 비행시간 항공권', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0022', '12월 오스트리아 패키지 잘츠부르크 7박9일 관광', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0023', '12월 직항 할슈타트 여행 헝가리 알프스 잘츠부르크', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0024', '12월 부다페스트 여행 비행시간 프라하 할슈타트 관광', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0025', '12월 부다페스트 할슈타트 가격 체코 패키지 잘츠부르크', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0026', '12월 부다페스트 알프스 일주 가격 동유럽 패키지', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0027', '12월 여행 관광 동유럽 체코 헝가리 비행시간', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0028', '12월 잘츠부르크 직항 여행 오스트리아 항공권 패키지', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0029', '12월 오스트리아 비행시간 체코 일주 할슈타트 프라하', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0030', '12월 관광 잘츠부르크 체코 헝가리 부다페스트 알프스', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0021', '스페인 포르투갈 패키지 가격 관광 여행 항공권 직항', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0022', '스페인 포르투갈 바르셀로나 가격 리스본 파티마 여행', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0023', '스페인 포르투갈 직항 바르셀로나 리스본 관광 파티마', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0024', '스페인 포르투갈 관광 마드리드 파티마 바르셀로나', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0025', '스페인 포르투갈 마드리드 리스본 직항 가격', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0026', '스페인 포르투갈 리스본 바르셀로나 남유럽 일주', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0027', '스페인 포르투갈 마드리드 남유럽 일주 직항 파티마', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0028', '스페인 포르투갈 관광 가격 리스본 마드리드 직항', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0029', '스페인 포르투갈 여행 파티마 항공권 패키지', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__SPAINPORTU_MKL_0030', '스페인 포르투갈 파티마 패키지 마드리드 항공권', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0026', '스페인 포르투갈 특가 추석연휴 미식 파티마 가을철 항공권 가볼만한곳', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0027', '스페인 포르투갈 특가 가을철 숙소 바르셀로나 겨울철 남유럽 일주 마드리드', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0028', '스페인 포르투갈 가격 리스본 직항 가을철 남유럽 일주 관광 겨울철 숙소', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0029', '스페인 포르투갈 가볼만한곳 남유럽 일주 항공권 가격 가을철 관광 패키지', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0030', '스페인 포르투갈 여행 바르셀로나 항공권 직항 숙소 가볼만한곳 추석연휴', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0031', '스페인 포르투갈 마드리드 가격 직항 가볼만한곳 파티마 미식 리스본 특가', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0032', '스페인 포르투갈 마드리드 여행 가을철 가격 힐링 직항 리스본 항공권', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0033', '스페인 포르투갈 관광 바르셀로나 리스본 겨울철 가을철 여행 직항', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0034', '스페인 포르투갈 마드리드 가격 관광 숙소 가을철 파티마 리스본', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0035', '스페인 포르투갈 가을철 패키지 숙소 힐링 가격 특가 겨울철 여행 직항', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0036', '스페인 포르투갈 파티마 미식 패키지 관광 가볼만한곳 남유럽 일주 가격', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0037', '스페인 포르투갈 패키지 바르셀로나 추석연휴 여행 마드리드 가을철 겨울철', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0038', '스페인 포르투갈 파티마 남유럽 일주 겨울철 마드리드 가격 미식 바르셀로나', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0039', '스페인 포르투갈 바르셀로나 파티마 항공권 힐링 가격 리스본 추석연휴', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0040', '스페인 포르투갈 추석연휴 가볼만한곳 바르셀로나 가을철 남유럽 일주 패키지', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0041', '스페인 포르투갈 남유럽 일주 여행 마드리드 파티마 관광 리스본 특가 가격', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0042', '스페인 포르투갈 특가 가격 남유럽 일주 힐링 파티마 마드리드 직항', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0043', '스페인 포르투갈 미식 힐링 직항 가격 마드리드 파티마 가을철 추석연휴', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0044', '스페인 포르투갈 가을철 항공권 숙소 가격 파티마 리스본 패키지 직항', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0045', '스페인 포르투갈 추석연휴 숙소 가을철 힐링 겨울철 항공권 마드리드 관광', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0046', '스페인 포르투갈 마드리드 특가 추석연휴 리스본 직항 바르셀로나 가격 관광', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0047', '스페인 포르투갈 바르셀로나 미식 추석연휴 숙소 가격 관광 직항 특가', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0048', '스페인 포르투갈 힐링 남유럽 일주 숙소 가을철 직항 항공권 관광 패키지', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0049', '스페인 포르투갈 패키지 숙소 가을철 여행 직항 마드리드 특가 바르셀로나', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_SPAINPORTU_ML_0050', '스페인 포르투갈 리스본 가볼만한곳 바르셀로나 패키지 추석연휴 여행 겨울철', 'Portugal');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0021', '방콕 추석연휴 해외 리조트 여행 패키지 날씨 태국', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0022', '방콕 해외 태국 여행 패키지 항공권 추석연휴 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0023', '방콕 해외 리조트 여행 날씨 패키지 태국 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0024', '방콕 직항 패키지 날씨 태국 여행 리조트 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0025', '방콕 직항 추석연휴 태국 해외 날씨 항공권 리조트', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0026', '방콕 직항 태국 추석연휴 날씨 리조트 항공권 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0027', '방콕 태국 리조트 패키지 해외 항공권 여행 날씨', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0028', '방콕 추석연휴 직항 여행 태국 해외 날씨 리조트', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0029', '방콕 태국 패키지 직항 항공권 날씨 여행 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0030', '방콕 날씨 직항 태국 항공권 패키지 리조트 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0031', '방콕 추석연휴 해외 패키지 항공권 리조트 태국 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0032', '방콕 리조트 날씨 항공권 추석연휴 직항 패키지 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0033', '방콕 해외 태국 항공권 패키지 리조트 여행 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0034', '방콕 직항 패키지 날씨 여행 해외 추석연휴 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MMK_0035', '방콕 리조트 해외 추석연휴 항공권 여행 패키지 태국', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0021', '방콕 왓포 항공권 해외 날씨 여행 왓프라깨우 왕궁', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0022', '방콕 항공권 날씨 왓포 왓프라깨우 해외 직항 왕궁', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0023', '방콕 해외 왓포 날씨 왓프라깨우 항공권 직항 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0024', '방콕 여행 해외 항공권 태국 왕궁 날씨 왓포', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0025', '방콕 직항 왕궁 왓프라깨우 해외 날씨 태국 왓포', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0026', '방콕 날씨 항공권 왓포 해외 태국 왓프라깨우 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0027', '방콕 태국 날씨 왓프라깨우 왓포 해외 직항 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0028', '방콕 항공권 해외 여행 왓포 직항 왓프라깨우 태국', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0029', '방콕 왕궁 직항 왓포 여행 왓프라깨우 태국 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSLT_0030', '방콕 왓프라깨우 왕궁 해외 직항 여행 왓포 날씨', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0021', '방콕 태국 리조트 날씨 항공권 여행 3박5일 가을', 'Bangkok');
