-- City Titles Part 047 (4601-4700번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0011', '일본여행 패키지 교토타워 기온 날씨 교토역 직항 리조트', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0012', '일본여행 항공권 기온 리조트 날씨 교토 패키지 직항', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0013', '일본여행 패키지 해외 오사카 직항 리조트 기온 청수사', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0014', '일본여행 항공권 청수사 날씨 기온 교토타워 해외 교토역', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0015', '일본여행 교토역 리조트 직항 항공권 해외 교토타워', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0016', '일본여행 날씨 교토타워 교토 교토역 오사카 기온 리조트', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0017', '일본여행 청수사 교토타워 오사카 직항 항공권 기온 날씨', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0018', '일본여행 해외 패키지 교토타워 청수사 오사카 날씨', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0019', '일본여행 기온 패키지 교토타워 해외 청수사 교토 교토역', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MRRRR_0020', '일본여행 해외 항공권 기온 날씨 오사카 교토타워 청수사', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0001', '일본여행 기온 해외 리조트 청수사 직항 패키지 날씨', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0002', '일본여행 날씨 직항 패키지 해외 에어텔 기온 교토', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0003', '일본여행 오사카 리조트 기온 직항 에어텔 교토 패키지', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0004', '일본여행 해외 청수사 오사카 에어텔 간사이공항 리조트', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0005', '일본여행 청수사 기온 패키지 에어텔 리조트 항공권', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0006', '일본여행 날씨 청수사 기온 직항 항공권 해외 에어텔', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0007', '일본여행 항공권 간사이공항 해외 리조트 패키지 오사카', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0008', '일본여행 기온 오사카 항공권 패키지 직항 에어텔 청수사', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0009', '일본여행 오사카 해외 청수사 기온 날씨 항공권 직항', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0010', '일본여행 오사카 직항 교토 해외 기온 항공권 간사이공항', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0011', '일본여행 청수사 오사카 직항 리조트 해외 패키지 교토', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0012', '일본여행 직항 오사카 간사이공항 해외 항공권 에어텔', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0013', '일본여행 오사카 리조트 교토 날씨 기온 패키지 에어텔', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0014', '일본여행 패키지 오사카 교토 항공권 리조트 직항 에어텔', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0015', '일본여행 항공권 날씨 교토 해외 직항 기온 리조트', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0016', '일본여행 에어텔 직항 간사이공항 패키지 기온 교토', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0017', '일본여행 패키지 청수사 항공권 오사카 직항 에어텔 기온', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0018', '일본여행 간사이공항 청수사 에어텔 교토 날씨 항공권', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0019', '일본여행 항공권 직항 에어텔 해외 패키지 날씨 청수사', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_RAN_0020', '일본여행 날씨 간사이공항 리조트 교토 항공권 기온', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0001', '후쿠오카 오사카 날씨 직항 여행 일본여행 항공권 해외', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0002', '후쿠오카 해외 일본여행 날씨 패키지 항공권 여행 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0003', '후쿠오카 리조트 여행 패키지 일본여행 직항 날씨 해외', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0004', '후쿠오카 여행 리조트 오사카 항공권 직항 날씨 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0005', '후쿠오카 직항 일본여행 리조트 날씨 해외 오사카 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0006', '후쿠오카 여행 패키지 리조트 일본여행 날씨 해외 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0007', '후쿠오카 리조트 해외 패키지 일본여행 여행 항공권 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0008', '후쿠오카 날씨 직항 리조트 해외 패키지 항공권 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0009', '후쿠오카 여행 패키지 직항 리조트 해외 오사카 일본여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0010', '후쿠오카 일본여행 항공권 직항 날씨 여행 리조트 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0011', '후쿠오카 리조트 여행 직항 항공권 패키지 해외 일본여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0012', '후쿠오카 항공권 패키지 여행 직항 날씨 오사카 리조트', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0013', '후쿠오카 일본여행 해외 리조트 패키지 직항 여행 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0014', '후쿠오카 패키지 리조트 오사카 해외 항공권 여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0015', '후쿠오카 날씨 여행 일본여행 리조트 해외 오사카 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0016', '후쿠오카 패키지 항공권 여행 직항 해외 일본여행 리조트', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0017', '후쿠오카 일본여행 직항 오사카 패키지 날씨 항공권 해외', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0018', '후쿠오카 일본여행 해외 날씨 직항 패키지 항공권 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0019', '후쿠오카 패키지 일본여행 직항 날씨 해외 여행 리조트', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MMK_0020', '후쿠오카 항공권 리조트 여행 일본여행 직항 해외 날씨', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0001', '후쿠오카 오사카 간사이공항 일본여행 에어텔 날씨 해외', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0002', '후쿠오카 직항 일본여행 교토 해외 간사이공항 날씨', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0003', '후쿠오카 교토 일본여행 리조트 간사이공항 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0004', '후쿠오카 항공권 에어텔 교토 나라 직항 교토 일본여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0005', '후쿠오카 날씨 항공권 해외 나라 리조트 온천 커플여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0006', '후쿠오카 날씨 교토 패키지 일본여행 온천 리조트', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0007', '후쿠오카 직항 해외 나라 여행 교토 오사카 커플여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0008', '후쿠오카 날씨 패키지 간사이공항 일본여행 에어텔', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0009', '후쿠오카 리조트 오사카 일본여행 교토 직항 커플여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0010', '후쿠오카 여행 일본여행 커플여행 에어텔 나라 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0011', '후쿠오카 일본여행 패키지 간사이공항 온천 나라 날씨', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0012', '후쿠오카 항공권 직항 온천 오사카 일본여행 여행 에어텔', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0013', '후쿠오카 해외 에어텔 일본여행 직항 패키지 간사이공항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0014', '후쿠오카 온천 간사이공항 여행 날씨 교토 오사카 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0015', '후쿠오카 해외 오사카 간사이공항 나라 직항 교토 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0016', '후쿠오카 간사이공항 날씨 해외 오사카 에어텔 나라 교토', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0017', '후쿠오카 교토 온천 에어텔 해외 리조트 나라 간사이공항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0018', '후쿠오카 항공권 날씨 리조트 나라 온천 일본여행 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0019', '후쿠오카 교토 직항 해외 항공권 온천 에어텔 일본여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKSH_0020', '후쿠오카 날씨 커플여행 교토 교토 직항 일본여행 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0001', '후쿠오카 나라 패키지 해외 오사카 커플여행 간사이공항 직항 여행 에어텔', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0002', '후쿠오카 직항 커플여행 간사이공항 오사카 에어텔 온천 리조트 교토 나라', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0003', '후쿠오카 여행 나라 항공권 일본여행 온천 리조트 날씨 오사카 교토 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0004', '후쿠오카 나라 날씨 온천 일본여행 직항 여행 에어텔 커플여행 해외 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0005', '후쿠오카 에어텔 여행 날씨 교토 온천 직항 나라 리조트 일본여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0006', '후쿠오카 해외 간사이공항 일본여행 항공권 교토 나라 패키지 에어텔 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0007', '후쿠오카 오사카 간사이공항 온천 리조트 일본여행 에어텔 교토 커플여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0008', '후쿠오카 항공권 온천 해외 커플여행 직항 나라 패키지 교토 일본여행 여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0009', '후쿠오카 직항 교토 커플여행 날씨 일본여행 여행 리조트 교토 에어텔 나라', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0010', '후쿠오카 나라 패키지 일본여행 교토 날씨 온천 해외 리조트 에어텔 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0011', '후쿠오카 여행 리조트 간사이공항 에어텔 직항 교토 나라 교토 항공권', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0012', '후쿠오카 직항 해외 온천 에어텔 교토 일본여행 나라 리조트 오사카 여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0013', '후쿠오카 나라 교토 에어텔 해외 리조트 직항 여행 패키지 온천 간사이공항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0014', '후쿠오카 여행 직항 간사이공항 패키지 해외 날씨 일본여행 온천 나라', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0015', '후쿠오카 일본여행 패키지 나라 리조트 해외 온천 날씨 교토 교토 항공권', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0016', '후쿠오카 날씨 오사카 리조트 일본여행 에어텔 직항 나라 교토 간사이공항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0017', '후쿠오카 커플여행 일본여행 교토 여행 리조트 에어텔 간사이공항 교토 날씨', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0018', '후쿠오카 교토 패키지 날씨 리조트 에어텔 온천 항공권 커플여행 일본여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0019', '후쿠오카 간사이공항 커플여행 직항 패키지 해외 온천 나라 에어텔 항공권', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MKLKLO_0020', '후쿠오카 교토 오사카 해외 교토 일본여행 날씨 패키지 온천 에어텔 여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0001', '10월 일본여행 후쿠오카 항공권 오사카 직항 리조트', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0002', '10월 해외 후쿠오카 날씨 직항 항공권 캐널시티하카타', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0003', '10월 오사카 패키지 해외 캐널시티하카타 후쿠오카타워', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0004', '10월 여행 오사카 후쿠오카타워 직항 날씨 일본여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0005', '10월 날씨 후쿠오카 오사카 후쿠오카타워 여행 리조트', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0006', '10월 직항 여행 후쿠오카 일본여행 패키지 해외', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0007', '10월 패키지 일본여행 오사카 후쿠오카 날씨 해외', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0008', '10월 날씨 캐널시티하카타 후쿠오카타워 오사카 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0009', '10월 여행 항공권 패키지 직항 후쿠오카 해외 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_OMKRT_0010', '10월 패키지 후쿠오카 오사카 날씨 여행 후쿠오카타워', 'Fukuoka');
