-- City Titles Part 045 (4401-4500번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRR_0012', '일본여행 날씨 일정 오사카 리조트 패키지 도톤보리', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRR_0013', '일본여행 리조트 날씨 일정 도톤보리 항공권 직항', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRR_0014', '일본여행 패키지 해외 날씨 항공권 리조트 도톤보리 직항', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRR_0015', '일본여행 날씨 일정 유니버셜스튜디오 오사카 직항 리조트', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRR_0016', '일본여행 항공권 날씨 도톤보리 오사카 리조트 직항 일정', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRR_0017', '일본여행 리조트 날씨 항공권 직항 일정 도톤보리', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRR_0018', '일본여행 날씨 항공권 오사카 패키지 리조트', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRR_0019', '일본여행 일정 리조트 항공권 오사카 도톤보리', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRR_0020', '일본여행 날씨 일정 유니버셜스튜디오 패키지 도톤보리', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0001', '일본여행 패키지 항공권 일정 해외 리조트', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0002', '일본여행 유니버셜스튜디오 일정 항공권 직항 패키지', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0003', '일본여행 직항 날씨 리조트 패키지 오사카 일정 해외', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0004', '일본여행 신사이바시 날씨 해외 유니버셜스튜디오 오사카성', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0005', '일본여행 오사카 일정 리조트 신사이바시 오사카성 패키지', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0006', '일본여행 도톤보리 오사카성 일정 날씨 직항 항공권', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0007', '일본여행 리조트 오사카 오사카성 유니버셜스튜디오 직항', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0008', '일본여행 일정 오사카성 해외 리조트 오사카 항공권', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0009', '일본여행 날씨 오사카 패키지 신사이바시 일정 해외 직항', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0010', '일본여행 오사카성 일정 오사카 리조트 패키지 도톤보리', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0011', '일본여행 패키지 오사카성 리조트 신사이바시 해외 항공권', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0012', '일본여행 직항 유니버셜스튜디오 오사카 일정 날씨 항공권', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0013', '일본여행 해외 오사카성 신사이바시 도톤보리 날씨 리조트', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0014', '일본여행 도톤보리 직항 유니버셜스튜디오 날씨 항공권', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0015', '일본여행 오사카성 일정 직항 도톤보리 해외 항공권', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0016', '일본여행 패키지 신사이바시 유니버셜스튜디오 날씨 리조트', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0017', '일본여행 직항 오사카성 신사이바시 해외 리조트', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0018', '일본여행 해외 패키지 일정 직항 신사이바시 날씨 리조트', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0019', '일본여행 리조트 항공권 도톤보리 직항 유니버셜스튜디오', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_MRRRR_0020', '일본여행 도톤보리 유니버셜스튜디오 패키지 오사카', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0001', '일본여행 리조트 패키지 해외 직항 교토 날씨 에어텔', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0002', '일본여행 에어텔 간사이공항 패키지 일정 인천출발 교토', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0003', '일본여행 리조트 날씨 도톤보리 인천출발 직항 에어텔', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0004', '일본여행 간사이공항 리조트 도톤보리 직항 인천출발', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0005', '일본여행 리조트 인천출발 항공권 에어텔 교토 해외 일정', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0006', '일본여행 도톤보리 교토 날씨 인천출발 에어텔 항공권', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0007', '일본여행 패키지 항공권 도톤보리 인천출발 에어텔 날씨', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0008', '일본여행 패키지 리조트 도톤보리 해외 간사이공항 직항', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0009', '일본여행 오사카 항공권 날씨 패키지 해외 교토 인천출발', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0010', '일본여행 날씨 간사이공항 교토 직항 도톤보리 에어텔', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0011', '일본여행 항공권 오사카 에어텔 리조트 교토 일정 직항', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0012', '일본여행 오사카 간사이공항 패키지 직항 리조트 항공권', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0013', '일본여행 도톤보리 리조트 간사이공항 인천출발 교토', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0014', '일본여행 패키지 해외 인천출발 도톤보리 오사카 항공권', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0015', '일본여행 에어텔 오사카 교토 패키지 날씨 간사이공항', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0016', '일본여행 항공권 간사이공항 일정 도톤보리 에어텔 해외', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0017', '일본여행 날씨 일정 교토 오사카 리조트 에어텔 패키지', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0018', '일본여행 인천출발 직항 도톤보리 간사이공항 해외 리조트', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0019', '일본여행 패키지 간사이공항 일정 해외 날씨 교토 오사카', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_OSAK_RAN_0020', '일본여행 일정 간사이공항 항공권 도톤보리 해외 직항', 'Osaka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0001', '교토 패키지 해외 오사카 여행 리조트 항공권 날씨 일본', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0002', '교토 리조트 오사카 일본 패키지 해외 날씨 항공권 직항', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0003', '교토 오사카 여행 일본 항공권 직항 리조트 해외 패키지', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0004', '교토 오사카 패키지 리조트 여행 해외 날씨 직항 일본', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0005', '교토 패키지 오사카 항공권 여행 직항 리조트 날씨 해외', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0006', '교토 해외 항공권 일본 패키지 오사카 날씨 리조트 직항', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0007', '교토 항공권 해외 직항 오사카 날씨 리조트 여행 일본', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0008', '교토 날씨 직항 리조트 여행 해외 일본 오사카 패키지', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0009', '교토 여행 항공권 오사카 일본 직항 패키지 해외 날씨', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0010', '교토 패키지 리조트 여행 직항 항공권 날씨 해외 오사카', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0011', '교토 직항 여행 날씨 오사카 해외 항공권 패키지 일본', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0012', '교토 항공권 해외 패키지 오사카 일본 리조트 여행 날씨', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0013', '교토 여행 오사카 항공권 해외 날씨 패키지 일본 리조트', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0014', '교토 리조트 직항 해외 일본 여행 날씨 오사카 항공권', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0015', '교토 날씨 일본 오사카 여행 해외 직항 항공권 패키지', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0016', '교토 해외 일본 날씨 직항 항공권 오사카 리조트 패키지', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0017', '교토 항공권 오사카 직항 일본 리조트 패키지 여행 해외', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0018', '교토 여행 패키지 항공권 일본 직항 오사카 날씨 리조트', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0019', '교토 리조트 오사카 해외 직항 패키지 날씨 일본 항공권', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MMK_0020', '교토 직항 오사카 해외 패키지 항공권 여행 리조트 날씨', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0001', '교토 간사이공항 해외 항공권 여행 온천 일본 직항 나라', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0002', '교토 온천 간사이공항 해외 패키지 날씨 직항 나라 여행', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0003', '교토 패키지 나라 리조트 간사이공항 오사카 여행 항공권', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0004', '교토 패키지 직항 여행 해외 간사이공항 항공권 온천', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0005', '교토 간사이공항 직항 나라 온천 에어텔 해외 날씨', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0006', '교토 커플여행 오사카 여행 날씨 간사이공항 나라 온천', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0007', '교토 여행 날씨 간사이공항 나라 온천 해외 오사카', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0008', '교토 일본 항공권 날씨 온천 패키지 나라 오사카 리조트', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0009', '교토 직항 간사이공항 날씨 해외 커플여행 온천 에어텔', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0010', '교토 날씨 해외 여행 커플여행 에어텔 오사카 온천', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0011', '교토 일본 커플여행 간사이공항 여행 에어텔 리조트 나라', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0012', '교토 오사카 해외 커플여행 리조트 여행 온천 간사이공항', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0013', '교토 리조트 일본 날씨 커플여행 간사이공항 직항 여행', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0014', '교토 오사카 날씨 여행 항공권 직항 패키지 간사이공항', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0015', '교토 커플여행 직항 해외 간사이공항 날씨 패키지 나라', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0016', '교토 에어텔 리조트 일본 직항 항공권 온천 오사카 날씨', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0017', '교토 오사카 온천 나라 리조트 해외 일본 여행 항공권', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0018', '교토 온천 날씨 에어텔 오사카 리조트 항공권 직항', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0019', '교토 여행 나라 커플여행 직항 오사카 간사이공항 리조트', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKSH_0020', '교토 리조트 오사카 커플여행 항공권 간사이공항 여행', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0001', '교토 오사카 직항 나라 온천 일본 항공권 에어텔 커플여행 날씨 패키지', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0002', '교토 여행 항공권 오사카 커플여행 에어텔 일본 나라 날씨 직항 온천', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0003', '교토 오사카 커플여행 에어텔 간사이공항 여행 일본 직항 리조트 온천', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0004', '교토 여행 오사카 일본 에어텔 해외 리조트 간사이공항 나라 패키지', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0005', '교토 일본 온천 오사카 날씨 리조트 항공권 해외 패키지 간사이공항', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0006', '교토 항공권 해외 나라 패키지 리조트 온천 오사카 일본 에어텔 직항 여행', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0007', '교토 해외 날씨 오사카 에어텔 나라 커플여행 온천 항공권 패키지', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0008', '교토 패키지 직항 해외 간사이공항 여행 커플여행 오사카 일본 항공권 날씨', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0009', '교토 간사이공항 커플여행 온천 나라 항공권 직항 해외 패키지 에어텔', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0010', '교토 에어텔 간사이공항 여행 해외 패키지 온천 커플여행 날씨 항공권 나라', 'Kyoto');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KYOT_MKLKLO_0011', '교토 패키지 항공권 오사카 해외 온천 날씨 에어텔 리조트 여행 커플여행', 'Kyoto');
