-- City Titles Part 012 (1101-1200번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0013', '대한항공 프리몬트스트리트 미국 돌비극장 여행 코카콜라스토어 라스베가스 금문교 피셔맨스워프', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0014', '돌비극장 그랜드캐년 여행 미국 코카콜라스토어 스타의거리 라스베가스 아시아나항공 그리피스천문대', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0015', '미국 라스베가스 스타의거리 대한항공 피어39 여행 프리몬트스트리트 그랜드캐년 돌비극장', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0016', '아시아나항공 프리몬트스트리트 피셔맨스워프 금문교 그랜드캐년 라스베가스 미국 여행 피어39', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0017', '피어39 라스베가스 여행 대한항공 프리몬트스트리트 미국 돌비극장 그랜드캐년 스타의거리', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0018', '그랜드캐년 돌비극장 아시아나항공 피셔맨스워프 라스베가스 금문교 코카콜라스토어 여행 미국', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0019', '금문교 라스베가스 미국 그랜드캐년 대한항공 스타의거리 코카콜라스토어 프리몬트스트리트 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0020', '피어39 라스베가스 금문교 그랜드캐년 프리몬트스트리트 코카콜라스토어 여행 미국 아시아나항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0001', '9월 여행 7일 6박8일 직항 대한항공 미서부패키지여행 그랜드캐년 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0002', '7월 여행 아시아나항공 미국 8대캐년 로스앤젤레스 가을 여행 8월', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0003', '하반기 여행 직항 8월 서부 대한항공 미국 7일 로스앤젤레스', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0004', '여행 아시아나항공 9월 서부 그랜드캐년 하반기 직항 2026년 로스앤젤레스', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0005', '7일 서부 10박12일 로스앤젤레스 여행 여행 대한항공 8박10일 미국', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0006', '서부 여행 직항 하반기 라스베가스 8대캐년 아시아나항공 10월 9월', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0007', '여행 로스앤젤레스 8박10일 서부 7일 8대캐년 가을 대한항공 미국', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0008', '9월 로스앤젤레스 2026년 직항 아시아나항공 여행 10월 그랜드캐년 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0009', '여행 대한항공 10박12일 여행 8월 서부 6월 미서부패키지여행 8대캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0010', '6월 로스앤젤레스 미서부패키지여행 6박8일 아시아나항공 라스베가스 여행 10월 8대캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0011', '7일 라스베가스 미서부패키지여행 그랜드캐년 6박8일 9월 8대캐년 여행 대한항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0012', '2026년 아시아나항공 여행 여행 서부 로스앤젤레스 그랜드캐년 10박12일 7일', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0013', '9월 6박8일 라스베가스 10박12일 여행 여행 대한항공 미서부패키지여행 8대캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0014', '직항 여행 로스앤젤레스 아시아나항공 6월 9월 서부 미국 8월', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0015', '대한항공 여행 7일 라스베가스 8대캐년 9월 미서부패키지여행 직항 2026년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0016', '아시아나항공 서부 직항 10박12일 8대캐년 여행 6박8일 로스앤젤레스 9월', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0017', '8대캐년 8박10일 여행 대한항공 로스앤젤레스 미국 9월 7월 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0018', '아시아나항공 서부 8박10일 7월 라스베가스 직항 9월 로스앤젤레스 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0019', '라스베가스 여행 미서부패키지여행 대한항공 6월 여행 9월 8월 로스앤젤레스', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_DMK_0020', '하반기 아시아나항공 여행 라스베가스 9월 여행 10박12일 로스앤젤레스 직항', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0001', '자이언캐년 연휴여행 금문교 그랜드캐년 그리피스천문대 해외가족여행 프리몬트스트리트 대한항공 피셔맨스워프 노팁 돌비극장 미국그랜드캐년여행 피어39 럭셔리 노쇼핑 부모님', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0002', '럭셔리 미서부여행 노팁 미국그랜드캐년여행 아시아나항공 스타의거리 그랜드캐년 금문교 해외가족여행 부모님 코카콜라스토어 연휴여행 피어39 노쇼핑 그리피스천문대 노옵션 프리몬트스트리트', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0003', '자이언캐년 그리피스천문대 해외가족여행 미서부여행 노옵션 대한항공 금문교 라스베가스여행 럭셔리 프리몬트스트리트 부모님 노팁 투어 코카콜라스토어 피어39 그랜드캐년 미국그랜드캐년여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0004', '부모님 피셔맨스워프 럭셔리 투어 연휴여행 해외가족여행 스타의거리 금문교 미서부여행 그랜드캐년 피어39 미국그랜드캐년여행 노옵션 아시아나항공 노팁 프리몬트스트리트', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0005', '럭셔리 노쇼핑 스타의거리 라스베가스여행 그리피스천문대 그랜드캐년 돌비극장 피어39 대한항공 미국그랜드캐년여행 노옵션 자이언캐년 코카콜라스토어 투어 프리몬트스트리트 금문교 피셔맨스워프', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0006', '코카콜라스토어 프리몬트스트리트 미국그랜드캐년여행 금문교 노쇼핑 스타의거리 자이언캐년 돌비극장 그랜드캐년 럭셔리 그리피스천문대 미서부여행 해외가족여행 아시아나항공 노옵션 투어 피셔맨스워프', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0007', '스타의거리 그랜드캐년 노팁 연휴여행 피어39 부모님 프리몬트스트리트 미국그랜드캐년여행 자이언캐년 피셔맨스워프 노옵션 대한항공 그리피스천문대 럭셔리 미서부여행 돌비극장', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0008', '연휴여행 스타의거리 미서부여행 피셔맨스워프 해외가족여행 피어39 아시아나항공 금문교 노쇼핑 그리피스천문대 노팁 미국그랜드캐년여행 돌비극장 그랜드캐년 노옵션 럭셔리 부모님', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0009', '연휴여행 노쇼핑 투어 피셔맨스워프 미서부여행 대한항공 노옵션 미국그랜드캐년여행 노팁 피어39 그리피스천문대 금문교 스타의거리 프리몬트스트리트 그랜드캐년 코카콜라스토어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0010', '그리피스천문대 자이언캐년 피어39 스타의거리 미서부여행 노쇼핑 아시아나항공 연휴여행 부모님 돌비극장 피셔맨스워프 코카콜라스토어 럭셔리 프리몬트스트리트 투어 미국그랜드캐년여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0011', '피셔맨스워프 해외가족여행 미국그랜드캐년여행 노옵션 투어 대한항공 라스베가스여행 자이언캐년 노팁 스타의거리 미서부여행 프리몬트스트리트 돌비극장 부모님 노쇼핑 금문교 그랜드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0012', '부모님 노옵션 스타의거리 프리몬트스트리트 돌비극장 연휴여행 미국그랜드캐년여행 미서부여행 투어 그리피스천문대 코카콜라스토어 피셔맨스워프 피어39 해외가족여행 아시아나항공 그랜드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0013', '스타의거리 그랜드캐년 피셔맨스워프 럭셔리 프리몬트스트리트 대한항공 해외가족여행 미서부여행 미국그랜드캐년여행 돌비극장 노쇼핑 연휴여행 코카콜라스토어 자이언캐년 그리피스천문대 부모님', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0014', '미국그랜드캐년여행 스타의거리 럭셔리 돌비극장 피어39 자이언캐년 노팁 투어 부모님 아시아나항공 연휴여행 그랜드캐년 라스베가스여행 노옵션 그리피스천문대 미서부여행 금문교', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0015', '그랜드캐년 피셔맨스워프 부모님 대한항공 투어 노쇼핑 노옵션 해외가족여행 연휴여행 미서부여행 금문교 노팁 미국그랜드캐년여행 자이언캐년 그리피스천문대 럭셔리', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0016', '미서부여행 코카콜라스토어 노팁 그랜드캐년 투어 노쇼핑 피어39 프리몬트스트리트 금문교 돌비극장 노옵션 해외가족여행 스타의거리 피셔맨스워프 부모님 럭셔리 아시아나항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0017', '자이언캐년 해외가족여행 피어39 프리몬트스트리트 미국그랜드캐년여행 연휴여행 금문교 미서부여행 노팁 대한항공 코카콜라스토어 투어 럭셔리 스타의거리 노쇼핑 노옵션', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0018', '연휴여행 아시아나항공 스타의거리 미서부여행 미국그랜드캐년여행 노옵션 금문교 해외가족여행 럭셔리 투어 부모님 그리피스천문대 그랜드캐년 코카콜라스토어 자이언캐년 노팁', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0019', '해외가족여행 미서부여행 럭셔리 대한항공 돌비극장 그랜드캐년 금문교 코카콜라스토어 그리피스천문대 노팁 피어39 연휴여행 부모님 스타의거리 자이언캐년 투어 라스베가스여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_ML_0020', '프리몬트스트리트 럭셔리 미국그랜드캐년여행 그리피스천문대 아시아나항공 노옵션 해외가족여행 노쇼핑 자이언캐년 부모님 그랜드캐년 돌비극장 투어 피어39 미서부여행 스타의거리 노팁', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0001', '라스베가스여행 미서부여행 대한항공 LA직항 모두투어 패키지 미국그랜드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0002', '6박7일 패키지 미주여행 미국그랜드캐년 LA직항 아시아나항공 모두투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0003', '라스베가스여행 LA직항 LA 패키지 대한항공 미국그랜드캐년 미국서부여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0004', '패키지 6박7일 LA LA직항 모두투어 미서부여행 아시아나항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0005', 'LA 미서부여행 패키지 LA직항 미주여행 미국서부여행 대한항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0006', '패키지 LA직항 6박7일 미국서부여행 라스베가스여행 미주여행 아시아나항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0007', '미국서부여행 6박7일 미서부여행 패키지 미국그랜드캐년 LA직항 대한항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0008', '미국서부여행 모두투어 아시아나항공 미국그랜드캐년 라스베가스여행 LA직항 미주여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0009', '미국그랜드캐년 모두투어 LA 미국서부여행 패키지 대한항공 미주여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0010', '미주여행 패키지 LA직항 미서부여행 6박7일 모두투어 아시아나항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0011', 'LA LA직항 미서부여행 라스베가스여행 모두투어 미국그랜드캐년 대한항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0012', '모두투어 미주여행 LA직항 라스베가스여행 미국그랜드캐년 아시아나항공 미국서부여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0013', '미서부여행 6박7일 패키지 모두투어 미국서부여행 대한항공 미주여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0014', '미서부여행 아시아나항공 미국서부여행 모두투어 미주여행 라스베가스여행 미국그랜드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0015', '미주여행 대한항공 미국그랜드캐년 미서부여행 모두투어 6박7일 LA직항', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0016', '아시아나항공 6박7일 LA직항 미국서부여행 라스베가스여행 미서부여행 모두투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0017', '모두투어 6박7일 LA직항 미국그랜드캐년 라스베가스여행 미주여행 대한항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0018', 'LA직항 6박7일 LA 아시아나항공 모두투어 미국서부여행 라스베가스여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0019', '패키지 라스베가스여행 모두투어 미주여행 미서부여행 대한항공 미국그랜드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_SNK_0020', '미서부여행 아시아나항공 라스베가스여행 미국그랜드캐년 미주여행 LA직항 LA', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0001', '라스베게스 피셔맨스워프 여행 여행 미서부패키지여행 금문교 대한항공 직항 그렌드캐년 스타의거리', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0002', '서부 그렌드캐년 미국 미서부패키지여행 그리피스천문대 여행 프리몬트스트리트 아시아나항공 8대캐년 그렌드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0003', '미국 대한항공 스타의거리 돌비극장 직항 여행 라스베게스 그리피스천문대 서부 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0004', '여행 아시아나항공 8대캐년 미서부패키지여행 피어39 로스엔젤레스 돌비극장 서부 여행 금문교', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0005', '로스엔젤레스 미국 대한항공 금문교 돌비극장 라스베게스 여행 프리몬트스트리트 여행 미서부패키지여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0006', '돌비극장 스타의거리 아시아나항공 로스엔젤레스 라스베게스 미국 여행 그렌드캐년 미서부패키지여행 직항', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0007', '대한항공 여행 돌비극장 8대캐년 그리피스천문대 로스엔젤레스 피셔맨스워프 직항 그렌드캐년 미서부패키지여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0008', '그렌드캐년 직항 여행 금문교 미국 라스베게스 아시아나항공 그렌드캐년 코카콜라스토어 로스엔젤레스', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0009', '여행 미서부패키지여행 그렌드캐년 그렌드캐년 금문교 직항 서부 대한항공 코카콜라스토어 8대캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0010', '미서부패키지여행 금문교 8대캐년 라스베게스 직항 여행 그렌드캐년 아시아나항공 피셔맨스워프 돌비극장', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0011', '그리피스천문대 여행 로스엔젤레스 라스베게스 스타의거리 여행 미서부패키지여행 그렌드캐년 금문교 대한항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0012', '피셔맨스워프 직항 미국 아시아나항공 금문교 여행 서부 그렌드캐년 8대캐년 라스베게스', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0013', '코카콜라스토어 돌비극장 라스베게스 직항 여행 여행 대한항공 서부 금문교 미서부패키지여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0014', '피셔맨스워프 그렌드캐년 8대캐년 그렌드캐년 아시아나항공 여행 로스엔젤레스 서부 직항 돌비극장', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0015', '미서부패키지여행 대한항공 로스엔젤레스 그렌드캐년 서부 8대캐년 그리피스천문대 스타의거리 피셔맨스워프 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0016', '서부 미서부패키지여행 스타의거리 아시아나항공 여행 8대캐년 돌비극장 여행 피셔맨스워프 직항', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0017', '미국 스타의거리 라스베게스 8대캐년 여행 미서부패키지여행 피셔맨스워프 피어39 대한항공 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0018', '여행 서부 8대캐년 코카콜라스토어 돌비극장 라스베게스 피어39 여행 아시아나항공 그렌드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0019', '금문교 그렌드캐년 여행 로스엔젤레스 여행 코카콜라스토어 8대캐년 미국 프리몬트스트리트 대한항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_OT_0020', '여행 아시아나항공 로스엔젤레스 서부 코카콜라스토어 피셔맨스워프 8대캐년 그리피스천문대 미서부패키지여행 직항', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0001', '라스베이거스 스트래토스피어타워 벨라지오분수쇼 프리몬트스트리트 투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0002', '라스베이거스 카지노 패키지 벨라지오분수쇼 미라지화산쇼 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0003', '라스베이거스 하이롤러 스트립 스트래토스피어타워 투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0004', '라스베이거스 프리몬트스트리트 스트립 카지노 투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0005', '라스베이거스 미라지화산쇼 벨라지오분수쇼 패키지', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0006', '라스베이거스 스트립 하이롤러 스트래토스피어타워 투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0007', '라스베이거스 프리몬트스트리트 스트립 카지노 패키지', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0008', '라스베이거스 미라지화산쇼 하이롤러 벨라지오분수쇼 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0009', '라스베이거스 스트립 스트래토스피어타워 하이롤러 투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0010', '라스베이거스 벨라지오분수쇼 프리몬트스트리트 미라지화산쇼 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0011', '라스베이거스 카지노 패키지 스트립 스트래토스피어타워 투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0012', '라스베이거스 하이롤러 벨라지오분수쇼 스트립 투어', 'LasVegas');
