-- City Titles Part 106 (10501-10600번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_DMKRT_0025', '12월 캐널시티하카타 후쿠오카타워 리조트 여행 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_DMKRT_0026', '12월 직항 일본여행 해외 오사카 후쿠오카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_DMKRT_0027', '12월 날씨 오사카 후쿠오카 캐널시티하카타 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_DMKRT_0028', '12월 후쿠오카 캐널시티하카타 해외 오사카 리조트', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_DMKRT_0029', '12월 해외 항공권 여행 패키지 캐널시티하카타 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_DMKRT_0030', '12월 패키지 일본여행 오사카 후쿠오카 리조트 해외', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0021', '일본여행 리조트 패키지 오사카 직항 항공권 후쿠오카타워', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0022', '일본여행 후쿠오카 항공권 후쿠오카타워 리조트 해외 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0023', '일본여행 해외 오사카 캐널시티하카타 리조트 후쿠오카타워', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0024', '일본여행 패키지 리조트 후쿠오카타워 직항 오사카 항공권', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0025', '일본여행 직항 후쿠오카타워 날씨 패키지 항공권 해외', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0026', '일본여행 오사카 리조트 후쿠오카 여행 캐널시티하카타', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0027', '일본여행 여행 패키지 리조트 후쿠오카타워 캐널시티하카타', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0028', '일본여행 후쿠오카타워 날씨 패키지 해외 캐널시티하카타', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0029', '일본여행 리조트 후쿠오카 날씨 캐널시티하카타 여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRR_0030', '일본여행 직항 후쿠오카 후쿠오카타워 캐널시티하카타', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0021', '일본여행 날씨 캐널시티하카타 후쿠오카타워 항공권', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0022', '일본여행 리조트 해외 후쿠오카 후쿠오카타워 항공권', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0023', '일본여행 나카스야타이거리 후쿠오카타워 직항 여행 리조트', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0024', '일본여행 패키지 오사카 후쿠오카 날씨 여행 해외 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0025', '일본여행 패키지 캐널시티하카타 나카스야타이거리 항공권', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0026', '일본여행 해외 후쿠오카 여행 나카스야타이거리 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0027', '일본여행 항공권 여행 직항 오호리공원 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0028', '일본여행 여행 캐널시티하카타 직항 후쿠오카 날씨', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0029', '일본여행 리조트 해외 날씨 항공권 직항 오호리공원', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_MRFIV_0030', '일본여행 패키지 다자이후텐만구 나카스야타이거리', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0021', '일본여행 항공권 에어텔 후쿠오카 해외 오사카 여행 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0022', '일본여행 리조트 여행 황금연휴 패키지 에어텔 후쿠오카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0023', '일본여행 후쿠오카 에어텔 황금연휴 직항 리조트 날씨', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0024', '일본여행 오사카 날씨 에어텔 해외 여행 황금연휴 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0025', '일본여행 황금연휴 항공권 에어텔 오사카 여행 후쿠오카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0026', '일본여행 오사카 황금연휴 에어텔 여행 항공권 직항 해외', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0027', '일본여행 해외 패키지 에어텔 후쿠오카 날씨 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0028', '일본여행 항공권 에어텔 오사카 해외 후쿠오카 직항 날씨', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0029', '일본여행 황금연휴 항공권 직항 후쿠오카 여행 패키지', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0030', '일본여행 날씨 직항 리조트 해외 여행 오사카 에어텔', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0021', '벳부 리조트 날씨 해외 일본여행 직항 패키지 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0022', '벳부 패키지 리조트 직항 유후인 일본여행 항공권 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0023', '벳부 유후인 패키지 직항 날씨 일본여행 리조트 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0024', '벳부 리조트 직항 패키지 일본여행 항공권 유후인 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0025', '벳부 직항 해외 날씨 리조트 패키지 항공권 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0026', '벳부 날씨 리조트 유후인 패키지 항공권 직항 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0027', '벳부 일본여행 해외 직항 리조트 항공권 날씨 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0028', '벳부 해외 패키지 직항 유후인 항공권 리조트 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0029', '벳부 날씨 패키지 항공권 직항 일본여행 리조트 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0030', '벳부 항공권 해외 패키지 유후인 직항 리조트 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0021', '벳부 에어텔 유후인 날씨 도쿄 오사카 해외 일본 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0022', '벳부 에어텔 직항 리조트 항공권 패키지 일본 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0023', '벳부 에어텔 항공권 커플여행 도쿄 일본 날씨 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0024', '벳부 패키지 에어텔 일본 유후인 오사카 커플여행 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0025', '벳부 도쿄 유후인 날씨 일본 오사카 커플여행 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0026', '벳부 커플여행 일본 에어텔 오사카 유후인 패키지 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0027', '벳부 오사카 날씨 항공권 직항 간사이공항 패키지 에어텔', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0028', '벳부 해외 도쿄 항공권 커플여행 날씨 직항 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0029', '벳부 해외 직항 도쿄 커플여행 날씨 에어텔 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0030', '벳부 오사카 패키지 항공권 일본 간사이공항 에어텔 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0021', '벳부 에어텔 리조트 간사이공항 오사카 패키지 커플여행 도쿄 항공권 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0022', '벳부 항공권 리조트 간사이공항 일본 에어텔 오사카 커플여행 도쿄 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0023', '벳부 에어텔 날씨 간사이공항 항공권 리조트 도쿄 직항 패키지 커플여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0024', '벳부 해외 항공권 에어텔 오사카 일본 유후인 도쿄 직항 간사이공항 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0025', '벳부 일본 오사카 항공권 패키지 리조트 간사이공항 직항 해외 유후인 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0026', '벳부 해외 유후인 날씨 에어텔 일본 간사이공항 커플여행 오사카 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0027', '벳부 일본 유후인 오사카 직항 항공권 에어텔 해외 날씨 간사이공항 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0028', '벳부 해외 커플여행 오사카 일본 항공권 도쿄 유후인 패키지 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0029', '벳부 간사이공항 커플여행 리조트 도쿄 유후인 해외 오사카 직항 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0030', '벳부 항공권 커플여행 해외 직항 오사카 도쿄 패키지 일본 리조트 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0021', '10월 해외 직항 날씨 리조트 패키지 일본여행 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0022', '10월 리조트 패키지 유후인 직항 해외 다케산 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0023', '10월 유후인 직항 벳부 온천 날씨 다케산 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0024', '10월 온천 직항 해외 항공권 날씨 일본여행 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0025', '10월 날씨 일본여행 벳부 직항 온천 유후인 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0026', '10월 직항 항공권 다케산 일본여행 날씨 유후인 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0027', '10월 벳부 해외 날씨 리조트 다케산 직항 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0028', '10월 해외 온천 일본여행 패키지 리조트 직항 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0029', '10월 벳부 일본여행 다케산 해외 항공권 리조트 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0030', '10월 직항 날씨 리조트 온천 해외 유후인 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0021', '11월 리조트 벳부 패키지 일본여행 날씨 항공권 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0022', '11월 해외 일본여행 직항 다케산 리조트 유후인 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0023', '11월 직항 리조트 날씨 벳부 항공권 일본여행 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0024', '11월 다케산 온천 직항 해외 날씨 패키지 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0025', '11월 리조트 온천 날씨 직항 패키지 벳부 다케산 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0026', '11월 해외 리조트 패키지 일본여행 온천 항공권 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0027', '11월 유후인 해외 항공권 날씨 다케산 리조트 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0028', '11월 직항 리조트 항공권 온천 일본여행 해외 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0029', '11월 직항 항공권 날씨 리조트 다케산 일본여행 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0030', '11월 직항 일본여행 해외 항공권 온천 벳부 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0021', '12월 리조트 온천 일본여행 날씨 직항 패키지 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0022', '12월 유후인 직항 리조트 온천 해외 벳부 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0023', '12월 날씨 일본여행 패키지 유후인 온천 항공권 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0024', '12월 유후인 다케산 항공권 날씨 온천 리조트 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0025', '12월 온천 리조트 항공권 직항 날씨 벳부 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0026', '12월 리조트 다케산 날씨 직항 일본여행 유후인 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0027', '12월 패키지 날씨 항공권 해외 직항 다케산 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0028', '12월 항공권 리조트 온천 날씨 벳부 직항 유후인 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0029', '12월 일본여행 유후인 온천 리조트 직항 벳부 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_DMKRT_0030', '12월 벳부 온천 해외 리조트 직항 유후인 날씨 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0021', '일본여행 벳부 해외 패키지 항공권 직항 리조트 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0022', '일본여행 유후인 온천 날씨 패키지 해외 벳부 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0023', '일본여행 직항 해외 리조트 온천 다케산 유후인 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0024', '일본여행 리조트 벳부 온천 해외 직항 날씨 유후인', 'BeppuYufuin');
