-- City Titles Part 029 (2801-2900번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_02', '11월 날씨 3박 5일 태국 항공권 패키지 가을 리조트', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_03', '11월 태국 패키지 해외 날씨 푸껫 항공권 여행 가을', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_04', '11월 직항 해외 푸껫 가을 항공권 3박 5일 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_05', '11월 3박 5일 직항 해외 여행 패키지 가을 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_06', '11월 태국 푸껫 3박 5일 항공권 패키지 해외 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_07', '11월 가을 3박 5일 푸껫 리조트 태국 패키지 여행', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_08', '11월 태국 패키지 직항 해외 가을 리조트 항공권 여행', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_09', '11월 패키지 태국 3박 5일 항공권 푸껫 해외 직항', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_10', '11월 날씨 가을 항공권 푸껫 패키지 리조트 해외 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0001', '싱가포르 패키지 여행 해외 직항 일정 항공권 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0002', '싱가포르 여행 항공권 해외 직항 리조트 패키지 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0003', '싱가포르 해외 리조트 날씨 일정 여행 패키지 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0004', '싱가포르 날씨 해외 일정 리조트 여행 패키지 직항', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0005', '싱가포르 일정 해외 직항 여행 리조트 항공권 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0006', '싱가포르 날씨 여행 리조트 일정 직항 항공권 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0007', '싱가포르 직항 리조트 항공권 패키지 날씨 일정 여행', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0008', '싱가포르 직항 해외 여행 일정 항공권 날씨 패키지', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0009', '싱가포르 날씨 여행 일정 패키지 리조트 직항 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0010', '싱가포르 날씨 여행 항공권 해외 일정 패키지 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0011', '싱가포르 여행 일정 해외 패키지 리조트 직항 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0012', '싱가포르 패키지 항공권 해외 리조트 여행 직항 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0013', '싱가포르 직항 리조트 일정 여행 항공권 해외 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0014', '싱가포르 리조트 패키지 항공권 여행 해외 날씨 직항', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0015', '싱가포르 항공권 직항 해외 날씨 패키지 일정 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0016', '싱가포르 날씨 일정 해외 여행 항공권 직항 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0017', '싱가포르 패키지 일정 리조트 항공권 날씨 해외 여행', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0018', '싱가포르 직항 리조트 해외 일정 패키지 여행 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0019', '싱가포르 날씨 직항 여행 패키지 리조트 항공권 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0020', '싱가포르 직항 해외 날씨 패키지 여행 리조트 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0001', '싱가포르 관광지 리조트 추천 체험 일정 쇼핑 시장 비치', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0002', '싱가포르 패키지 쇼핑 추천 리조트 여행 해외 먹거리', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0003', '싱가포르 버스 쇼핑 허니문 체험 날씨 항공권 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0004', '싱가포르 버스 관광지 시장 여행 추천 일정 항공권 쇼핑', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0005', '싱가포르 여행 추천 먹거리 허니문 일정 항공권 관광지', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0006', '싱가포르 체험 허니문 시장 파크 리조트 쇼핑 가족 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0007', '싱가포르 시장 날씨 추천 파크 관광지 해외 먹거리 버스', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0008', '싱가포르 일정 날씨 체험 리조트 시장 패키지 추천 직항', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0009', '싱가포르 여행 리조트 비치 직항 일정 시장 버스 패키지', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0010', '싱가포르 쇼핑 비치 일정 날씨 먹거리 가족 파크 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0011', '싱가포르 항공권 파크 가족 패키지 쇼핑 리조트 비치', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0012', '싱가포르 항공권 버스 허니문 패키지 일정 추천 먹거리', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0013', '싱가포르 관광지 가족 파크 시장 일정 패키지 먹거리', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0014', '싱가포르 체험 패키지 직항 비치 추천 쇼핑 해외 파크', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0015', '싱가포르 비치 버스 직항 시장 먹거리 파크 쇼핑 가족', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0016', '싱가포르 날씨 버스 해외 시장 여행 리조트 관광지', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0017', '싱가포르 허니문 일정 해외 관광지 직항 리조트 추천', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0018', '싱가포르 시장 해외 쇼핑 비치 체험 버스 허니문 추천', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0019', '싱가포르 허니문 쇼핑 리조트 여행 일정 패키지 가족', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0020', '싱가포르 여행 패키지 가족 날씨 버스 직항 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0001', '싱가포르 허니문 일정 해외 관광지 직항 가족 패키지 쇼핑 먹거리 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0002', '싱가포르 일정 여행 비치 추천 버스 해외 직항 날씨 체험 리조트 시장', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0003', '싱가포르 쇼핑 해외 패키지 날씨 먹거리 파크 일정 리조트 직항 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0004', '싱가포르 해외 체험 시장 비치 추천 일정 허니문 파크 버스 리조트 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0005', '싱가포르 시장 직항 비치 여행 먹거리 일정 쇼핑 리조트 버스 허니문', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0006', '싱가포르 파크 허니문 체험 비치 패키지 리조트 항공권 추천 버스 가족', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0007', '싱가포르 추천 먹거리 파크 가족 체험 리조트 직항 허니문 해외 패키지', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0008', '싱가포르 항공권 먹거리 패키지 쇼핑 시장 가족 비치 관광지 날씨 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0009', '싱가포르 추천 관광지 허니문 직항 쇼핑 항공권 시장 비치 버스 파크 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0010', '싱가포르 가족 파크 허니문 비치 직항 쇼핑 관광지 항공권 날씨 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0011', '싱가포르 허니문 관광지 먹거리 체험 해외 추천 항공권 여행 리조트 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0012', '싱가포르 먹거리 파크 버스 리조트 패키지 직항 관광지 일정 가족 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0013', '싱가포르 관광지 허니문 직항 파크 항공권 날씨 비치 일정 쇼핑 버스 시장', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0014', '싱가포르 먹거리 비치 일정 리조트 관광지 파크 패키지 체험 허니문 버스', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0015', '싱가포르 날씨 관광지 패키지 체험 먹거리 파크 가족 추천 일정 버스 직항', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0016', '싱가포르 날씨 관광지 비치 먹거리 쇼핑 체험 패키지 일정 여행 가족 직항', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0017', '싱가포르 해외 시장 버스 비치 허니문 체험 관광지 패키지 추천 가족 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0018', '싱가포르 추천 파크 비치 체험 허니문 쇼핑 가족 해외 시장 여행 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0019', '싱가포르 직항 쇼핑 관광지 시장 먹거리 날씨 해외 리조트 패키지 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0020', '싱가포르 비치 먹거리 항공권 여행 허니문 가족 관광지 버스 체험 파크', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0001', '인천출발 날짜 해외 여행 싱가포르 날씨 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0002', '인천출발 날짜 싱가포르 해외 여행 날씨 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0003', '인천출발 여행 날씨 항공권 해외 날짜 싱가포르', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0004', '인천출발 싱가포르 항공권 여행 날씨 해외 날짜', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0005', '인천출발 날짜 싱가포르 날씨 항공권 여행 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0006', '인천출발 해외 날씨 항공권 날짜 여행 싱가포르', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0007', '인천출발 날짜 여행 싱가포르 해외 항공권 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0008', '인천출발 항공권 해외 여행 날짜 날씨 싱가포르', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0009', '인천출발 날씨 해외 날짜 여행 항공권 싱가포르', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0010', '인천출발 해외 항공권 날씨 여행 날짜 싱가포르', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0011', '인천출발 싱가포르 날짜 항공권 날씨 해외 여행', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0012', '인천출발 항공권 날씨 여행 날짜 싱가포르 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0013', '인천출발 항공권 날짜 여행 날씨 싱가포르 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0014', '인천출발 날짜 싱가포르 여행 해외 항공권 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0015', '인천출발 항공권 날짜 해외 날씨 싱가포르 여행', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0016', '인천출발 해외 항공권 싱가포르 여행 날씨 날짜', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0017', '인천출발 날짜 싱가포르 날씨 해외 여행 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0018', '인천출발 여행 해외 날짜 항공권 싱가포르 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0019', '인천출발 싱가포르 날짜 날씨 항공권 여행 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0020', '인천출발 싱가포르 날짜 날씨 여행 항공권 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0001', '10월 항공권 여행 싱가포르 3박5일 날씨 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0002', '10월 날씨 여행 싱가포르 3박5일 항공권 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0003', '10월 날씨 항공권 여행 3박5일 해외 싱가포르', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0004', '10월 3박5일 항공권 날씨 싱가포르 여행 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0005', '10월 항공권 싱가포르 3박5일 여행 해외 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0006', '10월 여행 해외 3박5일 날씨 싱가포르 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0007', '10월 날씨 싱가포르 3박5일 여행 해외 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0008', '10월 싱가포르 여행 항공권 3박5일 날씨 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0009', '10월 싱가포르 날씨 3박5일 항공권 여행 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0010', '10월 항공권 3박5일 날씨 해외 여행 싱가포르', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_OMKTF_0011', '10월 3박5일 날씨 여행 항공권 해외 싱가포르', 'Singapore');
