-- City Titles Part 051 (5001-5100번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0011', '치앙마이 태국 패키지 일정 날씨 직항 리조트 여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0012', '치앙마이 리조트 해외 날씨 직항 일정 태국 항공권 여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0013', '치앙마이 직항 리조트 일정 항공권 패키지 해외 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0014', '치앙마이 태국 해외 일정 직항 리조트 날씨 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0015', '치앙마이 태국 직항 일정 리조트 패키지 여행 해외', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0016', '치앙마이 해외 태국 항공권 날씨 일정 직항 패키지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0017', '치앙마이 패키지 리조트 해외 여행 날씨 항공권 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0018', '치앙마이 항공권 패키지 일정 리조트 여행 직항 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0019', '치앙마이 리조트 해외 항공권 패키지 여행 일정 날씨', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0020', '치앙마이 리조트 해외 일정 날씨 패키지 여행 태국 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0021', '치앙마이 태국 리조트 패키지 해외 날씨 여행 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0022', '치앙마이 항공권 태국 해외 여행 일정 날씨 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0023', '치앙마이 일정 직항 날씨 여행 항공권 태국 패키지 해외', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0024', '치앙마이 날씨 태국 해외 직항 일정 여행 패키지 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0025', '치앙마이 패키지 항공권 리조트 해외 여행 직항 일정', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0026', '치앙마이 리조트 항공권 날씨 패키지 일정 여행 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0027', '치앙마이 항공권 리조트 여행 패키지 태국 날씨 해외', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0028', '치앙마이 여행 태국 직항 일정 항공권 리조트 날씨', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0029', '치앙마이 해외 직항 여행 일정 항공권 리조트 날씨', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MMK_0030', '치앙마이 태국 해외 날씨 리조트 패키지 여행 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0001', '치앙마이 가족 체험 일정 사파리 태국여행 마사지 날씨 코끼리 추천 여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0002', '치앙마이 트레킹 직항 마사지 일정 관광지 해외 추천 항공권 날씨 야시장', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0003', '치앙마이 일정 직항 쇼핑 사파리 마사지 가족 추천 트레킹 패키지 태국여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0004', '치앙마이 일정 항공권 마사지 체험 사파리 해외 트레킹 리조트 쇼핑 야시장', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0005', '치앙마이 사파리 체험 일정 관광지 가족 트레킹 날씨 추천 야시장 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0006', '치앙마이 쇼핑 마사지 사파리 일정 직항 여행 체험 해외 야시장 패키지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0007', '치앙마이 패키지 쇼핑 여행 날씨 추천 직항 사파리 관광지 체험 해외', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0008', '치앙마이 사파리 직항 관광지 해외 패키지 항공권 쇼핑 트레킹 가족 야시장', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0009', '치앙마이 야시장 패키지 항공권 추천 직항 체험 리조트 트레킹 쇼핑 사파리', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0010', '치앙마이 코끼리 사파리 추천 트레킹 리조트 체험 야시장 패키지 해외', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0011', '치앙마이 여행 쇼핑 리조트 마사지 직항 날씨 체험 코끼리 패키지 사파리', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0012', '치앙마이 해외 체험 트레킹 가족 패키지 날씨 직항 추천 마사지 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0013', '치앙마이 트레킹 쇼핑 사파리 관광지 여행 날씨 직항 야시장 가족 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0014', '치앙마이 사파리 일정 가족 리조트 트레킹 관광지 여행 추천 야시장 코끼리', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0015', '치앙마이 마사지 해외 항공권 패키지 야시장 일정 날씨 가족 사파리 트레킹', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0016', '치앙마이 야시장 쇼핑 사파리 리조트 트레킹 해외 가족 날씨 일정 체험', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0017', '치앙마이 추천 여행 해외 관광지 패키지 일정 가족 쇼핑 코끼리 태국여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0018', '치앙마이 추천 태국여행 일정 항공권 트레킹 직항 쇼핑 여행 마사지 패키지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0019', '치앙마이 태국여행 추천 야시장 관광지 직항 체험 사파리 마사지 여행 쇼핑', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0020', '치앙마이 야시장 가족 리조트 항공권 여행 해외 태국여행 추천 관광지 체험', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0021', '치앙마이 태국여행 관광지 쇼핑 리조트 코끼리 여행 해외 체험 직항 일정', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0022', '치앙마이 직항 쇼핑 가족 패키지 사파리 항공권 마사지 태국여행 해외', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0023', '치앙마이 일정 사파리 여행 코끼리 야시장 해외 관광지 리조트 체험 마사지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0024', '치앙마이 마사지 관광지 트레킹 날씨 항공권 사파리 여행 야시장 추천', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0025', '치앙마이 관광지 리조트 여행 코끼리 일정 항공권 날씨 태국여행 트레킹', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0026', '치앙마이 사파리 태국여행 여행 코끼리 날씨 항공권 관광지 리조트 쇼핑', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0027', '치앙마이 가족 추천 날씨 마사지 패키지 해외 트레킹 직항 항공권 체험', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0028', '치앙마이 항공권 리조트 체험 추천 트레킹 코끼리 해외 마사지 사파리', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0029', '치앙마이 추천 쇼핑 여행 날씨 일정 직항 마사지 관광지 항공권 트레킹', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_MKLP_0030', '치앙마이 가족 리조트 날씨 야시장 해외 태국여행 쇼핑 체험 추천 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0001', '해외여행 패키지 날씨 태국 관광지 치앙마이 일정 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0002', '해외여행 관광지 직항 일정 항공권 리조트 치앙마이 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0003', '해외여행 일정 태국 항공권 치앙마이 직항 리조트 패키지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0004', '해외여행 항공권 태국 날씨 리조트 패키지 일정 관광지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0005', '해외여행 직항 리조트 일정 치앙마이 항공권 패키지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0006', '해외여행 직항 날씨 치앙마이 관광지 일정 태국 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0007', '해외여행 패키지 태국 관광지 항공권 직항 치앙마이 일정', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0008', '해외여행 태국 치앙마이 항공권 리조트 날씨 일정 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0009', '해외여행 치앙마이 직항 일정 날씨 항공권 관광지 패키지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0010', '해외여행 리조트 패키지 치앙마이 일정 관광지 날씨', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0011', '해외여행 리조트 일정 치앙마이 태국 관광지 항공권 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0012', '해외여행 직항 항공권 관광지 태국 날씨 패키지 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0013', '해외여행 리조트 치앙마이 일정 태국 관광지 직항 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0014', '해외여행 치앙마이 태국 일정 날씨 리조트 항공권 관광지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0015', '해외여행 패키지 일정 직항 리조트 태국 치앙마이 날씨', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0016', '해외여행 태국 관광지 치앙마이 리조트 패키지 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0017', '해외여행 태국 항공권 날씨 리조트 관광지 치앙마이 일정', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0018', '해외여행 항공권 리조트 관광지 패키지 날씨 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0019', '해외여행 패키지 치앙마이 리조트 태국 날씨 직항 일정', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0020', '해외여행 패키지 관광지 일정 항공권 치앙마이 직항 날씨', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0021', '해외여행 리조트 항공권 직항 일정 패키지 날씨 치앙마이', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0022', '해외여행 직항 치앙마이 태국 리조트 일정 패키지 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0023', '해외여행 치앙마이 태국 직항 관광지 날씨 패키지 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0024', '해외여행 항공권 패키지 일정 관광지 태국 리조트 날씨', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0025', '해외여행 리조트 일정 관광지 직항 패키지 치앙마이 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0026', '해외여행 날씨 태국 패키지 직항 리조트 치앙마이 일정', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0027', '해외여행 관광지 일정 항공권 태국 직항 치앙마이 날씨', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0028', '해외여행 치앙마이 날씨 직항 패키지 관광지 리조트 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0029', '해외여행 리조트 태국 패키지 치앙마이 관광지 일정 날씨', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_TRIPMK_0030', '해외여행 패키지 항공권 날씨 태국 관광지 직항 치앙마이', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0001', '11월 치앙마이 리조트 항공권 날씨 해외여행 3박5일', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0002', '11월 패키지 관광지 날씨 직항 일정 3박5일 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0003', '11월 3박5일 항공권 일정 관광지 날씨 직항 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0004', '11월 해외여행 일정 3박5일 직항 항공권 리조트 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0005', '11월 리조트 직항 치앙마이 항공권 패키지 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0006', '11월 직항 항공권 날씨 3박5일 치앙마이 해외여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0007', '11월 해외여행 일정 3박5일 치앙마이 관광지 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0008', '11월 일정 치앙마이 관광지 항공권 직항 리조트 태국', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0009', '11월 직항 일정 리조트 3박5일 항공권 날씨 해외여행', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0010', '11월 날씨 리조트 패키지 직항 관광지 항공권 3박5일', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0011', '11월 해외여행 패키지 항공권 리조트 3박5일 일정', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0012', '11월 날씨 직항 태국 해외여행 관광지 치앙마이 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0013', '11월 항공권 직항 날씨 태국 3박5일 관광지 리조트', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0014', '11월 날씨 일정 치앙마이 해외여행 패키지 3박5일', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0015', '11월 치앙마이 패키지 해외여행 직항 태국 일정 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0016', '11월 패키지 관광지 항공권 일정 해외여행 직항', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0017', '11월 해외여행 리조트 치앙마이 3박5일 태국 관광지', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0018', '11월 직항 3박5일 패키지 일정 관광지 리조트 항공권', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0019', '11월 직항 패키지 태국 항공권 해외여행 날씨 일정', 'ChiangMai');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_CHIAM_NMTFPC_0020', '11월 패키지 태국 해외여행 3박5일 일정 치앙마이', 'ChiangMai');
