-- City Titles Part 116 (11501-11550번째 레코드)
-- 총 50개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0011', '월트디즈니 월테디즈니 베니스비치 베네스비치 산타모네카피어 로스앤졀레스 여행 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0012', '그리피스천문대 헐리우드사인 로스앤졀레스 패키지 인쳔출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0013', '산타모네카피어 베네스비치 로스앤졀레스 여행 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0014', '베벌리헬스 로데오드라이브 로스앤졀레스 패키지 인쳔출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0015', '헐리우드명예의거리 돌비극장 로스앤졀레스 여행 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0016', '게티센터 로데오드라이브 로스앤졀레스 패키지 인쳔출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0017', '산테모니카피어 베네스비치 헐리우드사인 로스앤졀레스 여행 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0018', '그리퍼스천문대 게티센터 로스앤졀레스 패키지 인쳔출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0019', '베벌리헬스 로데오드라이브 게티센터 로스앤졀레스 여행 인쳔출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_OT_0020', '헐리우드사인 그리피스천문대 로스앤졀레스 패키지 인쳔출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0001', '도쿄 해외 일정 패키지 여행 일본 날씨 리조트 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0002', '도쿄 리조트 일본 직항 날씨 해외 항공권 에어텔 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0003', '도쿄 일본 패키지 해외 여행 리조트 에어텔 직항 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0004', '도쿄 여행 에어텔 리조트 해외 항공권 일정 패키지 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0005', '도쿄 일본 리조트 해외 일정 에어텔 직항 항공권 날씨', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0006', '도쿄 직항 에어텔 해외 여행 항공권 리조트 일본 패키지', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0007', '도쿄 직항 일본 해외 여행 패키지 일정 날씨 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0008', '도쿄 에어텔 여행 직항 패키지 리조트 항공권 날씨 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0009', '도쿄 패키지 날씨 일정 에어텔 리조트 해외 여행 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0010', '도쿄 해외 항공권 리조트 직항 일정 날씨 여행 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0011', '도쿄 에어텔 리조트 일본 여행 날씨 일정 직항 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0012', '도쿄 직항 패키지 항공권 해외 에어텔 여행 일본 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0013', '도쿄 항공권 패키지 에어텔 일본 해외 리조트 여행 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0014', '도쿄 일본 일정 날씨 패키지 에어텔 해외 리조트 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0015', '도쿄 에어텔 날씨 항공권 일본 패키지 리조트 일정 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0016', '도쿄 날씨 해외 일정 리조트 직항 패키지 여행 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0017', '도쿄 직항 해외 에어텔 여행 날씨 패키지 항공권 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0018', '도쿄 항공권 리조트 직항 패키지 여행 날씨 일본 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0019', '도쿄 일본 날씨 패키지 일정 직항 항공권 해외 에어텔', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MMK_0020', '도쿄 여행 해외 날씨 패키지 일본 에어텔 항공권 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0001', '도쿄 에어텔 리조트 감성숙소 일본 패키지 해외 일정', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0002', '도쿄 에어텔 온천 준비물 료칸 일정 감성숙소 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0003', '도쿄 패키지 리조트 날씨 항공권 일본 에어텔 료칸 자유', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0004', '도쿄 감성숙소 온천 료칸 여행 일본 일정 날씨 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0005', '도쿄 감성숙소 가족 일본 에어텔 리조트 료칸 여행 날씨', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0006', '도쿄 패키지 온천 직항 준비물 일본 해외 감성숙소 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0007', '도쿄 일정 에어텔 일본 해외 항공권 패키지 준비물 직항', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0008', '도쿄 항공권 일정 자유 날씨 온천 준비물 에어텔 리조트', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0009', '도쿄 리조트 감성숙소 직항 항공권 여행 에어텔 패키지', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0010', '도쿄 해외 가족 리조트 온천 항공권 날씨 패키지 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0011', '도쿄 리조트 직항 날씨 일정 해외 감성숙소 온천 가족', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0012', '도쿄 감성숙소 료칸 준비물 여행 리조트 해외 일본', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0013', '도쿄 항공권 자유 패키지 일본 해외 날씨 에어텔 가족', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0014', '도쿄 료칸 직항 온천 준비물 일정 여행 자유 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0015', '도쿄 자유 온천 리조트 감성숙소 여행 료칸 항공권 해외', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0016', '도쿄 일정 일본 가족 리조트 자유 항공권 패키지 여행', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0017', '도쿄 여행 자유 직항 일본 일정 에어텔 온천 료칸', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0018', '도쿄 날씨 자유 일정 리조트 직항 해외 가족 온천', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0019', '도쿄 리조트 해외 날씨 자유 직항 패키지 온천 항공권', 'Tokyo');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_TOKY_MKLKSH_0020', '도쿄 해외 날씨 감성숙소 패키지 항공권 직항 일본 일정', 'Tokyo');
