-- City Titles Part 035 (3401-3500번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MMK_0012', '푸꾸옥 항공권 베트남 리조트 여행 해외 날씨 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MMK_0013', '푸꾸옥 여행 일정 해외 패키지 리조트 직항 동남아 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MMK_0014', '푸꾸옥 일정 여행 항공권 패키지 해외 직항 동남아', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MMK_0015', '푸꾸옥 날씨 베트남 패키지 일정 해외 여행 리조트 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MMK_0016', '푸꾸옥 패키지 동남아 일정 직항 항공권 리조트 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MMK_0017', '푸꾸옥 해외 여행 날씨 일정 리조트 직항 동남아 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MMK_0018', '푸꾸옥 동남아 일정 베트남 해외 여행 패키지 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MMK_0019', '푸꾸옥 베트남 항공권 리조트 패키지 날씨 여행 일정', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MMK_0020', '푸꾸옥 날씨 항공권 패키지 일정 베트남 동남아 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0001', '푸꾸옥 패키지 여행 해외 야경 날씨 호핑투어 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0002', '푸꾸옥 항공권 야시장 직항 야경 동남아 베트남 케이블카', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0003', '푸꾸옥 항공권 관광지 해외 리조트 자유 휴양 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0004', '푸꾸옥 직항 자유 동남아 휴양 해외 여행 날씨 야시장', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0005', '푸꾸옥 날씨 호핑투어 야경 여행 항공권 베트남 야시장', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0006', '푸꾸옥 관광지 동남아 야경 케이블카 자유 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0007', '푸꾸옥 호핑투어 야경 야시장 자유 해외 휴양 날씨 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0008', '푸꾸옥 휴양 야시장 항공권 자유 리조트 일정 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0009', '푸꾸옥 패키지 휴양 여행 에어텔 야시장 리조트 호핑투어', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0010', '푸꾸옥 해외 에어텔 케이블카 호핑투어 항공권 야경 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0011', '푸꾸옥 야경 직항 자유 케이블카 일정 항공권 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0012', '푸꾸옥 리조트 휴양 직항 동남아 해외 여행 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0013', '푸꾸옥 베트남 케이블카 야시장 야경 항공권 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0014', '푸꾸옥 동남아 관광지 케이블카 자유 날씨 호핑투어', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0015', '푸꾸옥 리조트 자유 호핑투어 일정 여행 케이블카 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0016', '푸꾸옥 케이블카 휴양 일정 에어텔 야경 야시장 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0017', '푸꾸옥 직항 날씨 케이블카 에어텔 야경 휴양 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0018', '푸꾸옥 리조트 일정 자유 야시장 항공권 해외 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0019', '푸꾸옥 리조트 야경 야시장 날씨 여행 항공권 동남아', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKSH_0020', '푸꾸옥 동남아 여행 직항 야시장 리조트 자유 관광지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0001', '푸꾸옥 야경 여행 휴양 동남아 에어텔 패키지 리조트 항공권 야시장', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0002', '푸꾸옥 케이블카 여행 자유 일정 야시장 휴양 날씨 야경 항공권 관광지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0003', '푸꾸옥 케이블카 여행 휴양 야경 동남아 호핑투어 에어텔 베트남 일정 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0004', '푸꾸옥 여행 베트남 패키지 항공권 날씨 자유 야경 호핑투어 동남아 관광지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0005', '푸꾸옥 동남아 야시장 패키지 자유 케이블카 해외 베트남 일정 리조트 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0006', '푸꾸옥 동남아 일정 관광지 직항 야시장 케이블카 리조트 여행 에어텔', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0007', '푸꾸옥 에어텔 호핑투어 패키지 날씨 휴양 해외 야경 항공권 케이블카', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0008', '푸꾸옥 에어텔 항공권 휴양 여행 자유 일정 해외 패키지 케이블카 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0009', '푸꾸옥 리조트 여행 베트남 휴양 항공권 케이블카 관광지 야경 야시장 자유', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0010', '푸꾸옥 항공권 베트남 패키지 동남아 야시장 일정 관광지 리조트 야경 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0011', '푸꾸옥 야시장 항공권 해외 관광지 휴양 케이블카 패키지 호핑투어 에어텔', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0012', '푸꾸옥 케이블카 베트남 직항 항공권 리조트 야시장 에어텔 날씨 일정 휴양', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0013', '푸꾸옥 휴양 패키지 날씨 직항 관광지 해외 일정 야시장 항공권 에어텔', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0014', '푸꾸옥 자유 해외 휴양 야경 패키지 관광지 리조트 에어텔 동남아 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0015', '푸꾸옥 야시장 패키지 여행 야경 베트남 해외 자유 직항 동남아 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0016', '푸꾸옥 야시장 케이블카 패키지 리조트 호핑투어 베트남 직항 에어텔 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0017', '푸꾸옥 에어텔 야경 케이블카 호핑투어 항공권 날씨 관광지 휴양 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0018', '푸꾸옥 휴양 관광지 에어텔 베트남 패키지 항공권 리조트 직항 일정 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0019', '푸꾸옥 날씨 여행 일정 직항 리조트 베트남 야시장 케이블카 호핑투어 휴양', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKLKLO_0020', '푸꾸옥 항공권 야시장 휴양 케이블카 패키지 야경 여행 호핑투어 자유', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0001', '푸꾸옥 동남아 항공권 국립공원 여행 리조트 패키지 일정', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0002', '푸꾸옥 해외 베트남 국립공원 여행 항공권 빈원더스', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0003', '푸꾸옥 여행 베트남 패키지 해외 일정 빈원더스 국립공원', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0004', '푸꾸옥 베트남 직항 항공권 국립공원 일정 빈원더스 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0005', '푸꾸옥 국립공원 해외 사오비치 일정 여행 빈원더스', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0006', '푸꾸옥 날씨 패키지 빈원더스 여행 직항 베트남 동남아', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0007', '푸꾸옥 여행 사오비치 동남아 국립공원 일정 베트남 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0008', '푸꾸옥 동남아 항공권 날씨 빈원더스 베트남 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0009', '푸꾸옥 베트남 항공권 날씨 패키지 동남아 여행 국립공원', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0010', '푸꾸옥 여행 빈원더스 리조트 동남아 해외 직항 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0011', '푸꾸옥 리조트 국립공원 베트남 패키지 직항 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0012', '푸꾸옥 베트남 동남아 리조트 패키지 빈원더스 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0013', '푸꾸옥 직항 해외 패키지 국립공원 리조트 날씨 사오비치', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0014', '푸꾸옥 베트남 일정 해외 패키지 사오비치 직항 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0015', '푸꾸옥 리조트 사오비치 빈원더스 베트남 항공권 국립공원', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0016', '푸꾸옥 항공권 베트남 패키지 동남아 리조트 국립공원', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0017', '푸꾸옥 항공권 빈원더스 사오비치 국립공원 여행 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0018', '푸꾸옥 패키지 빈원더스 해외 날씨 사오비치 일정 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0019', '푸꾸옥 패키지 사오비치 여행 직항 베트남 국립공원', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_MKR_0020', '푸꾸옥 날씨 해외 여행 국립공원 사오비치 빈원더스', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0001', '11월 항공권 패키지 일정 해외 리조트 여행 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0002', '11월 패키지 여행 푸꾸옥 동남아 리조트 항공권 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0003', '11월 동남아 날씨 항공권 패키지 베트남 푸꾸옥 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0004', '11월 푸꾸옥 날씨 리조트 여행 동남아 베트남 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0005', '11월 날씨 베트남 해외 동남아 패키지 리조트 일정', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0006', '11월 항공권 날씨 패키지 여행 직항 푸꾸옥 일정', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0007', '11월 3박5일 일정 패키지 직항 여행 리조트 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0008', '11월 베트남 3박5일 여행 날씨 항공권 해외 일정', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0009', '11월 푸꾸옥 베트남 리조트 해외 일정 3박5일 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0010', '11월 패키지 리조트 3박5일 해외 동남아 여행 일정', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0011', '11월 동남아 항공권 여행 푸꾸옥 해외 직항 일정', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0012', '11월 동남아 직항 리조트 푸꾸옥 여행 일정 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0013', '11월 여행 푸꾸옥 패키지 3박5일 항공권 직항 동남아', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0014', '11월 베트남 3박5일 일정 직항 리조트 날씨 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0015', '11월 여행 베트남 일정 해외 직항 패키지 날씨 동남아', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0016', '11월 동남아 패키지 날씨 푸꾸옥 일정 3박5일 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0017', '11월 해외 베트남 리조트 날씨 푸꾸옥 3박5일 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0018', '11월 푸꾸옥 일정 날씨 동남아 항공권 패키지 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0019', '11월 리조트 날씨 3박5일 일정 푸꾸옥 동남아 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_NMKTF_0020', '11월 리조트 푸꾸옥 해외 베트남 패키지 직항 일정', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0001', '12월 직항 일정 3박5일 여행 패키지 리조트 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0002', '12월 날씨 푸꾸옥 항공권 패키지 여행 베트남 3박5일', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0003', '12월 날씨 일정 해외 푸꾸옥 동남아 리조트 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0004', '12월 동남아 리조트 여행 패키지 해외 3박5일 푸꾸옥', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0005', '12월 베트남 3박5일 항공권 일정 동남아 직항 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0006', '12월 푸꾸옥 여행 날씨 항공권 직항 동남아 3박5일', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0007', '12월 여행 날씨 동남아 베트남 3박5일 일정 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0008', '12월 직항 일정 날씨 푸꾸옥 여행 리조트 동남아', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0009', '12월 항공권 3박5일 일정 리조트 날씨 패키지 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0010', '12월 3박5일 항공권 패키지 해외 여행 직항 베트남', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_PHUQU_DMKTF_0011', '12월 항공권 여행 리조트 날씨 일정 패키지 푸꾸옥', 'PhuQuoc');
