-- City Titles Part 038 (3701-3800번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKLKLO_0012', '코타키나발루 동남아 야시장 에어텔 일정 선셋 직항 여행 휴양 날씨 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKLKLO_0013', '코타키나발루 호핑투어 직항 야시장 선셋 날씨 야시장 패키지 여행 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKLKLO_0014', '코타키나발루 해외 휴양 야경 선셋 야시장 날씨 패키지 일정 야시장 관광지', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKLKLO_0015', '코타키나발루 리조트 휴양 말레이시아 해외 패키지 야시장 날씨 일정 야경', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKLKLO_0016', '코타키나발루 야경 야시장 일정 에어텔 관광지 항공권 날씨 직항 휴양', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKLKLO_0017', '코타키나발루 항공권 관광지 야경 휴양 야시장 에어텔 직항 선셋 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKLKLO_0018', '코타키나발루 말레이시아 일정 휴양 동남아 호핑투어 해외 에어텔 날씨', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKLKLO_0019', '코타키나발루 직항 야경 해외 리조트 에어텔 말레이시아 야시장 일정', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKLKLO_0020', '코타키나발루 날씨 리조트 동남아 항공권 휴양 여행 선셋 패키지 호핑투어', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0001', '코타키나발루 일정 말레이시아 패키지 직항 여행', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0002', '코타키나발루 패키지 직항 여행 날씨 시그널힐전망대', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0003', '코타키나발루 앗킨슨시계탑 동남아 날씨 리조트 말레이시아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0004', '코타키나발루 해외 앗킨슨시계탑 리조트 직항 말레이시아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0005', '코타키나발루 일정 해외 여행 날씨 항공권 패키지 동남아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0006', '코타키나발루 말레이시아 리조트 동남아 날씨 일정 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0007', '코타키나발루 직항 시티모스크 해외 리조트 여행', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0008', '코타키나발루 패키지 앗킨슨시계탑 해외 일정 시티모스크', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0009', '코타키나발루 일정 말레이시아 날씨 직항 시티모스크', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0010', '코타키나발루 해외 항공권 직항 시티모스크 말레이시아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0011', '코타키나발루 말레이시아 여행 시그널힐전망대 날씨 항공권', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0012', '코타키나발루 말레이시아 항공권 패키지 시그널힐전망대', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0013', '코타키나발루 시그널힐전망대 앗킨슨시계탑 동남아 여행', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0014', '코타키나발루 여행 패키지 날씨 동남아 항공권 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0015', '코타키나발루 패키지 앗킨슨시계탑 날씨 여행 시티모스크', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0016', '코타키나발루 직항 리조트 일정 말레이시아 시티모스크', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0017', '코타키나발루 패키지 동남아 리조트 항공권 말레이시아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0018', '코타키나발루 리조트 동남아 직항 앗킨슨시계탑 패키지', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0019', '코타키나발루 말레이시아 여행 시그널힐전망대 해외 리조트', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKR_0020', '코타키나발루 말레이시아 여행 동남아 패키지 항공권', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0001', '코타키나발루 동남아 직항 말레이시아 여행', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0002', '코타키나발루 여행 직항 동남아 일정 사피섬', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0003', '코타키나발루 말레이시아 직항 패키지 날씨 동남아 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0004', '코타키나발루 말레이시아 사피섬 날씨 패키지 일정 여행', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0005', '코타키나발루 말레이시아 날씨 여행 일정 직항', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0006', '코타키나발루 직항 사피섬 날씨 패키지 해외 여행', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0007', '코타키나발루 사피섬 툰쿠압둘라만해양공원 항공권', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0008', '코타키나발루 사피섬 여행 리조트 일정 말레이시아 직항', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0009', '코타키나발루 날씨 리조트 항공권 툰쿠압둘라만해양공원', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0010', '코타키나발루 동남아 일정 여행 항공권 직항 리조트', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0011', '코타키나발루 직항 일정 여행 해외 툰쿠압둘라만해양공원', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0012', '코타키나발루 일정 패키지 여행 툰쿠압둘라만해양공원 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0013', '코타키나발루 사피섬 리조트 말레이시아 항공권 여행', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0014', '코타키나발루 항공권 해외 패키지 직항 날씨', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0015', '코타키나발루 동남아 직항 일정 패키지 날씨 항공권', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0016', '코타키나발루 항공권 동남아 직항 사피섬 해외 날씨', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0017', '코타키나발루 여행 해외 말레이시아 사피섬 패키지 직항', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0018', '코타키나발루 동남아 말레이시아 직항 날씨 여행 일정', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0019', '코타키나발루 말레이시아 패키지 직항 사피섬 일정 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_MKRP_0020', '코타키나발루 직항 일정 사피섬 날씨 패키지 동남아 여행', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0001', '11월 항공권 패키지 해외 여행 직항 동남아 날씨', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0002', '11월 패키지 날씨 직항 말레이시아 해외 3박5일 일정', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0003', '11월 직항 패키지 동남아 말레이시아 여행 일정', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0004', '11월 직항 리조트 동남아 코타키나발루 여행 패키지', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0005', '11월 말레이시아 동남아 여행 패키지 해외 직항 리조트', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0006', '11월 3박5일 코타키나발루 말레이시아 일정 리조트', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0007', '11월 날씨 동남아 직항 여행 3박5일 항공권 리조트', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0008', '11월 여행 항공권 말레이시아 코타키나발루 날씨 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0009', '11월 일정 여행 해외 3박5일 날씨 리조트 패키지', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0010', '11월 코타키나발루 일정 3박5일 말레이시아 동남아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0011', '11월 해외 말레이시아 패키지 여행 동남아 직항 리조트', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0012', '11월 직항 항공권 리조트 3박5일 여행 말레이시아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0013', '11월 직항 3박5일 말레이시아 항공권 리조트 패키지', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0014', '11월 패키지 동남아 항공권 리조트 여행 해외 직항', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0015', '11월 날씨 3박5일 리조트 여행 일정 직항', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0016', '11월 여행 항공권 직항 말레이시아 날씨 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0017', '11월 3박5일 해외 일정 항공권 동남아 날씨', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0018', '11월 직항 항공권 여행 리조트 코타키나발루 날씨', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0019', '11월 일정 3박5일 동남아 항공권 코타키나발루', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_NMKTF_0020', '11월 항공권 리조트 직항 날씨 코타키나발루 말레이시아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0001', '12월 3박5일 직항 리조트 코타키나발루 말레이시아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0002', '12월 패키지 말레이시아 항공권 직항 동남아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0003', '12월 해외 패키지 일정 날씨 동남아 여행 코타키나발루', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0004', '12월 3박5일 여행 해외 직항 리조트 말레이시아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0005', '12월 동남아 해외 여행 리조트 직항 일정 코타키나발루', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0006', '12월 항공권 리조트 3박5일 패키지 직항 코타키나발루', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0007', '12월 날씨 일정 항공권 3박5일 동남아 해외 리조트', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0008', '12월 3박5일 항공권 말레이시아 패키지 리조트 일정', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0009', '12월 코타키나발루 여행 패키지 직항 날씨 동남아 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0010', '12월 여행 동남아 코타키나발루 일정 날씨 패키지', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0011', '12월 항공권 패키지 해외 직항 3박5일 일정 여행', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0012', '12월 해외 말레이시아 날씨 패키지 동남아 일정 항공권', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0013', '12월 일정 3박5일 여행 리조트 패키지 항공권', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0014', '12월 해외 리조트 항공권 코타키나발루 일정 패키지', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0015', '12월 여행 리조트 패키지 3박5일 항공권 날씨 해외', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0016', '12월 항공권 말레이시아 일정 직항 리조트 3박5일', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0017', '12월 3박5일 항공권 여행 리조트 동남아 일정 직항', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0018', '12월 여행 직항 날씨 동남아 일정 패키지 3박5일', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0019', '12월 코타키나발루 해외 일정 날씨 항공권 패키지', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_KOTAKI_DMKTF_0020', '12월 항공권 패키지 리조트 일정 해외 날씨 말레이시아', 'KotaKinabalu');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0001', '발리 직항 날씨 동남아 항공권 해외 리조트 일정', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0002', '발리 직항 일정 리조트 여행 날씨 해외 동남아 항공권', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0003', '발리 해외 직항 패키지 동남아 일정 항공권 인도네시아', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0004', '발리 날씨 해외 여행 인도네시아 항공권 일정 직항', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0005', '발리 패키지 날씨 일정 인도네시아 해외 직항 동남아', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0006', '발리 동남아 패키지 직항 일정 인도네시아 리조트 해외', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0007', '발리 동남아 해외 직항 리조트 패키지 인도네시아 일정', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0008', '발리 날씨 동남아 인도네시아 리조트 일정 여행 직항', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0009', '발리 해외 패키지 동남아 리조트 여행 일정 인도네시아', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0010', '발리 해외 여행 항공권 인도네시아 직항 일정 동남아', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_MMK_0011', '발리 여행 날씨 직항 인도네시아 항공권 리조트 동남아', 'Bali');
