-- City Titles Part 009 (801-900번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0020', '하와이 와이키키 패키지 다이아몬드헤드 마노아폭포 효도여행 인천출발', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0001', 'LA 로스앤젤레스 미국 패키지 여행 직항 미서부 할리우드 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0002', '로스앤젤레스 패키지 LA 미국 미주여행 직항 크루즈 할리우드 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0003', '미국 LA 로스앤젤레스 여행 패키지 직항 미서부 크루즈 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0004', '로스앤젤레스 LA 미주여행 패키지 미국 여행 직항 할리우드 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0005', 'LA 패키지 미국 로스앤젤레스 여행 직항 미서부 할리우드 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0006', '미주여행 로스앤젤레스 LA 미국 패키지 여행 직항 크루즈 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0007', '미서부 LA 로스앤젤레스 패키지 미국 여행 직항 할리우드 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0008', '로스앤젤레스 미국 미주여행 패키지 LA 여행 직항 크루즈 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0009', 'LA 미서부 패키지 미국 로스앤젤레스 여행 직항 할리우드 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0010', '미국 미주여행 로스앤젤레스 패키지 LA 여행 직항 크루즈 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0011', '로스앤젤레스 여행 LA 미국 패키지 직항 미서부 할리우드 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0012', '미국 패키지 미주여행 LA 로스앤젤레스 여행 직항 크루즈 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0013', 'LA 미국 미서부 패키지 로스앤젤레스 여행 직항 할리우드 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0014', '미주여행 미국 로스앤젤레스 LA 패키지 여행 직항 미서부 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0015', '로스앤젤레스 미서부 패키지 LA 미국 여행 직항 크루즈 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0016', 'LA 미국 여행 패키지 로스앤젤레스 직항 미서부 할리우드 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0017', '미국 로스앤젤레스 미주여행 패키지 LA 여행 직항 할리우드 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0018', '로스앤젤레스 패키지 미서부 LA 미국 여행 직항 크루즈 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0019', '미서부 미국 LA 로스앤젤레스 패키지 여행 직항 할리우드 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_CMK_0020', '미주여행 패키지 LA 로스앤젤레스 미국 여행 직항 크루즈 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0001', '할리우드사인 그리피스천문대 할리우드명예의거리 돌비극장 로스앤젤레스 여행 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0002', '산타모니카피어 베니스비치 로데오드라이브 게티센터 베벌리힐스 로스앤젤레스 패키지 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0003', '월트디즈니 게티센터 베벌리힐스 할리우드사인 로스앤젤레스 여행 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0004', '그리피스천문대 할리우드명예의거리 돌비극장 로스앤젤레스 패키지 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0005', '산타모니카피어 베니스비치 로스앤젤레스 여행 할리우드사인 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0006', '로데오드라이브 베벌리힐스 게티센터 로스앤젤레스 패키지 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0007', '할리우드사인 돌비극장 월트디즈니 로스앤젤레스 여행 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0008', '베니스비치 산타모니카피어 로스앤젤레스 패키지 게티센터 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0009', '할리우드명예의거리 로스앤젤레스 여행 그리피스천문대 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0010', '게티센터 로데오드라이브 베벌리힐스 로스앤젤레스 패키지 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0011', '그리피스천문대 산타모니카피어 로스앤젤레스 여행 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0012', '베벌리힐스 로데오드라이브 로스앤젤레스 패키지 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0013', '월트디즈니 할리우드사인 로스앤젤레스 여행 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0014', '돌비극장 할리우드명예의거리 로스앤젤레스 패키지 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0015', '베니스비치 산타모니카피어 베벌리힐스 로스앤젤레스 여행 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0016', '게티센터 할리우드사인 로스앤젤레스 패키지 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0017', '로데오드라이브 베벌리힐스 할리우드명예의거리 로스앤젤레스 여행 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0018', '그리피스천문대 게티센터 로스앤젤레스 패키지 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0019', '산타모니카피어 베니스비치 할리우드사인 로스앤젤레스 여행 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_MKL_0020', '베벌리힐스 로데오드라이브 게티센터 로스앤젤레스 패키지 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0001', '로스앤젤레스 여행 8박10일 2026년 가을 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0002', '로스앤젤레스 패키지 6월 7월 8월 여행 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0003', '9월 10월 하반기 로스앤젤레스 여행 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0004', '6박8일 10박12일 7일 로스앤젤레스 여행 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0005', '로스앤젤레스 패키지 8박10일 하반기 여행 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0006', '2026년 로스앤젤레스 여행 6월 7월 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0007', '8월 9월 가을 로스앤젤레스 패키지 여행 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0008', '7월 10월 로스앤젤레스 여행 6박8일 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0009', '로스앤젤레스 8박10일 여행 2026년 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0010', '로스앤젤레스 패키지 가을 10박12일 여행 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0011', '6월 8월 하반기 로스앤젤레스 여행 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0012', '7일 6박8일 로스앤젤레스 패키지 여행 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0013', '9월 2026년 로스앤젤레스 여행 8박10일 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0014', '10박12일 7월 로스앤젤레스 패키지 여행 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0015', '8월 6박8일 로스앤젤레스 여행 가을 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0016', '10월 하반기 로스앤젤레스 패키지 여행 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0017', '2026년 가을 로스앤젤레스 여행 7일 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0018', '6월 9월 로스앤젤레스 패키지 여행 8박10일 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0019', '7월 8월 로스앤젤레스 여행 10박12일 직항 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_DMK_0020', '하반기 2026년 로스앤젤레스 패키지 여행 6박8일 직항 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0001', '로스앤젤레스여행 LA 할리우드사인 그리피스천문대 산타모니카피어 베니스비치 로데오드라이브 게티센터 베벌리힐다저스 월트디즈니 요세미티 캘리포니아코스탈트레일 하이킹 한국인가이드 전일정가이드 맞춤여행 버킷리스트 인생여행 가을단풍 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0002', '미주여행 로스앤젤레스 LA 산타모니카피어 베니스비치 게티센터 베벌리힐스 할리우드사인 돌비극장 할리우드명예의거리 월트디즈니 캘리포니아코스탈트레일 요세미티 하이킹 한국인가이드 전일정가이드 맞춤여행 꿈의여행 버킷리스트 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0003', '가족여행 로스앤젤레스 LA 산타모니카피어 베니스비치 월트디즈니 게티센터 베벌리힐스 할리우드사인 한국인가이드 전일정가이드 맞춤여행 꿈의여행 인생여행 하이킹 가을단풍 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0004', '효도여행 로스앤젤레스 LA 게티센터 베벌리힐스 할리우드명예의거리 돌비극장 산타모니카피어 베니스비치 한국인가이드 전일정가이드 맞춤여행 꿈의여행 인생여행 하이킹 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0005', '우정여행 로스앤젤레스 LA 그리피스천문대 할리우드사인 산타모니카피어 베니스비치 로데오드라이브 게티센터 한국인가이드 전일정가이드 맞춤여행 꿈의여행 버킷리스트 하이킹 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0006', '졸업여행 로스앤젤레스 LA 할리우드명예의거리 돌비극장 베벌리힐스 로데오드라이브 게티센터 월트디즈니 한국인가이드 전일정가이드 맞춤여행 꿈의여행 인생여행 하이킹 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0007', '맞춤여행 로스앤젤레스 LA 산타모니카피어 베니스비치 로데오드라이브 게티센터 베벌리힐다저스 월트디즈니 한국인가이드 전일정가이드 하이킹 버킷리스트 인생여행 가을단풍 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0008', '꿈의여행 로스앤젤레스 LA 할리우드사인 그리피스천문대 할리우드명예의거리 돌비극장 산타모니카피어 베니스비치 게티센터 베벌리힐스 한국인가이드 전일정가이드 맞춤여행 하이킹 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0009', '인생여행 로스앤젤레스 LA 베니스비치 산타모니카피어 게티센터 베벌리힐스 로데오드라이브 할리우드사인 한국인가이드 전일정가이드 맞춤여행 꿈의여행 하이킹 가을단풍 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0010', '여행 로스앤젤레스 LA 할리우드명예의거리 돌비극장 게티센터 베벌리힐스 로데오드라이브 한국인가이드 전일정가이드 맞춤여행 꿈의여행 인생여행 하이킹 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0011', '로스앤젤레스여행 LA 월트디즈니 산타모니카피어 베니스비치 게티센터 로데오드라이브 베벌리힐스 할리우드사인 캘리포니아코스탈트레일 요세미티 하이킹 한국인가이드 전일정가이드 맞춤여행 가을단풍 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0012', '미주여행 로스앤젤레스 LA 게티센터 베벌리힐스 로데오드라이브 베니스비치 산타모니카피어 할리우드사인 그리피스천문대 한국인가이드 전일정가이드 맞춤여행 꿈의여행 하이킹 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0013', '가족여행 로스앤젤레스 LA 월트디즈니 베니스비치 산타모니카피어 게티센터 베벌리힐다저스 한국인가이드 전일정가이드 맞춤여행 꿈의여행 인생여행 하이킹 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0014', '효도여행 로스앤젤레스 LA 베벌리힐스 로데오드라이브 게티센터 할리우드명예의거리 돌비극장 한국인가이드 전일정가이드 맞춤여행 꿈의여행 하이킹 인생여행 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0015', '우정여행 로스앤젤레스 LA 베니스비치 산타모니카피어 할리우드사인 그리피스천문대 한국인가이드 전일정가이드 맞춤여행 꿈의여행 인생여행 하이킹 가을단풍 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0016', '졸업여행 로스앤젤레스 LA 할리우드사인 할리우드명예의거리 돌비극장 베벌리힐스 로데오드라이브 한국인가이드 전일정가이드 맞춤여행 꿈의여행 하이킹 인생여행 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0017', '맞춤여행 로스앤젤레스 LA 캘리포니아코스탈트레일 요세미티 산타모니카피어 베니스비치 한국인가이드 전일정가이드 하이킹 꿈의여행 인생여행 버킷리스트 가을단풍 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0018', '꿈의여행 로스앤젤레스 LA 그리피스천문대 할리우드사인 산타모니카피어 베니스비치 게티센터 베벌리힐스 한국인가이드 전일정가이드 맞춤여행 하이킹 버킷리스트 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0019', '인생여행 로스앤젤레스 LA 로데오드라이브 베벌리힐스 게티센터 베니스비치 산타모니카피어 월트디즈니 한국인가이드 전일정가이드 맞춤여행 꿈의여행 하이킹 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_ML_0020', '여행 로스앤젤레스 LA 다저스 LAFC직관 일일관광 골프여행 산타모니카피어 베니스비치 게티센터 베벌리힐스 로데오드라이브 한국인가이드 전일정가이드 맞춤여행 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0001', '9월 미국 로스앤젤레스 자유여행 미주여행 일정 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0002', '미국 로스앤젤레스 해외여행 크루즈패키지여행 미서부정복 일정 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0003', '로스앤젤레스 가족여행 미주여행 일정 미국 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0004', 'LA 로스앤젤레스 자유여행 미주여행 상품 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0005', '미서부정복 로스앤젤레스 일정 미주여행 가족 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0006', '크루즈패키지여행 로스앤젤레스 미주여행 일정 미국 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0007', '로스앤젤레스 해외여행 자유여행 일정 미서부정복 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0008', '미국 로스앤젤레스 상품 미주여행 크루즈패키지여행 일정 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0009', 'LAFC직관 로스앤젤레스 일일관광 미주여행 일정 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0010', '골프여행 로스앤젤레스 미주여행 일정 미국 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0011', '10월 로스앤젤레스 미주여행 자유여행 일정 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0012', '하반기 로스앤젤레스 미주여행 상품 일정 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0013', '7월 로스앤젤레스 자유여행 미주여행 일정 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0014', '8월 로스앤젤레스 가족여행 미주여행 일정 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0015', '가을 로스앤젤레스 미주여행 자유여행 일정 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0016', '홈쇼핑 로스앤젤레스 미주여행 상품 일정 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0017', '미서부 로스앤젤레스 자유여행 미주여행 일정 인천출발 대한항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0018', 'LA 로스앤젤레스 미서부정복 미주여행 일정 인천출발 아시아나항공', 'LosAngeles');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LA_SNK_0019', '크루즈패키지여행 로스앤젤레스 가족여행 일정 인천출발 대한항공', 'LosAngeles');
