-- City Titles Part 040 (3901-4000번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_DMKTF_0012', '12월 일정 발리 여행 패키지 3박5일 항공권', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_DMKTF_0013', '12월 여행 항공권 패키지 동남아 3박5일 리조트 발리', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_DMKTF_0014', '12월 인도네시아 동남아 일정 패키지 직항 3박5일', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_DMKTF_0015', '12월 3박5일 해외 리조트 여행 항공권 발리 일정', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_DMKTF_0016', '12월 일정 직항 발리 해외 날씨 동남아 항공권 여행', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_DMKTF_0017', '12월 항공권 3박5일 직항 발리 일정 여행 리조트', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_DMKTF_0018', '12월 직항 3박5일 항공권 여행 리조트 패키지 날씨', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_DMKTF_0019', '12월 여행 동남아 일정 해외 항공권 리조트 패키지', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BALI_DMKTF_0020', '12월 인도네시아 여행 날씨 리조트 동남아 일정 항공권', 'Bali');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0001', '방비엥 해외 항공권 동남아 라오스 리조트 여행 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0002', '방비엥 항공권 해외 여행 리조트 라오스 직항 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0003', '방비엥 리조트 항공권 라오스 해외 동남아 일정 날씨', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0004', '방비엥 패키지 리조트 항공권 일정 날씨 동남아 여행', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0005', '방비엥 일정 항공권 해외 패키지 동남아 날씨 리조트', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0006', '방비엥 동남아 직항 해외 날씨 항공권 리조트 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0007', '방비엥 패키지 라오스 일정 동남아 리조트 여행 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0008', '방비엥 날씨 동남아 라오스 항공권 리조트 직항 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0009', '방비엥 일정 해외 여행 동남아 항공권 리조트 날씨 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0010', '방비엥 리조트 항공권 날씨 라오스 동남아 해외 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0011', '방비엥 항공권 일정 라오스 해외 패키지 직항 동남아', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0012', '방비엥 동남아 리조트 라오스 패키지 직항 여행 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0013', '방비엥 리조트 일정 동남아 해외 항공권 패키지 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0014', '방비엥 패키지 여행 리조트 일정 날씨 직항 해외 동남아', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0015', '방비엥 직항 일정 항공권 라오스 해외 동남아 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0016', '방비엥 일정 동남아 여행 리조트 라오스 날씨 해외 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0017', '방비엥 날씨 리조트 패키지 여행 해외 항공권 일정', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0018', '방비엥 리조트 항공권 여행 해외 라오스 동남아 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0019', '방비엥 리조트 동남아 항공권 일정 라오스 날씨 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MMK_0020', '방비엥 리조트 일정 여행 날씨 라오스 패키지 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0001', '방비엥 날씨 일정 체험 리조트 요가 해외 야시장 카약', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0002', '방비엥 카약 요가 야경 트레킹 야시장 패키지 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0003', '방비엥 패키지 요가 직항 트레킹 야경 여행 야시장 카약', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0004', '방비엥 해외 날씨 야시장 리조트 요가 패키지 항공권', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0005', '방비엥 직항 요가 동남아 트레킹 항공권 리조트 여행', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0006', '방비엥 요가 라오스 패키지 관광지 항공권 열기구 일정', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0007', '방비엥 관광지 해외 열기구 직항 체험 항공권 야시장', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0008', '방비엥 카약 트레킹 요가 일정 패키지 동남아 해외 체험', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0009', '방비엥 해외 패키지 직항 야경 관광지 날씨 열기구 요가', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0010', '방비엥 라오스 트레킹 요가 동남아 야경 야시장 열기구', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0011', '방비엥 직항 체험 패키지 관광지 트레킹 야경 일정 여행', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0012', '방비엥 해외 관광지 라오스 항공권 리조트 체험 열기구', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0013', '방비엥 요가 여행 패키지 야경 동남아 일정 체험 열기구', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0014', '방비엥 야시장 카약 라오스 동남아 일정 체험 관광지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0015', '방비엥 해외 여행 체험 직항 날씨 일정 라오스 카약', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0016', '방비엥 패키지 날씨 야경 여행 해외 동남아 체험 요가', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0017', '방비엥 동남아 요가 직항 일정 날씨 트레킹 패키지 야경', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0018', '방비엥 트레킹 날씨 패키지 관광지 열기구 요가 야시장', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0019', '방비엥 요가 일정 관광지 야경 트레킹 라오스 야시장', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKSH_0020', '방비엥 직항 동남아 카약 일정 해외 요가 패키지 날씨', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0001', '방비엥 리조트 항공권 체험 라오스 여행 해외 열기구 요가 직항 날씨', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0002', '방비엥 패키지 항공권 동남아 여행 카약 해외 라오스 관광지 열기구 요가', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0003', '방비엥 카약 트레킹 야경 체험 동남아 요가 해외 일정 리조트 날씨 열기구', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0004', '방비엥 일정 카약 트레킹 야경 날씨 동남아 패키지 관광지 야시장 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0005', '방비엥 동남아 야시장 카약 해외 트레킹 열기구 체험 관광지 야경 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0006', '방비엥 리조트 직항 날씨 야시장 요가 체험 해외 동남아 열기구 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0007', '방비엥 동남아 체험 야시장 날씨 일정 항공권 패키지 여행 직항 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0008', '방비엥 항공권 야경 동남아 리조트 날씨 직항 야시장 패키지 체험 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0009', '방비엥 패키지 동남아 항공권 라오스 체험 여행 야시장 야경 관광지 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0010', '방비엥 날씨 여행 야시장 체험 야경 요가 항공권 리조트 일정 직항 열기구', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0011', '방비엥 항공권 여행 체험 직항 날씨 동남아 요가 리조트 트레킹 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0012', '방비엥 해외 항공권 카약 날씨 직항 관광지 체험 요가 일정 리조트 열기구', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0013', '방비엥 리조트 직항 요가 카약 야경 날씨 라오스 해외 관광지 야시장 일정', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0014', '방비엥 열기구 직항 트레킹 동남아 야시장 해외 일정 날씨 리조트 여행', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0015', '방비엥 동남아 카약 해외 야경 관광지 트레킹 요가 리조트 여행 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0016', '방비엥 야시장 체험 요가 동남아 여행 카약 관광지 일정 열기구 리조트', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0017', '방비엥 카약 항공권 야시장 여행 날씨 열기구 트레킹 리조트 요가 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0018', '방비엥 여행 야시장 직항 관광지 열기구 라오스 패키지 동남아 요가 체험', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0019', '방비엥 해외 야경 트레킹 항공권 일정 리조트 동남아 야시장 카약 날씨', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKLKLO_0020', '방비엥 체험 관광지 항공권 날씨 동남아 직항 야시장 요가 해외 열기구', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0001', '방비엥 날씨 전망대 라오스 리조트 남송강 해외 블루라군', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0002', '방비엥 전망대 항공권 직항 해외 라오스 여행 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0003', '방비엥 리조트 일정 동남아 남송강 날씨 해외 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0004', '방비엥 날씨 직항 동남아 블루라군 탐푸캄동굴 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0005', '방비엥 직항 블루라군 리조트 라오스 해외 탐푸캄동굴', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0006', '방비엥 일정 남송강 리조트 여행 직항 해외 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0007', '방비엥 블루라군 탐푸캄동굴 동남아 일정 직항 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0008', '방비엥 블루라군 직항 일정 남송강 패키지 리조트', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0009', '방비엥 블루라군 리조트 날씨 동남아 탐푸캄동굴 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0010', '방비엥 블루라군 탐푸캄동굴 항공권 리조트 전망대 날씨', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0011', '방비엥 동남아 남송강 여행 해외 직항 라오스 항공권', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0012', '방비엥 패키지 날씨 블루라군 항공권 여행 탐푸캄동굴', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0013', '방비엥 직항 라오스 남송강 블루라군 리조트 항공권 해외', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0014', '방비엥 일정 탐푸캄동굴 항공권 패키지 라오스 블루라군', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0015', '방비엥 블루라군 전망대 리조트 직항 항공권 라오스 날씨', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0016', '방비엥 탐푸캄동굴 패키지 여행 전망대 항공권 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0017', '방비엥 동남아 직항 날씨 전망대 탐푸캄동굴 패키지 일정', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0018', '방비엥 일정 항공권 여행 전망대 패키지 남송강 동남아', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0019', '방비엥 여행 동남아 직항 날씨 일정 패키지 해외 리조트', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_MKR_0020', '방비엥 직항 날씨 블루라군 전망대 해외 남송강 리조트', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0001', '12월 라오스 여행 패키지 리조트 4박6일 직항 방비엥', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0002', '12월 일정 항공권 날씨 패키지 해외 방비엥 4박6일', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0003', '12월 4박6일 날씨 동남아 항공권 리조트 라오스', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0004', '12월 여행 직항 패키지 일정 항공권 동남아 날씨', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0005', '12월 직항 여행 라오스 리조트 날씨 일정 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0006', '12월 리조트 여행 항공권 일정 날씨 라오스 4박6일', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0007', '12월 직항 항공권 패키지 해외 동남아 4박6일 날씨', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0008', '12월 4박6일 패키지 리조트 일정 동남아 방비엥 직항', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0009', '12월 해외 직항 날씨 일정 항공권 리조트 여행 패키지', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0010', '12월 라오스 해외 일정 항공권 날씨 방비엥 4박6일', 'VangVieng');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_VANGV_DMKTF_0011', '12월 해외 일정 라오스 방비엥 날씨 직항 여행', 'VangVieng');
