-- City Titles Part 055 (5401-5500번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0021', '마닐라 리조트 직항 패키지 해외 항공권 여행 날씨', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0022', '마닐라 날씨 직항 해외 리조트 필리핀 일정 항공권 여행', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0023', '마닐라 해외 여행 필리핀 항공권 일정 동남아 직항', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0024', '마닐라 동남아 패키지 일정 리조트 날씨 필리핀 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0025', '마닐라 여행 일정 리조트 해외 항공권 날씨 필리핀', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0026', '마닐라 일정 직항 해외 리조트 항공권 필리핀 날씨', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0027', '마닐라 동남아 필리핀 패키지 날씨 해외 직항 리조트', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0028', '마닐라 리조트 해외 항공권 직항 여행 패키지 날씨', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0029', '마닐라 필리핀 패키지 날씨 일정 여행 항공권 동남아', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MMK_0030', '마닐라 리조트 여행 직항 동남아 항공권 일정 필리핀', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0001', '마닐라 해외 열대과일 전망대 쇼핑 패키지 마사지 가족', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0002', '마닐라 직항 해외 필리핀 가족 여행 날씨 호핑 전망대', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0003', '마닐라 호핑 전망대 마사지 날씨 항공권 일정 추천 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0004', '마닐라 날씨 동남아 열대과일 일정 호핑 리조트 패키지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0005', '마닐라 직항 가족 항공권 추천 일정 전망대 호핑 동남아', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0006', '마닐라 항공권 열대과일 리조트 날씨 필리핀 패키지 가족', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0007', '마닐라 쇼핑 리조트 필리핀 일정 직항 관광지 패키지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0008', '마닐라 열대과일 관광지 해외 날씨 리조트 가족 호핑', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0009', '마닐라 해외 가족 마사지 일정 동남아 추천 전망대', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0010', '마닐라 열대과일 관광지 일정 동남아 전망대 호핑 폭포', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0011', '마닐라 폭포 동남아 열대과일 쇼핑 항공권 가족 날씨', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0012', '마닐라 일정 해외 직항 여행 패키지 관광지 추천 마사지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0013', '마닐라 패키지 직항 관광지 필리핀 리조트 호핑 가족', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0014', '마닐라 폭포 추천 가족 마사지 패키지 쇼핑 필리핀 여행', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0015', '마닐라 날씨 동남아 여행 폭포 필리핀 패키지 전망대', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0016', '마닐라 일정 쇼핑 항공권 해외 전망대 여행 호핑 패키지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0017', '마닐라 날씨 열대과일 전망대 리조트 호핑 해외 패키지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0018', '마닐라 해외 호핑 여행 열대과일 가족 폭포 항공권 추천', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0019', '마닐라 패키지 호핑 전망대 추천 폭포 여행 리조트 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0020', '마닐라 관광지 해외 여행 일정 열대과일 리조트 항공권', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0021', '마닐라 항공권 전망대 동남아 폭포 여행 리조트 쇼핑', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0022', '마닐라 전망대 추천 관광지 폭포 필리핀 직항 열대과일', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0023', '마닐라 마사지 관광지 리조트 쇼핑 열대과일 날씨 가족', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0024', '마닐라 항공권 필리핀 폭포 리조트 관광지 여행 마사지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0025', '마닐라 폭포 날씨 가족 일정 리조트 전망대 항공권 호핑', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0026', '마닐라 직항 전망대 필리핀 일정 날씨 마사지 관광지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0027', '마닐라 직항 열대과일 해외 패키지 동남아 리조트 폭포', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0028', '마닐라 일정 가족 추천 항공권 호핑 동남아 직항 여행', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0029', '마닐라 동남아 여행 전망대 호핑 가족 필리핀 쇼핑 일정', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKSH_0030', '마닐라 관광지 마사지 날씨 동남아 여행 호핑 전망대', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0001', '마닐라 폭포 리조트 동남아 항공권 관광지 추천 필리핀 일정 해외 호핑', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0002', '마닐라 여행 날씨 열대과일 리조트 쇼핑 패키지 일정 관광지 해외 동남아', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0003', '마닐라 전망대 필리핀 패키지 동남아 항공권 관광지 폭포 마사지 리조트', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0004', '마닐라 여행 날씨 마사지 항공권 일정 필리핀 해외 리조트 호핑 전망대', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0005', '마닐라 해외 마사지 리조트 열대과일 전망대 일정 호핑 직항 날씨 추천', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0006', '마닐라 날씨 폭포 여행 열대과일 필리핀 항공권 관광지 추천 마사지 일정', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0007', '마닐라 가족 항공권 리조트 동남아 날씨 전망대 마사지 추천 폭포 열대과일', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0008', '마닐라 항공권 여행 폭포 리조트 일정 패키지 호핑 직항 마사지 동남아', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0009', '마닐라 리조트 일정 해외 여행 열대과일 필리핀 날씨 호핑 항공권 관광지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0010', '마닐라 동남아 날씨 필리핀 항공권 열대과일 가족 마사지 직항 해외 추천', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0011', '마닐라 일정 전망대 마사지 관광지 열대과일 호핑 추천 리조트 직항 필리핀', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0012', '마닐라 패키지 폭포 동남아 추천 여행 마사지 관광지 직항 항공권 호핑', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0013', '마닐라 리조트 전망대 패키지 직항 필리핀 날씨 일정 폭포 쇼핑 관광지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0014', '마닐라 폭포 해외 일정 열대과일 여행 날씨 마사지 항공권 호핑 가족 쇼핑', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0015', '마닐라 호핑 리조트 가족 해외 쇼핑 열대과일 항공권 마사지 날씨 필리핀', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0016', '마닐라 항공권 필리핀 동남아 직항 패키지 전망대 마사지 추천 관광지 날씨', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0017', '마닐라 리조트 열대과일 필리핀 마사지 여행 동남아 일정 쇼핑 폭포 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0018', '마닐라 해외 일정 항공권 가족 여행 열대과일 호핑 날씨 마사지 필리핀', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0019', '마닐라 폭포 날씨 호핑 가족 관광지 항공권 추천 여행 전망대 마사지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0020', '마닐라 호핑 전망대 열대과일 날씨 직항 관광지 가족 항공권 동남아 여행', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0021', '마닐라 열대과일 해외 전망대 마사지 쇼핑 관광지 동남아 일정 가족 호핑', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0022', '마닐라 폭포 가족 추천 쇼핑 해외 리조트 필리핀 동남아 항공권 전망대', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0023', '마닐라 여행 해외 일정 열대과일 폭포 관광지 항공권 호핑 리조트 추천', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0024', '마닐라 리조트 여행 쇼핑 직항 동남아 추천 패키지 날씨 가족 전망대', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0025', '마닐라 추천 필리핀 동남아 일정 날씨 쇼핑 전망대 리조트 패키지 여행', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0026', '마닐라 패키지 열대과일 직항 리조트 전망대 호핑 폭포 마사지 날씨 추천', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0027', '마닐라 쇼핑 항공권 가족 전망대 리조트 필리핀 일정 폭포 해외 패키지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0028', '마닐라 추천 직항 관광지 여행 전망대 호핑 가족 필리핀 열대과일 마사지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0029', '마닐라 마사지 항공권 열대과일 필리핀 관광지 가족 일정 쇼핑 날씨 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKLKLO__0030', '마닐라 전망대 가족 패키지 일정 날씨 관광지 폭포 추천 리조트 필리핀', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0001', '마닐라 포트산티아고 패키지 인트라무로스 일정 여행 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0002', '마닐라 여행 동남아 리조트 직항 대성당 포트산티아고', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0003', '마닐라 날씨 인트라무로스 리잘공원 여행 리조트 대성당', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0004', '마닐라 해외 날씨 대성당 직항 리잘공원 항공권 리조트', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0005', '마닐라 동남아 필리핀 리조트 대성당 일정 직항', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0006', '마닐라 해외 인트라무로스 동남아 항공권 대성당', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0007', '마닐라 동남아 해외 필리핀 여행 인트라무로스 리잘공원', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0008', '마닐라 리잘공원 패키지 포트산티아고 대성당 동남아 직항', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0009', '마닐라 리조트 날씨 필리핀 항공권 직항 패키지 일정', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0010', '마닐라 패키지 인트라무로스 날씨 일정 대성당 리잘공원', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0011', '마닐라 리잘공원 일정 직항 여행 패키지 리조트', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0012', '마닐라 패키지 포트산티아고 인트라무로스 리조트 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0013', '마닐라 패키지 리잘공원 항공권 인트라무로스 리조트', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0014', '마닐라 날씨 해외 포트산티아고 항공권 패키지 리잘공원', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0015', '마닐라 일정 인트라무로스 직항 동남아 항공권 날씨', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0016', '마닐라 항공권 필리핀 직항 해외 인트라무로스 일정', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0017', '마닐라 리조트 직항 패키지 동남아 포트산티아고 일정', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0018', '마닐라 일정 항공권 직항 여행 인트라무로스 해외', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0019', '마닐라 날씨 리잘공원 일정 포트산티아고 패키지 직항', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0020', '마닐라 포트산티아고 리잘공원 직항 해외 동남아 패키지', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0021', '마닐라 항공권 필리핀 일정 여행 패키지 해외 직항', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0022', '마닐라 해외 필리핀 포트산티아고 직항 동남아 리조트', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0023', '마닐라 리잘공원 필리핀 여행 항공권 직항 패키지 일정', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0024', '마닐라 인트라무로스 일정 해외 동남아 리잘공원 항공권', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0025', '마닐라 항공권 일정 패키지 대성당 필리핀 포트산티아고', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0026', '마닐라 일정 해외 항공권 리잘공원 날씨 포트산티아고', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0027', '마닐라 직항 패키지 리잘공원 필리핀 대성당 인트라무로스', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0028', '마닐라 리조트 직항 패키지 여행 일정 항공권', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0029', '마닐라 패키지 여행 직항 리잘공원 항공권 날씨 동남아', 'Manila');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_MANIL_MKR__0030', '마닐라 항공권 날씨 리조트 포트산티아고 인트라무로스', 'Manila');
