-- City Titles Part 094 (9301-9400번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0022', '방콕 태국 패키지 리조트 직항 여행 날씨 3박5일', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0023', '방콕 해외 날씨 항공권 태국 패키지 직항 9월 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0024', '방콕 패키지 3박5일 추석연휴 직항 태국 해외', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0025', '방콕 여행 직항 3박5일 날씨 가을 해외 9월', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0026', '방콕 3박5일 패키지 가을 날씨 항공권 리조트 태국', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0027', '방콕 3박5일 추석연휴 여행 직항 해외 리조트 가을', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0028', '방콕 패키지 리조트 태국 9월 가을 추석연휴', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0029', '방콕 항공권 여행 날씨 가을 직항 3박5일 패키지', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MSMW_0030', '방콕 9월 날씨 추석연휴 직항 해외 여행 가을', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0021', '방콕 크루즈 가족 직항 날씨 아시아티크 해외 여행 요트 추천 야경 관광지', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0022', '방콕 해외 날씨 파타야 요트 크루즈 선셋 직항 야시장 마사지 투어 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0023', '방콕 날씨 여행 파타야 추천 항공권 투어 요트 해외 야시장 쇼핑', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0024', '방콕 아시아티크 항공권 쇼핑 투어 여행 야경 직항 요트 해외 파타야 추천', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0025', '방콕 파타야 여행 선셋 관광지 쇼핑 패키지 야경 항공권 요트 마사지 투어', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0026', '방콕 직항 관광지 날씨 파타야 아시아티크 투어 패키지 가족 쇼핑 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0027', '방콕 가족 아시아티크 날씨 크루즈 야경 패키지 관광지 쇼핑 항공권 마사지', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0028', '방콕 항공권 직항 투어 여행 관광지 패키지 날씨 선셋 아시아티크 쇼핑', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0029', '방콕 여행 날씨 투어 아시아티크 마사지 항공권 파타야 해외 추천 크루즈', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MKLT_0030', '방콕 직항 항공권 투어 날씨 아시아티크 선셋 쇼핑 해외 크루즈 파타야', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0021', '방콕 코타키나발루 태국 날씨 항공권 추석연휴 여행', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0022', '방콕 푸켓 해외 싱가포르 날씨 여행 리조트 태국 직항', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0023', '방콕 사이판 괌 푸켓 여행 싱가포르 코타키나발루', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0024', '방콕 코타키나발루 항공권 리조트 추석연휴 싱가포르', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0025', '방콕 날씨 패키지 여행 푸켓 직항 추석연휴 사이판', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0026', '방콕 해외 태국 추석연휴 괌 직항 여행 사이판', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0027', '방콕 사이판 패키지 날씨 항공권 리조트 싱가포르', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0028', '방콕 여행 사이판 싱가포르 해외 괌 리조트 푸켓 항공권', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0029', '방콕 추석연휴 날씨 여행 항공권 괌 해외 사이판 태국', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_BANGK_MPS_0030', '방콕 코타키나발루 추석연휴 직항 항공권 여행 태국 괌', 'Bangkok');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0021', '파타야 리조트 날씨 해외 항공권 태국 여행 패키지', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0022', '파타야 태국 항공권 여행 직항 해외 패키지 리조트', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0023', '파타야 직항 날씨 여행 리조트 태국 항공권 추석연휴', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0024', '파타야 패키지 리조트 직항 태국 여행 해외 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0025', '파타야 추석연휴 해외 여행 직항 항공권 날씨 리조트', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0026', '파타야 태국 항공권 직항 여행 리조트 추석연휴 해외', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0027', '파타야 리조트 태국 패키지 직항 날씨 추석연휴 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0028', '파타야 직항 태국 패키지 여행 날씨 추석연휴 리조트', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0029', '파타야 날씨 직항 태국 리조트 추석연휴 해외 패키지', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MMK_0030', '파타야 패키지 날씨 해외 리조트 추석연휴 태국 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0021', '파타야 워킹스트리트 해외 농눅열대식물원 진리의성전 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0022', '파타야 농눅열대식물원 날씨 해변 진리의성전 워킹스트리트', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0023', '파타야 해외 워킹스트리트 진리의성전 날씨 빅부다사원', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0024', '파타야 해변 파타야수상시장 항공권 해외 날씨 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0025', '파타야 여행 파타야수상시장 빅부다사원 진리의성전 해변', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0026', '파타야 파타야수상시장 진리의성전 해외 빅부다사원 해변', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0027', '파타야 여행 직항 진리의성전 농눅열대식물원', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0028', '파타야 날씨 빅부다사원 직항 워킹스트리트 여행', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0029', '파타야 여행 농눅열대식물원 빅부다사원 해외', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MSLS_0030', '파타야 여행 파타야수상시장 빅부다사원 해외 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0021', '파타야 해외 태국 직항 여행 추석연휴 가을 패키지', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0022', '파타야 추석연휴 패키지 리조트 태국 여행 직항 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0023', '파타야 해외 3박5일 9월 날씨 추석연휴 직항 태국', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0024', '파타야 3박5일 9월 항공권 가을 여행 직항 태국', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0025', '파타야 패키지 3박5일 해외 날씨 직항 여행 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0026', '파타야 해외 여행 항공권 가을 직항 태국 리조트', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0027', '파타야 항공권 리조트 9월 여행 패키지 추석연휴 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0028', '파타야 가을 항공권 해외 9월 날씨 패키지 리조트 태국', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0029', '파타야 여행 9월 3박5일 패키지 가을 해외 날씨 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMS 0030', '파타야 9월 여행 추석연휴 3박5일 가을 패키지 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMN_0021', '파타야 여행 태국 리조트 11월 가을 해외 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMN_0022', '파타야 날씨 태국 11월 항공권 3박5일 패키지 가을', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_AMN_0023', '파타야 추석연휴 패키지 태국 해외 여행 가을 11월', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0021', '파타야 항공권 숙소 마사지 패키지 리조트 쇼핑 에어텔 패키지 아시아티크', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0022', '파타야 쇼핑 패키지 태국 숙소 날씨 코스 패키지 마사지 호텔 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0023', '파타야 날씨 직항 추석연휴 숙소 해외 마사지 쇼핑 여행지 여행 아시아티크', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0024', '파타야 항공권 직항 패키지 숙소 에어텔 해외 패키지 여행 여행지 코스', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0025', '파타야 에어텔 호텔 여행지 패키지 날씨 코스 쇼핑 항공권 해외 여행 태국', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0026', '파타야 날씨 패키지 코스 호텔 여행 직항 아시아티크 리조트 추석연휴', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0027', '파타야 리조트 마사지 직항 쇼핑 패키지 여행 아시아티크 허니문 추석연휴', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0028', '파타야 항공권 쇼핑 호텔 추석연휴 숙소 여행지 날씨 여행 아시아티크 해외', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0029', '파타야 태국 해외 허니문 숙소 날씨 아시아티크 에어텔 쇼핑 호텔 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKLK_0030', '파타야 직항 여행지 패키지 에어텔 여행 항공권 태국 패키지 추석연휴 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0021', '파타야 해외 날씨 여행 항공권 인천출발 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0022', '파타야 해외 직항 날씨 인천출발 여행 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0023', '파타야 해외 항공권 날씨 여행 인천출발 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0024', '파타야 해외 인천출발 날씨 여행 직항 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0025', '파타야 여행 해외 날씨 인천출발 항공권 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0026', '파타야 직항 항공권 날씨 여행 해외 인천출발', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0027', '파타야 항공권 인천출발 직항 해외 여행 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0028', '파타야 날씨 여행 인천출발 직항 항공권 해외', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0029', '파타야 여행 직항 날씨 해외 항공권 인천출발', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSIS_0030', '파타야 직항 항공권 여행 인천출발 해외 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0021', '파타야 인천출발 직항 해외 여행 항공권 방콕 날씨 푸켓 치앙마이 태국', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0022', '파타야 치앙마이 항공권 날씨 푸켓 여행 인천출발 방콕 태국 해외 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0023', '파타야 여행 방콕 치앙마이 인천출발 푸켓 해외 직항 날씨 태국 항공권', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0024', '파타야 항공권 푸켓 해외 날씨 방콕 여행 인천출발 태국 치앙마이 직항', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0025', '파타야 치앙마이 항공권 방콕 해외 직항 태국 인천출발 여행 날씨 푸켓', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0026', '파타야 직항 항공권 해외 푸켓 태국 방콕 치앙마이 여행 날씨 인천출발', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0027', '파타야 여행 항공권 푸켓 인천출발 날씨 방콕 직항 해외 치앙마이 태국', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0028', '파타야 직항 태국 방콕 여행 해외 푸켓 날씨 인천출발 항공권 치앙마이', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0029', '파타야 치앙마이 태국 해외 푸켓 인천출발 항공권 직항 여행 방콕 날씨', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PATT_MKSICM_0030', '파타야 치앙마이 직항 푸켓 방콕 여행 해외 날씨 항공권 인천출발 태국', 'Pattaya');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_21', '푸껫 리조트 태국 직항 항공권 날씨 해외 패키지 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_22', '푸껫 태국 날씨 직항 리조트 여행 패키지 항공권 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_23', '푸껫 항공권 리조트 여행 날씨 해외 직항 태국 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_24', '푸껫 패키지 날씨 항공권 여행 리조트 직항 태국 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_25', '푸껫 태국 날씨 여행 직항 리조트 패키지 항공권 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_26', '푸껫 리조트 패키지 날씨 여행 항공권 해외 태국 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_27', '푸껫 항공권 패키지 해외 날씨 리조트 여행 직항 태국', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_28', '푸껫 여행 리조트 직항 태국 항공권 패키지 해외 날씨', 'PhuQuoc');
