-- City Titles Part 109 (10801-10900번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0040', '1월 패키지 관광 호주 골드코스트 여행 가족여행 6박7일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0041', '2월 호주 6박7일 여행 골드코스트 관광 가족여행 패키지', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0042', '2월 호주 6박7일 가족여행 골드코스트 관광 여행 패키지', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0043', '2월 관광 여행 패키지 6박7일 호주 골드코스트 가족여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0044', '2월 호주 6박7일 가족여행 골드코스트 패키지 관광 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0045', '2월 호주 패키지 6박7일 골드코스트 여행 가족여행 관광', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0046', '2월 패키지 관광 여행 6박7일 골드코스트 가족여행 호주', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0047', '2월 골드코스트 패키지 6박7일 호주 가족여행 여행 관광', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0048', '2월 호주 관광 6박7일 가족여행 패키지 골드코스트 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0049', '2월 여행 골드코스트 가족여행 호주 관광 6박7일 패키지', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0050', '2월 패키지 호주 6박7일 골드코스트 여행 가족여행 관광', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0051', '2월 6박7일 골드코스트 패키지 여행 관광 가족여행 호주', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0052', '2월 6박7일 호주 여행 패키지 관광 골드코스트 가족여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0053', '2월 가족여행 골드코스트 관광 패키지 여행 호주 6박7일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0054', '2월 6박7일 패키지 관광 호주 여행 가족여행 골드코스트', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0055', '2월 호주 6박7일 관광 여행 가족여행 패키지 골드코스트', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0056', '2월 패키지 관광 골드코스트 가족여행 6박7일 호주 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0057', '2월 골드코스트 패키지 6박7일 호주 여행 관광 가족여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0058', '2월 여행 호주 패키지 골드코스트 관광 가족여행 6박7일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0059', '2월 패키지 여행 관광 6박7일 골드코스트 호주 가족여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_DMK_0060', '2월 6박7일 관광 여행 호주 패키지 골드코스트 가족여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0001', '씨월드 드림월드 가족여행 골드코스트 호주 커럼빈 파라다이스 관광 6박7일 패키지', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0002', '커럼빈 씨월드 스카이포인트 파라다이스 호주 관광 가족여행 여행 패키지 6박7일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0003', '씨월드 여행 스카이포인트 6박7일 관광 가족여행 패키지 호주 커럼빈 드림월드 골드코스트', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0004', '가족여행 6박7일 여행 호주 스카이포인트 커럼빈 관광 골드코스트 드림월드 패키지', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0005', '관광 가족여행 드림월드 씨월드 패키지 6박7일 골드코스트 파라다이스 호주 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0006', '6박7일 관광 커럼빈 씨월드 파라다이스 드림월드 스카이포인트 호주 골드코스트 패키지', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0007', '관광 골드코스트 6박7일 커럼빈 패키지 가족여행 호주 씨월드 여행 파라다이스', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0008', '파라다이스 골드코스트 호주 씨월드 패키지 여행 관광 가족여행 6박7일 커럼빈', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0009', '6박7일 골드코스트 씨월드 파라다이스 스카이포인트 패키지 여행 커럼빈 관광 호주', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0010', '가족여행 관광 드림월드 파라다이스 스카이포인트 골드코스트 6박7일 호주 여행 커럼빈', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0011', '여행 커럼빈 파라다이스 가족여행 관광 골드코스트 호주 드림월드 스카이포인트 씨월드', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0012', '패키지 관광 가족여행 여행 골드코스트 커럼빈 호주 씨월드 파라다이스 6박7일 드림월드', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0013', '호주 커럼빈 씨월드 가족여행 드림월드 골드코스트 파라다이스 6박7일 관광 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0014', '관광 커럼빈 골드코스트 여행 가족여행 씨월드 파라다이스 스카이포인트 호주 패키지', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0015', '커럼빈 패키지 파라다이스 스카이포인트 드림월드 가족여행 6박7일 씨월드 호주 골드코스트', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0016', '가족여행 파라다이스 드림월드 커럼빈 골드코스트 스카이포인트 씨월드 관광 여행 패키지', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0017', '씨월드 스카이포인트 관광 패키지 여행 커럼빈 파라다이스 6박7일 골드코스트 드림월드', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0018', '드림월드 골드코스트 호주 가족여행 씨월드 커럼빈 여행 파라다이스 6박7일 관광', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0019', '드림월드 골드코스트 패키지 스카이포인트 여행 가족여행 파라다이스 관광 호주 커럼빈', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_ML_0020', '호주 커럼빈 가족여행 패키지 골드코스트 씨월드 스카이포인트 관광 6박7일 여행 드림월드', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0001', '골드코스트 가족 일정 여행 호주 연휴 오페라하우스 패키지 관광', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0002', '골드코스트 호주 여행 패키지 오페라하우스 가족 일정 관광 연휴', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0003', '골드코스트 일정 관광 호주 패키지 연휴 여행 오페라하우스 가족', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0004', '골드코스트 일정 여행 패키지 연휴 호주 오페라하우스 관광 가족', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0005', '골드코스트 연휴 여행 패키지 관광 일정 호주 오페라하우스 가족', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0006', '골드코스트 패키지 가족 오페라하우스 관광 일정 호주 연휴 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0007', '골드코스트 관광 가족 연휴 패키지 일정 오페라하우스 호주 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0008', '골드코스트 호주 관광 여행 패키지 일정 연휴 오페라하우스 가족', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0009', '골드코스트 호주 오페라하우스 가족 관광 패키지 여행 연휴 일정', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0010', '골드코스트 패키지 일정 연휴 관광 가족 호주 오페라하우스 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0011', '골드코스트 관광 일정 가족 호주 연휴 패키지 오페라하우스 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0012', '골드코스트 가족 관광 오페라하우스 일정 패키지 호주 여행 연휴', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0013', '골드코스트 일정 연휴 관광 패키지 호주 가족 오페라하우스 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0014', '골드코스트 호주 일정 관광 패키지 가족 여행 연휴 오페라하우스', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0015', '골드코스트 관광 연휴 여행 가족 호주 패키지 일정 오페라하우스', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0016', '골드코스트 관광 여행 호주 오페라하우스 패키지 일정 연휴 가족', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0017', '골드코스트 오페라하우스 관광 연휴 패키지 일정 호주 여행 가족', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0018', '골드코스트 일정 관광 여행 패키지 호주 오페라하우스 연휴 가족', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0019', '골드코스트 오페라하우스 호주 일정 관광 연휴 여행 가족 패키지', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNK_0020', '골드코스트 관광 호주 연휴 일정 패키지 여행 가족 오페라하우스', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0001', '호주 골드코스트 여행패키지 3박4일 항공 호텔 포함', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0002', '호주 골드코스트 자유여행 패키지 항공권 숙박 특가', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0003', '호주 골드코스트 패키지여행 4박5일 올인클루시브', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0004', '호주 골드코스트 가족여행 패키지 4박5일 추천', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0005', '호주 골드코스트 허니문 여행패키지 리조트 포함', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0006', '호주 골드코스트 효도여행 패키지 3박4일 특가', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0007', '호주 골드코스트 자유여행 실속 패키지 항공 호텔', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0008', '호주 골드코스트 여행패키지 5박6일 전일정 포함', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0009', '호주 골드코스트 패키지여행 직항 항공권 포함', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0010', '호주 골드코스트 자유여행 항공권 호텔 예약 특가', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0011', '호주 골드코스트 여행패키지 3박4일 인기상품', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0012', '호주 골드코스트 패키지여행 4박5일 실속형', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0013', '호주 골드코스트 자유여행 패키지 호텔 리조트 포함', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0014', '호주 골드코스트 여행패키지 성수기 특가상품', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0015', '호주 골드코스트 가족여행 패키지 자유일정 포함', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0016', '호주 골드코스트 패키지여행 인기 리조트 포함', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0017', '호주 골드코스트 여행 올인클루시브 패키지 4박5일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0018', '호주 골드코스트 자유여행 패키지 특가 항공 호텔', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0019', '호주 골드코스트 여행패키지 효도여행 추천상품', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_GPT_0020', '호주 골드코스트 허니문 패키지여행 4박5일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0001', '호주 관광 골드코스트 스카이포인트 가족 여행 브리즈번 4박6일 효도여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0002', '호주 가족 브리즈번 여행 스카이포인트 4박6일 관광 골드코스트 효도여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0003', '호주 브리즈번 관광 효도여행 가족 골드코스트 스카이포인트 4박6일 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0004', '호주 여행 스카이포인트 관광 골드코스트 가족 브리즈번 4박6일 효도여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0005', '호주 골드코스트 가족 스카이포인트 관광 여행 브리즈번 효도여행 4박6일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0006', '호주 관광 효도여행 브리즈번 스카이포인트 골드코스트 가족 여행 4박6일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0007', '호주 여행 브리즈번 골드코스트 스카이포인트 관광 효도여행 가족 4박6일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0008', '호주 스카이포인트 가족 브리즈번 여행 관광 효도여행 골드코스트 4박6일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0009', '호주 스카이포인트 효도여행 가족 브리즈번 골드코스트 관광 4박6일 여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0010', '호주 효도여행 가족 브리즈번 스카이포인트 4박6일 여행 관광 골드코스트', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0011', '호주 골드코스트 가족 스카이포인트 4박6일 여행 효도여행 관광 브리즈번', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0012', '호주 관광 4박6일 효도여행 골드코스트 여행 스카이포인트 브리즈번 가족', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0013', '호주 가족 효도여행 여행 골드코스트 4박6일 관광 스카이포인트 브리즈번', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0014', '호주 효도여행 여행 브리즈번 스카이포인트 가족 4박6일 관광 골드코스트', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0015', '호주 가족 관광 여행 효도여행 스카이포인트 브리즈번 골드코스트 4박6일', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0016', '호주 가족 스카이포인트 4박6일 효도여행 여행 관광 브리즈번 골드코스트', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0017', '호주 4박6일 스카이포인트 브리즈번 여행 효도여행 관광 가족 골드코스트', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0018', '호주 골드코스트 4박6일 관광 스카이포인트 가족 여행 브리즈번 효도여행', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0019', '호주 여행 가족 브리즈번 효도여행 관광 골드코스트 4박6일 스카이포인트', 'GoldCoast');
