-- City Titles Part 081 (8001-8100번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0009', '8대학탐방 국회의사당 자유의여신상 우드버리아울렛 브루클린브리지 월스트리트 효도관광 효도여행 나이아가라폭포 조기예약 스미소니언박물관 스테디셀러 킹스톤 링컨기념관 미동부 패키지 아이비리그탐방', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0010', '프린스턴대학교 조기예약 아이비리그탐방 토론토 미국동부 핵심관광 인천출발 국회의사당 911메모리얼 월스트리트 자유의여신상 패키지 커플여행 현지투어 힐링 여행가기좋은곳 8대학탐방', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0011', '우드버리아울렛 아이비리그탐방 핵심관광 현지투어 인천출발 월스트리트 조기예약 911메모리얼 미국동부 브루클린브리지 백악관 몬트리올 우정여행 패키지 스미소니언박물관 토론토 나이아가라폭포', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0012', '노팁관광여행 패키지 자유의여신상 힐링 몬트리올 아이비리그탐방 프린스턴대학교 인천출발 조기예약 토론토 월스트리트 국회의사당 킹스톤 제퍼슨기념관 911메모리얼 핵심관광 백악관', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0013', '여행가기좋은곳 링컨기념관 국회의사당 브루클린브리지 미동부 스미소니언박물관 나이아가라폭포 핵심관광 힐링 워싱턴여행 자유의여신상 조기예약 인천출발 패키지 월스트리트 우드버리아울렛 911메모리얼', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0014', '링컨기념관 몬트리올 911메모리얼 스미소니언박물관 조기예약 킹스톤 월스트리트 가족여행 우드버리아울렛 여행가기좋은곳 미동부 토론토 백악관 힐링 인천출발 효도관광 8대학탐방', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0015', '토론토 백악관 핵심관광 미동부 힐링 인천출발 효도여행 현지투어 제퍼슨기념관 국회의사당 조기예약 여행가기좋은곳 스미소니언박물관 스테디셀러 자유의여신상 몬트리올 미국동부', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0016', '여행가기좋은곳 911메모리얼 월스트리트 패키지 브루클린브리지 우드버리아울렛 자유의여신상 링컨기념관 스미소니언박물관 8대학탐방 토론토 힐링 킹스톤 나이아가라폭포 커플여행 인천출발 미동부', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0017', '여행가기좋은곳 링컨기념관 스미소니언박물관 몬트리올 조기예약 8대학탐방 월스트리트 프린스턴대학교 911메모리얼 힐링 아이비리그탐방 스테디셀러 토론토 제퍼슨기념관 우정여행 핵심관광 미국동부', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0018', '토론토 현지투어 노팁관광여행 아이비리그탐방 8대학탐방 여행가기좋은곳 핵심관광 브루클린브리지 힐링 제퍼슨기념관 우드버리아울렛 효도관광 킹스톤 911메모리얼 스미소니언박물관 링컨기념관 나이아가라폭포', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0019', '인천출발 프린스턴대학교 토론토 8대학탐방 자유의여신상 핵심관광 여행가기좋은곳 킹스톤 워싱턴여행 브루클린브리지 조기예약 월스트리트 국회의사당 몬트리올 힐링 링컨기념관 스테디셀러', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0020', '백악관 브루클린브리지 효도관광 인천출발 핵심관광 토론토 월스트리트 몬트리올 미동부 프린스턴대학교 가족여행 스미소니언박물관 나이아가라폭포 킹스톤 911메모리얼 제퍼슨기념관 여행가기좋은곳', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0001', '여행가기좋은곳 노팁노옵션 9월 여행관광사 대한항공 아이비리그탐방 노팁관광여행 조기예약 효도관광', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0002', '효도관광 노팁관광여행 아이비리그탐방 아시아나항공 조기예약 자유의여신상 미국동부여행 워싱턴여행 워싱턴여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0003', '미국동부여행 여행가기좋은곳 조기예약 9월 워싱턴여행 자유의여신상 대한항공 여행관광사 노팁관광여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0004', '가족투어 아시아나항공 워싱턴여행 노팁관광여행 9월 핵심관광 조기예약 아이비리그탐방 워싱턴여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0005', '노팁관광여행 여행관광사 워싱턴여행 조기예약 가족투어 대한항공 아이비리그탐방 워싱턴여행 9월', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0006', '워싱턴여행 노팁노옵션 가족투어 아시아나항공 조기예약 자유의여신상 핵심관광 효도관광 아이비리그탐방', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0007', '자유의여신상 워싱턴여행 여행가기좋은곳 대한항공 효도관광 미국동부여행 노팁관광여행 노팁노옵션 여행관광사', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0008', '워싱턴여행 핵심관광 9월 노팁관광여행 여행관광사 워싱턴여행 효도관광 미국동부여행 아시아나항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0009', '아이비리그탐방 핵심관광 노팁관광여행 노팁노옵션 워싱턴여행 가족투어 대한항공 조기예약 자유의여신상', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0010', '워싱턴여행 가족투어 9월 여행관광사 노팁노옵션 아이비리그탐방 워싱턴여행 아시아나항공 자유의여신상', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0011', '대한항공 미국동부여행 효도관광 9월 자유의여신상 워싱턴여행 노팁관광여행 여행가기좋은곳 여행관광사', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0012', '핵심관광 워싱턴여행 가족투어 아시아나항공 조기예약 미국동부여행 여행가기좋은곳 노팁관광여행 노팁노옵션', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0013', '노팁관광여행 아이비리그탐방 효도관광 조기예약 워싱턴여행 여행관광사 미국동부여행 9월 대한항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0014', '가족투어 효도관광 미국동부여행 아시아나항공 워싱턴여행 자유의여신상 여행관광사 조기예약 핵심관광', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0015', '노팁관광여행 노팁노옵션 여행관광사 9월 대한항공 아이비리그탐방 효도관광 워싱턴여행 가족투어', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0016', '아시아나항공 노팁관광여행 워싱턴여행 여행관광사 가족투어 워싱턴여행 자유의여신상 노팁노옵션 아이비리그탐방', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0017', '노팁노옵션 워싱턴여행 대한항공 자유의여신상 여행관광사 아이비리그탐방 9월 조기예약 핵심관광', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0018', '미국동부여행 아시아나항공 노팁관광여행 9월 조기예약 여행가기좋은곳 가족투어 워싱턴여행 자유의여신상', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0019', '노팁노옵션 워싱턴여행 여행관광사 조기예약 대한항공 9월 가족투어 아이비리그탐방 효도관광', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_SNK_0020', '9월 노팁관광여행 아이비리그탐방 가족투어 노팁노옵션 아시아나항공 여행가기좋은곳 워싱턴여행 효도관광', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0001', '해리스버그 백악관 대한항공 여행 토론토 직항 인천출발 미국동부어행 항공권 노팁 노쇼핑', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0002', '토론토 미국 직항 여행 워싱턴 나이아가라폭포 항공권 노팁 아시애나항공 몬트리올 인천출발', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0003', '링컨기념관 패키지 노옵션 대한항공 인천출발 미국동부어행 노쇼핑 워싱턴 여행 911메모리얼 토론토', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0004', '미동부 해리스버그 월스트리트 제퍼슨기념관 노옵션 여행 패키지 인천출발 항공권 애시아나항공 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0005', '미국동부어행 백악관 인천출발 여행 미국 브루클린브리지 스미소니언박물관 대한항공 항공권 워싱턴 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0006', '아시아나항공 여행 항공권 노쇼핑 어행 자우의어신상 해리스버그 미국동부여행 우드버리아울렛 뉴욕 인천출발', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0007', '대한항공 노팁 뉴욕 직항 미동부 몬트리올 어행 어행 월스트리트 인천출발 911메모리얼', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0008', '노팁 우드버리애울렛 패키지 인천출발 나으애가라폭포 워싱턴 여행 미국 직항 토론토 애시애나항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0009', '미동부 패키지 몬트리올 노옵션 링컨기념관 뉴욕 어행 인천출발 대한항공 백악관 노팁', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0010', '유드버리애울렛 여행 국회의사당 뉴욕 몬트리올 항공권 직항 미동부 미국동부어행 인천출발 아시아나항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0011', '어행 브루클린브리지 노옵션 워싱턴 우드버리아울렛 미동부 시닉터널 인천출발 여행 대한항공 노쇼핑', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0012', '직항 아시아나항공 노옵션 미국동부어행 911메모리얼 여행 스미소니언박물관 노팁 자유의여신상 노쇼핑 인천출발', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0013', '노팁 노쇼핑 대한항공 여행 토론토 미동부 우드버리애울렛 노옵션 인천출발 여행 링컨기념관', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0014', '여행 브루클린브리지 직항 911메모리얼 애시애나항공 노옵션 어행 워싱턴 국회의사당 미국동부어행 인천출발', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0015', '미국동부어행 노쇼핑 워싱턴 여행 대한항공 미국 스미소니언박물관 노팁 백악관 인천출발 프린스턴대학교', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0016', '브루클린브리지 노팁 프린스턴대학교 노옵션 아시아나항공 미국 시닉터널 인천출발 어행 항공권 워싱턴', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0017', '노팁 여행 시닉터널 대한항공 직항 킹스톤 패키지 뉴욕 여행 인천출발 트리니티교회', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0018', '어행 인천출발 노옵션 국회의사당 911메모리얼 어행 미동부 노쇼핑 우드버리아울렛 뉴욕 애시애나항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0019', '월스트리트 워싱턴 미국 어행 어행 대한항공 킹스톤 프린스턴대학교 패키지 미국동부어행 인천출발', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_OT_0020', '어행 애시아나항공 패키지 자우의여신상 링컨기념관 여행 인천출발 노쇼핑 제퍼슨기념관 노팁 항공권', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0001', '워싱턴 백악관 국회의사당 링컨기념관 제퍼슨기념관 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0002', '워싱턴 스미소니언박물관 백악관 국회의사당 패키지 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0003', '워싱턴 링컨기념관 제퍼슨기념관 국회의사당 백악관 투어', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0004', '워싱턴 백악관 국회의사당 프린스턴대학교 여행 패키지', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0005', '워싱턴 스미소니언박물관 백악관 국회의사당 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0006', '워싱턴 백악관 링컨기념관 제퍼슨기념관 패키지 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0007', '워싱턴 국회의사당 백악관 트리니티교회 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0008', '워싱턴 백악관 링컨기념관 제퍼슨기념관 투어', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0009', '워싱턴 국회의사당 백악관 브루클린브리지 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0010', '워싱턴 백악관 스미소니언박물관 국회의사당 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0011', '워싱턴 백악관 국회의사당 링컨기념관 여행 패키지', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0012', '워싱턴 제퍼슨기념관 백악관 국회의사당 투어', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0013', '워싱턴 백악관 국회의사당 911메모리얼 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0014', '워싱턴 백악관 국회의사당 월스트리트 패키지', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0015', '워싱턴 스미소니언박물관 링컨기념관 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0016', '워싱턴 백악관 제퍼슨기념관 링컨기념관 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0017', '워싱턴 국회의사당 백악관 스미소니언박물관 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0018', '워싱턴 백악관 링컨기념관 제퍼슨기념관 일정', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0019', '워싱턴 백악관 국회의사당 링컨기념관 여행 투어', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_GPT_0020', '워싱턴 백악관 국회의사당 제퍼슨기념관 여행 패키지', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0001', '캐나다 여행 패키지 캘거리 밴프 대한항공 아시아나항공 국적기 인천출발', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0002', '캘거리 밴프 캐나다 여행 패키지 국적기 대한항공 아시아나항공 인천출발', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0003', '캐나다동부 토론토 몬트리올 캘거리 여행 패키지 국적기 대한항공 인천출발', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0004', '캐나다 여행 패키지 캘거리 밴프 토론토 몬트리올 국적기 아시아나항공', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0005', '대한항공 아시아나항공 국적기 인천출발 캘거리 밴프 캐나다 여행 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0006', '인천출발 국적기 캘거리 밴프 캐나다 여행 패키지 대한항공 아시아나항공', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0007', '캐나다 여행 패키지 캘거리 밴프 국적기 대한항공 아시아나항공 인천출발', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0008', '캘거리 밴프 토론토 몬트리올 캐나다 여행 패키지 국적기 인천출발', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0009', '아시아나항공 대한항공 국적기 인천출발 캘거리 캐나다 여행 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0010', '캘거리 밴프 국적기 인천출발 대한항공 아시아나항공 캐나다 여행 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0011', '대한항공 국적기 아시아나항공 인천출발 캘거리 밴프 캐나다 여행 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0012', '아시아나항공 국적기 인천출발 캘거리 밴프 캐나다 여행 패키지 대한항공', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0013', '캐나다 여행 패키지 국적기 캘거리 밴프 인천출발 대한항공 아시아나항공', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0014', '캘거리 밴프 캐나다 여행 패키지 대한항공 아시아나항공 국적기 인천출발', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0015', '토론토 몬트리올 캐나다동부 캘거리 여행 패키지 국적기 대한항공', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0016', '아시아나항공 대한항공 국적기 인천출발 캘거리 밴프 캐나다 여행', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0017', '대한항공 아시아나항공 국적기 인천출발 캘거리 캐나다 밴프 여행 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0018', '국적기 인천출발 대한항공 아시아나항공 캘거리 밴프 캐나다 여행 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0019', '인천출발 국적기 대한항공 아시아나항공 캘거리 밴프 캐나다 여행 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_CMK_0020', '대한항공 아시아나항공 국적기 캘거리 밴프 캐나다 여행 패키지 인천출발', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_DMK_0001', '캘거리 캐나다 2025년 12월 6박 8일 국적기 인천출발 대한항공 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_DMK_0002', '밴프 캐나다 2025년 11월 6박 8일 국적기 인천출발 대한항공 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_DMK_0003', '캘거리 캐나다 26년 하반기 8박 10일 국적기 인천출발 아시아나항공', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_DMK_0004', '캘거리 캐나다 26년 하반기 국적기 인천출발 아시아나항공', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_DMK_0005', '밴프 캐나다 1월 국적기 인천출발 대한항공 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_DMK_0006', '캘거리 캐나다 여행적기 2026년 2월 국적기 인천출발 아시아나항공', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_DMK_0007', '캘거리 캐나다 여행적기 4월 8박 10일 국적기 인천출발 대한항공 패키지', 'Banff');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_BF_DMK_0008', '캘거리 캐나다 10일 2026년 국적기 인천출발 아시아나항공', 'Banff');
