-- City Titles Part 080 (7901-8000번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_CMK_0010', '패키지 8대캐년 로스앤젤레스 아시아나항공 여행 미국 직항 여행 라스베가스 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_CMK_0015', '미국 직항 서부 라스베가스 패키지 대한항공 그랜드캐년 여행 미서부패키지여행 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_MKL_0001', '라스베가스 그리피스천문대 코카콜라스토어 스타의거리 대한항공 여행 피셔맨스워프 돌비극장 미국 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_MKL_0003', '미국 여행 그리피스천문대 라스베가스 대한항공 코카콜라스토어 피어39 금문교 피셔맨스워프 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_MKL_0007', '코카콜라스토어 그랜드캐년 프리몬트스트리트 라스베가스 피셔맨스워프 미국 여행 스타의거리 대한항공 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_MKL_0012', '라스베가스 아시아나항공 그랜드캐년 금문교 여행 미국 피어39 스타의거리 그리피스천문대 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_MKL_0013', '대한항공 프리몬트스트리트 미국 돌비극장 여행 코카콜라스토어 라스베가스 금문교 피셔맨스워프 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_MKL_0016', '아시아나항공 프리몬트스트리트 피셔맨스워프 금문교 그랜드캐년 라스베가스 미국 여행 피어39 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_MKL_0019', '라스베가스 미국여행 금문교 그랜드캐년 대한항공 스타의거리 코카콜라스토어 프리몬트스트리트 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_DMK_0004', '여행 아시아나항공 9월 서부 그랜드캐년 하반기 직항 2026년 인천출발 로스앤젤레스', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_DMK_0012', '2026년 아시아나항공 여행 여행 서부 로스앤젤레스 그랜드캐년 10박12일 인천출발', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_DMK_0019', '라스베가스 여행 미서부패키지여행 대한항공 6월 여행 로스앤젤레스', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0001', '그랜드캐년 라스베이거스 미서부 패키지 후버댐 브라이스캐년 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0002', '그랜드캐년 요세미티 자이언캐년 앤텔로프캐년 미서부 패키지', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0003', '그랜드캐년 라스베이거스 미서부여행 브라이스캐년 자이언캐년', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0004', '그랜드캐년 미서부 패키지 라스베이거스 앤텔로프캐년 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0005', '그랜드캐년 자이언캐년 브라이스캐년 미서부 패키지 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0006', '그랜드캐년 라스베이거스 미서부 앤텔로프캐년 요세미티 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0007', '그랜드캐년 브라이스캐년 자이언캐년 미서부여행 패키지', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0008', '그랜드캐년 라스베이거스 요세미티 미서부 패키지 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0009', '그랜드캐년 앤텔로프캐년 자이언캐년 브라이스캐년 패키지', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0010', '그랜드캐년 라스베이거스 미서부 패키지 요세미티 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0011', '그랜드캐년 브라이스캐년 자이언캐년 미서부 패키지 일정', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0012', '그랜드캐년 미서부 라스베이거스 패키지 요세미티 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0013', '그랜드캐년 자이언캐년 브라이스캐년 미서부 패키지 일정', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0014', '그랜드캐년 미서부여행 라스베이거스 앤텔로프캐년 투어', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0015', '그랜드캐년 요세미티 브라이스캐년 자이언캐년 미서부 패키지', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0016', '그랜드캐년 라스베이거스 브라이스캐년 미서부 패키지 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0017', '그랜드캐년 앤텔로프캐년 미서부여행 라스베이거스 패키지', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0018', '그랜드캐년 자이언캐년 브라이스캐년 요세미티 패키지 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0019', '그랜드캐년 미서부 라스베이거스 요세미티 앤텔로프캐년 여행', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_GC_GPT_0020', '그랜드캐년 브라이스캐년 자이언캐년 앤텔로프캐년 미서부 패키지', 'GrandCanyon');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0001', '노쇼핑 뉴욕 직항 미동부 항공권 미국 워싱턴 패키지 대한항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0002', '미국동부여행 노옵션 아시아나항공 워싱턴 노쇼핑 직항 미국 뉴욕 미동부', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0003', '워싱턴 대한항공 미국동부여행 노옵션 직항 여행 미동부 뉴욕 미국', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0004', '미동부 미국 노팁 패키지 미국동부여행 노옵션 아시아나항공 항공권 노쇼핑', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0005', '여행 미국 노팁 워싱턴 미동부 항공권 패키지 대한항공 미국동부여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0006', '아시아나항공 여행 미동부 미국 워싱턴 노옵션 미국동부여행 노쇼핑 노팁', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0007', '미국 노쇼핑 미국동부여행 노팁 노옵션 패키지 대한항공 워싱턴 미동부', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0008', '여행 아시아나항공 미국동부여행 워싱턴 노옵션 미국 뉴욕 미동부 노쇼핑', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0009', '노팁 미국동부여행 직항 미동부 노쇼핑 노옵션 뉴욕 미국 대한항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0010', '항공권 직항 노옵션 여행 노쇼핑 뉴욕 노팁 미국 아시아나항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0011', '패키지 항공권 미국 미동부 노팁 미국동부여행 노쇼핑 대한항공 뉴욕', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0012', '노옵션 여행 아시아나항공 직항 미국 노팁 패키지 노쇼핑 미동부', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0013', '노팁 항공권 미국동부여행 워싱턴 뉴욕 미국 패키지 대한항공 직항', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0014', '항공권 패키지 미국동부여행 워싱턴 노쇼핑 미국 직항 노옵션 아시아나항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0015', '노쇼핑 패키지 워싱턴 직항 대한항공 항공권 여행 미동부 미국동부여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0016', '노옵션 항공권 아시아나항공 직항 노쇼핑 패키지 워싱턴 미동부 노팁', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0017', '항공권 노팁 워싱턴 노옵션 직항 대한항공 미동부 여행 패키지', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0018', '여행 노옵션 패키지 워싱턴 뉴욕 노팁 항공권 미동부 아시아나항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0019', '노팁 미동부 여행 대한항공 패키지 노옵션 항공권 뉴욕 직항', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_CMK_0020', '직항 노쇼핑 여행 항공권 미동부 패키지 아시아나항공 미국동부여행 노옵션', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0001', '자유의여신상 대한항공 우드버리아울렛 트리니티교회 뉴욕 여행 워싱턴 월스트리트 911메모리얼 나이아가라폭포 프린스턴대학교', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0002', '브루클린브리지 월스트리트 우드버리아울렛 뉴욕 아시아나항공 해리스버그 워싱턴 스미소니언박물관 여행 자유의여신상 제퍼슨기념관', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0003', '토론토 뉴욕 여행 자유의여신상 프린스턴대학교 911메모리얼 워싱턴 몬트리올 트리니티교회 우드버리아울렛 대한항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0004', '해리스버그 월스트리트 아시아나항공 워싱턴 여행 트리니티교회 우드버리아울렛 자유의여신상 백악관 시닉터널 뉴욕', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0005', '우드버리아울렛 뉴욕 백악관 워싱턴 킹스톤 몬트리올 대한항공 제퍼슨기념관 링컨기념관 여행 프린스턴대학교', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0006', '해리스버그 뉴욕 국회의사당 링컨기념관 토론토 여행 아시아나항공 워싱턴 제퍼슨기념관 백악관 트리니티교회', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0007', '워싱턴 자유의여신상 911메모리얼 링컨기념관 몬트리올 대한항공 여행 우드버리아울렛 뉴욕 토론토 킹스톤', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0008', '여행 아시아나항공 킹스톤 우드버리아울렛 워싱턴 스미소니언박물관 911메모리얼 프린스턴대학교 뉴욕 시닉터널 몬트리올', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0009', '자유의여신상 워싱턴 킹스톤 제퍼슨기념관 911메모리얼 몬트리올 뉴욕 브루클린브리지 대한항공 여행 우드버리아울렛', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0010', '여행 나이아가라폭포 국회의사당 뉴욕 제퍼슨기념관 워싱턴 프린스턴대학교 해리스버그 스미소니언박물관 몬트리올 아시아나항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0011', '여행 링컨기념관 트리니티교회 나이아가라폭포 브루클린브리지 911메모리얼 대한항공 제퍼슨기념관 월스트리트 워싱턴 뉴욕', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0012', '스미소니언박물관 나이아가라폭포 몬트리올 뉴욕 자유의여신상 트리니티교회 해리스버그 아시아나항공 링컨기념관 여행 워싱턴', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0013', '대한항공 워싱턴 911메모리얼 뉴욕 제퍼슨기념관 백악관 여행 링컨기념관 해리스버그 자유의여신상 국회의사당', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0014', '나이아가라폭포 월스트리트 토론토 국회의사당 프린스턴대학교 아시아나항공 링컨기념관 워싱턴 제퍼슨기념관 여행 뉴욕', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0015', '나이아가라폭포 911메모리얼 대한항공 제퍼슨기념관 킹스톤 여행 월스트리트 토론토 워싱턴 뉴욕 국회의사당', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0016', '나이아가라폭포 제퍼슨기념관 뉴욕 워싱턴 월스트리트 아시아나항공 여행 몬트리올 시닉터널 911메모리얼 해리스버그', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0017', '911메모리얼 뉴욕 트리니티교회 월스트리트 스미소니언박물관 국회의사당 대한항공 워싱턴 백악관 여행 몬트리올', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0018', '뉴욕 몬트리올 여행 911메모리얼 아시아나항공 브루클린브리지 링컨기념관 워싱턴 프린스턴대학교 월스트리트 자유의여신상', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0019', '해리스버그 대한항공 트리니티교회 여행 뉴욕 토론토 워싱턴 브루클린브리지 시닉터널 자유의여신상 링컨기념관', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_MKL_0020', '여행 911메모리얼 아시아나항공 백악관 뉴욕 워싱턴 월스트리트 프린스턴대학교 해리스버그 자유의여신상 시닉터널', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0001', '패키지 9월 여행 2026년 직항 워싱턴 10월 대한항공 여행 노팁', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0002', '10박12일 아시아나항공 9월 여행 패키지 항공권 노쇼핑 가을 미동부 워싱턴', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0003', '뉴욕 여행 미동부 패키지 2026년 항공권 10월 대한항공 7일 노팁', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0004', '워싱턴 노쇼핑 6월 여행 아시아나항공 직항 미국 9월 2026년 미국동부여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0005', '10박12일 9월 미국 노쇼핑 6박8일 미국동부여행 대한항공 항공권 여행 워싱턴', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0006', '직항 노팁 아시아나항공 여행 항공권 8월 6월 뉴욕 노쇼핑 9월', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0007', '7일 가을 9월 여행 노팁 미동부 미국동부여행 대한항공 노옵션 노쇼핑', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0008', '8월 여행 아시아나항공 노팁 노쇼핑 직항 9월 미국 6월 노옵션', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0009', '8박10일 6월 대한항공 뉴욕 노옵션 미국 여행 여행 10박12일 노팁', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0010', '10박12일 8박10일 여행 노팁 7일 직항 패키지 항공권 아시아나항공 미동부', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0011', '미국 여행 노쇼핑 노팁 10박12일 9월 하반기 미동부 노옵션 대한항공', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0012', '8박10일 7월 노옵션 여행 직항 워싱턴 여행 패키지 아시아나항공 하반기', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0013', '여행 하반기 대한항공 6박8일 패키지 항공권 6월 노쇼핑 워싱턴 미국', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0014', '9월 미국 직항 2026년 아시아나항공 노쇼핑 노팁 하반기 여행 패키지', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0015', '뉴욕 가을 7일 여행 패키지 미국 10박12일 대한항공 워싱턴 노쇼핑', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0016', '노쇼핑 여행 직항 하반기 아시아나항공 패키지 가을 노팁 미동부 10월', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0017', '뉴욕 노팁 6월 대한항공 패키지 미국동부여행 9월 노옵션 여행 10월', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0018', '미국동부여행 아시아나항공 9월 노옵션 8월 8박10일 노팁 직항 노쇼핑 여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0019', '하반기 뉴욕 미국 대한항공 여행 6박8일 직항 6월 여행 노옵션', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_DMK_0020', '6박8일 아시아나항공 8월 노옵션 미국 여행 직항 노팁 2026년 미동부', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0001', '자유의여신상 국회의사당 킹스톤 효도관광 워싱턴여행 현지투어 토론토 월스트리트 백악관 몬트리올 여행가기좋은곳 힐링 911메모리얼 미국동부 패키지 스테디셀러 브루클린브리지', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0002', '월스트리트 브루클린브리지 패키지 아이비리그탐방 나이아가라폭포 미동부 우드버리아울렛 힐링 현지투어 국회의사당 조기예약 몬트리올 효도관광 911메모리얼 가족여행 링컨기념관 제퍼슨기념관', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0003', '월스트리트 스미소니언박물관 우드버리아울렛 제퍼슨기념관 패키지 여행가기좋은곳 토론토 효도여행 프린스턴대학교 국회의사당 몬트리올 인천출발 핵심관광 미동부 아이비리그탐방 나이아가라폭포 백악관', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0004', '아이비리그탐방 힐링 토론토 몬트리올 링컨기념관 스테디셀러 인천출발 핵심관광 제퍼슨기념관 커플여행 백악관 효도관광 프린스턴대학교 911메모리얼 킹스톤 월스트리트 나이아가라폭포', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0005', '우드버리아울렛 몬트리올 패키지 현지투어 토론토 백악관 월스트리트 브루클린브리지 효도관광 킹스톤 링컨기념관 자유의여신상 제퍼슨기념관 아이비리그탐방 우정여행 스테디셀러 8대학탐방', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0006', '힐링 킹스톤 노팁관광여행 브루클린브리지 현지투어 토론토 미동부 우드버리아울렛 나이아가라폭포 스테디셀러 효도관광 백악관 조기예약 스미소니언박물관 프린스턴대학교 자유의여신상 여행가기좋은곳', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0007', '월스트리트 핵심관광 미동부 효도관광 스미소니언박물관 제퍼슨기념관 8대학탐방 아이비리그탐방 국회의사당 백악관 힐링 조기예약 우드버리아울렛 패키지 911메모리얼 브루클린브리지 워싱턴여행', 'Washington');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_WT_ML_0008', '우드버리아울렛 가족여행 미동부 월스트리트 킹스톤 링컨기념관 핵심관광 힐링 911메모리얼 효도관광 패키지 브루클린브리지 아이비리그탐방 조기예약 프린스턴대학교 백악관 몬트리올', 'Washington');
