-- City Titles Part 075 (7401-7500번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0013', '몽골 항공권 승마 밤하늘 직항 가격 관광 커플 힐링 양고기 게르 무비자', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0014', '몽골 게르 관광 직항 초원 테렐지 울란바토르 힐링 날씨 커플 밤하늘 가족', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0015', '몽골 힐링 별 날씨 밤하늘 승마 가격 직항 패키지 가족 양고기 관광 초원', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0016', '몽골 가족 커플 관광 밤하늘 양고기 무비자 항공권 게르 날씨 별 여행', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0017', '몽골 여행 별 가족 테렐지 날씨 커플 관광 무비자 울란바토르 가격 게르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0018', '몽골 밤하늘 가격 직항 여행 항공권 초원 울란바토르 무비자 힐링 가족', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0019', '몽골 승마 패키지 직항 관광 양고기 힐링 테렐지 여행 울란바토르 밤하늘', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0020', '몽골 테렐지 여행 무비자 커플 별 패키지 힐링 양고기 밤하늘 가족 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0021', '몽골 가격 패키지 직항 밤하늘 게르 커플 날씨 승마 항공권 별 초원', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0022', '몽골 밤하늘 가족 직항 게르 무비자 울란바토르 초원 가격 승마 별 항공권', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0023', '몽골 직항 별 커플 울란바토르 게르 밤하늘 패키지 가족 양고기 초원', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0024', '몽골 가족 패키지 게르 테렐지 울란바토르 관광 초원 양고기 힐링 승마', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0025', '몽골 항공권 밤하늘 별 여행 초원 가족 가격 게르 날씨 관광 울란바토르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0026', '몽골 밤하늘 커플 게르 별 양고기 패키지 직항 가격 항공권 관광 여행', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0027', '몽골 날씨 양고기 가격 패키지 테렐지 무비자 별 울란바토르 힐링 초원', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0028', '몽골 힐링 날씨 승마 양고기 별 가격 패키지 여행 무비자 직항 게르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0029', '몽골 가격 패키지 힐링 직항 무비자 테렐지 별 밤하늘 울란바토르 여행', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0030', '몽골 무비자 가족 별 울란바토르 힐링 여행 관광 가격 승마 테렐지 패키지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0031', '몽골 게르 날씨 밤하늘 별 울란바토르 관광 항공권 가족 무비자 승마 여행', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0032', '몽골 날씨 무비자 게르 직항 승마 초원 양고기 패키지 별 여행 커플', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0033', '몽골 관광 가격 커플 패키지 항공권 가족 게르 양고기 직항 별 승마 초원', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0034', '몽골 관광 밤하늘 힐링 커플 게르 항공권 직항 테렐지 초원 여행 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0035', '몽골 테렐지 별 무비자 커플 가격 직항 관광 패키지 울란바토르 게르 승마', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0036', '몽골 울란바토르 커플 관광 가족 힐링 승마 항공권 게르 밤하늘 날씨 초원', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0037', '몽골 테렐지 밤하늘 가족 커플 게르 무비자 날씨 관광 승마 양고기', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0038', '몽골 힐링 승마 울란바토르 직항 가족 게르 항공권 양고기 가격 초원 여행', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0039', '몽골 여행 가격 울란바토르 커플 힐링 무비자 테렐지 관광 게르 직항 날씨', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0040', '몽골 초원 게르 항공권 힐링 직항 승마 울란바토르 커플 별 여행 양고기', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0041', '몽골 가격 별 항공권 승마 초원 양고기 무비자 커플 직항 가족 힐링 날씨', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0042', '몽골 양고기 테렐지 커플 울란바토르 승마 힐링 게르 가격 무비자 초원', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0043', '몽골 양고기 가족 승마 패키지 초원 무비자 가격 테렐지 별 힐링 관광', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0044', '몽골 울란바토르 힐링 초원 무비자 패키지 게르 날씨 테렐지 관광 여행', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0045', '몽골 가격 패키지 항공권 여행 별 관광 초원 양고기 직항 테렐지 힐링', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0046', '몽골 테렐지 힐링 별 직항 커플 항공권 무비자 여행 날씨 관광 초원', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0047', '몽골 가격 커플 양고기 힐링 직항 날씨 테렐지 관광 패키지 별 여행', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0048', '몽골 울란바토르 여행 밤하늘 테렐지 관광 패키지 가족 별 힐링 게르 직항', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0049', '몽골 여행 패키지 울란바토르 무비자 힐링 커플 테렐지 항공권 날씨 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0050', '몽골 게르 힐링 직항 테렐지 초원 커플 가격 별 양고기 관광 가족 날씨', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0051', '몽골 게르 테렐지 커플 관광 밤하늘 항공권 승마 양고기 패키지 무비자', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0052', '몽골 날씨 관광 별 밤하늘 무비자 커플 직항 게르 항공권 힐링 패키지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0053', '몽골 날씨 관광 게르 무비자 밤하늘 별 가격 초원 테렐지 승마 양고기', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0054', '몽골 별 테렐지 패키지 날씨 무비자 힐링 양고기 여행 밤하늘 승마 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0055', '몽골 승마 밤하늘 울란바토르 커플 가격 무비자 직항 별 날씨 여행 항공권', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0056', '몽골 초원 항공권 게르 울란바토르 힐링 여행 패키지 별 가격 무비자 가족', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0057', '몽골 밤하늘 양고기 울란바토르 직항 승마 날씨 무비자 가격 패키지 가족', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0058', '몽골 패키지 직항 여행 승마 관광 초원 별 가족 가격 밤하늘 커플 항공권', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0059', '몽골 패키지 무비자 날씨 승마 가격 힐링 직항 게르 항공권 밤하늘 양고기', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_ML_0060', '몽골 무비자 날씨 가족 패키지 양고기 직항 별 초원 밤하늘 여행 테렐지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0001', '11월 힐링 패키지 승마 몽골 항공권 테렐지 직항 관광 여행 게르 별', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0002', '11월 승마 직항 몽골 힐링 2박 4일 게르 가족 테렐지 관광 울란바토르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0003', '11월 항공권 여행 초원 날씨 승마 패키지 직항 무비자 울란바토르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0004', '11월 초원 관광 별 패키지 2박 4일 날씨 테렐지 울란바토르 게르 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0005', '11월 가족 직항 게르 테렐지 몽골 관광 승마 힐링 항공권 무비자', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0006', '11월 커플 승마 게르 초원 날씨 가격 힐링 관광 무비자 테렐지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0007', '11월 힐링 가격 별 게르 승마 초원 몽골 직항 무비자 커플 울란바토르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0008', '11월 힐링 관광 커플 무비자 게르 테렐지 가족 직항 여행 울란바토르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0009', '11월 가족 직항 2박 4일 힐링 울란바토르 커플 승마 항공권 테렐지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0010', '11월 무비자 테렐지 몽골 커플 가족 2박 4일 관광 직항 게르 승마', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0011', '11월 항공권 날씨 관광 패키지 힐링 무비자 여행 몽골 가격 게르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0012', '11월 날씨 가족 가격 테렐지 커플 힐링 울란바토르 여행 직항 무비자', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0013', '11월 테렐지 승마 무비자 2박 4일 가격 날씨 몽골 울란바토르 항공권', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0014', '11월 테렐지 초원 울란바토르 무비자 승마 가격 관광 힐링 2박 4일', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0015', '11월 울란바토르 초원 힐링 커플 직항 게르 몽골 별 테렐지 가격 날씨', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0016', '11월 가족 승마 가격 힐링 여행 2박 4일 항공권 직항 무비자 관광', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0017', '11월 관광 게르 여행 커플 무비자 힐링 2박 4일 초원 승마 직항 별', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0018', '11월 몽골 울란바토르 힐링 직항 별 테렐지 승마 날씨 게르 항공권 커플', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0019', '11월 직항 커플 울란바토르 날씨 2박 4일 가격 여행 승마 패키지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0020', '11월 패키지 여행 승마 커플 관광 별 초원 가족 울란바토르 몽골 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0021', '11월 무비자 테렐지 가족 커플 게르 울란바토르 항공권 초원 가격 몽골', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0022', '11월 별 가족 항공권 승마 가격 직항 무비자 테렐지 날씨 게르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0023', '11월 테렐지 관광 초원 가족 항공권 여행 2박 4일 게르 몽골 패키지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0024', '11월 울란바토르 초원 직항 게르 가격 항공권 여행 패키지 승마 별 가족', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0025', '11월 울란바토르 몽골 승마 관광 2박 4일 직항 커플 테렐지 가족', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0026', '11월 가족 패키지 힐링 커플 2박 4일 게르 테렐지 몽골 울란바토르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0027', '11월 관광 힐링 항공권 2박 4일 직항 패키지 여행 몽골 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0028', '11월 커플 게르 관광 별 초원 항공권 직항 힐링 가족 여행 날씨 몽골', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0029', '11월 무비자 커플 승마 관광 항공권 울란바토르 날씨 직항 가족 몽골', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0030', '11월 초원 승마 가족 가격 테렐지 힐링 게르 관광 커플 날씨 여행 몽골', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0031', '11월 힐링 커플 별 날씨 무비자 울란바토르 패키지 2박 4일 여행 게르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0032', '11월 직항 가격 몽골 별 패키지 힐링 관광 무비자 2박 4일 커플', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0033', '11월 울란바토르 게르 관광 힐링 직항 가격 커플 테렐지 초원 패키지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0034', '11월 여행 힐링 울란바토르 날씨 가격 무비자 패키지 초원 2박 4일', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0035', '11월 게르 승마 힐링 관광 패키지 가족 울란바토르 항공권 직항 가격 별', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0036', '11월 항공권 게르 초원 테렐지 몽골 날씨 무비자 직항 가격 가족 별', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0037', '11월 날씨 패키지 2박 4일 직항 커플 힐링 울란바토르 무비자 게르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0038', '11월 별 커플 여행 몽골 가족 가격 힐링 관광 2박 4일 항공권 승마', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0039', '11월 항공권 가격 몽골 테렐지 여행 승마 2박 4일 게르 가족 무비자', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0040', '11월 항공권 날씨 가격 커플 별 2박 4일 무비자 몽골 울란바토르 여행', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0041', '11월 무비자 커플 테렐지 항공권 승마 2박 4일 가격 날씨 별 힐링', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0042', '11월 몽골 커플 패키지 테렐지 게르 관광 별 힐링 승마 울란바토르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0043', '11월 항공권 가격 무비자 직항 힐링 2박 4일 초원 울란바토르 별', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0044', '11월 가격 패키지 무비자 승마 날씨 2박 4일 별 몽골 여행 힐링 직항', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0045', '11월 패키지 가격 2박 4일 커플 항공권 울란바토르 직항 날씨 여행', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0046', '11월 여행 직항 항공권 초원 가격 커플 승마 패키지 몽골 날씨 관광', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0047', '11월 무비자 승마 몽골 테렐지 초원 관광 게르 패키지 울란바토르 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0048', '11월 관광 울란바토르 2박 4일 초원 커플 테렐지 날씨 가족 여행 게르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0049', '11월 힐링 게르 관광 가족 초원 항공권 가격 패키지 승마 2박 4일', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0050', '11월 가격 항공권 승마 날씨 패키지 무비자 테렐지 몽골 여행 가족 별', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0051', '11월 몽골 힐링 초원 게르 테렐지 무비자 울란바토르 커플 여행 별 날씨', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_MONGO_DML_0052', '11월 항공권 커플 힐링 직항 여행 승마 무비자 패키지 별 가격', 'Ulaanbaatar');
