-- City Titles Part 079 (7801-7900번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0001', '로토루아 체험 뉴질랜드 관광 보라보라섬 여행 홈쇼핑 패키지 투어 허니문 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0002', '로토루아 뉴질랜드 투어 패키지 남북섬 홈쇼핑 보라보라섬 여행 관광 체험 허니문', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0003', '로토루아 체험 패키지 여행 홈쇼핑 남북섬 뉴질랜드 투어 관광 보라보라섬 허니문', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0004', '로토루아 패키지 남북섬 보라보라섬 뉴질랜드 홈쇼핑 관광 체험 여행 허니문 투어', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0005', '로토루아 패키지 관광 허니문 보라보라섬 투어 뉴질랜드 홈쇼핑 여행 남북섬 체험', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0006', '로토루아 뉴질랜드 투어 여행 패키지 체험 관광 홈쇼핑 남북섬 허니문 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0007', '로토루아 뉴질랜드 허니문 체험 관광 여행 패키지 보라보라섬 홈쇼핑 투어 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0008', '로토루아 여행 패키지 남북섬 홈쇼핑 뉴질랜드 투어 관광 체험 보라보라섬 허니문', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0009', '로토루아 보라보라섬 투어 관광 홈쇼핑 허니문 남북섬 여행 체험 패키지 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0010', '로토루아 허니문 홈쇼핑 투어 체험 뉴질랜드 남북섬 보라보라섬 관광 패키지 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0011', '로토루아 패키지 남북섬 투어 보라보라섬 체험 홈쇼핑 허니문 뉴질랜드 관광 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0012', '로토루아 뉴질랜드 홈쇼핑 패키지 보라보라섬 투어 남북섬 관광 허니문 여행 체험', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0013', '로토루아 여행 남북섬 허니문 체험 뉴질랜드 패키지 관광 보라보라섬 홈쇼핑 투어', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0014', '로토루아 뉴질랜드 홈쇼핑 여행 허니문 남북섬 체험 투어 관광 패키지 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0015', '로토루아 보라보라섬 여행 체험 뉴질랜드 허니문 패키지 남북섬 투어 관광 홈쇼핑', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0016', '로토루아 남북섬 뉴질랜드 투어 허니문 여행 관광 보라보라섬 홈쇼핑 패키지 체험', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0017', '로토루아 체험 허니문 뉴질랜드 남북섬 투어 관광 패키지 여행 보라보라섬 홈쇼핑', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0018', '로토루아 투어 홈쇼핑 뉴질랜드 허니문 보라보라섬 패키지 여행 남북섬 체험 관광', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0019', '로토루아 홈쇼핑 관광 투어 뉴질랜드 남북섬 패키지 체험 보라보라섬 여행 허니문', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ML_0020', '로토루아 뉴질랜드 남북섬 투어 여행 보라보라섬 체험 홈쇼핑 허니문 패키지 관광', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0001', '로토루아 패키지 여행 보라보라섬 뉴질랜드 남북섬 09월', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0002', '로토루아 남북섬 09월 보라보라섬 뉴질랜드 패키지 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0003', '로토루아 뉴질랜드 남북섬 보라보라섬 여행 패키지 09월', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0004', '로토루아 남북섬 09월 뉴질랜드 보라보라섬 여행 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0005', '로토루아 09월 패키지 뉴질랜드 보라보라섬 남북섬 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0006', '로토루아 보라보라섬 뉴질랜드 패키지 남북섬 여행 09월', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0007', '로토루아 보라보라섬 여행 뉴질랜드 09월 패키지 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0008', '로토루아 여행 남북섬 뉴질랜드 09월 보라보라섬 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0009', '로토루아 여행 남북섬 보라보라섬 뉴질랜드 패키지 09월', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0010', '로토루아 남북섬 여행 뉴질랜드 보라보라섬 패키지 09월', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0011', '로토루아 패키지 뉴질랜드 여행 09월 남북섬 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0012', '로토루아 보라보라섬 여행 패키지 남북섬 뉴질랜드 09월', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0013', '로토루아 뉴질랜드 남북섬 패키지 보라보라섬 여행 09월', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0014', '로토루아 뉴질랜드 보라보라섬 패키지 09월 여행 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0015', '로토루아 패키지 09월 뉴질랜드 남북섬 보라보라섬 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0016', '로토루아 09월 여행 패키지 보라보라섬 뉴질랜드 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0017', '로토루아 09월 패키지 뉴질랜드 여행 남북섬 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0018', '로토루아 09월 남북섬 여행 보라보라섬 뉴질랜드 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0019', '로토루아 여행 뉴질랜드 보라보라섬 남북섬 패키지 09월', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNK_0020', '로토루아 보라보라섬 패키지 뉴질랜드 09월 여행 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0001', '뉴질랜드 로토루아 여행 패키지 와이토모 동굴 포함', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0002', '로토루아 온천투어 포함 뉴질랜드 패키지여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0003', '뉴질랜드 로토루아 호빗마을 투어 패키지여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0004', '로토루아 마오리 문화체험 포함 뉴질랜드 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0005', '뉴질랜드 로토루아 가족여행 패키지 6박8일', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0006', '대한항공 직항 뉴질랜드 로토루아 패키지 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0007', '뉴질랜드 로토루아 와이토모 반딧불 동굴 투어 포함', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0008', '로토루아 온천스파 자유여행+패키지 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0009', '뉴질랜드 로토루아 시티투어 포함 패키지여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0010', '뉴질랜드 로토루아 와이헤케섬 연계 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0011', '로토루아 호빗마을 + 와이토모 동굴 뉴질랜드 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0012', '뉴질랜드 로토루아 허니문 패키지 여행 추천', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0013', '뉴질랜드 로토루아 남북섬 일주 패키지 9박11일', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0014', '로토루아 뉴질랜드 온천과 골프투어 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0015', '뉴질랜드 로토루아 노팁 노옵션 럭셔리 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0016', '오클랜드 출발 뉴질랜드 로토루아 여행 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0017', '뉴질랜드 로토루아 와이토모 동굴 자유+패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0018', '뉴질랜드 로토루아 자연경관 관광 패키지여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0019', '로토루아 온천 + 마오리쇼 포함 뉴질랜드 여행상품', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_GPT_0020', '뉴질랜드 로토루아 골프 & 와이너리 투어 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0001', '로토루아 패키지 여행 뉴질랜드 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0002', '보라보라섬 패키지 여행 로토루아 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0003', '뉴질랜드 보라보라섬 여행 패키지 로토루아', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0004', '뉴질랜드 로토루아 패키지 보라보라섬 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0005', '여행 보라보라섬 패키지 뉴질랜드 로토루아', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0006', '여행 로토루아 뉴질랜드 패키지 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0007', '패키지 뉴질랜드 로토루아 여행 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0008', '뉴질랜드 패키지 로토루아 보라보라섬 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0009', '로토루아 패키지 뉴질랜드 여행 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0010', '패키지 로토루아 보라보라섬 여행 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0011', '보라보라섬 로토루아 패키지 여행 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0012', '여행 로토루아 패키지 뉴질랜드 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0013', '뉴질랜드 여행 보라보라섬 패키지 로토루아', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0014', '뉴질랜드 보라보라섬 로토루아 여행 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0015', '여행 패키지 뉴질랜드 로토루아 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0016', '뉴질랜드 로토루아 여행 패키지 보라보라섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0017', '보라보라섬 여행 패키지 로토루아 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0018', '보라보라섬 패키지 뉴질랜드 로토루아 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0019', '패키지 로토루아 보라보라섬 뉴질랜드 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_SNM_0020', '로토루아 여행 뉴질랜드 보라보라섬 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0001', '인천출발 남북섬 로토루아 뉴질랜드 패키지 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0002', '인천출발 로토루아 패키지 여행 뉴질랜드 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0003', '인천출발 여행 남북섬 패키지 로토루아 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0004', '인천출발 여행 로토루아 패키지 남북섬 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0005', '인천출발 로토루아 뉴질랜드 패키지 남북섬 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0006', '인천출발 남북섬 패키지 로토루아 여행 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0007', '인천출발 로토루아 뉴질랜드 여행 남북섬 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0008', '인천출발 남북섬 패키지 여행 로토루아 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0009', '인천출발 남북섬 로토루아 여행 뉴질랜드 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0010', '인천출발 여행 로토루아 남북섬 패키지 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0011', '인천출발 남북섬 로토루아 여행 패키지 뉴질랜드', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0012', '인천출발 패키지 여행 뉴질랜드 남북섬 로토루아', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0013', '인천출발 로토루아 뉴질랜드 여행 패키지 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0014', '인천출발 뉴질랜드 여행 로토루아 남북섬 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0015', '인천출발 뉴질랜드 남북섬 로토루아 여행 패키지', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0016', '인천출발 패키지 여행 로토루아 뉴질랜드 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0017', '인천출발 뉴질랜드 패키지 여행 로토루아 남북섬', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0018', '인천출발 뉴질랜드 패키지 여행 남북섬 로토루아', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0019', '인천출발 패키지 남북섬 로토루아 뉴질랜드 여행', 'Rotorua');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_LTL_ICH_0020', '인천출발 여행 남북섬 로토루아 뉴질랜드 패키지', 'Rotorua');
