-- City Titles Part 064 (6301-6400번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0007', '독일 일주 슈바인학세 힐링 항공권 가볼만한곳 가격 중세도시 관광 여행', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0008', '독일 일주 가볼만한곳 맥주 항공권 여행 슈바인학세 미식 관광 패키지', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0009', '독일 가격 여행 직항 겨울 힐링 일주 미식 슈바인학세 비행시간 가볼만한곳', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0010', '독일 일주 관광 가격 직항 맥주 미식 슈바인학세 숙소 중세도시 여행 겨울', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0011', '독일 중세도시 맥주 힐링 가격 항공권 숙소 패키지 미식 유람선 일주 관광', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0012', '독일 비행시간 중세도시 가을 여행 항공권 가볼만한곳 직항 일주 숙소', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0013', '독일 패키지 일주 가격 가볼만한곳 맥주 여행 비행시간 직항 항공권 가을', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0014', '독일 미식 관광 항공권 맥주 힐링 가을 패키지 직항 슈바인학세 숙소', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0015', '독일 항공권 일주 숙소 맥주 패키지 유람선 서유럽 가을 비행시간', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0016', '독일 일주 항공권 유람선 맥주 미식 겨울 슈바인학세 여행 숙소 패키지', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0017', '독일 맥주 직항 서유럽 슈바인학세 일주 미식 가볼만한곳 패키지 힐링', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0018', '독일 중세도시 비행시간 미식 가볼만한곳 관광 숙소 가격 유람선 서유럽', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0019', '독일 중세도시 서유럽 가볼만한곳 힐링 가을 항공권 맥주 일주 미식 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0020', '독일 여행 맥주 미식 직항 숙소 가볼만한곳 비행시간 겨울 힐링 중세도시', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0021', '독일 관광 가볼만한곳 슈바인학세 여행 유람선 중세도시 맥주 패키지 항공권', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0022', '독일 맥주 가격 비행시간 미식 겨울 관광 숙소 슈바인학세 가을 중세도시', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0023', '독일 여행 관광 슈바인학세 미식 비행시간 가을 패키지 유람선 일주 힐링', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0024', '독일 숙소 가을 일주 맥주 힐링 가볼만한곳 슈바인학세 직항 유람선', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0025', '독일 가격 가을 맥주 서유럽 유람선 비행시간 여행 숙소 패키지 겨울', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0026', '독일 맥주 슈바인학세 중세도시 힐링 숙소 서유럽 일주 직항 가을 여행', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0027', '독일 힐링 항공권 가을 직항 여행 유람선 겨울 중세도시 맥주 서유럽 일주', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0028', '독일 숙소 맥주 겨울 슈바인학세 비행시간 서유럽 여행 가볼만한곳 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0029', '독일 비행시간 겨울 숙소 관광 맥주 가격 미식 유람선 서유럽 패키지 직항', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GERMAN_ML_0030', '독일 직항 힐링 유람선 가을 항공권 가격 맥주 겨울 미식 여행 가볼만한곳', 'Germany');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0001', '덴마크 노르웨이 스웨덴 핀란드 관광 발틱 3개국 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0002', '덴마크 노르웨이 스웨덴 핀란드 발틱 3개국 북유럽 일주', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0003', '덴마크 노르웨이 스웨덴 핀란드 북유럽 일주 발틱 3개국', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0004', '덴마크 노르웨이 스웨덴 핀란드 여행 관광 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0005', '덴마크 노르웨이 스웨덴 핀란드 북유럽 일주 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0006', '덴마크 노르웨이 스웨덴 핀란드 패키지 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0007', '덴마크 노르웨이 스웨덴 핀란드 관광 패키지 북유럽 일주', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0008', '덴마크 노르웨이 스웨덴 핀란드 발틱 3개국 패키지 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0009', '덴마크 노르웨이 스웨덴 핀란드 발틱 3개국 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0010', '덴마크 노르웨이 스웨덴 핀란드 패키지 관광 발틱 3개국', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0011', '덴마크 노르웨이 스웨덴 핀란드 북유럽 일주 여행 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0012', '덴마크 노르웨이 스웨덴 핀란드 북유럽 일주 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0013', '덴마크 노르웨이 스웨덴 핀란드 항공권 패키지 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0014', '덴마크 노르웨이 스웨덴 핀란드 북유럽 일주 관광 여행', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0016', '덴마크 노르웨이 스웨덴 핀란드 관광 북유럽 일주 여행', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0018', '덴마크 노르웨이 스웨덴 핀란드 패키지 북유럽 일주 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0020', '덴마크 노르웨이 스웨덴 핀란드 여행 발틱 3개국 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0021', '덴마크 노르웨이 스웨덴 핀란드 항공권 북유럽 일주', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0022', '덴마크 노르웨이 스웨덴 핀란드 북유럽 일주 항공권 여행', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0023', '덴마크 노르웨이 스웨덴 핀란드 패키지 여행 항공권 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0024', '덴마크 노르웨이 스웨덴 핀란드 관광 여행 발틱 3개국', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0025', '덴마크 노르웨이 스웨덴 핀란드 발틱 3개국 여행 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0027', '덴마크 노르웨이 스웨덴 핀란드 여행 패키지 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0028', '덴마크 노르웨이 스웨덴 핀란드 항공권 여행 발틱 3개국', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_CMK_0029', '덴마크 노르웨이 스웨덴 핀란드 여행 패키지 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0001', '덴마크 노르웨이 스웨덴 핀란드 패키지 항공권 두바이왕궁', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0002', '덴마크 노르웨이 스웨덴 핀란드 발틱 3개국 여행 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0003', '덴마크 노르웨이 스웨덴 핀란드 스톡홀름 헬싱키 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0004', '덴마크 노르웨이 스웨덴 핀란드 관광 발틱 3개국 여행', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0005', '덴마크 노르웨이 스웨덴 핀란드 스톡홀름 헬싱키 코펜하겐', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0006', '덴마크 노르웨이 스웨덴 핀란드 스톡홀름 북유럽 일주', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0007', '덴마크 노르웨이 스웨덴 핀란드 패키지 카이로 헬싱키', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0008', '덴마크 노르웨이 스웨덴 핀란드 관광 코펜하겐 헬싱키', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0009', '덴마크 노르웨이 스웨덴 핀란드 두바이왕궁 항공권 헬싱키', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0010', '덴마크 노르웨이 스웨덴 핀란드 헬싱키 코펜하겐 카이로', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0011', '덴마크 노르웨이 스웨덴 핀란드 스톡홀름 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0012', '덴마크 노르웨이 스웨덴 핀란드 항공권 두바이왕궁 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0013', '덴마크 노르웨이 스웨덴 핀란드 발틱 3개국 여행', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0014', '덴마크 노르웨이 스웨덴 핀란드 발틱 3개국 코펜하겐', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0015', '덴마크 노르웨이 스웨덴 핀란드 항공권 카이로', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0016', '덴마크 노르웨이 스웨덴 핀란드 스톡홀름 관광 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0017', '덴마크 노르웨이 스웨덴 핀란드 스톡홀름 코펜하겐 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0018', '덴마크 노르웨이 스웨덴 핀란드 카이로 헬싱키 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0019', '덴마크 노르웨이 스웨덴 핀란드 헬싱키 관광 여행', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0020', '덴마크 노르웨이 스웨덴 핀란드 여행 코펜하겐 스톡홀름', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0021', '덴마크 노르웨이 스웨덴 핀란드 여행 항공권 북유럽 일주', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0022', '덴마크 노르웨이 스웨덴 핀란드 스톡홀름 카이로 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0023', '덴마크 노르웨이 스웨덴 핀란드 항공권 여행 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0024', '덴마크 노르웨이 스웨덴 핀란드 여행 스톡홀름 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0025', '덴마크 노르웨이 스웨덴 핀란드 발틱 3개국 두바이왕궁', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0026', '덴마크 노르웨이 스웨덴 핀란드 관광 패키지 여행', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0027', '덴마크 노르웨이 스웨덴 핀란드 스톡홀름 두바이왕궁 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0028', '덴마크 노르웨이 스웨덴 핀란드 발틱 3개국 관광 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0029', '덴마크 노르웨이 스웨덴 핀란드 여행 두바이왕궁 카이로', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__NORTHEUROPE_MKL_0030', '덴마크 노르웨이 스웨덴 핀란드 헬싱키 여행 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0001', '덴마크 노르웨이 스웨덴 핀란드 겨울철 발틱 3개국 패키지 가볼만한곳 숙소', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0002', '덴마크 노르웨이 스웨덴 핀란드 북유럽 일주 발틱 3개국 숙소 특식 겨울철', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0003', '덴마크 노르웨이 스웨덴 핀란드 특식 숙소 발틱 3개국 항공권 패키지 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0004', '덴마크 노르웨이 스웨덴 핀란드 특식 항공권 북유럽 일주 여행 숙소 겨울철', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0005', '덴마크 노르웨이 스웨덴 핀란드 관광 산악열차 크루즈2박 가을철 힐링', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0006', '덴마크 노르웨이 스웨덴 핀란드 가을철 추석연휴 항공권 힐링 발틱 3개국', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0007', '덴마크 노르웨이 스웨덴 핀란드 힐링 산악열차 항공권 크루즈2박 숙소 여행', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0008', '덴마크 노르웨이 스웨덴 핀란드 겨울철 가볼만한곳 숙소 항공권 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0009', '덴마크 노르웨이 스웨덴 핀란드 힐링 패키지 겨울철 항공권 관광', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0010', '덴마크 노르웨이 스웨덴 핀란드 관광 가볼만한곳 추석연휴 북유럽 일주 특식', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0011', '덴마크 노르웨이 스웨덴 핀란드 북유럽 일주 힐링 여행 크루즈2박 패키지', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0012', '덴마크 노르웨이 스웨덴 핀란드 추석연휴 힐링 발틱 3개국 겨울철 가을철', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0013', '덴마크 노르웨이 스웨덴 핀란드 북유럽 일주 추석연휴 크루즈2박 가볼만한곳', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0014', '덴마크 노르웨이 스웨덴 핀란드 가을철 숙소 패키지 가볼만한곳 항공권', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0015', '덴마크 노르웨이 스웨덴 핀란드 가을철 겨울철 특식 힐링 크루즈2박', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0016', '덴마크 노르웨이 스웨덴 핀란드 숙소 겨울철 패키지 특식 크루즈2박', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0017', '덴마크 노르웨이 스웨덴 핀란드 패키지 추석연휴 항공권 가을철 북유럽 일주', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0018', '덴마크 노르웨이 스웨덴 핀란드 관광 숙소 가볼만한곳 여행 추석연휴', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0019', '덴마크 노르웨이 스웨덴 핀란드 숙소 패키지 겨울철 항공권 특식 여행', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0020', '덴마크 노르웨이 스웨덴 핀란드 겨울철 항공권 가볼만한곳 북유럽 일주 힐링', 'Norway');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_NORTHEUROPE_ML_0021', '덴마크 노르웨이 스웨덴 핀란드 숙소 관광 특식 북유럽 일주 가볼만한곳', 'Norway');
