-- City Titles Part 073 (7201-7300번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0033', '12월 직항 가격 여행 5성급호텔 항공권 특식 계림 발마사지 먹방 커플', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0034', '12월 3박5일 계림 커플 특식 가족 항공권 먹방 패키지 직항 발마사지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0035', '12월 발마사지 가격 무비자 커플 날씨 힐링 관광 5성급호텔 특식 패키지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0036', '12월 여행 관광 5성급호텔 무비자 가족 특식 계림 양삭 먹방 발마사지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0037', '12월 5성급호텔 패키지 직항 가격 여행 중국 먹방 관광 특식 양삭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0038', '12월 여행 계림 특식 가족 항공권 가격 먹방 커플 양삭 패키지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0039', '12월 가격 날씨 먹방 항공권 중국 관광 직항 가족 무비자 커플 발마사지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0040', '12월 양삭 가격 날씨 무비자 먹방 여행 커플 항공권 계림 패키지 특식', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0041', '12월 날씨 여행 계림 중국 커플 항공권 힐링 무비자 패키지 발마사지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0042', '12월 특식 계림 양삭 항공권 날씨 힐링 관광 무비자 패키지 5성급호텔', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0043', '12월 관광 날씨 발마사지 가족 먹방 항공권 중국 3박5일 패키지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0044', '12월 패키지 3박5일 직항 5성급호텔 힐링 양삭 여행 무비자 커플 가족', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0045', '12월 중국 패키지 힐링 양삭 가족 계림 커플 먹방 직항 관광 5성급호텔', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0046', '12월 가족 발마사지 특식 먹방 5성급호텔 3박5일 무비자 가격 날씨', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0047', '12월 5성급호텔 중국 계림 관광 여행 발마사지 커플 항공권 패키지 가족', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0048', '12월 특식 패키지 3박5일 가격 5성급호텔 발마사지 계림 가족 무비자', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0049', '12월 힐링 발마사지 특식 직항 여행 3박5일 패키지 날씨 항공권 가족', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0050', '12월 커플 양삭 관광 먹방 직항 무비자 가족 특식 패키지 발마사지', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0051', '12월 특식 직항 5성급호텔 관광 가격 무비자 커플 여행 힐링 먹방', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0052', '12월 항공권 계림 날씨 패키지 커플 5성급호텔 가격 양삭 힐링 3박5일', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0053', '12월 날씨 계림 직항 관광 특식 가족 발마사지 양삭 5성급호텔 커플', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0054', '12월 5성급호텔 가족 패키지 양삭 힐링 커플 가격 계림 관광 먹방 중국', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0055', '12월 힐링 관광 발마사지 양삭 패키지 무비자 계림 직항 3박5일 특식', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0056', '12월 패키지 먹방 항공권 특식 무비자 관광 커플 양삭 발마사지 중국', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0057', '12월 힐링 양삭 커플 5성급호텔 계림 직항 특식 중국 가격 3박5일', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0058', '12월 양삭 날씨 특식 먹방 5성급호텔 관광 무비자 항공권 커플 중국', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0059', '12월 무비자 중국 먹방 특식 날씨 계림 3박5일 여행 발마사지 직항', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_DML_0060', '12월 5성급호텔 발마사지 힐링 패키지 특식 직항 관광 날씨 무비자 가격', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0001', '여행 북경 장가계 샤먼 하이난 계림 충칭 상하이 백두산', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0002', '여행 샤먼 백두산 충칭 장가계 북경 계림 상하이 하이난', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0003', '여행 백두산 북경 상하이 하이난 계림 충칭 샤먼 장가계', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0004', '여행 하이난 샤먼 북경 계림 상하이 백두산 장가계 충칭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0005', '여행 샤먼 상하이 계림 백두산 하이난 장가계 충칭 북경', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0006', '여행 하이난 충칭 샤먼 장가계 계림 상하이 백두산 북경', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0007', '여행 북경 충칭 하이난 장가계 계림 백두산 샤먼 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0008', '여행 계림 상하이 북경 장가계 충칭 백두산 샤먼 하이난', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0009', '여행 하이난 상하이 백두산 샤먼 충칭 계림 장가계 북경', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0010', '여행 상하이 하이난 샤먼 북경 백두산 충칭 장가계 계림', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0011', '여행 상하이 백두산 충칭 샤먼 하이난 북경 장가계 계림', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0012', '여행 장가계 하이난 북경 계림 샤먼 상하이 백두산 충칭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0013', '여행 백두산 충칭 상하이 계림 하이난 북경 샤먼 장가계', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0014', '여행 하이난 장가계 충칭 상하이 계림 백두산 샤먼 북경', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0015', '여행 장가계 하이난 백두산 상하이 충칭 샤먼 계림 북경', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0016', '여행 충칭 계림 샤먼 장가계 북경 하이난 백두산 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0017', '여행 상하이 장가계 충칭 하이난 샤먼 계림 백두산 북경', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0018', '여행 충칭 하이난 장가계 백두산 북경 계림 샤먼 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0019', '여행 샤먼 계림 충칭 백두산 장가계 북경 상하이 하이난', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0020', '여행 샤먼 장가계 계림 상하이 북경 하이난 충칭 백두산', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0021', '여행 샤먼 백두산 장가계 계림 충칭 하이난 상하이 북경', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0022', '여행 백두산 북경 샤먼 계림 장가계 상하이 하이난 충칭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0023', '여행 백두산 샤먼 북경 충칭 하이난 상하이 계림 장가계', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0024', '여행 샤먼 백두산 계림 북경 장가계 상하이 하이난 충칭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0025', '여행 북경 백두산 충칭 계림 샤먼 하이난 장가계 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0026', '여행 하이난 장가계 샤먼 백두산 충칭 북경 계림 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0027', '여행 하이난 계림 북경 상하이 백두산 샤먼 충칭 장가계', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0028', '여행 북경 하이난 장가계 계림 충칭 상하이 백두산 샤먼', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0029', '여행 백두산 북경 하이난 샤먼 장가계 계림 충칭 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0030', '여행 백두산 북경 장가계 샤먼 충칭 하이난 계림 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0031', '패키지 샤먼 북경 계림 장가계 상하이 하이난 백두산', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0032', '패키지 계림 장가계 북경 상하이 하이난 샤먼 충칭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0033', '패키지 샤먼 계림 장가계 북경 백두산 하이난 충칭', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0034', '패키지 상하이 백두산 북경 계림 장가계 하이난 샤먼', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0035', '패키지 장가계 북경 충칭 하이난 계림 백두산 샤먼', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0036', '패키지 충칭 하이난 샤먼 백두산 장가계 상하이 계림', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0037', '패키지 상하이 계림 북경 하이난 충칭 장가계 백두산', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0038', '패키지 상하이 충칭 하이난 계림 장가계 샤먼 백두산', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0039', '패키지 상하이 충칭 하이난 장가계 백두산 계림 샤먼', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0040', '패키지 상하이 장가계 계림 북경 샤먼 하이난 백두산', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0041', '패키지 하이난 충칭 백두산 계림 샤먼 상하이 북경', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0042', '패키지 하이난 계림 장가계 상하이 백두산 충칭 북경', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0043', '패키지 장가계 샤먼 계림 북경 백두산 상하이 하이난', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0044', '패키지 샤먼 백두산 충칭 하이난 북경 장가계 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0045', '패키지 백두산 계림 충칭 장가계 북경 샤먼 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0046', '패키지 북경 샤먼 장가계 계림 하이난 상하이 백두산', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0047', '패키지 계림 장가계 상하이 북경 하이난 백두산 샤먼', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0048', '패키지 충칭 장가계 샤먼 계림 백두산 북경 하이난', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0049', '패키지 충칭 백두산 계림 샤먼 상하이 북경 장가계', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0050', '패키지 샤먼 장가계 상하이 북경 계림 충칭 백두산', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0051', '패키지 하이난 북경 충칭 샤먼 장가계 백두산 상하이', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0052', '패키지 하이난 백두산 북경 상하이 계림 충칭 샤먼', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0053', '패키지 샤먼 장가계 하이난 백두산 충칭 북경 계림', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0054', '패키지 충칭 상하이 장가계 계림 북경 샤먼 하이난', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0055', '패키지 상하이 하이난 북경 백두산 장가계 샤먼 계림', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0056', '패키지 북경 장가계 샤먼 백두산 하이난 충칭 계림', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0057', '패키지 장가계 하이난 샤먼 충칭 백두산 상하이 계림', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0058', '패키지 상하이 샤먼 장가계 북경 백두산 계림 하이난', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0059', '패키지 상하이 북경 하이난 충칭 샤먼 장가계 백두산', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_GUILIN_NCK_0060', '패키지 계림 상하이 하이난 북경 백두산 장가계 샤먼', 'Guilin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0001', '몽골 직항 무비자 패키지 가격 울란바토르 항공권', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0002', '몽골 테렐지 항공권 무비자 가격 직항 여행 관광', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0003', '몽골 직항 패키지 무비자 여행 테렐지 날씨 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0004', '몽골 항공권 여행 울란바토르 직항 패키지 날씨 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0005', '몽골 무비자 테렐지 관광 여행 울란바토르 패키지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0006', '몽골 날씨 패키지 테렐지 무비자 여행 울란바토르', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0007', '몽골 관광 여행 항공권 테렐지 패키지 가격 날씨', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0008', '몽골 관광 여행 무비자 울란바토르 항공권 날씨', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0009', '몽골 여행 가격 날씨 항공권 직항 무비자 패키지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0010', '몽골 여행 가격 패키지 무비자 직항 날씨 테렐지', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0011', '몽골 울란바토르 날씨 직항 여행 항공권 무비자 가격', 'Ulaanbaatar');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MONGO_CMK_0012', '몽골 가격 직항 관광 여행 무비자 날씨 패키지', 'Ulaanbaatar');
