-- City Titles Part 013 (1201-1300번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0013', '라스베이거스 프리몬트스트리트 미라지화산쇼 벨라지오분수쇼 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0014', '라스베이거스 카지노 스트립 스트래토스피어타워 투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0015', '라스베이거스 벨라지오분수쇼 하이롤러 미라지화산쇼 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0016', '라스베이거스 스트립 프리몬트스트리트 벨라지오분수쇼 투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0017', '라스베이거스 스트립 카지노 벨라지오분수쇼 패키지', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0018', '라스베이거스 스트립 스트래토스피어타워 미라지화산쇼 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0019', '라스베이거스 프리몬트스트리트 스트립 벨라지오분수쇼 투어', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_GPT_0020', '라스베이거스 카지노 벨라지오분수쇼 미라지화산쇼 패키지', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0001', '뉴욕 패키지 여행 미국동부여행 미동부 노팁 노옵션 노쇼핑 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0002', '미국 뉴욕 여행 패키지 미동부 미국동부여행 국적기 대한항공 아시아나항공 직항 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0003', '캐나다 미국 뉴욕 여행 패키지 미동부 노팁 노옵션 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0004', '뉴욕 여행 패키지 미국동부여행 캐나다 미동부 항공권 대한항공 아시아나항공 직항', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0005', '미국 뉴욕 여행 패키지 미동부 노쇼핑 노팁 노옵션 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0006', '뉴욕 패키지 여행 미국 캐나다 미동부 미국동부여행 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0007', '뉴욕 여행 패키지 미동부 노팁 노옵션 노쇼핑 미국동부여행 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0008', '미국 뉴욕 패키지 여행 미동부 캐나다 노팁 노옵션 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0009', '뉴욕 여행 패키지 미국동부여행 미동부 항공권 대한항공 아시아나항공 인천출발 직항', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0010', '캐나다 미국 뉴욕 여행 패키지 미동부 노쇼핑 노옵션 노팁 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0011', '뉴욕 패키지 여행 미국 미동부 미국동부여행 항공권 대한항공 아시아나항공 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0012', '미국 뉴욕 여행 패키지 미동부 캐나다 미국동부여행 국적기 대한항공 아시아나항공 직항', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0013', '뉴욕 여행 패키지 미동부 미국동부여행 캐나다 항공권 대한항공 아시아나항공 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0014', '미국 뉴욕 패키지 여행 캐나다 미동부 노팁 노옵션 노쇼핑 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0015', '뉴욕 여행 패키지 미국동부여행 미동부 노팁 노옵션 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0016', '캐나다 미국 뉴욕 패키지 여행 미동부 노쇼핑 항공권 대한항공 아시아나항공 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0017', '뉴욕 여행 패키지 미국 미동부 미국동부여행 노옵션 항공권 대한항공 아시아나항공 직항', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0018', '뉴욕 패키지 여행 캐나다 미동부 노팁 노옵션 항공권 대한항공 아시아나항공 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0019', '미국 뉴욕 여행 패키지 미동부 미국동부여행 노팁 노쇼핑 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_CMK_0020', '뉴욕 패키지 여행 미국동부여행 캐나다 미동부 항공권 대한항공 아시아나항공 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0001', '덤보 윌리엄스버그 브루클린브리지 베슬 엣지전망대 뉴욕여행 패키지 국적기 대한항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0002', '뉴욕 자유의여신상 오페라의유령 록펠러등대 모마미술관 미국동부여행 패키지 항공권', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0003', '브루클린브리지 윌리엄스버그 덤보 베슬 엣지전망대 뉴욕여행 패키지 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0004', '뉴욕 자유의여신상 월스트리트 모마미술관 오페라의유령 미국동부여행 패키지 국적기', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0005', '베슬 엣지전망대 브루클린브리지 덤보 윌리엄스버그 뉴욕여행 패키지 국적기 대한항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0006', '뉴욕 자유의여신상 록펠러등대 모마미술관 오페라의유령 여행 패키지 항공권 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0007', '브루클린브리지 덤보 윌리엄스버그 베슬 엣지전망대 뉴욕여행 패키지 국적기 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0008', '뉴욕 자유의여신상 월스트리트 오페라의유령 록펠러등대 미동부여행 패키지 국적기', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0009', '베슬 엣지전망대 덤보 윌리엄스버그 브루클린브리지 뉴욕 패키지 여행 항공권', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0010', '뉴욕 자유의여신상 모마미술관 오페라의유령 록펠러등대 패키지 여행 항공권 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0011', '덤보 윌리엄스버그 브루클린브리지 베슬 엣지전망대 뉴욕여행 미동부 패키지 국적기', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0012', '뉴욕 자유의여신상 오페라의유령 록펠러등대 월스트리트 패키지 여행 항공권', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0013', '브루클린브리지 덤보 윌리엄스버그 베슬 뉴욕여행 패키지 아시아나항공 국적기', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0014', '뉴욕 모마미술관 오페라의유령 자유의여신상 록펠러등대 패키지 여행 항공권', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0015', '덤보 브루클린브리지 윌리엄스버그 베슬 뉴욕여행 패키지 국적기 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0016', '뉴욕 자유의여신상 월스트리트 록펠러등대 오페라의유령 패키지 여행 국적기', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0017', '브루클린브리지 덤보 윌리엄스버그 베슬 뉴욕여행 패키지 국적기 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0018', '뉴욕 자유의여신상 오페라의유령 모마미술관 록펠러등대 패키지 여행 국적기', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0019', '덤보 윌리엄스버그 브루클린브리지 베슬 뉴욕여행 패키지 아시아나항공 국적기', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_MKL_0020', '뉴욕 자유의여신상 록펠러등대 모마미술관 오페라의유령 여행 패키지 국적기', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0001', '뉴욕 여행 8박10일 2026년 가을 미국동부여행 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0002', '미국 뉴욕 6박8일 6월 여행 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0003', '뉴욕 패키지여행 10박12일 7월 미국동부여행 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0004', '뉴욕 여행 7일여정 2026년 8월 패키지 국적기 대한항공 아시아나항공 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0005', '미국 뉴욕 6박8일 2025년 9월 여행 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0006', '뉴욕 패키지여행 10박12일 2025년 10월 미국동부여행 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0007', '뉴욕 여행 8박10일 2026년 상반기 미동부 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0008', '미국 뉴욕 6박8일 2026년 하반기 여행 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0009', '뉴욕 여행 10박12일 2025년 하반기 미국동부여행 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0010', '뉴욕 여행 7일 2026년 상반기 패키지 국적기 대한항공 아시아나항공 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0011', '뉴욕 패키지여행 8박10일 2026년 6월 미국동부여행 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0012', '미국 뉴욕 6박8일 하반기 여행 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0013', '뉴욕 여행 10박12일 2026년 하반기 미동부 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0014', '뉴욕 패키지여행 8박10일 7월 미국동부여행 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0015', '뉴욕 여행 6박8일 2025년 10월 미동부 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0016', '미국 뉴욕 8박10일 2026년 가을 여행 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0017', '뉴욕 패키지여행 10박12일 2026년 상반기 미국동부여행 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0018', '뉴욕 여행 6박8일 2026년 8월 미동부 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0019', '뉴욕 패키지여행 8박10일 2025년 9월 미국동부여행 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_DMK_0020', '뉴욕 여행 7일 2025년 6월 미동부 패키지 국적기 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0001', '뉴욕여행 미국동부 핵심일정 우드버리아울렛 럭셔리 상품 미서부관광 3대캐년 크루즈 올랜도 나이아가라크루즈 메트로폴리탄 코스 현지투어 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0002', '가족여행 뉴욕 미국동부 핵심일정 우드버리아울렛 미서부관광 3대캐년 크루즈 올랜도 나이아가라크루즈 메트로폴리탄 코스 현지투어 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0003', '뉴욕 미동부 핵심일정 효도여행 우드버리아울렛 럭셔리 상품 미서부관광 3대캐년 크루즈 올랜도 나이아가라크루즈 메트로폴리탄 코스 현지투어 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0004', '뉴욕 미국동부 핵심일정 우드버리아울렛 럭셔리 상품 미서부관광 3대캐년 크루즈 올랜도 나이아가라크루즈 메트로폴리탄 코스 커플여행 현지투어 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0005', '뉴욕여행 미동부 미국동부 핵심일정 우드버리아울렛 럭셔리 상품 크루즈 올랜도 나이아가라크루즈 메트로폴리탄 현지투어 패키지 코스 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0006', '뉴욕 핵심일정 우드버리아울렛 럭셔리 상품 가족여행 미서부관광 올랜도 3대캐년 크루즈 메트로폴리탄 코스 현지투어 나이아가라크루즈 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0007', '뉴욕 미국동부 우드버리아울렛 럭셔리 상품 핵심일정 미서부관광 크루즈 올랜도 메트로폴리탄 나이아가라크루즈 코스 효도여행 현지투어 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0008', '뉴욕 미동부 핵심일정 우드버리아울렛 미서부관광 크루즈 올랜도 메트로폴리탄 3대캐년 코스 커플여행 현지투어 나이아가라크루즈 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0009', '뉴욕여행 미국동부 미동부 핵심일정 우드버리아울렛 럭셔리 상품 나이아가라크루즈 올랜도 메트로폴리탄 크루즈 현지투어 코스 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0010', '가족여행 뉴욕 핵심일정 미국동부 우드버리아울렛 럭셔리 상품 올랜도 메트로폴리탄 미서부관광 3대캐년 현지투어 나이아가라크루즈 코스 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0011', '효도여행 뉴욕 미동부 미국동부 핵심일정 우드버리아울렛 럭셔리 상품 올랜도 메트로폴리탄 나이아가라크루즈 현지투어 코스 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0012', '뉴욕 핵심일정 미국동부 미동부 커플여행 우드버리아울렛 럭셔리 상품 올랜도 메트로폴리탄 나이아가라크루즈 현지투어 코스 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0013', '뉴욕여행 미동부 미국동부 핵심일정 우드버리아울렛 럭셔리 상품 미서부관광 올랜도 메트로폴리탄 3대캐년 나이아가라크루즈 코스 현지투어 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0014', '뉴욕 미국동부 미동부 핵심일정 우드버리아울렛 럭셔리 상품 올랜도 크루즈 메트로폴리탄 나이아가라크루즈 코스 현지투어 가족여행 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0015', '뉴욕 핵심일정 미국동부 미동부 우드버리아울렛 럭셔리 상품 크루즈 올랜도 메트로폴리탄 나이아가라크루즈 코스 효도여행 현지투어 미서부관광 3대캐년 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0016', '뉴욕 미동부 핵심일정 우드버리아울렛 럭셔리 상품 미국동부 올랜도 메트로폴리탄 나이아가라 커플여행 현지투어 코스 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0017', '뉴욕여행 미국동부 미동부 핵심일정 우드버리아울렛 럭셔리 상품 올랜도 나이아가라크루즈 메트로폴리탄 코스 현지투어 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0018', '뉴욕 미동부 핵심일정 미국동부 우드버리아울렛 럭셔리 상품 올랜도 나이아가라크루즈 가족여행 메트로폴리탄 현지투어 코스 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0019', '뉴욕 핵심일정 미국동부 미동부 우드버리아울렛 럭셔리 상품 미서부관광 효도여행 크루즈 올랜도 3대캐년 메트로폴리탄 나이아가라크루즈 현지투어 코스 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_ML_0020', '뉴욕 미동부 핵심일정 커플여행 미국동부 우드버리아울렛 럭셔리 상품 크루즈 올랜도 메트로폴리탄 나이아가라크루즈 코스 현지투어 패키지 인천출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0001', '미동부 현지투어 뉴욕 자유 여행 미국 6박8일 항공권 포함 패키지 캐나다여행 여행코스 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0002', '뉴욕 미동부 여행 미국 현지투어 자유 항공권 포함 패키지 6박8일 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0003', '미국 뉴욕 미동부 여행 패키지 현지투어 자유 항공권 포함 6박8일 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0004', '뉴욕 여행 미국 미동부 현지투어 자유 항공권 포함 패키지 캐나다여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0005', '미동부 미국 뉴욕 여행 패키지 현지투어 자유 항공권 포함 6박8일 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0007', '미국 뉴욕 여행 패키지 미동부 현지투어 자유 항공권 포함 6박8일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0008', '뉴욕 여행 미동부 패키지 미국 현지투어 자유 항공권 포함 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0009', '미동부 뉴욕 여행 미국 패키지 현지투어 자유 항공권 포함 6박8일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0010', '뉴욕 미국 미동부 여행 패키지 현지투어 자유 항공권 포함 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0011', '미국 뉴욕 패키지 여행 미동부 현지투어 자유 항공권 포함 6박8일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0012', '뉴욕 여행 미동부 미국 패키지 현지투어 자유 항공권 포함 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0013', '미동부 여행 뉴욕 미국 패키지 현지투어 자유 항공권 포함 6박8일', 'NewYork');
