-- City Titles Part 014 (1301-1400번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0014', '뉴욕 패키지 여행 미국 미동부 현지투어 자유 항공권 포함 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0015', '미국 뉴욕 여행 미동부 패키지 현지투어 자유 항공권 포함 6박8일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0017', '미동부 뉴욕 미국 여행 패키지 현지투어 자유 항공권 포함 6박8일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0018', '뉴욕 패키지 미국 미동부 여행 현지투어 자유 항공권 포함 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0019', '미국 미동부 뉴욕 여행 패키지 현지투어 자유 항공권 포함 6박8일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_SNK_0020', '뉴욕 여행 미국 미동부 패키지 현지투어 자유 항공권 포함 8박10일', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0001', '뉴역 패키지 여행 케나다 미국 미둥부여행 노팁 노옵션 노쇼핑 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0002', '미국 뉴욕 패키지 여행 미둥부 케나다 항공권 대한항공 아시아나항공 직항 인촌출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0003', '케나다 뉴욕 여행 패키지 미동부 노팁 노옵션 항공권 대한항공 아시아나항공 인천츨발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0004', '뉴욕 여행 패키지 미국동부여행 케나다 미동부 항공권 대한항공 아시아나항공 인촌출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0005', '미국 뉴욕 여행 패키지 미둥부 노쇼핑 노팁 노옵션 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0006', '뉴역 패키지 여행 미국 케나다 미동부 미국동부여행 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0007', '뉴욕 패키지 여행 미동부 노팁 노옵션 노쇼핑 미국동부여행 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0008', '미국 뉴욕 여행 패키지 미둥부 케나다 항공권 대한항공 아시아나항공 인촌출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0009', '뉴욕 패키지 여행 미국동부여행 미동부 항공권 대한항공 아시아나항공 인천츨발 직항', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0010', '케나다 미국 뉴욕 여행 패키지 미동부 노쇼핑 노옵션 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0011', '뉴역 패키지 여행 미국 미동부 미국동부여행 항공권 대한항공 아시아나항공 인촌출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0012', '미국 뉴욕 여행 패키지 미둥부 케나다 미국동부여행 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0013', '뉴욕 여행 패키지 미동부 미국동부여행 케나다 항공권 대한항공 아시아나항공 인천츨발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0014', '미국 뉴역 패키지 여행 케나다 미동부 노팁 노옵션 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0015', '뉴욕 여행 패키지 미국동부여행 미둥부 항공권 대한항공 아시아나항공 인촌출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0016', '케나다 뉴욕 여행 패키지 미동부 미국동부여행 노쇼핑 항공권 대한항공 아시아나항공', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0017', '뉴역 패키지 여행 미국 미둥부 미국동부여행 항공권 대한항공 아시아나항공 인천츨발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0018', '미국 뉴욕 패키지 여행 케나다 미동부 항공권 대한항공 아시아나항공 직항 인촌출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0019', '뉴욕 여행 패키지 미동부 케나다 미국동부여행 항공권 대한항공 아시아나항공 인천츨발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_OT_0020', '케나다 뉴욕 패키지 여행 미국 미둥부 항공권 대한항공 아시아나항공 인촌출발', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0001', '뉴욕 자유의여신상 브루클린브리지 타임스퀘어 엣지전망대 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0002', '뉴욕 패키지 투어 브로드웨이 오페라의유령 엣지전망대 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0003', '뉴욕 자유의여신상 브루클린브리지 엠파이어스테이트 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0004', '뉴욕 덤보 윌리엄스버그 브루클린브리지 패키지 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0005', '뉴욕 엣지전망대 베슬 모마미술관 패키지 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0006', '뉴욕 자유의여신상 록펠러센터 브루클린브리지 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0007', '뉴욕 브로드웨이 오페라의유령 엠파이어스테이트 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0008', '뉴욕 브루클린브리지 자유의여신상 월스트리트 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0009', '뉴욕 엠파이어스테이트 자유의여신상 덤보 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0010', '뉴욕 베슬 엣지전망대 브루클린브리지 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0011', '뉴욕 모마미술관 브루클린브리지 자유의여신상 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0012', '뉴욕 록펠러센터 자유의여신상 브로드웨이 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0013', '뉴욕 오페라의유령 엣지전망대 브루클린브리지 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0014', '뉴욕 브루클린브리지 자유의여신상 패키지 투어', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0015', '뉴욕 자유의여신상 타임스퀘어 브루클린브리지 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0016', '뉴욕 덤보 윌리엄스버그 자유의여신상 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0017', '뉴욕 베슬 브루클린브리지 엣지전망대 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0018', '뉴욕 브루클린브리지 자유의여신상 투어 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0019', '뉴욕 록펠러센터 자유의여신상 모마미술관 여행', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_NY_GPT_0020', '뉴욕 엣지전망대 브루클린브리지 자유의여신상 패키지', 'NewYork');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0001', '여행 패키지 캐나다 밴쿠버 로키산맥 국적기 대한항공 아시아나항공 항공권 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0002', '캐나다여행 밴쿠버 패키지 로키산맥 밴프 국적기 대한항공 아시아나항공 직항', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0003', '패키지 여행 캐나다 밴쿠버 로키산맥 미동부 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0004', '밴쿠버 여행 패키지 캐나다 로키산맥 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0005', '여행 캐나다 패키지 밴쿠버 로키산맥 항공권 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0006', '캐나다 밴쿠버 패키지 여행 로키산맥 밴프 국적기 대한항공 아시아나항공 직항', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0007', '패키지 캐나다여행 밴쿠버 로키산맥 항공권 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0008', '밴쿠버 캐나다여행 패키지 로키산맥 밴프 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0009', '여행 패키지 캐나다 밴쿠버 로키산맥 국적기 대한항공 아시아나항공 직항', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0011', '패키지 여행 캐나다 밴쿠버 로키산맥 밴프 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0012', '여행 캐나다 밴쿠버 패키지 로키산맥 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0013', '밴쿠버 캐나다 패키지 여행 로키산맥 항공권 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0014', '캐나다여행 패키지 밴쿠버 로키산맥 국적기 대한항공 아시아나항공 직항', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0015', '여행 패키지 밴쿠버 캐나다 로키산맥 국적기 대한항공 아시아나항공 항공권', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0016', '패키지 캐나다 밴쿠버 여행 로키산맥 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0017', '밴쿠버 캐나다여행 패키지 로키산맥 항공권 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0018', '여행 캐나다 밴쿠버 패키지 로키산맥 국적기 대한항공 아시아나항공 항공권', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0019', '캐나다여행 밴쿠버 패키지 여행 로키산맥 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_CMK_0020', '패키지 여행 캐나다 밴쿠버 로키산맥 국적기 대한항공 아시아나항공 직항', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0001', '밴프 로키산맥 밴쿠버박물관 나이아가라 투잭호수 캐나다여행 패키지 국적기', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0002', '밴쿠버 로키산맥 밴프 나이아가라 투잭호수 여행 패키지 국적기 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0003', '로키산맥 밴프 밴쿠버박물관 나이아가라 투잭호수 캐나다 패키지 여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0004', '밴쿠버 로키산맥 밴프 나이아가라 밴쿠버박물관 캐나다여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0005', '밴프 나이아가라 로키산맥 투잭호수 밴쿠버박물관 여행 캐나다 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0006', '밴쿠버 로키산맥 밴프 투잭호수 나이아가라 캐나다여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0007', '밴쿠버 로키산맥 밴프 밴쿠버박물관 나이아가라 여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0008', '밴프 나이아가라 투잭호수 밴쿠버박물관 로키산맥 캐나다 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0009', '밴쿠버 로키산맥 밴프 투잭호수 밴쿠버박물관 캐나다여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0010', '나이아가라 밴프 로키산맥 밴쿠버박물관 투잭호수 여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0011', '밴쿠버 로키산맥 밴프 나이아가라 밴쿠버박물관 캐나다 여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0012', '밴프 로키산맥 투잭호수 밴쿠버박물관 나이아가라 캐나다 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0013', '밴쿠버 로키산맥 밴프 나이아가라 투잭호수 여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0014', '밴프 로키산맥 나이아가라 밴쿠버박물관 투잭호수 캐나다 여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0015', '밴쿠버 로키산맥 밴프 투잭호수 나이아가라 여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0016', '밴프 로키산맥 나이아가라 밴쿠버박물관 투잭호수 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0017', '밴쿠버 로키산맥 밴프 나이아가라 밴쿠버박물관 여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0018', '밴프 로키산맥 밴쿠버박물관 투잭호수 나이아가라 캐나다여행', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0019', '밴쿠버 로키산맥 밴프 나이아가라 투잭호수 캐나다여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_MKL_0020', '밴프 나이아가라 로키산맥 밴쿠버박물관 투잭호수 여행 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0001', '밴쿠버 캐나다여행 8박10일 2026년 가을 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0002', '밴프 밴쿠버 6박8일 7월 캐나다여행 국적기 대한항공 아시아나항공 패키지', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0003', '밴쿠버 캐나다 10박12일 9월 여행 패키지 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0004', '밴프 밴쿠버 8박10일 2025년 하반기 여행 캐나다 패키지 국적기', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0005', '밴쿠버 6월 7일 여행 캐나다 패키지 국적기 대한항공 아시아나항공 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0006', '밴쿠버 7월 8박 캐나다여행 패키지 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0007', '밴프 밴쿠버 8월 10박12일 여행 캐나다 패키지 국적기 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0008', '밴쿠버 9월 6박8일 캐나다여행 패키지 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0009', '밴프 밴쿠버 10월 7일 여행 캐나다 패키지 국적기 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0010', '밴쿠버 2026년 하반기 8박10일 캐나다여행 패키지 국적기 대한항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0011', '밴프 밴쿠버 2026년 상반기 6박8일 캐나다 여행 패키지 국적기', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0012', '밴쿠버 10박12일 가을 캐나다여행 패키지 국적기 대한항공 아시아나항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0013', '밴프 밴쿠버 8박10일 6월 캐나다 여행 패키지 국적기 인천출발', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0014', '밴쿠버 7월 10박12일 여행 캐나다 패키지 국적기 대한항공', 'Vancouver');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_VC_DMK_0015', '밴프 밴쿠버 9월 7일 여행 캐나다 패키지 국적기 아시아나항공', 'Vancouver');
