-- City Titles Part 028 (2701-2800번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_02', '푸껫 패키지 마사지 쇼핑 호텔 날씨 빅부다 빠통비치 여행 태국 숙소', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_03', '푸껫 빅부다 여행 날씨 패키지 항공권 빠통비치 숙소 쇼핑 호텔 마사지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_04', '푸껫 빅부다 쇼핑 태국 마사지 날씨 왓찰롱 숙소 항공권 호텔 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_05', '푸껫 항공권 태국 쇼핑 숙소 패키지 마사지 여행 빠통비치 호텔 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_06', '푸껫 패키지 호텔 빅부다 날씨 항공권 태국 빠통비치 마사지 숙소 왓찰롱', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_07', '푸껫 태국 패키지 날씨 빅부다 왓찰롱 항공권 여행 빠통비치 호텔 마사지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_08', '푸껫 마사지 숙소 여행 항공권 빅부다 호텔 왓찰롱 패키지 날씨 태국 쇼핑', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_09', '푸껫 패키지 호텔 왓찰롱 쇼핑 날씨 여행 빠통비치 빅부다 마사지 숙소', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_10', '푸껫 날씨 태국 마사지 쇼핑 왓찰롱 패키지 호텔 숙소 여행 빠통비치', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_11', '푸껫 쇼핑 왓찰롱 빠통비치 마사지 호텔 태국 패키지 빅부다 항공권 여행', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_12', '푸껫 마사지 호텔 항공권 숙소 패키지 날씨 쇼핑 빅부다 태국 빠통비치', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_13', '푸껫 패키지 마사지 여행 날씨 빠통비치 빅부다 항공권 왓찰롱 태국 쇼핑', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_14', '푸껫 항공권 마사지 날씨 패키지 왓찰롱 여행 빅부다 빠통비치 쇼핑 숙소', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_15', '푸껫 빅부다 태국 마사지 빠통비치 숙소 패키지 항공권 호텔 여행 쇼핑', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_16', '푸껫 쇼핑 태국 항공권 빅부다 여행 빠통비치 호텔 숙소 날씨 마사지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_17', '푸껫 숙소 쇼핑 태국 왓찰롱 여행 빠통비치 호텔 날씨 항공권 빅부다', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_18', '푸껫 숙소 빠통비치 빅부다 왓찰롱 마사지 여행 패키지 항공권 호텔 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_19', '푸껫 호텔 날씨 여행 패키지 쇼핑 태국 빠통비치 마사지 왓찰롱 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_20', '푸껫 빠통비치 쇼핑 숙소 왓찰롱 호텔 빅부다 날씨 항공권 여행 마사지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_01', '푸껫 허니문 디저트 쇼핑 패키지 항공권 호텔 요트 여행지 직항 해외 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_02', '푸껫 패키지 호핑투어 마사지 에어텔 여행 태국 요트 여행지 숙소 쇼핑', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_03', '푸껫 숙소 호핑투어 마사지 리조트 여행지 태국 디저트 쇼핑 항공권 해외', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_04', '푸껫 에어텔 마사지 요트 해외 호핑투어 태국 날씨 허니문 항공권 호텔', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_05', '푸껫 여행 직항 여행지 허니문 야시장 항공권 해외 마사지 리조트 에어텔', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_06', '푸껫 마사지 에어텔 호핑투어 날씨 여행지 해외 야시장 디저트 패키지 요트', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_07', '푸껫 호핑투어 요트 숙소 해외 마사지 쇼핑 직항 날씨 허니문 호텔 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_08', '푸껫 직항 여행 야시장 디저트 쇼핑 호텔 에어텔 마사지 여행지 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_09', '푸껫 요트 디저트 허니문 날씨 여행 호핑투어 마사지 호텔 해외 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_10', '푸껫 요트 숙소 리조트 호텔 에어텔 여행 태국 마사지 해외 호핑투어', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_11', '푸껫 태국 호텔 허니문 날씨 마사지 야시장 숙소 패키지 쇼핑 호핑투어', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_12', '푸껫 허니문 리조트 요트 디저트 마사지 날씨 항공권 야시장 태국 호핑투어', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_13', '푸껫 날씨 항공권 여행 해외 야시장 호핑투어 패키지 리조트 에어텔 직항', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_14', '푸껫 에어텔 마사지 야시장 패키지 항공권 요트 호핑투어 여행지 직항', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_15', '푸껫 호텔 디저트 쇼핑 리조트 마사지 숙소 허니문 패키지 호핑투어 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_16', '푸껫 해외 디저트 허니문 여행 에어텔 항공권 야시장 호텔 쇼핑 호핑투어', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_17', '푸껫 여행 패키지 날씨 마사지 호핑투어 해외 태국 직항 항공권 쇼핑', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_18', '푸껫 해외 디저트 날씨 에어텔 숙소 호텔 태국 여행 직항 항공권 리조트', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_19', '푸껫 항공권 호핑투어 리조트 여행 호텔 허니문 숙소 에어텔 디저트 쇼핑', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_20', '푸껫 숙소 여행 허니문 항공권 직항 날씨 요트 쇼핑 해외 리조트 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_01', '태국 요트 숙소 직항 에어텔 푸껫 여행지 패키지 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_02', '태국 호텔 항공권 에어텔 숙소 디저트 태국 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_03', '태국 디저트 패키지 쇼핑 날씨 여행 항공권 여행지 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_04', '태국 항공권 요트 여행 푸껫 해외 허니문 직항 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_05', '태국 푸껫 호텔 여행지 패키지 해외 쇼핑 여행 마사지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_06', '태국 디저트 패키지 항공권 리조트 해외 호텔 숙소', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_07', '태국 마사지 쇼핑 디저트 에어텔 리조트 해외 푸껫', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_08', '태국 디저트 태국 항공권 마사지 날씨 숙소 패키지 푸껫', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_09', '태국 리조트 항공권 디저트 허니문 요트 쇼핑 푸껫 숙소', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_10', '태국 해외 여행지 에어텔 날씨 패키지 직항 푸껫 리조트', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_11', '태국 쇼핑 요트 에어텔 숙소 여행지 직항 허니문 여행', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_12', '태국 해외 패키지 디저트 태국 숙소 쇼핑 여행지 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_13', '태국 리조트 요트 항공권 날씨 숙소 직항 태국 에어텔', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_14', '태국 쇼핑 항공권 에어텔 호텔 패키지 패키지 푸껫 여행', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_15', '태국 패키지 요트 쇼핑 날씨 태국 디저트 에어텔 여행지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_16', '태국 리조트 허니문 여행 쇼핑 요트 에어텔 여행지 호텔', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_17', '태국 호텔 해외 날씨 직항 쇼핑 숙소 요트 태국 에어텔', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_18', '태국 직항 쇼핑 허니문 마사지 요트 숙소 패키지 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_19', '태국 디저트 직항 쇼핑 리조트 요트 여행 해외 허니문', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_20', '태국 에어텔 호텔 여행 요트 태국 패키지 마사지 해외', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_01', '태국 패키지 여행지 날씨 푸껫 쇼핑 요트 에어텔 디저트 리조트 허니문', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_02', '태국 해외 요트 직항 디저트 항공권 푸껫 허니문 숙소 패키지 태국 호텔', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_03', '태국 해외 디저트 리조트 직항 숙소 패키지 마사지 호텔 항공권 푸껫', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_04', '태국 태국 허니문 여행지 항공권 요트 쇼핑 디저트 호텔 해외 푸껫 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_05', '태국 해외 숙소 디저트 날씨 여행지 요트 리조트 패키지 호텔 직항 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_06', '태국 직항 에어텔 태국 날씨 패키지 쇼핑 허니문 여행 숙소 항공권 해외', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_07', '태국 허니문 패키지 태국 에어텔 푸껫 요트 날씨 직항 쇼핑 마사지 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_08', '태국 에어텔 푸껫 항공권 패키지 숙소 날씨 여행 디저트 패키지 허니문', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_09', '태국 패키지 쇼핑 호텔 태국 에어텔 숙소 해외 항공권 요트 여행 여행지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_10', '태국 항공권 호텔 에어텔 여행 리조트 숙소 날씨 패키지 허니문 직항', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_11', '태국 날씨 여행 항공권 여행지 푸껫 숙소 마사지 허니문 디저트 요트 쇼핑', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_12', '태국 태국 날씨 직항 쇼핑 여행 호텔 항공권 푸껫 리조트 숙소 해외', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_13', '태국 쇼핑 에어텔 여행지 디저트 패키지 항공권 해외 호텔 날씨 리조트', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_14', '태국 쇼핑 허니문 패키지 항공권 푸껫 해외 리조트 마사지 에어텔 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_15', '태국 항공권 푸껫 요트 호텔 숙소 여행지 해외 에어텔 패키지 직항 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_16', '태국 호텔 허니문 쇼핑 요트 여행 마사지 푸껫 태국 에어텔 리조트 해외', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_17', '태국 리조트 요트 태국 마사지 여행지 허니문 쇼핑 항공권 날씨 숙소 해외', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_18', '태국 패키지 푸껫 요트 여행지 숙소 항공권 마사지 쇼핑 태국 에어텔', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_19', '태국 푸껫 날씨 해외 리조트 숙소 요트 마사지 태국 쇼핑 허니문 패키지', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_20', '태국 요트 해외 디저트 항공권 태국 에어텔 호텔 여행 숙소 여행지 쇼핑', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_01', '태국 해외 항공권 직항 여행 푸껫 날씨 태국 인천출발', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_02', '태국 여행 해외 인천출발 항공권 푸껫 직항 태국 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_03', '태국 항공권 직항 여행 푸껫 인천출발 해외 날씨 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_04', '태국 항공권 직항 해외 푸껫 여행 인천출발 태국 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_05', '태국 항공권 해외 여행 태국 푸껫 날씨 인천출발 직항', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_06', '태국 날씨 해외 태국 항공권 푸껫 여행 인천출발 직항', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_07', '태국 항공권 해외 태국 푸껫 인천출발 여행 직항 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_08', '태국 푸껫 항공권 직항 해외 인천출발 태국 여행 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_09', '태국 직항 해외 여행 날씨 항공권 태국 인천출발 푸껫', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_10', '태국 직항 태국 푸껫 해외 날씨 인천출발 여행 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_11', '태국 태국 해외 푸껫 인천출발 항공권 여행 직항 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_12', '태국 푸껫 인천출발 직항 날씨 태국 항공권 해외 여행', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_13', '태국 태국 직항 항공권 해외 인천출발 날씨 여행 푸껫', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_14', '태국 날씨 직항 해외 푸껫 여행 인천출발 항공권 태국', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_15', '태국 푸껫 날씨 여행 인천출발 태국 해외 직항 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_16', '태국 여행 푸껫 날씨 항공권 해외 태국 직항 인천출발', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_17', '태국 직항 해외 푸껫 태국 여행 날씨 인천출발 항공권', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_18', '태국 해외 인천출발 여행 태국 직항 항공권 푸껫 날씨', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_19', '태국 인천출발 태국 항공권 여행 날씨 푸껫 해외 직항', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_20', '태국 날씨 태국 푸껫 인천출발 직항 해외 항공권 여행', 'Phuket');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_01', '11월 패키지 3박 5일 해외 직항 날씨 태국 여행', 'Phuket');
