-- City Titles Part 011 (1001-1100번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0011', '샌프란시스코여행 요세미티국립공원 세콰이어 킹스캐년 하이킹 맞춤여행 전일정가이드 버킷리스트 꿈의여행 인생여행 가을단풍 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0012', '미주여행 샌프란시스코 캘리포니아코스탈트레일 요세미티국립공원 세콰이어 킹스캐년 맞춤여행 꿈의여행 인생여행 가을단풍 하이킹 전일정가이드 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0013', '가족여행 샌프란시스코 요세미티국립공원 피너클스 세콰이어 킹스캐년 국립공원 산호세 맞춤여행 한국인가이드 전일정가이드 버킷리스트 꿈의여행 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0014', '효도여행 샌프란시스코 요세미티국립공원 세콰이어 킹스캐년 피너클스 국립공원 전일정가이드 한국인가이드 하이킹 맞춤여행 인생여행 버킷리스트 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0015', '우정여행 샌프란시스코 캘리포니아코스탈트레일 요세미티국립공원 세콰이어 킹스캐년 하이킹 전일정가이드 한국인가이드 맞춤여행 꿈의여행 버킷리스트 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0016', '졸업여행 요세미티국립공원 샌프란시스코 세콰이어 킹스캐년 피너클스 국립공원 전일정가이드 한국인가이드 인생여행 맞춤여행 가을단풍 버킷리스트 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0017', '맞춤여행 샌프란시스코 요세미티국립공원 세콰이어 킹스캐년 피너클스 국립공원 한국인가이드 전일정가이드 하이킹 인생여행 꿈의여행 가을단풍 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0018', '꿈의여행 요세미티국립공원 샌프란시스코 캘리포니아코스탈트레일 세콰이어 킹스캐년 인생여행 졸업여행 전일정가이드 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0019', '인생여행 샌프란시스코 요세미티국립공원 피너클스 세콰이어 킹스캐년 캘리포니아코스탈트레일 맞춤여행 버킷리스트 전일정가이드 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_ML_0020', '여행 샌프란시스코 캘리포니아코스탈트레일 요세미티국립공원 세콰이어 킹스캐년 피너클스 국립공원 가을단풍 한국인가이드 인천출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0001', '미주여행 샌프란시스코여행 미국서부여행 라스베가스여행 그랜드캐년 투어 인천출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0002', '샌프란시스코여행 미주여행 미국서부여행 라스베가스여행 그랜드캐년 투어 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0003', '미국서부여행 라스베가스여행 샌프란시스코여행 미주여행 그랜드캐년 투어 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0004', '라스베가스여행 샌프란시스코여행 미주여행 미국서부여행 그랜드캐년 투어 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0005', '그랜드캐년 샌프란시스코여행 미주여행 미국서부여행 라스베가스여행 투어 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0006', '샌프란시스코여행 라스베가스여행 미국서부여행 미주여행 그랜드캐년 투어 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0007', '미주여행 미국서부여행 샌프란시스코여행 라스베가스여행 그랜드캐년 투어 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0008', '샌프란시스코여행 미주여행 그랜드캐년 미국서부여행 라스베가스여행 투어 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0009', '라스베가스여행 미주여행 샌프란시스코여행 미국서부여행 그랜드캐년 투어 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0010', '샌프란시스코여행 그랜드캐년 라스베가스여행 미주여행 미국서부여행 투어 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0011', '미주여행 샌프란시스코여행 미국서부여행 그랜드캐년 라스베가스여행 투어 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0012', '샌프란시스코여행 라스베가스여행 미주여행 미국서부여행 그랜드캐년 투어 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0013', '미국서부여행 그랜드캐년 샌프란시스코여행 라스베가스여행 미주여행 투어 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0014', '라스베가스여행 샌프란시스코여행 미주여행 그랜드캐년 미국서부여행 투어 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0015', '그랜드캐년 샌프란시스코여행 미국서부여행 미주여행 라스베가스여행 투어 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0017', '미주여행 라스베가스여행 샌프란시스코여행 그랜드캐년 미국서부여행 투어 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0018', '샌프란시스코여행 미국서부여행 라스베가스여행 미주여행 그랜드캐년 투어 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0019', '미국서부여행 미주여행 샌프란시스코여행 그랜드캐년 라스베가스여행 투어 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_SNK_0020', '샌프란시스코여행 미주여행 라스베가스여행 미국서부여행 그랜드캐년 투어 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0001', '샌프랜시스코 패키지 미국 라스베게스 그렌드캐년 미주여행 직항 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0002', '미주여행 샌프랜시스코 라스베게스 미국 패키지 그렌드캐년 직항 인쳔출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0003', '라스베게스 샌프랜시스코 미국 미주여행 패키지 직항 그렌드캐년 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0005', '미국 샌프랜시스코 라스베게스 미주여행 패키지 직항 그렌드캐년 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0006', '샌프랜시스코 라스베게스 미국 미주여행 패키지 직항 그렌드캐년 인쳔출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0007', '미주여행 샌프랜시스코 미국 패키지 라스베게스 직항 그렌드캐년 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0008', '샌프랜시스코 패키지 미국 미주여행 라스베게스 직항 그렌드캐년 인쳔출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0009', '코잇타워 롬벗스트리트 캘리포니아코스탈트레일 샌프랜시스코 여행 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0010', '요세메티국립공원 세쿼이어 킹스케년 피네클스 국립공원 샌프랜시스코 패키지 인쳔출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0011', '샌프랜시스코 패키지 미주여행 라스베게스 미국 직항 그렌드캐년 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0012', '미주여행 샌프랜시스코 라스베게스 미국 패키지 직항 그렌드캐년 인쳔출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0013', '샌프랜시스코 미주여행 미국 라스베게스 패키지 직항 그렌드캐년 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0014', '라스베게스 샌프랜시스코 미국 미주여행 패키지 직항 그렌드캐년 인쳔출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0015', '샌프랜시스코 라스베게스 미주여행 미국 패키지 직항 그렌드캐년 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0016', '미국 샌프랜시스코 라스베게스 패키지 미주여행 직항 그렌드캐년 인쳔출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0017', '샌프랜시스코 패키지 미국 라스베게스 미주여행 직항 그렌드캐년 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0018', '미주여행 샌프랜시스코 미국 라스베게스 패키지 직항 그렌드캐년 인쳔출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0019', '라스베게스 미주여행 샌프랜시스코 미국 패키지 직항 그렌드캐년 인쳔출발 대한항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_OT_0020', '샌프랜시스코 미주여행 라스베게스 미국 패키지 직항 그렌드캐년 인쳔출발 아시아나항공', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0001', '샌프란시스코 금문교 피셔맨스워프 알카트라즈섬 롬바드스트리트 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0002', '샌프란시스코 코이트타워 요세미티국립공원 금문교 피셔맨스워프 패키지', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0003', '샌프란시스코 알카트라즈섬 금문교 롬바드스트리트 코이트타워 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0004', '샌프란시스코 금문교 피셔맨스워프 롬바드스트리트 코이트타워 투어', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0005', '샌프란시스코 요세미티국립공원 금문교 피셔맨스워프 알카트라즈섬 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0006', '샌프란시스코 금문교 피셔맨스워프 롬바드스트리트 패키지 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0007', '샌프란시스코 알카트라즈섬 코이트타워 금문교 피셔맨스워프 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0008', '샌프란시스코 금문교 롬바드스트리트 피셔맨스워프 요세미티 투어', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0009', '샌프란시스코 코이트타워 금문교 피셔맨스워프 알카트라즈섬 패키지', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0010', '샌프란시스코 요세미티국립공원 금문교 롬바드스트리트 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0011', '샌프란시스코 피셔맨스워프 금문교 롬바드스트리트 패키지 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0012', '샌프란시스코 코이트타워 알카트라즈섬 금문교 피셔맨스워프 투어', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0013', '샌프란시스코 금문교 요세미티국립공원 롬바드스트리트 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0014', '샌프란시스코 롬바드스트리트 금문교 피셔맨스워프 코이트타워 패키지', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0015', '샌프란시스코 금문교 피셔맨스워프 요세미티 알카트라즈섬 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0016', '샌프란시스코 코이트타워 금문교 롬바드스트리트 패키지 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0017', '샌프란시스코 피셔맨스워프 금문교 알카트라즈섬 코이트타워 투어', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0018', '샌프란시스코 요세미티국립공원 금문교 롬바드스트리트 알카트라즈섬 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0019', '샌프란시스코 금문교 피셔맨스워프 롬바드스트리트 코이트타워 여행', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_SF_GPT_0020', '샌프란시스코 알카트라즈섬 금문교 피셔맨스워프 요세미티 패키지', 'SanFrancisco');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0001', '라스베가스 여행 대한항공 그랜드캐년 로스앤젤레스 패키지 여행 미국 8대캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0002', '직항 로스앤젤레스 미국 여행 8대캐년 패키지 미서부패키지여행 그랜드캐년 아시아나항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0003', '라스베가스 그랜드캐년 패키지 대한항공 여행 여행 미국 미서부패키지여행 서부', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0004', '서부 여행 패키지 여행 미국 8대캐년 라스베가스 로스앤젤레스 아시아나항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0005', '라스베가스 직항 대한항공 미국 여행 서부 패키지 8대캐년 그랜드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0006', '패키지 라스베가스 미서부패키지여행 아시아나항공 미국 여행 8대캐년 그랜드캐년 로스앤젤레스', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0007', '8대캐년 직항 서부 패키지 그랜드캐년 대한항공 여행 미국 라스베가스', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0008', '그랜드캐년 미서부패키지여행 직항 패키지 라스베가스 여행 여행 로스앤젤레스 아시아나항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0009', '그랜드캐년 직항 대한항공 여행 미서부패키지여행 라스베가스 8대캐년 패키지 미국', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0010', '패키지 8대캐년 로스앤젤레스 아시아나항공 여행 미국 직항 여행 라스베가스', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0011', '미국 여행 대한항공 로스앤젤레스 직항 라스베가스 패키지 그랜드캐년 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0012', '미국 로스앤젤레스 패키지 여행 그랜드캐년 아시아나항공 8대캐년 라스베가스 직항', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0013', '라스베가스 로스앤젤레스 직항 패키지 여행 여행 서부 대한항공 그랜드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0014', '8대캐년 여행 로스앤젤레스 패키지 그랜드캐년 서부 라스베가스 미국 아시아나항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0015', '미국 직항 서부 라스베가스 패키지 대한항공 그랜드캐년 여행 미서부패키지여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0016', '미국 서부 여행 직항 미서부패키지여행 라스베가스 로스앤젤레스 아시아나항공 패키지', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0017', '서부 로스앤젤레스 8대캐년 여행 미서부패키지여행 대한항공 그랜드캐년 패키지 직항', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0018', '미국 패키지 로스앤젤레스 여행 미서부패키지여행 여행 아시아나항공 8대캐년 그랜드캐년', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0019', '라스베가스 서부 미국 패키지 대한항공 직항 로스앤젤레스 미서부패키지여행 여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_CMK_0020', '아시아나항공 미국 패키지 서부 로스앤젤레스 8대캐년 여행 여행 미서부패키지여행', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0001', '라스베가스 그리피스천문대 코카콜라스토어 스타의거리 대한항공 여행 피셔맨스워프 돌비극장 미국', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0002', '여행 금문교 라스베가스 미국 스타의거리 그랜드캐년 아시아나항공 피어39 돌비극장', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0003', '미국 여행 그리피스천문대 라스베가스 대한항공 코카콜라스토어 피어39 금문교 피셔맨스워프', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0004', '미국 코카콜라스토어 프리몬트스트리트 여행 돌비극장 아시아나항공 라스베가스 그랜드캐년 피셔맨스워프', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0005', '돌비극장 코카콜라스토어 미국 라스베가스 그랜드캐년 피어39 여행 대한항공 피셔맨스워프', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0006', '라스베가스 그리피스천문대 여행 피셔맨스워프 스타의거리 아시아나항공 피어39 그랜드캐년 미국', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0007', '코카콜라스토어 그랜드캐년 프리몬트스트리트 라스베가스 피셔맨스워프 미국 여행 스타의거리 대한항공', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0008', '피셔맨스워프 그리피스천문대 그랜드캐년 아시아나항공 미국 여행 스타의거리 라스베가스 금문교', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0009', '대한항공 여행 그랜드캐년 돌비극장 금문교 라스베가스 프리몬트스트리트 스타의거리 미국', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0010', '여행 금문교 라스베가스 그리피스천문대 스타의거리 그랜드캐년 아시아나항공 코카콜라스토어 미국', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0011', '여행 프리몬트스트리트 그리피스천문대 금문교 대한항공 코카콜라스토어 돌비극장 라스베가스 미국', 'LasVegas');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_LV_MKL_0012', '라스베가스 아시아나항공 그랜드캐년 금문교 여행 미국 피어39 스타의거리 그리피스천문대', 'LasVegas');
