-- City Titles Part 107 (10601-10700번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0025', '일본여행 해외 다케산 항공권 날씨 직항 리조트 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0026', '일본여행 리조트 항공권 날씨 패키지 해외 벳부 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0027', '일본여행 유후인 해외 리조트 직항 벳부 패키지 온천', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0028', '일본여행 해외 온천 리조트 직항 패키지 유후인 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0029', '일본여행 벳부 직항 해외 항공권 온천 리조트 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MRR_0030', '일본여행 날씨 항공권 다케산 직항 리조트 패키지 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0021', '일본여행 직항 온천 날씨 해외 오사카 간사이공항 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0022', '일본여행 온천 간사이공항 해외 리조트 벳부 날씨 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0023', '일본여행 유후인 항공권 오사카 간사이공항 날씨 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0024', '일본여행 벳부 간사이공항 유후인 패키지 에어텔 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0025', '일본여행 해외 간사이공항 에어텔 리조트 유후인 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0026', '일본여행 온천 벳부 패키지 날씨 간사이공항 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0027', '일본여행 패키지 항공권 해외 직항 유후인 리조트 오사카', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0028', '일본여행 패키지 벳부 항공권 직항 간사이공항 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0029', '일본여행 리조트 유후인 항공권 오사카 벳부 해외 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_RAN_0030', '일본여행 오사카 해외 항공권 벳부 온천 에어텔', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_AUSTRIA_DMKL_0012', '12월 비행시간 체코 할슈타트 잘츠부르크 일주 동유럽', 'Austria');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0018', '프랑스 에스카르고 먹거리 숙소 겨울 관광 가볼만한곳 힐링 향수공방체험', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0019', '프랑스 에스카르고 파리 항공권 노르망디 관광 가격 향수공방체험 숙소', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_FRANCE_ML_0020', '프랑스 부르기뇽 힐링 관광 비행시간 향수공방체험 겨울 날씨 패키지 파리', 'France');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0019', '이탈리아 가격 가을 날씨 숙소 관광 비행시간 파스타', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0015', '이탈리아 가격 먹거리 날씨 파스타 피자 숙소 항공권', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_ITALY_ML_0014', '이탈리아 피자 겨울 비행시간 힐링 직항 가격 가볼만한곳', 'Italy');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0001', '씨엠립 해외 하롱베이 일정 리조트 캄보디아 항공권 직항', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0002', '씨엠립 리조트 캄보디아 일정 해외 하롱베이 날씨 패키지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0003', '씨엠립 동남아 해외 하롱베이 직항 리조트 날씨 일정', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0004', '씨엠립 동남아 직항 리조트 해외 날씨 항공권 패키지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0005', '씨엠립 날씨 항공권 일정 직항 리조트 하롱베이 해외', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0006', '씨엠립 캄보디아 해외 항공권 일정 동남아 직항 리조트', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0007', '씨엠립 하롱베이 패키지 여행 날씨 리조트 동남아 해외', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0008', '씨엠립 리조트 하롱베이 항공권 직항 여행 동남아 패키지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0009', '씨엠립 항공권 여행 캄보디아 패키지 직항 동남아 해외', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0010', '씨엠립 날씨 동남아 여행 패키지 항공권 캄보디아 해외', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0011', '씨엠립 동남아 일정 항공권 날씨 패키지 캄보디아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0012', '씨엠립 날씨 해외 리조트 직항 항공권 캄보디아 패키지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0013', '씨엠립 날씨 항공권 리조트 동남아 여행 해외 하롱베이', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0014', '씨엠립 일정 여행 패키지 항공권 동남아 직항 캄보디아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0015', '씨엠립 직항 일정 해외 리조트 여행 캄보디아 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0016', '씨엠립 직항 하롱베이 동남아 여행 일정 패키지 캄보디아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0017', '씨엠립 해외 항공권 직항 패키지 여행 리조트 캄보디아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0018', '씨엠립 해외 일정 직항 날씨 여행 하롱베이 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0019', '씨엠립 동남아 항공권 직항 날씨 하롱베이 해외 리조트', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MMK_0020', '씨엠립 날씨 항공권 직항 캄보디아 동남아 리조트 해외', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0001', '씨엠립 항공권 관광지 여행 일정 케이블카 직항 리조트', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0002', '씨엠립 케이블카 호핑투어 하롱베이 캄보디아 직항 해외', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0003', '씨엠립 관광지 툭툭이 직항 일정 자유 날씨 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0004', '씨엠립 하롱베이 리조트 패키지 직항 관광지 해외 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0005', '씨엠립 크루즈 해외 쪽배 동남아 직항 호핑투어 툭툭이', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0006', '씨엠립 툭툭이 호핑투어 날씨 자유 동남아 해외 야시장', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0007', '씨엠립 리조트 캄보디아 케이블카 크루즈 여행 쪽배 일정', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0008', '씨엠립 크루즈 야시장 관광지 일정 자유 케이블카 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0009', '씨엠립 호핑투어 캄보디아 항공권 패키지 날씨 크루즈', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0010', '씨엠립 툭툭이 캄보디아 항공권 날씨 직항 일정 케이블카', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0011', '씨엠립 호핑투어 항공권 동남아 툭툭이 케이블카 하롱베이', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0012', '씨엠립 해외 크루즈 케이블카 하롱베이 자유 쪽배', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0013', '씨엠립 하롱베이 케이블카 크루즈 여행 호핑투어 캄보디아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0014', '씨엠립 야시장 케이블카 패키지 직항 리조트 툭툭이 일정', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0015', '씨엠립 일정 항공권 관광지 호핑투어 야시장 캄보디아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0016', '씨엠립 해외 날씨 관광지 호핑투어 여행 툭툭이 자유', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0017', '씨엠립 케이블카 동남아 직항 항공권 해외 하롱베이', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0018', '씨엠립 패키지 리조트 쪽배 야시장 툭툭이 여행 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0019', '씨엠립 하롱베이 항공권 일정 날씨 쪽배 툭툭이 직항', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKSH_0020', '씨엠립 툭툭이 자유 일정 하롱베이 동남아 관광지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0001', '씨엠립 동남아 관광지 캄보디아 자유 해외 케이블카 여행 일정 항공권', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0002', '씨엠립 여행 캄보디아 직항 해외 호핑투어 항공권 자유 관광지 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0003', '씨엠립 항공권 하롱베이 해외 툭툭이 호핑투어 캄보디아 리조트 야시장', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0004', '씨엠립 동남아 자유 리조트 쪽배 일정 해외 야시장 하롱베이 패키지 관광지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0005', '씨엠립 여행 관광지 크루즈 날씨 자유 쪽배 케이블카 툭툭이 리조트 항공권', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0006', '씨엠립 관광지 날씨 툭툭이 동남아 패키지 야시장 항공권 자유 캄보디아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0007', '씨엠립 케이블카 자유 관광지 리조트 크루즈 캄보디아 동남아 호핑투어 쪽배', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0008', '씨엠립 패키지 날씨 자유 하롱베이 호핑투어 일정 툭툭이 동남아 야시장', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0009', '씨엠립 크루즈 하롱베이 야시장 날씨 쪽배 캄보디아 해외 관광지 직항', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0010', '씨엠립 케이블카 직항 해외 여행 날씨 일정 쪽배 캄보디아 리조트 야시장', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0011', '씨엠립 자유 케이블카 여행 쪽배 항공권 관광지 일정 해외 호핑투어', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0012', '씨엠립 일정 직항 호핑투어 쪽배 관광지 여행 항공권 해외 하롱베이 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0013', '씨엠립 자유 크루즈 여행 리조트 해외 패키지 케이블카 관광지 항공권', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0014', '씨엠립 크루즈 동남아 호핑투어 일정 쪽배 케이블카 관광지 하롱베이 야시장', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0015', '씨엠립 캄보디아 항공권 관광지 호핑투어 리조트 패키지 동남아 여행 직항', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0016', '씨엠립 리조트 동남아 항공권 야시장 여행 하롱베이 케이블카 패키지 관광지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0017', '씨엠립 날씨 패키지 툭툭이 케이블카 동남아 항공권 캄보디아 야시장 해외', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0018', '씨엠립 하롱베이 쪽배 여행 일정 크루즈 날씨 항공권 캄보디아 관광지 직항', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0019', '씨엠립 캄보디아 쪽배 야시장 일정 여행 크루즈 동남아 해외 항공권 리조트', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKLKLO_0020', '씨엠립 툭툭이 크루즈 항공권 하롱베이 일정 쪽배 해외 여행 자유 케이블카', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0001', '캄보디아 앙코르와트 프놈쿨렌 해외 직항 리조트 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0002', '캄보디아 패키지 앙코르와트 프놈쿨렌 동남아 여행 해외', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0003', '캄보디아 앙코르와트 하롱베이 프놈쿨렌 일정 패키지 직항', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0004', '캄보디아 리조트 프놈쿨렌 동남아 일정 앙코르와트 씨엠립', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0005', '캄보디아 직항 하롱베이 씨엠립 패키지 프놈쿨렌 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0006', '캄보디아 일정 앙코르톰 프놈쿨렌 하롱베이 씨엠립 직항', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0007', '캄보디아 여행 프놈쿨렌 일정 날씨 리조트 씨엠립 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0008', '캄보디아 패키지 앙코르톰 직항 하롱베이 여행 항공권', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0009', '캄보디아 일정 하롱베이 앙코르와트 씨엠립 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0010', '캄보디아 패키지 직항 하롱베이 여행 리조트 씨엠립 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0011', '캄보디아 앙코르와트 여행 씨엠립 패키지 항공권 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0012', '캄보디아 앙코르와트 패키지 날씨 해외 직항 씨엠립', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0013', '캄보디아 동남아 앙코르톰 프놈쿨렌 여행 하롱베이 씨엠립', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0014', '캄보디아 여행 날씨 앙코르와트 직항 프놈쿨렌 씨엠립', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0015', '캄보디아 앙코르톰 리조트 항공권 동남아 하롱베이 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0016', '캄보디아 동남아 날씨 여행 하롱베이 프놈쿨렌 일정', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_MKRT_0017', '캄보디아 프놈쿨렌 날씨 앙코르톰 여행 해외 씨엠립 직항', 'SiemReap');
