-- City Titles Part 053 (5201-5300번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0001', '보라카이 직항 일정 동남아 쇼핑 해외 에메랄드바다 호핑 케이블카 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0002', '보라카이 호핑 리조트 케이블카 필리핀 추천 보트 직항 쇼핑 날씨 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0003', '보라카이 스쿠버다이빙 항공권 에메랄드바다 패키지 날씨 직항 동남아 여행', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0004', '보라카이 항공권 에메랄드바다 리조트 가족 추천 여행 날씨 직항 해외 쇼핑', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0005', '보라카이 일정 가족 관광지 직항 리조트 필리핀 케이블카 호핑 날씨', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0006', '보라카이 관광지 쇼핑 가족 스쿠버다이빙 보트 에메랄드바다 케이블카 동남아', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0007', '보라카이 패키지 날씨 가족 추천 리조트 스쿠버다이빙 호핑 여행', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0008', '보라카이 쇼핑 직항 스쿠버다이빙 추천 패키지 필리핀 해외 보트 케이블카', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0009', '보라카이 가족 일정 추천 필리핀 날씨 패키지 보트 케이블카 항공권 호핑', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0010', '보라카이 가족 보트 여행 해외 패키지 필리핀 관광지 동남아 추천 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0011', '보라카이 보트 항공권 직항 관광지 일정 호핑 케이블카 리조트 동남아 추천', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0012', '보라카이 케이블카 일정 필리핀 호핑 항공권 날씨 패키지 보트 리조트 가족', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0013', '보라카이 가족 에메랄드바다 해외 스쿠버다이빙 직항 쇼핑 여행 관광지', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0014', '보라카이 추천 항공권 쇼핑 날씨 가족 스쿠버다이빙 직항 여행 일정', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0015', '보라카이 가족 동남아 날씨 보트 항공권 패키지 관광지 호핑 스쿠버다이빙', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0016', '보라카이 추천 호핑 패키지 쇼핑 스쿠버다이빙 동남아 필리핀 해외 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0017', '보라카이 케이블카 패키지 호핑 가족 날씨 여행 쇼핑 추천 필리핀 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0018', '보라카이 호핑 보트 해외 여행 가족 관광지 동남아 추천 리조트 직항', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0019', '보라카이 스쿠버다이빙 리조트 일정 보트 여행 호핑 쇼핑 동남아 추천', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0020', '보라카이 추천 날씨 동남아 필리핀 패키지 해외 케이블카 여행 관광지 쇼핑', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0021', '보라카이 케이블카 해외 패키지 추천 여행 관광지 스쿠버다이빙 가족 필리핀', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0022', '보라카이 관광지 쇼핑 여행 패키지 가족 케이블카 필리핀 항공권 일정 보트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0023', '보라카이 일정 해외 보트 스쿠버다이빙 가족 여행 케이블카 호핑', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0024', '보라카이 보트 관광지 항공권 케이블카 일정 호핑 동남아 여행 리조트 추천', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0025', '보라카이 날씨 보트 에메랄드바다 추천 패키지 스쿠버다이빙 여행 일정 해외', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0026', '보라카이 필리핀 해외 동남아 가족 날씨 패키지 케이블카 직항 호핑 보트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0027', '보라카이 해외 케이블카 추천 쇼핑 동남아 여행 호핑 필리핀 관광지 가족', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0028', '보라카이 호핑 관광지 여행 에메랄드바다 일정 해외 보트 직항 쇼핑', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0029', '보라카이 보트 일정 리조트 직항 가족 패키지 케이블카 항공권 동남아 추천', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKLKLO_0030', '보라카이 호핑 가족 동남아 날씨 쇼핑 직항 관광지 리조트 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0001', '보라카이 직항 해외 여행 항공권 날씨 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0002', '보라카이 패키지 일정 동남아 해외 리조트 여행 필리핀', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0003', '보라카이 푸카 항공권 윌리스록 필리핀 리조트 해외', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0004', '보라카이 직항 화이트비치 여행 해외 일정 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0005', '보라카이 윌리스록 항공권 필리핀 날씨 해외 여행 푸카', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0006', '보라카이 푸카 마운트루호전망대 리조트 날씨 일정 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0007', '보라카이 마운트루호전망대 화이트비치 일정 리조트 동남아', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0008', '보라카이 일정 직항 윌리스록 마운트루호전망대 동남아', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0009', '보라카이 직항 여행 마운트루호전망대 필리핀 일정 패키지', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0010', '보라카이 직항 필리핀 여행 마운트루호전망대 일정 동남아', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0011', '보라카이 패키지 여행 직항 마운트루호전망대 일정 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0012', '보라카이 리조트 항공권 화이트비치 날씨 패키지 해외', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0013', '보라카이 푸카 항공권 마운트루호전망대 윌리스록 필리핀', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0014', '보라카이 마운트루호전망대 패키지 푸카 해외 리조트 여행', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0015', '보라카이 필리핀 마운트루호전망대 날씨 항공권 일정', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0016', '보라카이 해외 날씨 여행 일정 직항 윌리스록 화이트비치', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0017', '보라카이 동남아 윌리스록 리조트 항공권 마운트루호전망대', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0018', '보라카이 필리핀 해외 직항 날씨 푸카 동남아 패키지', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0019', '보라카이 직항 날씨 필리핀 동남아 리조트 해외 푸카', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0020', '보라카이 해외 윌리스록 패키지 리조트 푸카 화이트비치', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0021', '보라카이 여행 마운트루호전망대 윌리스록 푸카 해외 일정', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0022', '보라카이 마운트루호전망대 푸카 날씨 직항 항공권 해외', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0023', '보라카이 마운트루호전망대 리조트 동남아 윌리스록 푸카', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0024', '보라카이 필리핀 패키지 일정 화이트비치 직항', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0025', '보라카이 화이트비치 필리핀 여행 마운트루호전망대 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0026', '보라카이 여행 필리핀 리조트 패키지 화이트비치', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0027', '보라카이 패키지 날씨 마운트루호전망대 여행 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0028', '보라카이 해외 필리핀 여행 마운트루호전망대 윌리스록', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0029', '보라카이 직항 필리핀 동남아 항공권 마운트루호전망대', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_MKR_0030', '보라카이 일정 푸카 날씨 항공권 직항 윌리스록 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0001', '인천출발 보라카이 필리핀 쇼핑 해외 동남아 여행', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0002', '인천출발 보트 동남아 보라카이 날씨 스쿠버다이빙 쇼핑', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0003', '인천출발 동남아 보라카이 직항 케이블카 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0004', '인천출발 호핑 보라카이 보트 일정 직항 항공권 동남아', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0005', '인천출발 필리핀 패키지 날씨 호핑 보라카이 스쿠버다이빙', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0006', '인천출발 보트 케이블카 항공권 필리핀 패키지', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0007', '인천출발 날씨 항공권 동남아 케이블카 리조트 일정', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0008', '인천출발 필리핀 날씨 일정 호핑 보트 동남아', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0009', '인천출발 쇼핑 스쿠버다이빙 동남아 호핑 해외 날씨 일정', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0010', '인천출발 필리핀 일정 스쿠버다이빙 리조트 여행 보트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0011', '인천출발 케이블카 날씨 필리핀 호핑 여행 스쿠버다이빙', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0012', '인천출발 동남아 해외 날씨 항공권 여행 스쿠버다이빙', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0013', '인천출발 일정 직항 필리핀 보라카이 리조트 패키지', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0014', '인천출발 호핑 스쿠버다이빙 쇼핑 케이블카 동남아 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0015', '인천출발 해외 보라카이 패키지 케이블카 스쿠버다이빙', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0016', '인천출발 호핑 동남아 패키지 여행 리조트 항공권 일정', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0017', '인천출발 여행 동남아 직항 케이블카 패키지 쇼핑 날씨', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0018', '인천출발 필리핀 스쿠버다이빙 보라카이 쇼핑 호핑 날씨', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0019', '인천출발 보라카이 여행 해외 쇼핑 필리핀 리조트 일정', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0020', '인천출발 날씨 호핑 일정 패키지 여행 보라카이 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0021', '인천출발 보트 보라카이 호핑 필리핀 여행 패키지', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0022', '인천출발 동남아 일정 패키지 항공권 쇼핑 보라카이', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0023', '인천출발 패키지 리조트 케이블카 스쿠버다이빙 필리핀', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0024', '인천출발 보트 해외 호핑 쇼핑 여행 항공권 패키지', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0025', '인천출발 스쿠버다이빙 직항 케이블카 호핑 보트 쇼핑', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0026', '인천출발 동남아 해외 보트 패키지 리조트 날씨 항공권', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0027', '인천출발 호핑 케이블카 여행 보트 직항 필리핀 보라카이', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0028', '인천출발 항공권 보트 필리핀 해외 보라카이 리조트 직항', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0029', '인천출발 보라카이 리조트 호핑 필리핀 동남아 패키지', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_ICMR_0030', '인천출발 패키지 항공권 보트 해외 케이블카 스쿠버다이빙', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0001', '10월 3박4일 필리핀 여행 일정 항공권 동남아 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0002', '10월 필리핀 일정 항공권 리조트 날씨 직항 여행', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0003', '10월 필리핀 3박4일 패키지 항공권 여행 직항 해외', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0004', '10월 3박4일 직항 여행 보라카이 리조트 필리핀', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0005', '10월 해외 3박4일 여행 항공권 동남아 필리핀 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0006', '10월 해외 패키지 직항 날씨 보라카이 여행 필리핀', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0007', '10월 동남아 날씨 패키지 여행 필리핀 직항 리조트', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0008', '10월 3박4일 항공권 여행 직항 보라카이 패키지', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0009', '10월 날씨 직항 해외 패키지 필리핀 일정 항공권 여행', 'Boracay');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_BORAC_OMKTF_0010', '10월 여행 일정 3박4일 필리핀 패키지 직항 동남아', 'Boracay');
