-- City Titles Part 049 (4801-4900번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0011', '일본여행 패키지 후쿠오카 직항 오사카 날씨 리조트 여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0012', '일본여행 항공권 날씨 패키지 에어텔 후쿠오카 리조트', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0013', '일본여행 리조트 에어텔 오사카 해외 황금연휴 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0014', '일본여행 항공권 황금연휴 해외 에어텔 직항 여행 날씨', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0015', '일본여행 리조트 패키지 날씨 여행 해외 황금연휴', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0016', '일본여행 에어텔 항공권 직항 리조트 여행 패키지 오사카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0017', '일본여행 해외 오사카 후쿠오카 패키지 항공권 황금연휴', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0018', '일본여행 패키지 항공권 황금연휴 직항 오사카 여행', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0019', '일본여행 리조트 패키지 항공권 오사카 해외 여행 직항', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_FUKYO_RAN_0020', '일본여행 여행 날씨 오사카 해외 패키지 에어텔 후쿠오카', 'Fukuoka');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0001', '벳부 직항 패키지 일본여행 해외 날씨 항공권 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0002', '벳부 날씨 해외 일본여행 유후인 직항 항공권 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0003', '벳부 해외 항공권 일본여행 날씨 직항 리조트 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0004', '벳부 리조트 날씨 직항 유후인 해외 패키지 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0005', '벳부 유후인 일본여행 해외 패키지 직항 날씨 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0006', '벳부 항공권 해외 패키지 날씨 유후인 리조트 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0007', '벳부 유후인 해외 직항 패키지 날씨 리조트 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0008', '벳부 해외 날씨 직항 유후인 리조트 항공권 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0009', '벳부 패키지 리조트 해외 직항 날씨 유후인 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0010', '벳부 패키지 유후인 일본여행 해외 항공권 날씨 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0011', '벳부 해외 유후인 일본여행 직항 리조트 패키지 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0012', '벳부 유후인 항공권 일본여행 패키지 직항 리조트 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0013', '벳부 리조트 항공권 날씨 해외 일본여행 패키지 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0014', '벳부 패키지 날씨 일본여행 리조트 해외 항공권 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0015', '벳부 리조트 일본여행 패키지 항공권 날씨 해외 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0016', '벳부 패키지 날씨 항공권 해외 유후인 일본여행 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0017', '벳부 패키지 리조트 일본여행 해외 직항 날씨 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0018', '벳부 유후인 날씨 리조트 항공권 패키지 일본여행 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0019', '벳부 항공권 일본여행 패키지 리조트 직항 날씨 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MMK_0020', '벳부 일본여행 패키지 직항 해외 날씨 항공권 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0001', '벳부 항공권 리조트 에어텔 오사카 간사이공항 일본', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0002', '벳부 오사카 직항 항공권 일본 리조트 날씨 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0003', '벳부 리조트 일본 직항 항공권 오사카 해외 커플여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0004', '벳부 해외 간사이공항 패키지 유후인 도쿄 에어텔 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0005', '벳부 일본 직항 항공권 커플여행 리조트 에어텔 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0006', '벳부 유후인 해외 날씨 직항 패키지 간사이공항 에어텔', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0007', '벳부 해외 오사카 도쿄 일본 패키지 리조트 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0008', '벳부 직항 패키지 항공권 에어텔 커플여행 날씨 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0009', '벳부 에어텔 해외 항공권 간사이공항 직항 날씨 일본', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0010', '벳부 날씨 항공권 오사카 도쿄 에어텔 해외 커플여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0011', '벳부 에어텔 리조트 일본 패키지 커플여행 도쿄 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0012', '벳부 커플여행 유후인 도쿄 직항 오사카 날씨 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0013', '벳부 도쿄 에어텔 유후인 해외 오사카 항공권 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0014', '벳부 유후인 직항 간사이공항 오사카 에어텔 해외 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0015', '벳부 에어텔 리조트 간사이공항 유후인 항공권 일본 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0016', '벳부 오사카 일본 간사이공항 날씨 에어텔 해외 커플여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0017', '벳부 간사이공항 오사카 일본 날씨 패키지 유후인 에어텔', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0018', '벳부 일본 유후인 패키지 오사카 간사이공항 항공권 도쿄', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0019', '벳부 에어텔 리조트 커플여행 일본 직항 항공권 오사카', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKSH_0020', '벳부 리조트 도쿄 직항 간사이공항 유후인 일본 오사카', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0001', '벳부 리조트 패키지 항공권 커플여행 에어텔 유후인 간사이공항 직항 일본', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0002', '벳부 에어텔 항공권 일본 유후인 해외 직항 리조트 간사이공항 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0003', '벳부 날씨 항공권 유후인 에어텔 리조트 일본 도쿄 커플여행 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0004', '벳부 날씨 커플여행 직항 해외 유후인 일본 항공권 오사카 리조트 도쿄', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0005', '벳부 리조트 해외 직항 일본 에어텔 커플여행 간사이공항 도쿄 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0006', '벳부 리조트 유후인 에어텔 날씨 직항 일본 간사이공항 도쿄 해외 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0007', '벳부 유후인 날씨 간사이공항 도쿄 에어텔 해외 커플여행 리조트 일본', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0008', '벳부 직항 일본 날씨 도쿄 패키지 유후인 해외 항공권 에어텔 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0009', '벳부 오사카 유후인 해외 패키지 도쿄 간사이공항 에어텔 날씨 일본', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0010', '벳부 도쿄 직항 유후인 오사카 일본 날씨 에어텔 해외 커플여행 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0011', '벳부 에어텔 날씨 해외 커플여행 패키지 리조트 오사카 일본 직항 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0012', '벳부 유후인 간사이공항 해외 날씨 직항 오사카 패키지 커플여행 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0013', '벳부 직항 에어텔 날씨 커플여행 항공권 패키지 리조트 유후인 일본', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0014', '벳부 일본 간사이공항 리조트 도쿄 항공권 유후인 에어텔 직항 날씨 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0015', '벳부 해외 에어텔 항공권 날씨 패키지 오사카 리조트 커플여행 유후인 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0016', '벳부 날씨 직항 해외 일본 간사이공항 도쿄 유후인 에어텔 항공권 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0017', '벳부 유후인 오사카 일본 패키지 에어텔 날씨 간사이공항 해외 커플여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0018', '벳부 커플여행 항공권 패키지 간사이공항 에어텔 해외 직항 리조트 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0019', '벳부 간사이공항 오사카 도쿄 날씨 리조트 항공권 일본 직항 패키지 에어텔', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_MKLKLO_0020', '벳부 커플여행 일본 항공권 해외 에어텔 유후인 날씨 간사이공항 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0001', '10월 일본여행 패키지 유후인 온천 항공권 다케산 날씨', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0002', '10월 리조트 벳부 다케산 일본여행 항공권 온천 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0003', '10월 일본여행 온천 유후인 해외 벳부 날씨 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0004', '10월 일본여행 패키지 리조트 다케산 해외 항공권 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0005', '10월 유후인 온천 항공권 패키지 날씨 해외 벳부', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0006', '10월 일본여행 온천 날씨 패키지 항공권 리조트 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0007', '10월 벳부 직항 다케산 리조트 온천 해외 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0008', '10월 다케산 벳부 직항 날씨 온천 항공권 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0009', '10월 다케산 해외 일본여행 리조트 벳부 온천 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0010', '10월 일본여행 다케산 리조트 날씨 직항 벳부 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0011', '10월 패키지 온천 항공권 유후인 리조트 다케산 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0012', '10월 다케산 유후인 벳부 해외 날씨 일본여행 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0013', '10월 직항 리조트 날씨 해외 유후인 일본여행 다케산', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0014', '10월 날씨 온천 리조트 유후인 항공권 직항 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0015', '10월 리조트 벳부 해외 다케산 직항 항공권 유후인', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0016', '10월 일본여행 항공권 다케산 온천 날씨 벳부 직항', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0017', '10월 일본여행 패키지 다케산 직항 유후인 온천 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0018', '10월 날씨 온천 패키지 일본여행 유후인 벳부 리조트', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0019', '10월 리조트 다케산 패키지 날씨 해외 벳부 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_OMKRT_0020', '10월 다케산 유후인 항공권 벳부 날씨 해외 일본여행', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0001', '11월 온천 다케산 일본여행 리조트 직항 유후인 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0002', '11월 날씨 패키지 유후인 온천 일본여행 해외 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0003', '11월 해외 리조트 패키지 다케산 날씨 온천 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0004', '11월 벳부 리조트 날씨 유후인 다케산 항공권 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0005', '11월 날씨 다케산 패키지 리조트 일본여행 벳부 항공권', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0006', '11월 직항 온천 유후인 리조트 날씨 항공권 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0007', '11월 벳부 일본여행 직항 다케산 온천 유후인 해외', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0008', '11월 유후인 다케산 일본여행 항공권 해외 벳부 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0009', '11월 리조트 유후인 다케산 벳부 일본여행 직항 패키지', 'BeppuYufuin');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_BEPP_NMKRT_0010', '11월 패키지 벳부 날씨 일본여행 온천 직항 항공권', 'BeppuYufuin');
