-- City Titles Part 095 (9401-9500번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_29', '푸껫 항공권 날씨 여행 해외 직항 리조트 태국 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MMK_30', '푸껫 날씨 해외 패키지 여행 리조트 태국 항공권 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_21', '푸껫 항공권 쇼핑 빅부다 마사지 호텔 여행 숙소 태국 날씨 왓찰롱 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_22', '푸껫 숙소 호텔 여행 빅부다 마사지 왓찰롱 패키지 빠통비치 쇼핑 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_23', '푸껫 호텔 숙소 빠통비치 항공권 마사지 빅부다 왓찰롱 쇼핑 여행 태국', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_24', '푸껫 날씨 왓찰롱 항공권 쇼핑 태국 숙소 마사지 빠통비치 빅부다 호텔', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_25', '푸껫 태국 빠통비치 왓찰롱 마사지 항공권 호텔 날씨 쇼핑 빅부다 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_26', '푸껫 항공권 태국 여행 패키지 숙소 날씨 쇼핑 빠통비치 호텔 마사지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_27', '푸껫 날씨 여행 패키지 호텔 태국 마사지 항공권 쇼핑 빠통비치 왓찰롱', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_28', '푸껫 패키지 날씨 왓찰롱 쇼핑 마사지 항공권 여행 숙소 빅부다 태국', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_29', '푸껫 항공권 패키지 쇼핑 날씨 호텔 태국 마사지 빅부다 빠통비치 왓찰롱', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MFLTLF_30', '푸껫 날씨 빠통비치 태국 쇼핑 여행 호텔 마사지 왓찰롱 항공권 빅부다', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_21', '푸껫 에어텔 쇼핑 야시장 여행지 요트 리조트 허니문 패키지 마사지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_22', '푸껫 리조트 허니문 직항 여행지 에어텔 디저트 항공권 해외 숙소 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_23', '푸껫 태국 여행지 쇼핑 호텔 요트 디저트 항공권 날씨 호핑투어 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_24', '푸껫 호텔 디저트 직항 요트 항공권 호핑투어 리조트 패키지 여행지 숙소', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_25', '푸껫 리조트 야시장 요트 패키지 태국 에어텔 허니문 호텔 직항 날씨 쇼핑', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_26', '푸껫 호텔 리조트 에어텔 날씨 여행지 디저트 야시장 직항 여행 허니문', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_27', '푸껫 요트 허니문 태국 직항 해외 에어텔 호텔 여행지 날씨 숙소 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_28', '푸껫 요트 여행 디저트 패키지 호텔 에어텔 쇼핑 직항 야시장 숙소 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_29', '푸껫 해외 마사지 직항 호핑투어 패키지 여행 에어텔 여행지 쇼핑 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_AMLP_30', '푸껫 패키지 마사지 디저트 에어텔 항공권 호핑투어 호텔 여행지 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_21', '태국 요트 허니문 마사지 태국 쇼핑 호텔 날씨 항공권', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_22', '태국 여행 디저트 태국 숙소 직항 요트 리조트 마사지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_23', '태국 숙소 쇼핑 여행지 패키지 디저트 여행 요트 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_24', '태국 쇼핑 날씨 여행지 푸껫 해외 마사지 여행 태국', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_25', '태국 디저트 패키지 숙소 여행지 태국 에어텔 요트 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_26', '태국 푸껫 호텔 디저트 패키지 마사지 패키지 허니문', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_27', '태국 디저트 직항 요트 쇼핑 푸껫 태국 날씨 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_28', '태국 태국 패키지 여행지 호텔 직항 에어텔 디저트 숙소', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_29', '태국 호텔 항공권 날씨 패키지 디저트 허니문 요트 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLK_30', '태국 여행 마사지 푸껫 호텔 숙소 패키지 쇼핑 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_21', '태국 여행 직항 태국 쇼핑 디저트 에어텔 여행지 숙소 패키지 요트 허니문', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_22', '태국 패키지 마사지 요트 쇼핑 디저트 여행 항공권 푸껫 여행지 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_23', '태국 패키지 호텔 마사지 디저트 쇼핑 요트 리조트 날씨 항공권 에어텔', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_24', '태국 숙소 에어텔 여행 해외 마사지 요트 허니문 태국 항공권 푸껫 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_25', '태국 허니문 패키지 리조트 쇼핑 마사지 여행지 요트 직항 호텔 숙소 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_26', '태국 직항 태국 푸껫 리조트 날씨 마사지 허니문 해외 에어텔 요트 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_27', '태국 허니문 해외 직항 패키지 디저트 여행 에어텔 쇼핑 패키지 태국', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_28', '태국 디저트 태국 항공권 패키지 해외 호텔 에어텔 요트 리조트 여행지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_29', '태국 쇼핑 허니문 에어텔 여행 여행지 직항 숙소 태국 해외 푸껫 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKLKLN_30', '태국 디저트 허니문 요트 푸껫 항공권 마사지 여행지 패키지 숙소 쇼핑', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_21', '태국 여행 항공권 해외 직항 인천출발 날씨 푸껫 태국', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_22', '태국 항공권 직항 날씨 태국 여행 해외 푸껫 인천출발', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_23', '태국 여행 인천출발 푸껫 날씨 항공권 태국 직항 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_24', '태국 날씨 해외 여행 푸껫 항공권 직항 태국 인천출발', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_25', '태국 해외 태국 날씨 항공권 직항 푸껫 인천출발 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_26', '태국 해외 태국 항공권 푸껫 인천출발 날씨 직항 여행', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_27', '태국 인천출발 태국 여행 해외 직항 항공권 날씨 푸껫', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_28', '태국 태국 인천출발 푸껫 날씨 여행 항공권 해외 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_29', '태국 날씨 태국 여행 푸껫 해외 직항 항공권 인천출발', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_MKEIC_30', '태국 푸껫 여행 직항 항공권 해외 인천출발 날씨 태국', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_21', '11월 여행 해외 직항 날씨 3박 5일 태국 푸껫 가을', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_22', '11월 항공권 푸껫 패키지 여행 리조트 3박 5일 날씨', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_23', '11월 날씨 가을 3박 5일 태국 푸껫 패키지 리조트', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_24', '11월 직항 리조트 항공권 가을 패키지 푸껫 태국 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_25', '11월 여행 해외 태국 항공권 리조트 푸껫 패키지 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_26', '11월 푸껫 해외 3박 5일 날씨 패키지 태국 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_27', '11월 날씨 가을 직항 태국 여행 3박 5일 패키지', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_28', '11월 패키지 해외 푸껫 태국 3박 5일 여행 직항', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_PHUKET_NMTFA_29', '11월 태국 푸껫 직항 가을 항공권 여행 패키지 해외', 'PhuQuoc');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0021', '싱가포르 리조트 패키지 직항 여행 항공권 일정 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0022', '싱가포르 직항 항공권 리조트 패키지 일정 날씨 여행', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0023', '싱가포르 항공권 직항 여행 날씨 리조트 패키지 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0024', '싱가포르 날씨 패키지 해외 여행 일정 항공권 직항', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0025', '싱가포르 패키지 여행 직항 일정 해외 리조트 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0026', '싱가포르 날씨 여행 패키지 해외 리조트 직항 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0027', '싱가포르 날씨 일정 직항 여행 리조트 항공권 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0028', '싱가포르 항공권 패키지 일정 여행 직항 해외 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0029', '싱가포르 항공권 직항 리조트 여행 해외 패키지 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MMK_0030', '싱가포르 항공권 여행 리조트 패키지 직항 날씨 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0021', '싱가포르 가족 먹거리 비치 항공권 일정 날씨 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0022', '싱가포르 시장 관광지 항공권 여행 리조트 해외 비치', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0023', '싱가포르 리조트 패키지 허니문 날씨 해외 관광지 체험', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0024', '싱가포르 추천 여행 시장 쇼핑 날씨 파크 허니문 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0025', '싱가포르 버스 여행 직항 패키지 먹거리 허니문 추천', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0026', '싱가포르 일정 리조트 허니문 버스 추천 체험 쇼핑', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0027', '싱가포르 파크 패키지 가족 먹거리 허니문 리조트 추천', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0028', '싱가포르 날씨 항공권 패키지 쇼핑 시장 해외 가족', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0029', '싱가포르 날씨 버스 먹거리 파크 리조트 해외 패키지', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKSH_0030', '싱가포르 리조트 체험 파크 항공권 쇼핑 직항 추천 버스', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0021', '싱가포르 여행 시장 해외 직항 비치 항공권 패키지 체험 허니문 쇼핑 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0022', '싱가포르 파크 시장 버스 쇼핑 패키지 리조트 관광지 일정 날씨 허니문', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0023', '싱가포르 리조트 시장 파크 비치 허니문 먹거리 날씨 관광지 직항 여행', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0024', '싱가포르 리조트 가족 직항 여행 허니문 해외 항공권 관광지 시장 먹거리', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0025', '싱가포르 먹거리 쇼핑 파크 리조트 패키지 허니문 가족 체험 비치 일정', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0026', '싱가포르 일정 패키지 파크 시장 체험 먹거리 추천 직항 쇼핑 항공권 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0027', '싱가포르 날씨 관광지 쇼핑 먹거리 항공권 해외 허니문 체험 여행 리조트', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0028', '싱가포르 해외 쇼핑 항공권 날씨 허니문 여행 관광지 직항 가족 패키지', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0029', '싱가포르 패키지 비치 일정 쇼핑 항공권 시장 여행 날씨 버스 먹거리 파크', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_MKLKLO_0030', '싱가포르 허니문 패키지 리조트 시장 직항 날씨 먹거리 버스 가족 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0021', '인천출발 날씨 날짜 해외 여행 항공권 싱가포르', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0022', '인천출발 날짜 여행 날씨 싱가포르 항공권 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0023', '인천출발 여행 날짜 싱가포르 항공권 날씨 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0024', '인천출발 해외 날짜 여행 날씨 싱가포르 항공권', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0025', '인천출발 날짜 항공권 여행 날씨 싱가포르 해외', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0026', '인천출발 항공권 여행 해외 날씨 싱가포르 날짜', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0027', '인천출발 해외 여행 날짜 항공권 싱가포르 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0028', '인천출발 여행 싱가포르 날짜 항공권 해외 날씨', 'Singapore');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_LSR_SINGAP_ICSTMD_0029', '인천출발 여행 해외 날씨 날짜 싱가포르 항공권', 'Singapore');
