-- City Titles Part 084 (8301-8400번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0011', '캐나다여행 토론토 캐나다동부 미동부 관광지 나이아가라 폭포 몬트리올 퀘벡 관광코스 일정 미국여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0012', '토론토 캐나다여행 캐나다동부 미동부 관광지 나이아가라 폭포 소규모 단독투어 현지투어 관광코스 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0013', '캐나다여행 토론토 시즌 캐나다동부 미동부 관광지 나이아가라 폭포 메이플 효도여행 일정 현지투어 단독투어', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0014', '토론토 캐나다여행 캐나다동부 미동부 관광지 나이아가라 폭포 미국여행 미국패키지 관광코스 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0015', '캐나다여행 토론토 캐나다동부 미동부 관광지 나이아가라 폭포 몬트리올 퀘벡 메이플 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0016', '토론토 캐나다여행 캐나다동부 미동부 관광지 나이아가라 폭포 관광코스 현지투어 단독투어 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0017', '캐나다여행 토론토 시즌 캐나다동부 미동부 관광지 나이아가라 폭포 소규모 투어 단독투어 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0018', '토론토 캐나다여행 캐나다동부 미동부 관광지 나이아가라 폭포 미국여행 관광코스 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0019', '캐나다여행 토론토 캐나다동부 미동부 관광지 나이아가라 폭포 미국패키지 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_ML_0020', '토론토 캐나다여행 캐나다동부 미동부 관광지 나이아가라 폭포 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0001', '캐나가 여행 패키지 토론도 나이아가르 캐나다동부 국적기 대안항공 아시하나항공 인천츨발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0002', '캐나다 여행 패키지 토돈토 나이아가라 미동부 국적기 대안항공 아시아나학공 인천출발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0003', '케나다 여행 패키지 토론도 나이아가리 캐나다동부 국적기 대한항공 아시하나항공 인천츨발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0004', '케나가 여행 패키지 토돈토 나이아가르 미동부 국적기 대안항공 아시아나항공 인천출발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0007', '캐나가 여행 패키지 토론도 나이아가라 캐나다동부 국적기 대한항공 아시아나학공 인천츨발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0008', '캐나다 여행 패키지 토돈토 나이아가르 미동부 국적기 대안항공 아시하나항공 인천출발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0009', '캐나다 여행 패키지 토론도 나이아가라 캐나다동부 국적기 대한항공 아시아나학공 인천츨발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0010', '캐나가 여행 패키지 토돈토 나이아가리 미동부 국적기 대안항공 아시하나항공 인천출발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0011', '케나다 여행 패키지 토론도 나이아가르 캐나다동부 국적기 대한항공 아시아나항공 인천츨발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0012', '케나다 여행 패키지 토돈토 나이아가라 미동부 국적기 대안항공 아시아나학공 인천출발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0013', '캐나가 여행 패키지 토론도 나이아가라 캐나다동부 국적기 대한항공 아시하나항공 인천츨발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0014', '케나다 여행 패키지 토돈토 나이아가리 미동부 국적기 대안항공 아시아나항공 인천출발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0015', '케나다 여행 패키지 토론도 나이아가르 캐나다동부 국적기 대한항공 아시아나학공 인천츨발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0016', '캐나가 여행 패키지 토돈토 나이아가라 미동부 국적기 대안항공 아시하나항공 인천출발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0017', '케나다 여행 패키지 토론도 나이아가리 캐나다동부 국적기 대한항공 아시아나학공 인천츨발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0018', '케나다 여행 패키지 토돈토 나이아가르 미동부 국적기 대안항공 아시하나항공 인천출발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0019', '케나가 여행 패키지 토론도 나이아가라 캐나다동부 국적기 대한항공 아시아나학공 인천츨발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_OT_0020', '캐나다 여행 패키지 토돈토 나이아가리 미동부 국적기 대안항공 아시하나항공 인천출발', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0001', '토론토 나이아가라 퀘벡 몬트리올 캐나다동부 패키지 여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0002', '토론토 미동부 캐나다 나이아가라 7박10일 패키지 여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0003', '토론토 몬트리올 퀘벡 나이아가라 동부 캐나다 패키지여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0004', '캐나다동부 토론토 퀘벡 몬트리올 나이아가라 패키지', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0005', '토론토 나이아가라 퀘벡 몬트리올 여행 10박12일', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0006', '토론토 퀘벡 몬트리올 캐나다 패키지 나이아가라 여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0007', '토론토 미동부 뉴욕 나이아가라 캐나다동부 패키지여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0008', '캐나다 토론토 나이아가라 퀘벡 몬트리올 여행 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0009', '토론토 나이아가라 몬트리올 퀘벡 캐나다 패키지 여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0010', '토론토 퀘벡 몬트리올 나이아가라 캐나다동부 패키지여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0011', '캐나다동부 토론토 나이아가라 패키지 여행 7박10일', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0012', '토론토 퀘벡 몬트리올 나이아가라 미동부 캐나다 여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0013', '토론토 나이아가라 퀘벡 몬트리올 캐나다 패키지 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0014', '토론토 퀘벡 몬트리올 나이아가라 캐나다 패키지 여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0015', '토론토 미동부 캐나다 나이아가라 몬트리올 퀘벡 여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0016', '토론토 나이아가라 캐나다동부 퀘벡 몬트리올 여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0017', '토론토 캐나다동부 나이아가라 퀘벡 몬트리올 패키지', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0018', '토론토 퀘벡 몬트리올 캐나다 나이아가라 여행', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0019', '토론토 캐나다동부 나이아가라 퀘벡 몬트리올 일정', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_TR_GPT_0020', '토론토 나이아가라 퀘벡 몬트리올 캐나다 패키지', 'Toronto');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0001', '미국 캐나다 퀘벡 여행 패키지 인천출발 국적기 대한항공 아시아나항공 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0002', '퀘벡 가족여행 미국 캐나다 패키지 인천출발 국적기 항공권 대한항공 아시아나', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0003', '미국 캐나다 미동부 퀘벡 패키지 인천출발 국적기 직항 아시아나 대한항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0004', '퀘벡 패키지 미국 캐나다 여행 국적기 항공권 인천출발 아시아나항공 대한항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0005', '미국 캐나다 여행 패키지 인천출발 국적기 항공 대한항공 아시아나 퀘벡', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0006', '퀘벡 가족여행 미국 캐나다 패키지 국적기 항공권 인천출발 대한항공 아시아나', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0007', '미국 캐나다 퀘벡 미동부 여행 패키지 인천출발 국적기 직항 대한항공 아시아나', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0008', '캐나다 퀘벡 미국 여행 패키지 인천출발 국적기 항공권 아시아나항공 대한항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0009', '퀘벡 패키지 여행 미국 캐나다 인천출발 국적기 직항 항공 대한항공 아시아나', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0010', '미국 캐나다 여행 패키지 국적기 퀘벡 항공권 인천출발 아시아나항공 대한항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0011', '가족여행 캐나다 미국 패키지 퀘벡 인천출발 국적기 직항 항공 대한항공 아시아나', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0012', '미국 캐나다 미동부 여행 국적기 퀘벡 항공권 패키지 인천출발 아시아나항공 대한항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0013', '캐나다 미국 여행 패키지 인천출발 국적기 퀘벡 직항 항공권 아시아나 대한항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0014', '미국 캐나다 여행 패키지 국적기 항공권 인천출발 아시아나 대한항공 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0015', '가족여행 미국 캐나다 미동부 패키지 퀘벡 국적기 직항 인천출발 아시아나항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0016', '패키지 여행 미국 캐나다 퀘벡 국적기 항공권 인천출발 대한항공 아시아나항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0017', '미국 캐나다 여행 패키지 퀘벡 인천출발 국적기 항공권 아시아나 대한항공 직항', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0018', '캐나다 미국 여행 패키지 퀘벡 인천출발 국적기 직항 아시아나항공 대한항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0019', '가족여행 미국 캐나다 패키지 퀘벡 국적기 항공권 인천출발 아시아나 대한항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_CMK_0020', '미국 캐나다 미동부 퀘벡 여행 인천출발 국적기 직항 패키지 아시아나 대한항공', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0001', '나이아가라 폭포뷰 호텔 몬트리올 퀘벡 몽모렌시폭포 여행 패키지 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0002', '몬트리올 퀘벡 나이아가라 킹스톤 노트르담성당 포함 미국 캐나다 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0003', '몽트랑블랑 로렌시안 트리탑 나이아가라 캐나다 미국 패키지 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0004', '퀘벡 몬트리올 나이아가라 몽모렌시폭포 포함 캐나다 여행 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0005', '나이아가라 폭포 퀘벡 몬트리올 킹스톤 노트르담성당 캐나다 패키지 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0006', '미국 캐나다 패키지 여행 나이아가라 몬트리올 몽트랑블랑 포함 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0007', '몬트리올 퀘벡 나이아가라 로렌시안 트리탑 미국 캐나다 패키지 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0008', '캐나다 미국 여행 패키지 나이아가라 퀘벡 몬트리올 몽모렌시폭포 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0009', '나이아가라 폭포 퀘벡 몬트리올 몽트랑블랑 포함 패키지 인천출발 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0010', '퀘벡 몬트리올 킹스톤 노트르담성당 포함 캐나다 패키지 여행 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0011', '나이아가라 몽트랑블랑 로렌시안 트리탑 포함 미국 캐나다 패키지 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0012', '몬트리올 퀘벡 나이아가라 노트르담성당 몽모렌시폭포 포함 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0013', '캐나다 미국 여행 나이아가라 퀘벡 몬트리올 로렌시안 트리탑 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0014', '나이아가라 폭포 퀘벡 몬트리올 포함 미국 캐나다 미동부 여행 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0015', '퀘벡 몬트리올 나이아가라 몽모렌시폭포 포함 인천출발 패키지 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0016', '미국 캐나다 패키지 나이아가라 몬트리올 퀘벡 몽트랑블랑 포함 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0017', '나이아가라 폭포 뷰포인트 퀘벡 몬트리올 포함 캐나다 패키지 인천출발', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0018', '퀘벡 몬트리올 킹스톤 나이아가라 포함 미국 캐나다 패키지 여행', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0019', '나이아가라 몽모렌시폭포 로렌시안 트리탑 포함 캐나다 여행 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_MKL_0020', '캐나다 미국 여행 나이아가라 퀘벡 몬트리올 노트르담성당 포함 일정', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0001', '12월 미국 캐나다 미동부 여행 7박9일 일정 나이아가라 퀘벡 인천출발 패키지', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0002', '11월 캐나다 패키지 여행 8일 일정 몬트리올 나이아가라 포함 국적기 직항', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0003', '미국 캐나다 여행 패키지 9일 일정 퀘벡 몬트리올 나이아가라 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0004', '미국 캐나다 패키지 여행 2026년 1월 출발 10일 일정 인천출발 나이아가라 퀘벡 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0005', '캐나다 미국 여행 패키지2025년 12월 출발 7박9일 일정 국적기 직항 인천출발 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0006', '미국 캐나다 패키지 여행 8일 일정 나이아가라 몬트리올 퀘벡 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0007', '캐나다 미국 패키지 여행 11월 출발 9일 일정 국적기 직항 인천출발 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0008', '미국 캐나다 패키지 여행 12월 10일 일정 나이아가라 퀘벡 몬트리올 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0009', '캐나다 미국 여행 패키지 7박9일 일정 인천출발 국적기 항공권', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0010', '미국 캐나다 여행 패키지 8일 일정 국적기 직항 나이아가라 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0011', '미국 캐나다 미동부 여행 9일 일정 나이아가라 몬트리올 퀘벡 포함', 'Quebec');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_QB_DMK_0012', '캐나다 미국 패키지 여행 10일 일정 국적기 직항 인천출발 포함', 'Quebec');
