-- City Titles Part 110 (10901-11000번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_LDW_GOLDCOST_SNM_0020', '호주 관광 4박6일 스카이포인트 여행 효도여행 브리즈번 가족 골드코스트', 'GoldCoast');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0001', '12월 여행 하롱베이 패키지 4박6일 동남아 직항', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0002', '12월 리조트 항공권 해외 날씨 직항 여행 하롱베이', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0003', '12월 패키지 날씨 씨엠립 항공권 캄보디아 일정 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0004', '12월 패키지 일정 캄보디아 하롱베이 날씨 4박6일', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0005', '12월 해외 여행 동남아 4박6일 직항 리조트 패키지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0006', '12월 씨엠립 동남아 일정 날씨 해외 직항 패키지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0007', '12월 날씨 패키지 씨엠립 해외 여행 리조트 직항', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0008', '12월 씨엠립 여행 리조트 직항 해외 날씨 패키지', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0009', '12월 직항 하롱베이 4박6일 해외 패키지 일정 씨엠립', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0010', '12월 일정 씨엠립 직항 여행 항공권 패키지 캄보디아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0011', '12월 씨엠립 일정 동남아 직항 항공권 해외 여행 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0012', '12월 씨엠립 일정 날씨 하롱베이 항공권 직항 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0013', '12월 하롱베이 여행 패키지 일정 4박6일 동남아 날씨', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0014', '12월 캄보디아 4박6일 직항 해외 동남아 리조트 여행', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0015', '12월 캄보디아 패키지 여행 날씨 해외 리조트 씨엠립', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0016', '12월 날씨 씨엠립 리조트 하롱베이 패키지 해외 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0017', '12월 캄보디아 일정 날씨 씨엠립 여행 직항 동남아', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0018', '12월 동남아 패키지 리조트 캄보디아 직항 씨엠립 해외', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0019', '12월 동남아 날씨 해외 패키지 항공권 여행 씨엠립', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250901_LSR_SIEMR_DMKTF_0020', '12월 해외 동남아 캄보디아 리조트 4박6일 여행', 'SiemReap');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0001', '백두산 연휴 항공권 추석 서파 관광 북파 중국 여행', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0002', '백두산 중국 항공권 관광 북파 연휴 여행 서파 추석', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0003', '백두산 중국 북파 관광 항공권 연휴 패키지 여행 추석', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0004', '백두산 북파 관광 패키지 서파 여행 추석 중국 항공권', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0005', '백두산 북파 항공권 중국 연휴 서파 패키지 추석 여행', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0006', '백두산 여행 패키지 항공권 추석 북파 중국 연휴 서파', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0007', '백두산 연휴 중국 추석 여행 패키지 항공권 북파 관광', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0008', '백두산 서파 여행 패키지 연휴 중국 관광 항공권 북파', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0009', '백두산 연휴 서파 패키지 관광 추석 항공권 북파 중국', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0010', '백두산 관광 여행 패키지 항공권 북파 연휴 추석 중국', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0011', '백두산 북파 서파 연휴 관광 패키지 추석 중국 항공권', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0012', '백두산 연휴 추석 관광 중국 북파 여행 패키지 항공권', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0013', '백두산 관광 추석 여행 패키지 중국 서파 북파 연휴', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0014', '백두산 서파 패키지 여행 연휴 북파 항공권 중국 관광', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0015', '백두산 연휴 여행 항공권 관광 서파 추석 중국 북파', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0016', '백두산 패키지 중국 관광 서파 여행 추석 북파 연휴', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0017', '백두산 북파 추석 연휴 관광 여행 서파 패키지 중국', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0018', '백두산 서파 북파 패키지 항공권 중국 연휴 관광 추석', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0019', '백두산 관광 서파 북파 항공권 여행 중국 패키지 추석', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_CMK_0020', '백두산 서파 추석 여행 항공권 패키지 관광 중국 연휴', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0001', '백두산 패키지 두만강 온천 북파 항공권 추석 천지 연휴', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0002', '백두산 중국 패키지 연휴 여행 관광 온천 천지 추석', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0003', '백두산 북파 패키지 중국 여행 서파 관광 연휴 천지', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0004', '백두산 관광 연휴 중국 패키지 두만강 여행 항공권 천지', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0005', '백두산 연휴 여행 두만강 패키지 중국 서파 천지 관광', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0006', '백두산 온천 서파 두만강 천지 연휴 여행 항공권 추석', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0007', '백두산 항공권 북파 여행 관광 천지 두만강 연휴 추석', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0008', '백두산 천지 온천 서파 패키지 추석 두만강 중국 관광', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0009', '백두산 두만강 온천 천지 중국 서파 연휴 항공권 관광', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0010', '백두산 여행 두만강 추석 온천 천지 패키지 연휴 관광', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0011', '백두산 서파 항공권 여행 추석 중국 관광 두만강 천지', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0012', '백두산 두만강 항공권 관광 패키지 추석 온천 여행 서파', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0013', '백두산 천지 항공권 북파 두만강 중국 온천 관광 추석', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0014', '백두산 연휴 천지 온천 서파 중국 북파 추석 여행', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0015', '백두산 북파 여행 연휴 천지 항공권 추석 패키지 중국', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0016', '백두산 패키지 연휴 여행 관광 북파 온천 천지 중국', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0017', '백두산 관광 북파 여행 온천 두만강 서파 천지 항공권', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0018', '백두산 관광 천지 여행 연휴 중국 북파 패키지 항공권', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0019', '백두산 항공권 서파 추석 패키지 천지 두만강 온천 여행', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_MKL_0020', '백두산 여행 천지 항공권 온천 두만강 연휴 서파 북파', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0001', '백두산 샤먼 상하이 충칭 사천성 광저우 중국 장가계', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0002', '백두산 광저우 장가계 샤먼 중국 상하이 대련 충칭 청도', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0003', '백두산 청도 대련 광저우 장가계 충칭 샤먼 사천성', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0004', '백두산 사천성 충칭 중국 대련 상하이 광저우 장가계', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0005', '백두산 대련 청도 광저우 샤먼 상하이 충칭 사천성', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0006', '백두산 상하이 장가계 사천성 대련 샤먼 청도 중국 충칭', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0007', '백두산 사천성 광저우 청도 충칭 샤먼 중국 장가계 대련', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0008', '백두산 상하이 사천성 샤먼 중국 장가계 대련 충칭 청도', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0009', '백두산 충칭 대련 청도 광저우 중국 사천성 상하이 샤먼', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0010', '백두산 사천성 충칭 대련 중국 상하이 광저우 장가계', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0011', '백두산 사천성 대련 청도 샤먼 충칭 광저우 장가계', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0012', '백두산 샤먼 청도 중국 광저우 장가계 사천성 상하이', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0013', '백두산 샤먼 장가계 상하이 대련 충칭 중국 청도 광저우', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0014', '백두산 상하이 샤먼 광저우 충칭 청도 사천성 대련 중국', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0015', '백두산 대련 중국 장가계 청도 사천성 광저우 샤먼 충칭', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0016', '백두산 샤먼 대련 충칭 광저우 중국 청도 사천성 장가계', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0017', '백두산 샤먼 중국 상하이 사천성 광저우 장가계 청도', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0018', '백두산 장가계 샤먼 충칭 중국 광저우 사천성 청도 대련', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0019', '백두산 상하이 대련 중국 충칭 샤먼 장가계 청도 광저우', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_SNK_0020', '백두산 사천성 충칭 대련 샤먼 장가계 광저우 중국 청도', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0001', '백두산 3박4일 중국 서파 등산 항공권 추석 관광 특가 여행 연휴 힐링', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0002', '백두산 중국 서파 등산 관광 패키지 북파 특가 트레킹 여행 연휴 자연', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0003', '백두산 중국 서파 힐링 추석 자연 항공권 여행 연휴 트레킹 특가 북파', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0004', '백두산 3박4일 중국 트레킹 패키지 서파 힐링 관광 항공권 연휴 여행', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0005', '백두산 특가 북파 중국 힐링 연휴 자연 항공권 3박4일 추석 여행 패키지', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0006', '백두산 패키지 서파 트레킹 중국 북파 항공권 자연 관광 여행 등산', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0007', '백두산 패키지 서파 관광 추석 북파 3박4일 연휴 등산 중국 힐링 항공권', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0008', '백두산 3박4일 서파 특가 추석 힐링 항공권 연휴 트레킹 등산 관광 자연', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0009', '백두산 3박4일 등산 트레킹 자연 중국 관광 북파 여행 패키지 연휴 힐링', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0010', '백두산 여행 트레킹 자연 추석 북파 연휴 관광 중국 힐링 패키지 등산', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0011', '백두산 연휴 항공권 힐링 추석 자연 서파 패키지 등산 3박4일 여행 중국', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0012', '백두산 3박4일 자연 추석 항공권 여행 연휴 패키지 트레킹 특가 등산', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0013', '백두산 연휴 항공권 특가 중국 서파 여행 힐링 추석 북파 등산 패키지', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0014', '백두산 서파 힐링 여행 항공권 추석 자연 북파 연휴 등산 3박4일 관광', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0015', '백두산 등산 힐링 여행 항공권 특가 트레킹 연휴 추석 패키지 자연', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0016', '백두산 힐링 항공권 북파 추석 중국 관광 3박4일 여행 연휴 특가 자연', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0017', '백두산 3박4일 트레킹 북파 관광 서파 여행 특가 힐링 항공권 중국', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0018', '백두산 항공권 추석 연휴 관광 여행 패키지 등산 3박4일 서파 트레킹', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0019', '백두산 북파 연휴 서파 관광 트레킹 여행 항공권 자연 힐링 3박4일 중국', 'BaekduMountain');
