-- City Titles Part 088 (8701-8800번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0080', '10월 추석 연휴 서파 중국 백두산 북파 패키지 관광', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0021', '백두산 북파 등산 3박4일 자연 패키지 트레킹 연휴 특가 여행 관광 중국', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0022', '백두산 항공권 북파 등산 연휴 추석 관광 자연 특가 3박4일 힐링 트레킹', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0023', '백두산 특가 3박4일 여행 등산 중국 추석 관광 힐링 북파 연휴 트레킹', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0024', '백두산 연휴 3박4일 서파 힐링 추석 트레킹 항공권 자연 패키지 북파', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0025', '백두산 항공권 연휴 관광 북파 자연 패키지 특가 추석 서파 중국 3박4일', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0026', '백두산 힐링 관광 북파 중국 추석 3박4일 서파 여행 항공권 연휴 특가', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0027', '백두산 자연 추석 트레킹 등산 항공권 3박4일 연휴 특가 관광 여행 북파', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0028', '백두산 힐링 자연 항공권 연휴 등산 중국 패키지 관광 여행 북파 서파', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0029', '백두산 중국 추석 자연 패키지 관광 북파 3박4일 힐링 등산 트레킹 연휴', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_BMOUNTAIN_ML_0030', '백두산 추석 특가 패키지 중국 여행 서파 등산 3박4일 북파 자연 관광', 'BaekduMountain');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0021', '홍콩 항공권 관광 날씨 가격 여행 패키지 마카오', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0022', '홍콩 비행시간 항공권 관광 패키지 여행 가격 직항', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0023', '홍콩 날씨 관광 여행 패키지 직항 마카오 호텔', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0024', '홍콩 비행시간 직항 항공권 마카오 날씨 패키지 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0025', '홍콩 관광 비행시간 직항 날씨 여행 호텔 항공권', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0026', '홍콩 여행 직항 비행시간 관광 호텔 날씨 가격', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0027', '홍콩 호텔 가격 마카오 관광 항공권 여행 패키지', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0028', '홍콩 마카오 항공권 직항 여행 패키지 날씨 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0029', '홍콩 여행 가격 관광 항공권 직항 비행시간 마카오', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0030', '홍콩 마카오 비행시간 호텔 날씨 관광 여행 패키지', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0031', '홍콩 호텔 관광 항공권 날씨 직항 여행 마카오 가격', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0032', '홍콩 호텔 직항 패키지 항공권 날씨 마카오 가격', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0033', '홍콩 여행 가격 관광 항공권 패키지 날씨 직항 호텔', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0034', '홍콩 직항 가격 패키지 비행시간 여행 마카오 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0035', '홍콩 날씨 패키지 항공권 관광 호텔 비행시간 마카오', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0036', '홍콩 직항 가격 비행시간 날씨 마카오 항공권 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0037', '홍콩 여행 마카오 직항 패키지 관광 비행시간 날씨', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0038', '홍콩 날씨 관광 여행 직항 가격 마카오 패키지 호텔', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0039', '홍콩 마카오 관광 항공권 여행 가격 호텔 날씨 직항', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_CMK_0040', '홍콩 호텔 가격 마카오 날씨 관광 직항 여행 패키지', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0021', '11월 호텔 가격 비행시간 패키지 2박 3일 직항', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0022', '11월 마카오 항공권 직항 비행시간 패키지 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0023', '11월 패키지 호텔 날씨 가격 2박 3일 마카오', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0024', '11월 여행 가격 호텔 직항 패키지 비행시간 날씨', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0025', '11월 관광 홍콩 날씨 가격 항공권 패키지 직항', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0026', '11월 마카오 관광 호텔 비행시간 2박 3일 날씨', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0027', '11월 날씨 관광 홍콩 2박 3일 여행 비행시간', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0028', '11월 날씨 홍콩 직항 비행시간 호텔 패키지 가격', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0029', '11월 여행 가격 관광 날씨 호텔 마카오 패키지', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0030', '11월 호텔 가격 패키지 직항 관광 2박 3일 홍콩', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0051', '12월 항공권 홍콩 비행시간 가격 패키지 2박 3일', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0052', '12월 마카오 2박 3일 항공권 호텔 여행 홍콩', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0053', '12월 항공권 2박 3일 직항 마카오 날씨 호텔', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0054', '12월 패키지 직항 홍콩 비행시간 호텔 마카오 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0055', '12월 호텔 날씨 가격 마카오 비행시간 직항 여행', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0056', '12월 홍콩 마카오 관광 여행 항공권 호텔 가격', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0057', '12월 2박 3일 패키지 가격 마카오 여행 비행시간', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0058', '12월 2박 3일 직항 패키지 홍콩 비행시간 마카오', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0059', '12월 마카오 가격 관광 호텔 날씨 직항 여행', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__HONGKONG_DMK_0060', '12월 관광 직항 여행 비행시간 홍콩 2박 3일', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0021', '홍콩 패키지 날씨 항공권 야경 직항 힐링 호텔 가격 먹거리 가족 비행시간', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0022', '홍콩 도심 야경 가볼만한곳 가격 트램 가족 비행시간 커플 힐링 먹거리', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0023', '홍콩 야경 패키지 여행 트램 힐링 커플 가족 호텔 직항 마카오 날씨', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0024', '홍콩 먹거리 가볼만한곳 가격 직항 날씨 호텔 패키지 마카오 도심 항공권', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0025', '홍콩 커플 야경 항공권 여행 도심 호텔 직항 패키지 날씨 비행시간 가격', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0026', '홍콩 먹거리 날씨 도심 트램 관광 비행시간 여행 항공권 가격 힐링 패키지', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0027', '홍콩 가볼만한곳 직항 커플 여행 호텔 항공권 힐링 트램 패키지 날씨', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0028', '홍콩 커플 가격 여행 힐링 날씨 트램 호텔 가볼만한곳 가족 항공권 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0029', '홍콩 항공권 호텔 비행시간 가볼만한곳 야경 커플 관광 마카오 가격 여행', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0030', '홍콩 가볼만한곳 호텔 가족 여행 날씨 커플 비행시간 항공권 먹거리 가격', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0031', '홍콩 트램 도심 마카오 먹거리 커플 패키지 야경 비행시간 가족 직항 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0032', '홍콩 날씨 가격 커플 여행 관광 힐링 패키지 직항 트램 가볼만한곳 먹거리', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0033', '홍콩 날씨 호텔 패키지 가격 가족 힐링 도심 비행시간 먹거리 가볼만한곳', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0034', '홍콩 가격 도심 야경 여행 날씨 가볼만한곳 힐링 커플 패키지 마카오 호텔', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0035', '홍콩 항공권 트램 날씨 야경 직항 마카오 가족 패키지 커플 비행시간', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0036', '홍콩 커플 가족 날씨 관광 힐링 먹거리 호텔 야경 마카오 가볼만한곳 도심', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0037', '홍콩 날씨 가족 가격 비행시간 야경 힐링 도심 먹거리 커플 마카오 패키지', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0038', '홍콩 날씨 관광 직항 마카오 패키지 비행시간 가족 힐링 트램 호텔 도심', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0039', '홍콩 트램 도심 호텔 비행시간 패키지 항공권 힐링 가볼만한곳 먹거리', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0040', '홍콩 트램 도심 직항 야경 호텔 항공권 가격 비행시간 날씨 마카오 커플', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0041', '홍콩 여행 호텔 직항 가볼만한곳 패키지 커플 힐링 날씨 비행시간 야경', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0042', '홍콩 도심 항공권 힐링 트램 커플 날씨 패키지 가볼만한곳 여행 직항 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0043', '홍콩 패키지 직항 야경 힐링 커플 가격 트램 여행 날씨 가족 비행시간', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0044', '홍콩 비행시간 먹거리 가격 커플 관광 가족 호텔 야경 항공권 가볼만한곳', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0045', '홍콩 커플 먹거리 가격 마카오 관광 항공권 호텔 여행 가볼만한곳 트램', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0046', '홍콩 트램 날씨 직항 커플 패키지 도심 항공권 호텔 여행 관광 비행시간', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0047', '홍콩 힐링 가족 트램 호텔 직항 야경 여행 가볼만한곳 관광 가격 먹거리', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0048', '홍콩 가볼만한곳 비행시간 먹거리 트램 가족 야경 힐링 직항 패키지 관광', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0049', '홍콩 가족 먹거리 트램 항공권 힐링 여행 야경 날씨 커플 가격 호텔', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0050', '홍콩 먹거리 가격 가볼만한곳 직항 항공권 비행시간 가족 호텔 힐링 날씨', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0051', '홍콩 비행시간 도심 가볼만한곳 여행 날씨 관광 마카오 패키지 가족 먹거리', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0052', '홍콩 직항 관광 비행시간 힐링 날씨 가족 패키지 트램 도심 여행 가격', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0053', '홍콩 가격 가족 날씨 호텔 먹거리 야경 패키지 관광 여행 직항 비행시간', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0054', '홍콩 패키지 가격 마카오 커플 여행 힐링 비행시간 먹거리 직항 가볼만한곳', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0055', '홍콩 여행 힐링 비행시간 관광 패키지 마카오 날씨 야경 먹거리 커플', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0056', '홍콩 가족 여행 직항 도심 먹거리 트램 커플 비행시간 마카오 호텔 패키지', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0057', '홍콩 날씨 가격 가볼만한곳 항공권 마카오 패키지 야경 도심 여행 호텔', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0058', '홍콩 힐링 호텔 먹거리 여행 관광 항공권 날씨 커플 가족 직항 비행시간', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0059', '홍콩 관광 마카오 항공권 커플 가족 호텔 비행시간 가볼만한곳 도심 야경', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM_HONGKONG_ML_0060', '홍콩 도심 날씨 관광 항공권 여행 비행시간 가격 패키지 힐링 가족 야경', 'HongKong');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MAKAO_CMK_0021', '마카오 직항 홍콩 가격 관광 항공권 비행시간 날씨', 'Macau');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MAKAO_CMK_0022', '마카오 여행 직항 관광 가격 날씨 항공권 홍콩 비행시간', 'Macau');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MAKAO_CMK_0023', '마카오 날씨 홍콩 패키지 관광 비행시간 직항 여행', 'Macau');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MAKAO_CMK_0024', '마카오 직항 패키지 항공권 홍콩 여행 날씨 관광', 'Macau');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MAKAO_CMK_0025', '마카오 여행 직항 관광 날씨 가격 패키지 항공권', 'Macau');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MAKAO_CMK_0026', '마카오 날씨 직항 관광 가격 비행시간 패키지 항공권', 'Macau');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MAKAO_CMK_0027', '마카오 여행 비행시간 홍콩 가격 관광 항공권 패키지', 'Macau');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MAKAO_CMK_0028', '마카오 여행 날씨 패키지 홍콩 직항 비행시간 관광', 'Macau');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_KTM__MAKAO_CMK_0029', '마카오 홍콩 패키지 비행시간 관광 직항 여행 항공권', 'Macau');
