-- City Titles Part 060 (5901-6000번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0011', '일본고베 항공권 리조트 패키지 여행 직항 날씨 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0012', '일본고베 여행 오사카 패키지 해외 리조트 항공권 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0013', '일본고베 직항 오사카 리조트 여행 항공권 패키지 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0014', '일본고베 해외 항공권 여행 리조트 날씨 직항 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0015', '일본고베 오사카 패키지 항공권 리조트 여행 해외 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0016', '일본고베 오사카 여행 패키지 리조트 날씨 해외 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0017', '일본고베 항공권 여행 직항 오사카 해외 날씨 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0018', '일본고베 여행 패키지 리조트 해외 오사카 직항 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0019', '일본고베 리조트 패키지 해외 여행 직항 오사카 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0020', '일본고베 해외 패키지 직항 항공권 오사카 날씨 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0021', '일본고베 패키지 항공권 해외 여행 직항 날씨 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0022', '일본고베 날씨 항공권 직항 리조트 여행 패키지 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0023', '일본고베 오사카 여행 항공권 리조트 날씨 해외 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0024', '일본고베 직항 항공권 여행 리조트 해외 날씨 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0025', '일본고베 날씨 여행 리조트 직항 해외 오사카 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0026', '일본고베 해외 직항 여행 날씨 리조트 항공권 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0027', '일본고베 해외 리조트 항공권 패키지 오사카 날씨 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0028', '일본고베 해외 직항 항공권 오사카 날씨 패키지 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0029', '일본고베 오사카 항공권 직항 날씨 리조트 패키지 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MMK_0030', '일본고베 항공권 해외 날씨 리조트 여행 직항 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0001', '일본고베 간사이공항 오사카 온천 해외 커플여행 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0002', '일본고베 패키지 항공권 에어텔 나라 커플여행 날씨 온천', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0003', '일본고베 나라 패키지 에어텔 커플여행 항공권 교토', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0004', '일본고베 날씨 나라 오사카 여행 간사이공항 패키지 교토', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0005', '일본고베 날씨 여행 에어텔 커플여행 패키지 간사이공항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0006', '일본고베 리조트 날씨 커플여행 해외 에어텔 온천 교토', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0007', '일본고베 패키지 에어텔 리조트 여행 나라 오사카 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0008', '일본고베 교토 여행 온천 간사이공항 나라 리조트 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0009', '일본고베 나라 직항 교토 에어텔 여행 리조트 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0010', '일본고베 항공권 해외 에어텔 오사카 리조트 여행 온천', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0011', '일본고베 해외 리조트 나라 커플여행 패키지 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0012', '일본고베 리조트 에어텔 패키지 간사이공항 항공권 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0013', '일본고베 에어텔 교토 간사이공항 나라 리조트 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0014', '일본고베 날씨 오사카 리조트 항공권 간사이공항 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0015', '일본고베 온천 간사이공항 날씨 리조트 여행 해외 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0016', '일본고베 교토 여행 간사이공항 직항 나라 오사카 온천', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0017', '일본고베 직항 교토 커플여행 온천 해외 항공권 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0018', '일본고베 에어텔 여행 날씨 나라 오사카 직항 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0019', '일본고베 리조트 직항 오사카 나라 간사이공항 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0020', '일본고베 온천 여행 커플여행 해외 교토 에어텔 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0021', '일본고베 온천 해외 오사카 항공권 교토 직항 커플여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0022', '일본고베 커플여행 리조트 항공권 직항 교토 해외 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0023', '일본고베 나라 간사이공항 에어텔 여행 항공권 날씨 교토', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0024', '일본고베 에어텔 항공권 해외 직항 나라 간사이공항 온천', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0025', '일본고베 에어텔 항공권 리조트 날씨 커플여행 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0026', '일본고베 커플여행 여행 해외 날씨 간사이공항 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0027', '일본고베 해외 에어텔 패키지 오사카 항공권 리조트 온천', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0028', '일본고베 커플여행 패키지 나라 온천 직항 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0029', '일본고베 나라 온천 교토 리조트 에어텔 날씨 간사이공항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKSH_0030', '일본고베 에어텔 리조트 간사이공항 교토 커플여행 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0001', '일본고베 간사이공항 항공권 리조트 날씨 에어텔 직항 온천 해외 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0002', '일본고베 교토 간사이공항 커플여행 항공권 오사카 여행 패키지 직항 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0003', '일본고베 항공권 여행 직항 날씨 오사카 온천 해외 간사이공항 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0004', '일본고베 교토 리조트 나라 여행 에어텔 날씨 패키지 직항 간사이공항 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0005', '일본고베 패키지 여행 교토 커플여행 날씨 오사카 해외 항공권 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0006', '일본고베 간사이공항 오사카 커플여행 리조트 날씨 항공권 해외 패키지 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0007', '일본고베 교토 온천 커플여행 해외 오사카 날씨 항공권 여행 간사이공항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0008', '일본고베 직항 항공권 커플여행 여행 날씨 온천 에어텔 리조트 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0009', '일본고베 날씨 교토 온천 에어텔 나라 직항 간사이공항 커플여행 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0010', '일본고베 나라 오사카 해외 커플여행 여행 교토 패키지 직항 간사이공항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0011', '일본고베 오사카 리조트 패키지 간사이공항 에어텔 온천 커플여행 해외 교토', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0012', '일본고베 리조트 항공권 날씨 여행 오사카 직항 패키지 나라 커플여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0013', '일본고베 나라 온천 직항 여행 날씨 커플여행 오사카 간사이공항 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0014', '일본고베 직항 여행 커플여행 오사카 나라 간사이공항 리조트 날씨 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0015', '일본고베 리조트 간사이공항 에어텔 교토 패키지 여행 항공권 커플여행 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0016', '일본고베 교토 패키지 온천 오사카 에어텔 해외 직항 리조트 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0017', '일본고베 오사카 날씨 리조트 해외 여행 직항 교토 에어텔 온천 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0018', '일본고베 나라 리조트 커플여행 해외 오사카 항공권 교토 에어텔 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0019', '일본고베 직항 해외 나라 리조트 오사카 온천 교토 항공권 간사이공항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0020', '일본고베 해외 커플여행 패키지 직항 오사카 항공권 리조트 날씨 여행 나라', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0021', '일본고베 에어텔 패키지 날씨 온천 교토 나라 항공권 리조트 해외 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0022', '일본고베 패키지 온천 에어텔 리조트 오사카 해외 간사이공항 여행 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0023', '일본고베 패키지 리조트 나라 항공권 직항 해외 커플여행 날씨 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0024', '일본고베 여행 리조트 날씨 간사이공항 커플여행 교토 직항 패키지 나라', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0025', '일본고베 교토 직항 에어텔 날씨 온천 패키지 항공권 여행 해외 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0026', '일본고베 교토 간사이공항 해외 항공권 패키지 여행 나라 직항 온천 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0027', '일본고베 직항 날씨 교토 오사카 온천 간사이공항 여행 해외 나라 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0028', '일본고베 오사카 커플여행 날씨 직항 온천 해외 교토 간사이공항 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0029', '일본고베 리조트 날씨 항공권 간사이공항 여행 나라 온천 패키지 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_MKLKLO_0030', '일본고베 오사카 간사이공항 여행 교토 온천 날씨 커플여행 리조트 에어텔', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0001', '10월 리조트 날씨 오사카 일본 항공권 직항 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0002', '10월 패키지 해외 일본 고베 유니버셜스튜디오', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0003', '10월 우메다스카이빌딩 일본 패키지 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0004', '10월 날씨 직항 일본 고베 여행 해외 오사카 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0005', '10월 패키지 일본 유니버셜스튜디오 직항 오사카 리조트', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0006', '10월 여행 오사카 직항 항공권 유니버셜스튜디오 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0007', '10월 우메다스카이빌딩 날씨 고베 해외 항공권 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0008', '10월 우메다스카이빌딩 오사카 직항 일본 날씨 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0009', '10월 직항 해외 우메다스카이빌딩 오사카 항공권 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0010', '10월 오사카 유니버셜스튜디오 고베 해외 패키지 항공권', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0011', '10월 우메다스카이빌딩 오사카 패키지 리조트 직항 고베', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0012', '10월 날씨 우메다스카이빌딩 고베 여행 패키지 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0013', '10월 해외 리조트 여행 오사카 항공권 패키지 날씨', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0014', '10월 해외 유니버셜스튜디오 우메다스카이빌딩 날씨 여행', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0015', '10월 리조트 고베 항공권 여행 날씨 일본 직항 패키지', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0016', '10월 우메다스카이빌딩 패키지 리조트 직항', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0017', '10월 항공권 일본 직항 패키지 여행 오사카 고베', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0018', '10월 오사카 우메다스카이빌딩 패키지 리조트 직항 해외', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0019', '10월 우메다스카이빌딩 고베 여행 패키지 일본 오사카', 'Kobe');
INSERT INTO public.titles (id, title, city) VALUES ('20250902_LSR_KOBE_OMKRT_0020', '10월 고베 일본 우메다스카이빌딩 항공권 직항 패키지', 'Kobe');
