-- City Titles Part 008 (701-800번째 레코드)
-- 총 100개의 INSERT 문

INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_MKL_0020', '진주만 선셋비치 알로하타워 하와이 패키지 아시아나항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0001', '상반기 2026년 4박6일 하와이 인천출발 대한항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0002', '1월 2월 5박7일 하와이 인천출발 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0003', '3월 4월 6박8일 하와이 인천출발 대한항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0004', '크리스마스 연말연시 6박8일 하와이 인천출발 아시아나항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0005', '상반기 고래시즌 4박6일 하와이 인천출발 대한항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0006', '7월 8월 여름휴가 5박7일 하와이 인천출발 아시아나항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0007', '하반기 9월 10월 6박8일 하와이 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0008', '상반기 2026년 5박7일 하와이 인천출발 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0009', '5박7일 2026년 크리스마스 하와이 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0010', '연말연시 4박6일 하와이 인천출발 아시아나항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0011', '고래시즌 6박8일 상반기 하와이 인천출발 대한항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0012', '1월 3월 5박7일 하와이 인천출발 아시아나항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0013', '2월 4월 6박8일 하와이 인천출발 대한항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0014', '하반기 9월 5박7일 하와이 인천출발 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0015', '10월 6박8일 하와이 인천출발 대한항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0016', '상반기 4박6일 하와이 인천출발 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0017', '2026년 상반기 6박8일 하와이 인천출발 대한항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0018', '7월 8월 5박7일 하와이 인천출발 아시아나항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0019', '크리스마스 6박8일 하와이 인천출발 대한항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_DMK_0020', '연말연시 5박7일 하와이 인천출발 아시아나항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0001', '하와이 와이키키해변 다이아몬드헤드 하나우마베이 마노아폭포 코코헤드 선셋비치 할로나블로우홀 진주만 애리조나기념관 이올라니궁전 알로하타워 여름휴가 와이켈레아울렛 서핑 스노클링 웨일와칭 오아후 마우이 리조트 오션뷰 인천출발 대한항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0002', '하와이 와이키키 다이아몬드헤드 하나우마베이 마노아폭포 선셋비치 진주만 알로하타워 애리조나기념관 쇼핑 노팁 노옵션 와이켈레아울렛 오아후 마우이 리조트 인천출발 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0003', '하와이 와이키키해변 다이아몬드헤드 하나우마베이 마노아폭포 코코헤드 선셋비치 할로나블로우홀 진주만 애리조나기념관 이올라니궁전 알로하타워 힐링 오아후 마우이 리조트 오션뷰 인천출발 대한항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0004', '하와이 와이키키 다이아몬드헤드 하나우마베이 마노아폭포 코코헤드 선셋비치 서핑 스노클링 웨일와칭 와이켈레아울렛 쇼핑 리조트 오션뷰 인천출발 아시아나항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0005', '하와이 오아후 마우이 와이키키해변 다이아몬드헤드 하나우마베이 마노아폭포 선셋비치 할로나블로우홀 진주만 알로하타워 리조트 오션뷰 와이켈레아울렛 인천출발 대한항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0006', '하와이 와이키키 이올라니궁전 알로하타워 진주만 다이아몬드헤드 하나우마베이 마노아폭포 코코헤드 선셋비치 와이켈레아울렛 서핑 스노클링 리조트 인천출발 아시아나항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0007', '하와이 와이키키해변 다이아몬드헤드 마노아폭포 하나우마베이 선셋비치 코코헤드 할로나블로우홀 진주만 애리조나기념관 이올라니궁전 알로하타워 오션뷰 리조트 와이켈레아울렛 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0008', '하와이 오아후 마우이 와이키키 다이아몬드헤드 마노아폭포 코코헤드 선셋비치 서핑 스노클링 웨일와칭 리조트 오션뷰 인천출발 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0009', '하와이 와이키키 이올라니궁전 알로하타워 진주만 선셋비치 할로나블로우홀 코코헤드 마노아폭포 다이아몬드헤드 리조트 오션뷰 와이켈레아울렛 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0010', '하와이 와이키키해변 다이아몬드헤드 하나우마베이 마노아폭포 선셋비치 오아후 마우이 리조트 오션뷰 와이켈레아울렛 서핑 스노클링 인천출발 아시아나항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0011', '하와이 와이키키 코코헤드 선셋비치 마노아폭포 하나우마베이 할로나블로우홀 리조트 오션뷰 와이켈레아울렛 쇼핑 인천출발 대한항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0012', '하와이 오아후 마우이 와이키키해변 다이아몬드헤드 마노아폭포 하나우마베이 진주만 알로하타워 이올라니궁전 리조트 오션뷰 인천출발 아시아나항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0013', '하와이 와이키키해변 선셋비치 코코헤드 마노아폭포 하나우마베이 할로나블로우홀 리조트 오션뷰 와이켈레아울렛 서핑 인천출발 대한항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0014', '하와이 와이키키 다이아몬드헤드 마노아폭포 하나우마베이 코코헤드 선셋비치 진주만 이올라니궁전 알로하타워 리조트 오션뷰 인천출발 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0015', '하와이 오아후 마우이 와이키키 다이아몬드헤드 하나우마베이 마노아폭포 선셋비치 코코헤드 할로나블로우홀 와이켈레아울렛 쇼핑 리조트 인천출발 대한항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0016', '하와이 와이키키해변 다이아몬드헤드 하나우마베이 마노아폭포 선셋비치 코코헤드 리조트 오션뷰 와이켈레아울렛 서핑 스노클링 웨일와칭 인천출발 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0017', '하와이 와이키키 진주만 애리조나기념관 알로하타워 이올라니궁전 다이아몬드헤드 하나우마베이 마노아폭포 코코헤드 선셋비치 리조트 오션뷰 인천출발 대한항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0018', '하와이 오아후 마우이 와이키키해변 다이아몬드헤드 마노아폭포 하나우마베이 선셋비치 리조트 오션뷰 와이켈레아울렛 인천출발 아시아나항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0019', '하와이 와이키키해변 다이아몬드헤드 마노아폭포 하나우마베이 코코헤드 선셋비치 할로나블로우홀 리조트 오션뷰 와이켈레아울렛 인천출발 대한항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_ML_0020', '하와이 와이키키 다이아몬드헤드 하나우마베이 마노아폭포 코코헤드 선셋비치 리조트 오션뷰 와이켈레아울렛 서핑 인천출발 아시아나항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0001', '하와이 패키지 부모님효도 추석여행 가족 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0002', '하와이 홈쇼핑여행 미국 비용 4인가족 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0003', '와이키키 패키지 하와이 추석여행 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0004', '하와이 부모님효도 패키지 4인가족 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0005', '미국 하와이 패키지 가족 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0006', '하와이 추석여행 패키지 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0007', '와이키키 하와이 패키지 가족 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0008', '하와이 패키지 해외여행 홈쇼핑여행 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0009', '하와이 비용 4인가족 패키지 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0010', '하와이 와이키키 패키지 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0011', '하와이 부모님효도 해외여행 패키지 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0012', '하와이 추석여행 와이키키 패키지 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0013', '하와이 미국 패키지 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0014', '하와이 홈쇼핑여행 패키지 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0015', '와이키키 하와이 가족 패키지 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0016', '하와이 패키지 일정 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0017', '하와이 해외여행 패키지 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0018', '하와이 와이키키 4인가족 패키지 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0019', '하와이 부모님효도 패키지 인천출발 대한항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_SNK_0020', '하와이 추석여행 패키지 와이키키 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0001', '하외이 패키지 미국 와이케키 투어 인쳔출발 대한항공 미주여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0002', '하외이 미국 패키지 와이케키 투어 인쳔출발 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0003', '하외이 패키지 와이케키 투어 미국 인쳔출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0004', '하외이 미국 와이케키 패키지 투어 인쳔출발 아시아나항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0005', '하외이 와이케키 패키지 미국 투어 인쳔출발 대한항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0006', '하외이 패키지 투어 미국 와이케키 인쳔출발 아시아나항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0007', '하외이 투어 와이케키 패키지 미국 인쳔출발 대한항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0008', '하외이 패키지 미국 와이케키 투어 인쳔출발 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0009', '하외이 미국 와이케키 투어 패키지 인쳔출발 대한항공 미주여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0010', '하외이 투어 패키지 와이케키 미국 인쳔출발 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0011', '하외이 와이케키해변 다이아먼드헤드 하나우마배이 마노아폭포 코코헤드 선셋비치 할로나블로우홀 인쳔출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0012', '알로하타워 이올라니궁전 애리조나기념관 진주만 와이케키 하외이 인쳔출발 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0013', '선셋비치 코코헤드 마노아폭포 하나우마배이 와이케키 하외이 인쳔출발 대한항공 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0014', '다이아먼드헤드 와이케키 이올라니궁전 알로하타워 하외이 인쳔출발 아시아나항공 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0015', '하외이 와이케키 코코헤드 마노아폭포 선셋비치 인쳔출발 대한항공 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0016', '하외이 진주만 애리조나기념관 와이케키 인쳔출발 아시아나항공 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0017', '하외이 와이케키 다이아먼드헤드 하나우마배이 인쳔출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0018', '하외이 알로하타워 와이케키해변 마노아폭포 인쳔출발 아시아나항공 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0019', '하외이 선셋비치 코코헤드 와이케키 인쳔출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_OT_0020', '하외이 하나우마배이 와이케키 다이아먼드헤드 인쳔출발 아시아나항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0001', '하와이 패키지 와이키키 해변 다이아몬드헤드 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0002', '하와이 와이키키 다이아몬드헤드 하나우마베이 마노아폭포 패키지 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0003', '하와이 인천출발 패키지 와이키키 다이아몬드헤드 진주만 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0004', '하와이 와이키키 코코헤드 선셋비치 할로나블로우홀 가족여행 패키지', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0005', '하와이 다이아몬드헤드 마노아폭포 와이키키 해변 인천출발 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0006', '하와이 와이키키 패키지 다이아몬드헤드 이올라니궁전 알로하타워 해외여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0007', '하와이 패키지 와이키키 진주만 애리조나기념관 인천출발 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0008', '하와이 와이키키 다이아몬드헤드 하나우마베이 마노아폭포 리조트 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0009', '하와이 인천출발 패키지 와이키키 알로하타워 진주만 졸업여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0010', '하와이 와이키키 해변 다이아몬드헤드 알로하타워 리조트 가족여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0011', '하와이 와이키키 패키지 다이아몬드헤드 마노아폭포 서핑 효도여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0012', '하와이 인천출발 패키지 와이키키 하나우마베이 선셋비치 우정여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0013', '하와이 와이키키 해변 다이아몬드헤드 마노아폭포 아시아나항공 패키지', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0014', '하와이 와이키키 패키지 다이아몬드헤드 알로하타워 리조트 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0015', '하와이 와이키키 진주만 애리조나기념관 이올라니궁전 효도여행 패키지', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0016', '하와이 와이키키 다이아몬드헤드 하나우마베이 패키지 인천출발 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0017', '하와이 와이키키 패키지 다이아몬드헤드 코코헤드 선셋비치 아시아나항공', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0018', '하와이 와이키키 다이아몬드헤드 마노아폭포 인천출발 대한항공 여행', 'Honolulu');
INSERT INTO public.titles (id, title, city) VALUES ('20250829_CS_HL_GPT_0019', '하와이 패키지 와이키키 알로하타워 진주만 애리조나기념관 가족여행', 'Honolulu');
