-- Add extra columns present in Excel but missing in ep_data
alter table public.ep_data
  add column if not exists naver_category text,
  add column if not exists naver_product_id text,
  add column if not exists condition text,
  add column if not exists import_flag text,
  add column if not exists parallel_import text,
  add column if not exists order_made text,
  add column if not exists product_flag text,
  add column if not exists adult text,
  add column if not exists goods_type text,
  add column if not exists barcode text,
  add column if not exists manufacture_define_number text,
  add column if not exists brand_certification text,
  add column if not exists card_event text,
  add column if not exists event_words text,
  add column if not exists coupon text,
  add column if not exists partner_coupon_download text,
  add column if not exists interest_free_event text,
  add column if not exists point numeric,
  add column if not exists installation_costs numeric,
  add column if not exists search_tag text,
  add column if not exists group_id text,
  add column if not exists vendor_id text,
  add column if not exists coordi_id text,
  add column if not exists minimum_purchase_quantity int,
  add column if not exists review_count int,
  add column if not exists shipping text,
  add column if not exists attribute text,
  add column if not exists option_detail text,
  add column if not exists seller_id text;


